### ISSUE TITLE
[BUG] [scala-sttp] Generated code fails to compile if array item is a nested enum

### ISSUE THREAD

**Issue by bgong-mdsol** [OpenAPITools/openapi-generator#10055]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ ] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Having a contract with the array like `sort_by` in example below, and a type which is referencing the nested enum, the code below is generated with wrong enum `Seq[SortBy]` which causes compile to fail.

##### openapi-generator version

The both version 5.2.0 and the latest master branch

##### OpenAPI declaration file content or url

```yaml
components:
  schemas:
    Users:
      properties:
        emails:
          items:
            type: string
          type: array
        search:
          enum:
          - first_name
          - last_name
          - email
          - full_name
          type: string
        sort_by:
          items:
            enum:
            - first_name
            - last_name
            - email
            type: string
          type: array
      type: object
```

##### Generation Details
```shell
openapi-generator-cli generate \
  -g scala-sttp \
  -i name_of_file.yaml \
  -p mainPackage=myPackage \
  -o myApi
```

Generated model class `Users`:

```scala
case class Users(
  emails: Option[Seq[String]] = None,
  search: Option[UsersEnums.Search] = None,
  sortBy: Option[UsersEnums.Seq[SortBy]] = None
)

object UsersEnums {

  type Search = Search.Value
  type Seq[SortBy] = Seq[SortBy].Value
  object Search extends Enumeration {
    val FirstName = Value("first_name")
    val LastName = Value("last_name")
    val Email = Value("email")
    val FullName = Value("full_name")
  }

  object Seq[SortBy] extends Enumeration {
  }

}

```
Expected model class `Users` should be
```scala
case class Users(
  emails: Option[Seq[String]] = None,
  search: Option[UsersEnums.Search] = None,
  sortBy: Option[Seq[UsersEnums.SortBy]] = None
)

object UsersEnums {

  type Search = Search.Value
  type SortBy = SortBy.Value
  object Search extends Enumeration {
    val FirstName = Value("first_name")
    val LastName = Value("last_name")
    val Email = Value("email")
    val FullName = Value("full_name")
  }

  object SortBy extends Enumeration {
    val FirstName = Value("first_name")
    val LastName = Value("last_name")
    val Email = Value("email")
  }
}
```
