### ISSUE TITLE
[REQ] [python-flask] Distinction between "null" and "undefined"

### ISSUE THREAD

**Issue by LeComptoirDesPharmacies** [OpenAPITools/openapi-generator#10076]
### Is your feature request related to a problem? Please describe.

It does not seems to be possible to distinct "null" and "undefined" when receiving request body parameters in Python.

For example : 
Schema :
```
User:
  type: object
  properties:
    firstname:
      type: string
    lastname:
      type: string
    email:
      type: string
      nullable: true
  required:
    - firstname
    - lastname
```

Payload A : 
```
{
  firstname: "John",
  lastname: "Doe",
  email: null,
}
```

Payload B : 
```
{
  firstname: "John",
  lastname: "Doe",
}
```
Using payload A and B do not have the same meaning using Json Merge Patch format from RFC 7386.
(See : https://datatracker.ietf.org/doc/html/rfc7386)

Payload A should set 'None' to attribute email and Payload B should let the email untouched.

## Describe the solution you'd like

It could be nice to have a solution like JsonNullable used on the Java Codegen (See : https://github.com/OpenAPITools/jackson-databind-nullable)
We could wrap with "nullable" attributes from Python model.mustache and it will allow to distinct between "None" and "undefined" using ".is_set" or ".get".

Note : 
If a "to_dict" method is present on the model, it should not generate Entry<Key,Value> for the "undefined" attributes.
