### ISSUE TITLE
[BUG] 5.2.0 Platform class kotlin.Unit requires explicit JsonAdapter to be registered

### ISSUE THREAD

**Issue by patiramyadav** [OpenAPITools/openapi-generator#10126]
When using latest version 5.2.1
 
```
java.lang.IllegalArgumentException: Platform class kotlin.Unit requires explicit JsonAdapter to be registered
	at com.squareup.moshi.ClassJsonAdapter$1.create(ClassJsonAdapter.java:75)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:145)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:105)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:79)
```

Spec:
```
paths:
  /v1/schedules/{id}/cancel:
    patch:
      tags:
        - Schedules
      summary: Cancel a schedule
      operationId: cancel
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid

```
Generated Request Config:

```
    fun cancelRequestConfig(id: java.util.UUID) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()

        return RequestConfig(
            method = RequestMethod.PATCH,
            path = "/v1/schedules/{id}/cancel".replace("{"+"id"+"}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            body = localVariableBody
        )
    }
```

Getting above issue when RequestConfig instance is returned by cancelRequestConfig method.
