### ISSUE TITLE
[REQ] Add stale bot

### ISSUE THREAD

**Issue by falnyr** [OpenAPITools/openapi-generator#10138]
### Is your feature request related to a problem? Please describe.

There seems to be A LOT of issues that are recorded but not followed-up on in the project. Although it is good to keep track of them, they should really only be a concern if someone is actively facing the issue.

## Describe the solution you'd like

I would like to add https://github.com/marketplace/stale stale bot to the OpenAPITools org. This way it will be much less noise on the repositories and it will be less daunting for newcomers to pick up an issue and start working on it. At the same time, if someone really needs a feature/bug fix - they will need to actively participate on a PR/Issue to prevent it from going stale.

## Describe alternatives you've considered

There could be manual triaging but that's very time consuming.

## Additional context

Stale is implemented by many open source organisations and it's free.

FYI: This is primarily for the authors to decide whether this is a good idea or not.
@jimschubert @grokify @lukoyanov @wing328 @jmini @tomplus @ackintosh @quen2404 @macjohnny @cbornet @yue9944882 @JFCote

**Comment by JFCote** [comment]
@wing328 should be the one to take a decision but I agree that this project has way too much open issue and at least 50% are from very old version and not wanted anymore. I've read the description of the plugin and I agree it would help.

@falnyr  Is it possible to add the plugin at the project level instead of the org level? There are other projects in the org that don't have the level of activity that OpenApi Generator have, like my own project OpenAPI Style Validator and I'm not sure it would be a very good match.

**Comment by falnyr** [comment]
@JFCote The bot behaves like any other GitHub Application - you can enable it globally or per repository.
![image](https://user-images.githubusercontent.com/6673296/129253881-f53e691a-bf9d-4054-9442-50475bc87669.png)

**Comment by falnyr** [comment]
This is the default configuration, which in my opinion has reasonable settings: 

```yaml
# Number of days of inactivity before an issue becomes stale
daysUntilStale: 60
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7
# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - security
# Label to use when marking an issue as stale
staleLabel: wontfix
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
```

Let me know if you're happy with this and I'll submit a PR @wing328
