### ISSUE TITLE
[BUG] [scala-sttp] Not Found Type ByteArray

### ISSUE THREAD

**Issue by bgong-mdsol** [OpenAPITools/openapi-generator#10150]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x]  Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When generating a scala-sttp client with data-schema defined as the example below(`format: byte`, `type: string`), the code is generated with the reference to ByteArray which causes compile to fail. 

##### openapi-generator version

The both version 5.2.0 and the latest master branch

##### OpenAPI declaration file content

```yaml
components:
  schemas:
     TraceWithScreenshotData:
        properties:
           screenshot:
               description: |-
                   The screenshot image encoded using base64.
                   A screenshot should start with a data uri scheme 'data:image/png;base64'.
              format: byte
              type: string
        type: object
```

##### Generation Details

Command line used for generation
```shell
openapi-generator-cli generate \
  -g scala-sttp \
  -i name_of_file.yaml \
  -p mainPackage=myPackage \
  -o myApi
```
Generated model class `TraceWithScreenshotData`
```scala
case class TraceWithScreenshotData(
  /* The screenshot image encoded using base64. A screenshot should start with a data uri scheme 'data:image/png;base64'. */
  screenshot: Option[ByteArray] = None
)
```
##### Steps to reproduce

See above

##### Related issues/PRs

similar issue in scala-akka client: https://github.com/OpenAPITools/openapi-generator/issues/5580
