### ISSUE TITLE
[BUG][JAVA] Deserialization of array with uniqueItems=true doesn't preserve order

### ISSUE THREAD

**Issue by abrudin** [OpenAPITools/openapi-generator#10167]
After https://github.com/OpenAPITools/openapi-generator/issues/5254 was fixed and merged, when using Jackson, arrays with uniqueItems=true gets deserialized to HashSet rather than LinkedHashSet, thus not preserving order as expected.

Even though the field (myProp) is initialized to an empty LinkedHashSet, it is promptly overwritten with a regular HashSet given that there is no deserialization-hint (@JsonDeserialize(as = LinkedHashSet.class)) on the setMyProp-method. The method invoked looks like this:
```
  @JsonProperty(JSON_PROPERTY_MY_PROP)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMyProp(Set<SomeEnum> myProp) {
    this.myProp = myProp;
  }
 ```
and thus there is no way for Jackson to understand that order needs to be preserved.

This issue is present in version 5.2.1

**Comment by MelleD** [comment]
With the new version 5.3.1 the JsonNullable handling ist broken

The PR (https://github.com/OpenAPITools/openapi-generator/pull/10241) broke the JsonNullable deserialization. If you use a JsonNullable with uniqueItems. This code will generated:

e.g.
```
@JsonDeserialize(as = LinkedHashSet.class)
public void setFoos(JsonNullable<Set<String>> foos) {
  this.foos = foos;
}
```

Exception

```
[.c.j.MappingJackson2HttpMessageConverter] : Failed to evaluate Jackson deserialization for type [[simple type, class FooDto]]: com.fasterxml.jackson.databind.JsonMappingException: Failed to narrow type [simple type, class org.openapitools.jackson.nullable.JsonNullable<java.util.Set<java.lang.String>>] with annotation (value java.util.LinkedHashSet), from 'setFoos': Class `java.util.LinkedHashSet` not subtype of `org.openapitools.jackson.nullable.JsonNullable<java.util.Set<java.lang.String>>`
```

```
foos:
  type: array
  uniqueItems: true
  items:
    type: string
  maxItems: 10
  nullable: true
```

**Comment by wing328** [comment]
@borsch can you please take a look at this issue when you've time? Thanks.

**Comment by MelleD** [comment]
@borsch it is at all possible to specify a concrete implementation in a wrapper. You can't do that with optionals either, right?

**Comment by borsch** [comment]
@MelleD I believe it doesn't. Most likely JsonNullable+Set still would have default impl - HashSet

**Comment by MelleD** [comment]
I'm not a Jackson expert either, maybe it's possible with an own serializer. I'll ask at stackoverflow. If I find a solution, I'll do a PR .

Are you doing a PR to make it work again with JsonNullable?

**Comment by borsch** [comment]
@MelleD not yet

**Comment by borsch** [comment]
@MelleD I spent some time googling possible solution how to keep both `JsonNullable` & `LinkedHashSet`, but haven't found anything yet. Here is a solution that I've mentioned before - skip `@JsonDeserializer` for `JsonNullable` fields

https://github.com/OpenAPITools/openapi-generator/pull/11495

**Comment by MelleD** [comment]
Thanks for the quick PR.

Did you enable the Optional feature? I have never used the option, but not that in the constellation is also broken.

**Comment by borsch** [comment]
@MelleD I haven't heard about such feature. Can you give an example how to enable it? I'll test it later

**Comment by MelleD** [comment]
@borsch Ah i think is just for parameter in the API classes
https://openapi-generator.tech/docs/generators/spring
<useOptional >

**Comment by borsch** [comment]
@MelleD yep

**Comment by welshm** [comment]
FWIW - I am trying to add `Optional` support to POJOs as well - I will keep this in mind if I can get agreement on adding Optional there - https://github.com/OpenAPITools/openapi-generator/pull/11384

**Comment by MelleD** [comment]
@welshm The idea has come up a few times. What don't you like about the JsonNullable?

**Comment by welshm** [comment]
> @welshm The idea has come up a few times. What don't you like about the JsonNullable?

They can both be used - in my view they solve different problems. I see three use cases. 

If a value is not required to be present but `null` is not a valid type for that value - it would be Optional (since it cannot be set to `null`).

If a value has `null` as a valid type, then it would be JsonNullable (regardless of required or not).

If a value is required and `null` is not a valid type - then the value must be present so it can be the data type directly (such as `String`)

**Comment by MelleD** [comment]
Yes that's correct JsonNullable is just for the Tristate and in the moste cases for the json patch.
But how you would like to difference if you would like to use JsonNullable or Optional. Because currently you can just set nullable: true, correct?

**Comment by welshm** [comment]
I see the first case as when I would want Optional over JsonNullable - a value is not required to be present in the JSON schema, but if it is present it must not be `null`. Optional enforces that (the value is not present so the optional is empty) while JsonNullable does not (because it would allow `null` to be set)

```
schemas:
    OptionalsExample:
      required:
        - fieldTwo
      type: object
      properties:
        fieldOne:
          type: string
          description: 'A non-required string that cannot be null'
          nullable: false
        fieldTwo:
          type: string
          description: 'A required string that cannot be null'
          nullable: false
    NullablesExample:
      required:
        - fieldFour
      type: object
      properties:
        fieldThree:
          type: string
          description: 'A non-required string that can be null'
          nullable: true
        fieldFoud:
          type: string
          description: 'A required string that can be null'
          nullable: true
```

Assuming a patch request...
```
optionalsExample {
    "fieldOne":  "a_new_value",
    "fieldTwo": null      <---- Converts to Optional.empty() and is ignored in the patch because null is not a valid value, and a value is not required.
}

nullablesExample {
  "fieldThree": "another_new_value",
  "fieldFour":  null     <---- Converts to JsonNullable.of(null) and is used by the patch to set the value to null.
}
```
