### ISSUE TITLE
[BUG] [scala-sttp] Enumeration - operator constant name collision

### ISSUE THREAD

**Issue by bgong-mdsol** [OpenAPITools/openapi-generator#10187]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description
scala-sttp client generator generates the enumeration object with the same name `X3D` for `=` and `!=` 

##### openapi-generator version

The both version 5.2.0 and the latest master branch (5.3.x)

##### OpenAPI declaration file content or url

If you post the code inline, please wrap it with
```yaml
components:
  schemas:
      Condition:
          properties:
             operator:
                 description: The comparison operator.
                 enum:
                 - =
                 - '!='
                 - '>'
                 - <
                 - '>='
                 - <=
                 type: string
          type: object
```

##### Generation Details
Command line used for generation
```shell
openapi-generator-cli generate \
  -g scala-sttp \
  -i name_of_file.yaml \
  -p mainPackage=myPackage \
  -o myApi
```

##### Steps to reproduce

Generated object `ConditionEnums`
```scala
object ConditionEnums {

  type Operator = Operator.Value
  object Operator extends Enumeration {
    val X3D = Value("&#x3D;")
    val X3D = Value("!&#x3D;")
    val Gt = Value("&gt;")
    val Lt = Value("&lt;")
    val Gtx3D = Value("&gt;&#x3D;")
    val Ltx3D = Value("&lt;&#x3D;")
  }
```

##### Suggest a fix

We can add name mapping for these encoded operators
