### ISSUE TITLE
[BUG][Go] Skip setting readOnly properties with default values in model constructors

### ISSUE THREAD

**Issue by code-lucidal58** [OpenAPITools/openapi-generator#10195]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

In Go client-side SDK, there are two model constructors, `New<model-name>()` and `New<model-name>WithDefaults()`. Both of these functions' purpose is to set properties with their default values, except that the former i.e. `New<model-name>()`, excludes required properties.
These functions are setting the default values for readOnly properties as well. This leads to the addition of such properties to the JSON request. Howver, readOnly properties should not be part of request for create and update requests. 

##### openapi-generator version

v5.2.1

##### OpenAPI declaration file content or url
```yaml
    ReadOnlyWithDefault:
      type: object
      properties:
        prop1:
          type: string
          readOnly: true
        prop2:
          type: string
          readOnly: true
          default: 'defaultProp2'
        prop3:
          type: string
          default: 'defaultProp3'
```
The generated Model constructors looks as follows:
```go
func NewReadOnlyWithDefault() *ReadOnlyWithDefault {
	this := ReadOnlyWithDefault{}
	var prop2 string = "defaultProp2"
	this.Prop2 = &prop2
	var prop3 string = "defaultProp3"
	this.Prop3 = &prop3
	return &this
}
```
However, it should look as below:
```go
func NewReadOnlyWithDefault() *ReadOnlyWithDefault {
	this := ReadOnlyWithDefault{}
	var prop3 string = "defaultProp3"
	this.Prop3 = &prop3
	return &this
}
```

##### Suggest a fix
Add a config flag: `skipReadonlyPropertiesInInt`, whose default value will be `false` to get the behaviour as it is right now. If this flag is `true` then skip readonly properties in the model constructors.
