### ISSUE TITLE
[BUG] composed schemas with type described do not set the correct isArray isObject etc booleans

### ISSUE THREAD

**Issue by spacether** [OpenAPITools/openapi-generator#10330]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ ] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

[BUG] composed schemas with type described do not set the correct isArray isObject etc booleans

##### openapi-generator version

5.2.1

##### OpenAPI declaration file content or url

Generate models for these components

```yaml
    ComposedObject:
      type: object
      allOf:
        - {}
    ComposedNumber:
      type: number
      allOf:
        - {}
    ComposedString:
      type: string
      allOf:
        - {}
    ComposedBool:
      type: boolean
      allOf:
        - {}
    ComposedArray:
      type: array
      items: {}
      allOf:
        - {}
    ComposedNone:
      type: 'null'
      allOf:
        - {}
```

##### Generation Details

Generate models for those components in any generator

##### Steps to reproduce

Generate models for those components in any generator

##### Suggest a fix

When those models are ingested, we should set the isArray etc booleans correctly on our codegenModel instance
