### ISSUE TITLE
[REQ] support for const keyword

### ISSUE THREAD

**Issue by jorgerod** [OpenAPITools/openapi-generator#10445]
### Is your feature request related to a problem? Please describe.

OpenAPI's Schema Object for **OAS 3.1** to use JSON Schema 2019-09, which includes the [const keyword](http://json-schema.org/draft/2020-12/json-schema-validation.html#rfc.section.6.1.3) (In this [PR: Defining constant value in response](https://github.com/OAI/OpenAPI-Specification/issues/1313)  the introduction of this keyword was discussed)

## Describe the solution you'd like

The OpenAPI Spec would looks like:

```yaml
components:
  schemas:
    UserBody:
      type: object
      properties:
        kind:  
          type: string
          const: MyConstant
        id:
          type: integer
        firstName:
          type: string
        lastName:
          type: string
```

## Describe alternatives you've considered

IMHO, define an enum attribute with a single value in the list is not the same.

## Related issues

https://github.com/OpenAPITools/openapi-generator/issues/1916
