### ISSUE TITLE
[BUG] [dart-dio-next] Map will nullable value

### ISSUE THREAD

**Issue by jaumard** [OpenAPITools/openapi-generator#10465]
I need to generate a Map of String, Object. So my definition look like this:

```yaml
template:
          type: object
          nullable: true
          additionalProperties:
            type: object
            nullable: true
```

I was expecting that 
```dart
@BuiltValueField(wireName: r'template')
BuiltMap<String, JsonObject?>? get template;
```
But got this:
```dart
@BuiltValueField(wireName: r'template')
BuiltMap<String, JsonObject>? get template;
```
So of course it crash a runtime when something null is on the map :(
