### ISSUE TITLE
[BUG] [dart-dio-next] `readOnly: true` is not considered for required fields

### ISSUE THREAD

**Issue by tiholic** [OpenAPITools/openapi-generator#10471]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

BuiltValues are validating for null if the field is added to `required` fields list. But if the field is `readOnly: true`, built value should not throw error if we are using the data for write operation. Any suggestions on how to achieve this?

##### openapi-generator version

`openapi-generator-cli 5.2.1`
`commit : 8403e59`

##### OpenAPI declaration file content or url
If you post the code inline, please wrap it with
```yaml
components:
  schemas:
    RefreshCredentials:
      type: object
      properties:
        access:
          type: string
          readOnly: true
        expires_in:
          type: number
          format: float
          readOnly: true
        refresh:
          type: string
          writeOnly: true
      required:
      - access
      - expires_in
      - refresh
```

##### Generation Details
generator: `dart-dio-next`

##### Steps to reproduce

run generator, then run build runner.

`refreh_credentials.dart` looks fine
```dart
  @BuiltValueField(wireName: r'access')
  String get access;

  @BuiltValueField(wireName: r'expires_in')
  double get expiresIn;

  @BuiltValueField(wireName: r'refresh')
  String get refresh;
```
but generated `refresh_credentials.g.dart` doesn't:

```dart
...
  @override
  _$RefreshCredentials build() {
    final _$result = _$v ??
        new _$RefreshCredentials._(
            access: BuiltValueNullFieldError.checkNotNull(
                access, 'RefreshCredentials', 'access'),                // <----- THIS LINE
            expiresIn: BuiltValueNullFieldError.checkNotNull(
                expiresIn, 'RefreshCredentials', 'expiresIn'),                // <----- THIS LINE
            refresh: BuiltValueNullFieldError.checkNotNull(
                refresh, 'RefreshCredentials', 'refresh'));
    replace(_$result);
    return _$result;
  }
```

Lines pointed above are to ensure access/expiresIn are not null while they are supposed to be when building the value for write.
