### ISSUE TITLE
[REQ][rust-server] Regex pattern validation for strings

### ISSUE THREAD

**Issue by Foorack** [OpenAPITools/openapi-generator#10546]
### Is your feature request related to a problem? Please describe.

Taking the following object as example:

```yaml
    UserID:
      type: string
      title: UserID
      pattern: '[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}'
```

The server then allows invalid user ID's which are not compliant with the defined pattern.
