### ISSUE TITLE
[BUG][csharp-netcore] Path level servers overrides are ignored 

### ISSUE THREAD

**Issue by hamermike** [OpenAPITools/openapi-generator#10639]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description
Path level servers overrides are ignored. Using the provided sample both `https://api.pet.com/v2` and `https://api.user.com/v2` are not included within the generated SDK. This is an issue with all specs tested.

##### OpenAPI declaration file content or url
[openapi-test.yaml.zip](https://github.com/OpenAPITools/openapi-generator/files/7376272/openapi-test.yaml.zip)

```yaml
servers:
- url: https://api.root.com/v3
# ... 
paths:
  /pet:
    servers:
      - url: https://api.pet.com/v2
   # ...
   /user:
    servers:
      - url: https://api.user.com/v2
```

##### Generation Details
`openapi-generator-cli generate -g csharp-netcore -i openapi-test.yaml -o sdk-test`

##### Steps to reproduce
1. Generate the SDK using the provided spec.
2. Verify that the generated SDK ignores servers defined within paths.

##### Related issues/PRs
Related issue from 2018 with a different SDK https://github.com/OpenAPITools/openapi-generator/issues/1694.

##### Suggest a fix
Servers defined within paths should be used for those paths which have been defined.
