### ISSUE TITLE
[BUG][rust-reqwest] Explode param is not handled

### ISSUE THREAD

**Issue by mickaelmagniez** [OpenAPITools/openapi-generator#10689]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [X] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Even if openapi specs is 
```yaml
explode: true
```

Params value is sent has a comma delimited value `param=value1,value2`, should be `param=value1&param=value2`

##### openapi-generator version
5.3.0

##### OpenAPI declaration file content or url

```yaml
  parameters:
    - name: tags
      in: query
      description: Tags to filter by
      required: true
      style: form
      explode: true
      schema:
        type: array
        items:
          type: string
```

##### Generation Details

```bash
$ ./bin/generate-samples.sh ./bin/configs/rust-reqwest-petstore-explode.yaml

$ cat ./samples/client/petstore/rust/reqwest/petstore-explode/src/apis/pet_api.rs |grep tags
```
