### ISSUE TITLE
[BUG]  JDK17 does not have JavaTimeFormatter

### ISSUE THREAD

**Issue by dstibbe** [OpenAPITools/openapi-generator#10828]
##### Description

Generating a client using the openapi-generator-maven-plugin results in an APIClient that extends JavaTimeFormatter. However,  this class  is not available in JDK17.

##### openapi-generator version

openapi-generator-maven-plugin: 5.3.0

##### OpenAPI declaration file content or url

```yaml
{
  "openapi": "3.0.1",
  "info": {
    "title": "Some API"
  },
  "paths": {
    "/api/x": {
      "post": {
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/TheModel"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "TheModel": {        
        "type": "object",
        "properties": {
          "timeStarted": {
            "type": "string",
            "format": "date-time"
          },
          "timeSubmitted": {
            "type": "string",
            "format": "date-time",
            "nullable": true
          },
          "timePublished": {
            "type": "string",
            "format": "date-time",
            "nullable": true
          }
        }
      }
    }
  }
}
```

##### Generation Details
```xml
<plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>infocaster-service</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <apiPackage>some.api</apiPackage>
                            <generateApiTests>false</generateApiTests>
                            <generateApiDocumentation>false</generateApiDocumentation>
                            <skipValidateSpec>true</skipValidateSpec>
                            <modelPackage>some.api.model</modelPackage>
                            <generateModelTests>false</generateModelTests>
<supportingFilesToGenerate>ApiClient.java,Authentication.java,HttpBasicAuth.java,HttpBearerAuth.java,ApiKeyAuth.java,RFC3339DateFormat.java
                            </supportingFilesToGenerate>
                            <generateModelDocumentation>false</generateModelDocumentation>
                            <inputSpec>${project.basedir}/src/main/resources/some-api.yaml</inputSpec>
                            <generatorName>java</generatorName>
                            <library>resttemplate</library>
                            <configOptions>
                                <dateLibrary>java8</dateLibrary>
                                <useOptional>true</useOptional>
                                <useBeanValidation>true</useBeanValidation>
                                <hideGenerationTimestamp>true</hideGenerationTimestamp>
                            </configOptions>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

##### Steps to reproduce

```mvn clean install```

##### Related issues/PRs

-

##### Suggest a fix

Have the generator use OffsetDateTime.
