### ISSUE TITLE
[REQ] Document how import mappings work for TS

### ISSUE THREAD

**Issue by aryzing** [OpenAPITools/openapi-generator#10887]
### Is your feature request related to a problem? Please describe.

I just can't get the import mappings to work in TS (`typescript-fetch`) -- are they even supported?. They seem to be completely ignored. 

I'm trying to use a custom model already defined in the code. I've tried various combinations of `typeMappings`, `languageSpecificPrimitives` and `importMappings`, but the result is always the same: the import maps are completely ignored and the models end up being imported from `./`, which causes an error as they're not defined there.

## Describe the solution you'd like

Clear documentation as to how import mappings work with TS, or document that they don't work / are not available.

## Describe alternatives you've considered

Created a [post on stackoverflow](https://stackoverflow.com/questions/70011098/how-does-importmappings-work-for-typescript-fetch) regarding this issue.

## Additional context

This is the config I've been playing around with. The import maps seem to have no effect on the generated code.

```yaml
inputSpec: openapi.yaml
outputDir: generated
generatorName: typescript-fetch
typeMappings:
  User: ApiUser
languageSpecificPrimitives:
  - User
importMappings:
  User: "src/User.ts"
  ApiUser: "src/User.ts"
additionalProperties:
  supportsES6: "true"
  typescriptThreePlus: "true"
```
