### ISSUE TITLE
[BUG] [C-libcurl] The parameter "import mappings" does not take effect

### ISSUE THREAD

**Issue by ityuhui** [OpenAPITools/openapi-generator#10994]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

I use below command line to generate a c-libcurl client with the parameters
--type-mappings "int-or-string=IntOrString" 
--import-mappings "IntOrString=../custom-model/int_or_string 

```shell
java -DdebugModels -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -i /root/swagger.json   -g c    -o /root/output --skip-validate-spec --type-mappings "int-or-string=IntOrString" --import-mappings "IntOrString=../custom-model/int_or_string"
```

The `type-mappings` takes effect but `import-mappings` does not.

```c
#include "int_or_string.h"    <---- This should be "../custom-model/int_or_string.h"

typedef struct v1_service_port_t {
...
    int_or_string_t *target_port; 
}
```

I think this is a bug or "import mappings" is not implemented for the C-libcurl generator.

Hi @wing328 @zhemant 

Could you please give any advice to fix this issue ?

Maybe it shoud be implemented in the file [CLibcurlClientCodegen.java](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CLibcurlClientCodegen.java)

##### openapi-generator version

master

##### OpenAPI declaration file content or url

```yaml
    "intstr.IntOrString": {
      "description": "IntOrString is a type that can hold an int32 or a string.  When used in JSON or YAML marshalling and unmarshalling, it produces or consumes the inner type.  This allows you to have, for example, a JSON field that can accept a name or number.",
      "format": "int-or-string",
      "type": "string"
    },
...

        "targetPort": {
          "$ref": "#/definitions/intstr.IntOrString",
          "description": "Number or name of the port to access on the pods targeted by the service. Number must be in the range 1 to 65535. Name must be an IANA_SVC_NAME. If this is a string, it will be looked up as a named port in the target Pod's container ports. If this is not specified, the value of the 'port' field is used (an identity map). This field is ignored for services with clusterIP=None, and should be omitted or set equal to the 'port' field. More info: https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service"
        }


```
