### ISSUE TITLE
[BUG][aspnetcore] Wrong Enum definition

### ISSUE THREAD

**Issue by sedainterxion** [OpenAPITools/openapi-generator#11118]
##### Description

It creates the enum successfully. But then if there is a property that is a list of the enum, the generator tries to define the enum again. 

##### openapi-generator version

5.3.0

##### OpenAPI declaration file content or url
```
components:
  schemas:
    Connection:
      description: Connection
      properties:
        id:
          maxLength: 80
          type: string
        name:
          maxLength: 80
          type: string
        outer_vlan_ethertypes:
          description: "The ethertype of the outer tag in hexadecimal notation."
          example:
            - "0x8100"
          items:
            default: "0x8100"
            enum:
              - "0x8100"
              - "0x88a8"
              - "0x9100"
            type: string
          type: array
      title: Connection
      type: object
```
##### Generation Details

![image](https://user-images.githubusercontent.com/36731383/145985863-385279b2-b40f-49ea-bc30-d1815ab0bfa9.png)
