### ISSUE TITLE
[REQ][Python] deserialize and expose response even if it's not a 2xx code

### ISSUE THREAD

**Issue by davidstosik** [OpenAPITools/openapi-generator#11137]
### Is your feature request related to a problem? Please describe.

We have endpoints that sometimes return error codes with more details in the body, for example:
```yaml
        "403":
          description: The user is not allowed to post an article.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      key:
                        type: string
                        description: A key that represents the type of error returned.
                        enum:
                          - unconfirmed
                          - blocked
                      message:
                        type: string
                        description: A human-readable error.
                        example: The user needs to confirm their account first.
```

Another example could be a 422 (unprocessable entity) response on post, where the body describes what was wrong with the data that was submitted (for example "title is required" or "format is invalid", etc).

## Describe the solution you'd like

There are two tenants I guess.

1. Maybe it's not necessary to raise exceptions when the clients meets response codes that are [not 2xx](https://github.com/OpenAPITools/openapi-generator/blob/97e079fde0dd6cb3f589e1d80254c432642927dd/modules/openapi-generator/src/main/resources/python/rest.mustache#L206)? I'd be interested to see if there's a possibility to have endpoint methods that will just return a clean response object, whatever the code is.
2. Even if the the client keeps throwing exceptions for error responses, it would be nice if I could access more than the raw body or status. As a matter of fact, the generator generated an `InlineResponse403` object, but it is not using it anywhere!

## Describe alternatives you've considered

Ideally, I'd love to see a client that allows me to do this:

```python
response = api_instance.article_get(1)
if(!response.success): # qualified by a 2xx response
    # handle_failure
else:
    print("The article's title is: " + response.data.title)

response = api_instance.article_post("Article Title", body)
if(!response.success):
    for error in response.data.errors:
        print(error.message)

try:
    response = api_instance.article_get(1, throw_exception=True)
except ApiException as e:
    # Handle exception
```

## Additional context

I don't necessarily want to enter a debate on whether one should use exceptions for flow control or not (I'll accept there are different schools – [a good read if you're interested anyway](https://softwareengineering.stackexchange.com/questions/189222/are-exceptions-as-control-flow-considered-a-serious-antipattern-if-so-why)), but in my opinion, scenarios that are known (documented), and likely to happen in a fully functional software aren't really a match with what the word "exception" means to me. But anyway, it would be nice to have the choice, or, at the very least to be able to use the response similarly whatever the response code is (even if I need a `try:`/`except:`).
