### ISSUE TITLE
[JAVA] Spring generator generates "defaultValue" for query parameters

### ISSUE THREAD

**Issue by vitkep** [OpenAPITools/openapi-generator#11219]
##### Description

I'm trying to generate stubs for a spring-boot petstore sample application using currently released and latest version 5.3.1 of the OpenAPI Generator Gradle Plugin. My intention is to migrate the application to OAS3. My swagger file contains specification of a query parameter of type "enum" and a default value for this parameter. The OpenApi Generator generates as expected OAS3 code. But it generates `defaultValue` method for `@Parameter` interface, which doesn't have `defaultValue` since OAS3 anymore. This causes a compile error.

Used technologies:
- Java
- Gradle
- Spring Boot
- OpenApi Sping generator

##### openapi-generator version

5.3.1

##### OpenAPI declaration file content or url

A snippet from my Swagger file with query parameter specification:
```yaml
      parameters:
        - name: status
          in: query
          description: Status values that need to be considered for filter
          required: false
          explode: true
          schema:
            type: string
            enum:
              - available
              - pending
              - sold
            default: available
```
Snippet from my generator config:
```
    generatorName = 'spring'
    configOptions = [
            useSpringfox           : 'false',
            useSpringController    : 'true',
            oas3                   : 'true',
            dateLibrary            : 'java8',
            interfaceOnly          : 'true',
            skipDefaultInterface   : 'true',
            serializableModel      : 'true',
            delegatePattern        : 'false',
            hideGenerationTimestamp: 'true',
            useTags                : 'true',
            library                : 'spring-cloud'
    ]
```

##### Command line used for generation

Generation via gradle task

##### Steps to reproduce

Generate code with OpenAPI Generator Gradle Plugin 5.3.1

##### Suggest a fix/enhancement

After generation I get compile error, because `@Parameter` interface doesn't have `defaultValue`method.

Generated method:
```java
    ResponseEntity<List<Pet>> findPetsByStatus(
             @Parameter(
                     name = "status", 
                     description = "Status values that need to be considered for filter", 
                     schema = @Schema(allowableValues = "available, pending, sold"), 
                     defaultValue = "available") 
             @Valid @RequestParam(value = "status", required = false, defaultValue = "available") String status
```
I'm not sure if it is a bug or a wrong configuration. But I suppose it is a bug, because `defaultValue` will be generated for `@ApiParam` for OAS2. I assume `defaultValue` should be generated for `@Schema`.
