### ISSUE TITLE
[BUG] Typescript-Angular generated package.json dependency problems

### ISSUE THREAD

**Issue by ttimot24** [OpenAPITools/openapi-generator#11233]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [X] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description
Currently in package.json angular 13 requires typescript >= 4.4.2 but the tsickle requires max 4.3.x

##### openapi-generator version
5.3.1

**Comment by tobiashochguertel** [comment]
With the current master / docker image `:latest` the package.json of the generator `typescript-angular` is broken because the dependecy `tsickle` doesn't get a version number. 

![grafik](https://user-images.githubusercontent.com/3332669/207855200-26e0ba8b-b3a2-4baf-9c18-f2aab27e06f7.png)

to reproduce the issue:

```
.generate:
  stage: generate
  tags:
    - shell
  script:
    - docker run --rm --user 1000:1000 -v "${PWD}:/local" openapitools/openapi-generator-cli generate -t /local/templates/$GENERATOR  -c /local/openapi/config.$GENERATOR.yaml -i /local/$INPUT_SPEC -o /local/openapi-build/$GENERATOR
    - ls -lha ./openapi-build/$GENERATOR
    - test -f ./openapi-build/$GENERATOR/package.json && cat ./openapi-build/$GENERATOR/package.json
```

File: `config.typescript-angular.yaml`
```yaml
---
generatorName: typescript-angular
npmRepository: https://npm.pkg.hochguertel.work/
npmName: quiz_api_ts-angular
supportsES6: true
useSingleRequestParameter: false
```

File: `package.json` _with current :latest docker image of openapi generator_
```
{
  "name": "quiz_api_ts-angular",
  "version": "1.1.0",
  "description": "OpenAPI client for quiz_api_ts-angular",
  "author": "OpenAPI-Generator Contributors",
  "repository": {
    "type": "git",
    "url": "https://github.com/GIT_USER_ID/GIT_REPO_ID.git"
  },
  "keywords": [
    "openapi-client",
    "openapi-generator"
  ],
  "license": "Unlicense",
  "scripts": {
    "build": "ng-packagr -p ng-package.json"
  },
  "peerDependencies": {
    "@angular/core": "^15.0.3",
    "rxjs": "^7.5.5"
  },
  "devDependencies": {
    "@angular/common": "^15.0.3",
    "@angular/compiler": "^15.0.3",
    "@angular/compiler-cli": "^15.0.3",
    "@angular/core": "^15.0.3",
    "@angular/platform-browser": "^15.0.3",
    "ng-packagr": "^15.0.2",
    "reflect-metadata": "^0.1.3",
    "rxjs": "^7.5.5",
    "tsickle": "^",
    "typescript": ">=4.8.2 <4.10.0",
    "zone.js": "^0.11.5"
  },
  "publishConfig": {
    "registry": "https://npm.pkg.hochguertel.work/"
  }
}
```


----

with version 6.2.1 of openapi-generator it was working:

File: `package.json` _with version 6.2.1 of openapi-generator_
```
.generate:
  stage: generate
  tags:
    - shell
  script:
    - docker run --rm --user 1000:1000 -v "${PWD}:/local" openapitools/openapi-generator-cli:v6.2.1 generate -t /local/templates/$GENERATOR  -c /local/openapi/config.$GENERATOR.yaml -i /local/$INPUT_SPEC -o /local/openapi-build/$GENERATOR
    - ls -lha ./openapi-build/$GENERATOR
    - test -f ./openapi-build/$GENERATOR/package.json && cat ./openapi-build/$GENERATOR/package.json
```

File: `package.json`
```
{
  "name": "quiz_api_ts-angular",
  "version": "1.1.0",
  "description": "OpenAPI client for quiz_api_ts-angular",
  "author": "OpenAPI-Generator Contributors",
  "repository": {
    "type": "git",
    "url": "https://github.com/GIT_USER_ID/GIT_REPO_ID.git"
  },
  "keywords": [
    "openapi-client",
    "openapi-generator"
  ],
  "license": "Unlicense",
  "scripts": {
    "build": "ng-packagr -p ng-package.json"
  },
  "peerDependencies": {
    "@angular/core": "^14.0.5",
    "rxjs": "^7.5.5"
  },
  "devDependencies": {
    "@angular/common": "^14.0.5",
    "@angular/compiler": "^14.0.5",
    "@angular/compiler-cli": "^14.0.5",
    "@angular/core": "^14.0.5",
    "@angular/platform-browser": "^14.0.5",
    "ng-packagr": "^14.0.2",
    "reflect-metadata": "^0.1.3",
    "rxjs": "^7.5.5",
    "tsickle": "^0.46.3",
    "typescript": ">=4.6.0 <=4.8.0",
    "zone.js": "^0.11.5"
  },
  "publishConfig": {
    "registry": "https://npm.pkg.hochguertel.work/"
  }
}
```
