### ISSUE TITLE
[BUG] [JAVA] OAS3 incorrect data type when providing a default value

### ISSUE THREAD

**Issue by kevinparaport** [OpenAPITools/openapi-generator#11367]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When providing a default value, UI is saying the value is a string when it's an integer. Example JSON shows the variable as the correct data type though.

##### openapi-generator version

5.3.1

##### OpenAPI declaration file content or url

<!-- if it is a bug, a json or yaml that produces it.
If you post the code inline, please wrap it with
```yaml
- name: page
          in: query
          description: Zero-based page index of results to return
          required: false
          schema:
            type: integer
            format: int32
            default: 100
```
(for YAML code) or

##### Generation Details

Using OAS3 = true

##### Related issues/PRs

https://github.com/OpenAPITools/openapi-generator/pull/9775

##### Suggest a fix/enhancement

My guess is that the OAS3 changes for Java just aren't setting the type correctly in the mustache templates.

![incorrectdatatype](https://user-images.githubusercontent.com/77290090/150474239-e9e78488-726d-427b-8f8e-c13efc174ed8.PNG)
![correctdatatype](https://user-images.githubusercontent.com/77290090/150474245-ea9bbb59-2c21-4131-89e8-a37d309bb236.PNG)
