### ISSUE TITLE
[BUG] [JAVA] [SPRING] Optional values aren't optional in POJOs, only in path params

### ISSUE THREAD

**Issue by welshm** [OpenAPITools/openapi-generator#11383]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?

##### Description

Optional values aren't optional in POJOs, only in path params.

##### openapi-generator version

5.3.0

##### OpenAPI declaration file content or url

`modules/openapi-generator/src/test/resources/3_0/petstore-with-nullable-required.yaml`

##### Generation Details

```
generatorName: spring
outputDir: samples/openapi3/server/petstore/springboot-nullable
inputSpec: modules/openapi-generator/src/test/resources/3_0/petstore-with-nullable-required.yaml
templateDir: modules/openapi-generator/src/main/resources/JavaSpring
additionalProperties:
  groupId: org.openapitools.openapi3
  documentationProvider: springdoc
  artifactId: springboot
  snapshotVersion: "true"
  hideGenerationTimestamp: "true"
  openApiNullable: "true"
  useOptional: "true"
```

##### Steps to reproduce

Generate POJOs

##### Suggest a fix
Update `pojo.mustache` to enable optional fields and any updates required for nullables
