### ISSUE TITLE
[BUG][CSHARP-NETCORE] Type boolean with enum constraint produces incorrect code.

### ISSUE THREAD

**Issue by jafin** [OpenAPITools/openapi-generator#11393]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [X] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

In an API, that constrains a boolean to true (via enum), it will produce invalid code when using the csharp-dotnet generator.

##### openapi-generator version

openapi-generator-cli-5.4.0-20220124.094022-41.jar
openapi-generator-cli-6.0.0-20220104.102705-29.jar

##### OpenAPI declaration file content or url

```yaml
 CurrencyUpdate:
      type: object
      properties:
        default:
          type: boolean
          nullable: true
          format: boolean
          example: true
          enum:
            - true
```
##### Generation Details

Output:
```c#
        [JsonConverter(typeof(StringEnumConverter))]
        public enum DefaultEnum
        {
            /// <summary>
            /// Enum True for value: true
            /// </summary>
            True = true
        }
```

##### Steps to reproduce

```shell
java -jar openapi-generator-cli-5.4.0-20220124.094022-41.jar generate -i https://api-docs.firefly-iii.org/firefly-iii-1.5.4.yaml -g csharp-netcore -o ./output/
```
