### ISSUE TITLE
[go-server] Support go custom tags

### ISSUE THREAD

**Issue by andrewkav** [OpenAPITools/openapi-generator#1145]
##### Description
Sometimes there is a necessity to add extra tags to generated models. For example when using validators based on go tags.
Example of generated code:
```go
type SomeStruct struct {
	ID string `json:"id,omitempty" validate:"required"`
}
```

##### openapi-generator version
3.3.0

##### OpenAPI declaration file content or url
-

##### Command line used for generation
-

##### Steps to reproduce
-

##### Related issues/PRs
-

##### Suggest a fix/enhancement
Suggesting to use vendor extension `x-go-custom-tag` to include the tag into generated model
example of YAML
```yaml
    SomeStruct:
      type: object
      properties:
        id:
          type: string
          x-go-custom-tag: validate:"required"
```
