### ISSUE TITLE
[BUG] KOTLIN URI gerneration for URIs with default value misses the package info and uses wrong quotes.

### ISSUE THREAD

**Issue by StefanMMS** [OpenAPITools/openapi-generator#11469]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

If the openAPI Spec contains a URI Property with a default value the codegenerator generates code with missing package description and wrong quotes.

##### openapi-generator version

Version 5.4.0

##### OpenAPI declaration file content or url

```yaml
Problem:
      type: object
      required:
        - status
        - title
      properties:
        type:
          type: string
          format: uri
          description: |
            An absolute URI that identifies the problem type.  When dereferenced,
            it SHOULD provide human-readable documentation for the problem type
            (e.g., using HTML).
          default: "about:blank"
...
```

##### Generation Details

The model class generated includes following code:

```kotlin
    /* An absolute URI that identifies the problem type.  When dereferenced, it SHOULD provide human-readable documentation for the problem type (e.g., using HTML).  */
    @field:JsonProperty("type")
    val type: java.net.URI? = URI.create('about:blank'),
```

##### Suggest a fix

The generated code should look like:
```kotlin
    /* An absolute URI that identifies the problem type.  When dereferenced, it SHOULD provide human-readable documentation for the problem type (e.g., using HTML).  */
    @field:JsonProperty("type")
    val type: java.net.URI? = java.net.URI.create("about:blank"),
```
