### ISSUE TITLE
[BUG] Exception in thread "main" java.lang.RuntimeException: Could not process model

### ISSUE THREAD

**Issue by simllll** [OpenAPITools/openapi-generator#11514]
##### Description

Exception in thread "main" java.lang.RuntimeException: Could not process model 'IInterviewQuestion'.Please make sure that your schema is correct!
        at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:492)
        at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:888)
        at org.openapitools.codegen.cmd.Generate.execute(Generate.java:441)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -9
        at java.base/java.lang.String.substring(String.java:1841)
        at org.openapitools.codegen.languages.TypeScriptAxiosClientCodegen.postProcessModels(TypeScriptAxiosClientCodegen.java:233)
        at org.openapitools.codegen.DefaultGenerator.processModels(DefaultGenerator.java:1302)
        at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:487)
        ... 4 more

##### openapi-generator version

Works with 5.3.1 and lower, but does not work with 5.4

##### OpenAPI declaration file content or url

excerpt, if I remove "moduleOptions" it works again.
```
IInterviewQuestion:
      properties:
        identifier:
          type: string
          description: 'this is the question id (NO object id, includes step id)'
        baseIdentifier:
          type: string
          description: 'this is the base of the question id (no step id included)'
        _id:
          type: string
          deprecated: true
        sourceId:
          type: string
          description: 'source id to reidentify a question'
        module:
          type: string
        moduleOptions:
          properties: {}
          additionalProperties:
            anyOf:
              -
                type: string
              -
                type: number
                format: double
              -
                type: boolean
            nullable: true
          type: object
```

##### Generation Details

typescript-axios

`openapi-generator-cli generate -t openapi-template -p apiPackage=apipkg -p modelPackage=modelPkg -p withSeparateModelsAndApi=true -p modelPropertyNaming=original -p supportsES6=true -i ../../services/admin-api/dist/swagger/swagger.yaml -g typescript-axios -o src/api-client 

`
