### ISSUE TITLE
[BUG][Customization] "folder" custom template parameter gets ignored

### ISSUE THREAD

**Issue by OnkelTem** [OpenAPITools/openapi-generator#11794]
I use this configuration file to generate additional files for each API in a new "state" sub-directory:

```yaml
templateDir: openapi-templates
files:
  asd.mustache:
    folder: state
    templateType: API
    destinationFilename: Asd.ts
```

But I get all the files right in the "api" directory. I also tried using relative path "../state" but it didn't work out.

At the same time, using `SupportingFiles` type does create custom folders, but it's useless in my case, as I need to create special files for each API: state, slice, sagaes etc.
