### ISSUE TITLE
[BUG][JAVA]: date-time format should use pattern when provided (JavaSpring generator)

### ISSUE THREAD

**Issue by cbommb** [OpenAPITools/openapi-generator#11853]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When a pattern in provided for date-time format properties, it should be used instead of defaulting to `DateTimeFormat.ISO.DATE_TIME`.
The current behavior makes it impossible to use any other format. 

##### openapi-generator version

5.4.0
##### OpenAPI declaration file content or url

```yaml
schemas:
  Metadata:
    description: some meta
    type: object
    properties:
      created:
        description: A valid date-time representation as defined by RFC 3339
        type: string
        format: date-time
        pattern: yyyy-MM-dd HH:mm:ss
```

##### Steps to reproduce

using above yaml template generates :

```java
@JsonProperty("created")
@DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME))
private OffsetDateTime created
```
instead I expect to generate :
```java
@JsonProperty("created")
@DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
private OffsetDateTime created;
```

##### Suggest a fix

in https://github.com/OpenAPITools/openapi-generator/blob/v5.4.0/modules/openapi-generator/src/main/resources/JavaSpring/pojo.mustache

the following code :
```
{{#isDateTime}}
@DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME)
{{/isDateTime}}

```

could be improved with :
```
{{#isDateTime}}
{{#pattern}}
@DateTimeFormat(pattern = "{{pattern}}")
{{/pattern}}
{{^pattern}}
@DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME)
{{/pattern}}
{{/isDateTime}}
```
