### ISSUE TITLE
[BUG] Handle empty string for non-required query parameter

### ISSUE THREAD

**Issue by metalmatze** [OpenAPITools/openapi-generator#11883]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### openapi-generator version

v5.4.0

##### OpenAPI declaration file content or url

```yaml
  /objectives/alerts:
    get:
      summary: Get the MultiBurnrateAlerts for the Objective
      operationId: GetMultiBurnrateAlerts
      tags:
        - objectives
      parameters:
        - in: query
          name: expr
          required: true
          schema:
            type: string
        - in: query
          name: grouping
          required: false
          schema:
            type: string
        - in: query
          name: inactive
          required: false
          schema:
            type: boolean
            default: false
```

It's about the last query parameter called _inactive_ here.

The problem seems to be, that even though the parameter isn't required the code doesn't handle a non existing `&inactive` in the URL and instantly returns `500 internal server error`

https://github.com/OpenAPITools/openapi-generator/blob/941d4845d73536473ac6ef63ebaa6e762bdf0606/modules/openapi-generator/src/main/resources/go-server/routers.mustache#L201-L209

##### Generation Details

`docker run openapitools/openapi-generator-cli:v5.4.0`

##### Steps to reproduce

This first one works as the parameter doesn't have an empty string but `f`
http://localhost:9099/api/v1/objectives/alerts?expr=&inactive=f 
The second one doesn't work, as the string is `""` and that results in a parse error.
http://localhost:9099/api/v1/objectives/alerts?expr=&inactive=

Here's the Go stdlib for parsing the boolean that returns a syntaxError:
https://cs.opensource.google/go/go/+/refs/tags/go1.18:src/strconv/atob.go;l=10

##### Suggest a fix

Something similar to other types should be just fine. For example:
https://github.com/OpenAPITools/openapi-generator/blob/941d4845d73536473ac6ef63ebaa6e762bdf0606/modules/openapi-generator/src/main/resources/go-server/routers.mustache#L184-L191
