### ISSUE TITLE
[BUG] uint64 maximum 1.844...e+19 is parsed as 384 (overflow error)

### ISSUE THREAD

**Issue by felixvd** [OpenAPITools/openapi-generator#11940]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Large integers in the OpenAPI specification are not read in correctly.

I am generating a client from a spec that specifies the `uint64` maximum `1.8446744073709552e+19`, but the value is parsed as `384`.

##### openapi-generator version

5.4.0

##### OpenAPI declaration file content or url

Just add the `size` property to `petstore.yaml`, so it looks like this:

```yaml
[...]
        status:
          type: string
          description: pet status in the store
          deprecated: true
          enum:
            - available
            - pending
            - sold        
        size:
          description: in bytes
          maximum: 1.8446744073709552e+19
          minimum: 0
          type: integer
      xml:
        name: Pet
    ApiResponse:
      title: An uploaded response
[...]
```

##### Generation Details

`openapi-generator-cli generate -i petstore.yaml -g python`

##### Steps to reproduce

The steps above produce this code:

```python
    validations = {
        ('size',): {
            'inclusive_maximum': 384,
            'inclusive_minimum': 0,
        },
    }
```

`inclusive_maximum` should be `1.8446744073709552e+19` instead.

##### Related issues/PRs

https://github.com/OpenAPITools/openapi-generator/issues/10620 is very similar.

##### Suggest a fix

I don't know where it happens, but it is clearly an overflow error. For `1.844e+19`, the generated code is `'inclusive_maximum': -6744073709551616,`.
