### ISSUE TITLE
[BUG][Kotlin] Nullable attribute is ignored if field is not required

### ISSUE THREAD

**Issue by ggajews** [OpenAPITools/openapi-generator#11962]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When generating model with fields not required nullable attribute is ignored

##### openapi-generator version

5.3.0

##### OpenAPI declaration file content or url

```yaml
components:
  schemas:
    Cat:
          type: object
          xml:
            name: cat
          properties:
            id:
              type: integer
              format: int64
              nullable: false
            name:
              type: boolean
              nullable: true
```

##### Steps to reproduce

Generate this class. Expected result:
```kotlin
data class Cat (

    @SerializedName("id")
    val id: kotlin.Long,

    @SerializedName("name")
    val name: kotlin.Boolean? = null

)
```
actual:

```kotlin
data class Cat (

    @SerializedName("id")
    val id: kotlin.Long? = null,

    @SerializedName("name")
    val name: kotlin.Boolean? = null

)
```

##### Related issues/PRs

https://github.com/OpenAPITools/openapi-generator/issues/4530

##### Suggest a fix

Copy the solution from `/data_class_req_var.mustache` to `data_class_opt_var.mustache`
```
{{#isNullable}}?{{/isNullable}}{{#defaultValue}} = {{{.}}}{{/defaultValue}}
```
