### ISSUE TITLE
generator "spring" writes sourceFolder property not back into pom.xml (Batch-Mode)

### ISSUE THREAD

**Issue by s-Klein-DG** [OpenAPITools/openapi-generator#12052]
Iam using Docker-Image "openapitools/openapi-generator-cli:v5.3.0" for Code-Generation.

**Description**
I placed theOriginal [petstore.yaml](https://github.com/OpenAPITools/openapi-generator-cli/blob/master/examples/v3.0/petstore.yaml) in dir: 
"~/example/volume/spec-files/petstore.yaml" 

**Batch-Generation-Config in dir**
"~/example/volume/generator-configs/pestore-server.yaml"

**~/example/volume/generator-configs/pestore-server.yaml"**
```
inputSpec: ./volume/spec-files/petstore.yaml
outputDir: ./generated/java/spring/server-demo
generatorName: spring
artifactId: petstore-demo-server
artifactVersion: 0.0.1
groupId: de.demo
additionalProperties:
  snapshotVersion: false
  useBeanValidation: true
  library: spring-boot
  sourceFolder: src/gen/java/main
  interfaceOnly: true
  artifactUrl: https://not-set-demo.de
  basePackage: de.demo.server
  apiPackage: de.demo.server.api
  modelPackage: de.demo.server.model
  configPackage: de.demo.server.config
  unhandledException: true
  hideGenerationTimestamp: true
  dateLibrary: java8
  serializableModel: true
```
Than these steps (validation and code-gen): 
Spin up a container in interactive mode with a volume mount to "~/example/volume/" Container-Internally as "/volume" 
```
docker run -it -rm -v "${PWD}/volume:/volume" --entrypoint /bin/bash --rm openapitools/openapi-generator-cli:v5.3.0 
```
create a alias for the entrypoint of the generator image.
```
alias openapi-generator='/usr/local/bin/docker-entrypoint.sh'
```
test if the generator prints out the help information, to see if its working
```
openapi-generator --help
```
validate your Spec-File:
```
openapi-generator validate -i /volume/spec-files/petstore.yaml
```
Generate-Code
```
openapi-generator batch ./volume/generator-configs/*.yaml"
```

As Result the code is generated, but the sourceDirectory Tag in generated pom.xml is not set to the value of the Additional-Property -> "sourceFolder: src/gen/java/main".
the default is set here in pom.xml to "src/main/java".

But [Dokumentation](https://openapi-generator.tech/docs/generators/spring) says that this value should reflect into pom of the generated code.
