### ISSUE TITLE
[Kotlin][typescript-fetch] Bug Invalid date when parsing JSON in typescript

### ISSUE THREAD

**Issue by greenbourne277** [OpenAPITools/openapi-generator#12116]
##### Description
I use my OpenAPI declaration for generating Kotlin code and Typescript code. 
My Kotlin code provides an API that returns JSON. The API is called by my Frontend. The generated typescript code fails to parse date and date-time datatypes  correctly. Instead it results in 'Invalid Date'.

##### openapi-generator version

5.4.0

##### OpenAPI declaration file content or url

```yaml
RightRest:
  required:
    - startDate
  type: object
  properties:
    createdOn:
      type: string
      format: date-time
    endDate:
      type: string
      format: date
    lastUpdatedOn:
      type: string
      format: date-time
    startDate:
      type: string
      format: date
```

The JSON my backend returns:

```json
{"startDate":{"year":2022,"month":1,"day":1},
"createdOn":{"dateTime":{"date":{"year":2022,"month":4,"day":7},"time":{"hour":7,"minute":51,"second":55,"nano":542397000}},"offset":{"totalSeconds":0}},
"endDate":{"year":2023,"month":1,"day":1},
"lastUpdatedOn":{"dateTime":{"date":{"year":2022,"month":4,"day":7},"time":{"hour":7,"minute":51,"second":55,"nano":542397000}},"offset":{"totalSeconds":0}}}     
```

The generated code in Typescript that fails to parse JSON:
```ts
export function RightRestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RightRest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {    
        'createdOn': !exists(json, 'createdOn') ? undefined : (new Date(json['createdOn'])),
        'endDate': !exists(json, 'endDate') ? undefined : (new Date(json['endDate'])),
        'lastUpdatedOn': !exists(json, 'lastUpdatedOn') ? undefined : (new Date(json['lastUpdatedOn'])),
        'startDate': (new Date(json['startDate'])),
    };
}

```
##### Command line used for generation
I'm using the Gradle plugin.

Kotlin generation:
```kotlin
openApiGenerate {
    inputSpec.set("$projectDir/src/main/openapi/openapi.yaml")
    outputDir.set("$buildDir/generated")
    generatorName.set("kotlin")
    apiPackage.set("de.zbw.lori.api.v1")
    modelPackage.set("de.zbw.lori.model")
    configOptions.set(mapOf(
        Pair("dateLibrary", "java8")
    ).toMutableMap())
}
```

Typescript generation:

```kotlin
openApiGenerate {
    inputSpec.set("${project(":app:lori:api").projectDir.path}/src/main/openapi/openapi.yaml")
    outputDir.set("$projectDir/src/generated-sources/openapi")
    generatorName.set("typescript-fetch")
    val npmVersion by System.getProperties()
    additionalProperties.set(
        mapOf(
            Pair("supportsES6", "true"),
            Pair("npmVersion", "$npmVersion"),
            Pair("typescriptThreePlus", "true")
        ).toMutableMap()
    )
}

```

##### Suggest a fix/enhancement
Maybe the Kotlin generator provides an option to generate a different type of JSON which Typescript is able to understand?
