### ISSUE TITLE
 [BUG] [Dart] additional properties of type: object doesn't generate with mapCastOfType

### ISSUE THREAD

**Issue by 0xNF** [OpenAPITools/openapi-generator#12165]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

The `additionalProperties` field, which specified a `Map<T1, T2>` in Dart, doesn't generate properly by fields defined by 
```yaml
schema:
   type: string
   additionalProperties:
      type: object
```

##### openapi-generator version
6.0.0

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.3
info:
  version: "1.1"
  title: Dart MappedValue Fail
servers:
  - url: 'localhost'
    variables:
      host:
        default: localhost
components:
  schemas:
    ItemGood:
      type: object
      properties:
        mappedProps:
          type: string
          additionalProperties:
            type: string
    ItemBad:
      type: object
      properties:
        mappedProps:
          type: string
          additionalProperties:
            type: object
paths:
  /items:
    get:
      operationId: GetItems
      responses:
        "200":
          description: A list of Items
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ItemGood'
```

##### Generation Details

1. `java -jar ..\openapi-generator\modules\openapi-generator-cli\target\openapi-generator-cli.jar generate -i .\shadowspec.yaml -g dart -o mapped`

##### Steps to reproduce

After generation, see the `./mapped/lib/model/item_good.dart` and `./mapped/lib/model/item_bad.dart` files.

ItemGood, defined as 
```yaml
    ItemGood:
      type: object
      properties:
        mappedProps:
          type: string
          additionalProperties:
            type: string
```

generates correctly with

```dart
      return ItemGood(
        mappedProps: mapCastOfType<String, String>(json, r'mappedProps') ?? const {},
      );
```

However, ItemBad, defined as
```yaml
    ItemBad:
      type: object
      properties:
        mappedProps:
          type: string
          additionalProperties:
            type: object
```

generates incorrectly, using `mapValueOfType` instead of `mapCastOfType`:
```dart
      return ItemBad(
        mappedProps: mapValueOfType<Map<String, Object>>(json, r'mappedProps') ?? const {},
      );
```

##### Suggest a fix

Maps should try to generate with mapValueOfType in as many situations as possible

**Comment by 0xNF** [comment]
Slightly modifying the schema to look like this instead:
```yaml
 ItemBad:
      type: object
      properties:
        mappedProps:
          type: string
          additionalProperties: true
```

and then inserting a check for `additionalPropertiesIsAnyType` into `modules\openapi-generator\src\main\resources\dart2\serialization\native\native_class.mustache:173` 

```mustache
                {{^items.isMap}}
                  {{#additionalPropertiesIsAnyType}}
        {{{name}}}: mapCastOfType<String, Object>(json, r'{{{baseName}}}'){{#required}}{{^isNullable}}!{{/isNullable}}{{/required}}{{^required}}{{#defaultValue}} ?? {{{.}}}{{/defaultValue}}{{/required}},
                  {{/additionalPropertiesIsAnyType}}
                  {{^additionalPropertiesIsAnyType}}
        {{{name}}}: mapValueOfType<{{{datatypeWithEnum}}}>(json, r'{{{baseName}}}'){{#required}}{{^isNullable}}!{{/isNullable}}{{/required}}{{^required}}{{#defaultValue}} ?? {{{.}}}{{/defaultValue}}{{/required}},
                  {{/additionalPropertiesIsAnyType}}
                {{/items.isMap}}
```
I can get the dart generators to correctly deserialize the value using  `mapCastOfType` instead of `mapValueOfType`

But I don't know what the correct way to do this really is. Some issues I have include:

1. The existing examples for `mapCastOfType` use `<String, dynamic>` but because the instance member is generated as ` Map<String, Object>` and not a `Map<String, dynamic>` I have to deviate from the pre-existing pattern.
2. I have to modify my schema to work around the generator. I don't see what the semantic difference is between `additionalProperties: true` and `additionalProperties: type: object` is, these should be equivalent (I think?), and so the generator shouldn't be distinguishing between the two in the way it does, but I don't know where to fix this.
