### ISSUE TITLE
[BUG] isString in enumVars is always `false`

### ISSUE THREAD

**Issue by OnkelTem** [OpenAPITools/openapi-generator#12168]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?

We get `isString: false`  for ANY `enum` - be it a string one or int.

E.g. this one:
```yaml
    GuardIntervalEnum:
      type: string
      enum:
        - '1_32'
        - '1_16'
        - '1_8'
        - '1_4'
        - '1_128'
        - '19_128'
        - '19_256'
```        

makes this `enumVars`:

```
[{name=_132, isString=false, value='1_32'}, {name=_116, isString=false, value='1_16'}, {name=_18, isString=false, value='1_8'}, {name=_14, isString=false, value='1_4'}, {name=_1128, isString=false, value='1_128'}, {name=_19128, isString=false, value='19_128'}, {name=_19256, isString=false, value='19_256'}]`
```

Version: 5.3.1

Any ideas?
