### ISSUE TITLE
[BUG][Java] additionalProperties with properties generates incorrect/broken model

### ISSUE THREAD

**Issue by visualage** [OpenAPITools/openapi-generator#12204]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [X] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When a type in schema has a property that has both `additionalProperties` and `properties`, the Java engine generates broken code. For the given example, the following code was generated:

```java
  public Pet putFoobarItem(String key, String foobarItem) {
    if (this.foobar == null) {
      this.foobar = ;
    }
    this.foobar.put(key, foobarItem);
    return this;
  }
```

It is obvious that the code is broken.

For other engines, the generated code also does not do what the schema specifies, i.e. typechecks for specified properties, and the presence check for required properties.

##### openapi-generator version

5.4.0

##### OpenAPI declaration file content or url

```yaml
components:
  schemas:
    Pet:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        foobar:
          type: object
          additionalProperties:
            type: string
          properties:
            fooint:
              type: integer
            fooboolean:
              type: boolean
            foostring:
              type: string
            barint:
              type: integer
          required:
            - fooint
            - fooboolean
            - foostring
```
Full YAML file: https://gist.github.com/visualage/202b8865fb684097fb5a8d9bd7c7b2ff

##### Generation Details

```
java -jar openapi-generator-cli-5.4.0.jar generate -g java -i bad.yaml -o java
```

##### Steps to reproduce

Use the command line above. Check the generated file `java/src/main/java/org/openapitools/client/model/Pet.java`.

##### Related issues/PRs

None.

##### Suggest a fix

We should generate a specific model class when the property type is `object` and has `properties` defined, regardless if `additionalProperties` is there or not. If `additionalProperties` is there, we need to enhance the class so that any unrecognized properties would be put into a special map property. This can be done in Java Jackson by `@JsonAnyGetter` and `@JsonAnySetter` annotations. I am not familiar with other engine/language/libraries, so can't speak for them.
