### ISSUE TITLE
[REQ][JAVA][SPRING] Support for auto generating spring security annotations in controllers/methods

### ISSUE THREAD

**Issue by bluenick2k17** [OpenAPITools/openapi-generator#12219]
### Is your feature request related to a problem? Please describe.

This feature request is related to the desire to keep as much of my API configuration generated through the Open API spec file as possible. Currently if I want to set up authentication, I can define some of what I want inside my YML file but I still need to manually go through and do security setup on the controller/request level.

## Describe the solution you'd like

Introduction of an Open API extension for `securitySchemes` (e.g. `x-spring-preauthorize`) whose value is a string. When a scheme using this extension is used on a request, the [Spring `@PreAuthorize(...)`](https://www.baeldung.com/spring-security-method-security#3-using-preauthorize-and-postauthorize-annotations) annotation is applied to the method in the `*Api` class. If a scheme using this extension is used in the root level `security` property, my understanding is that the scheme would automatically be applied to each operation individually unless it's overridden on the request level.

## Describe alternatives you've considered

- Alternatives to `@PreAuthorize` tag but still auto-generating: `@Secured`, `@RolesAllowed`
  - `@PreAuthorize` provides the best flexibility with implementation including the ability to specify different security requirements besides roles, and being able to AND and OR different requirements (e.g. `hasRole("ROLE_A") AND hasRole("ROLE_B")`).
- Alternative to auto generating: manual configuration
  - Manual configuration is possible and feasible when extending the `*Api` class and adding the additional annotation in the controller. However, this decouples the authorization from the spec document for my API, so ideally I would prefer to have it all working together.

### Example YAML and Generated Method

YAML Config (Lines omitted for brevity)

```yaml
paths:
  /pet:
    put:
      tags:
      - pet
      summary: Update an existing pet
      security:
      - spring_role_auth
components:
  securitySchemes:
    spring_role_auth:
      type: http
      scheme: basic
      x-spring-preauthorize: "'hasRole(ROLE_A') AND hasRole('ROLE_B')"
```

Generated API File Method

```java
//Added import
import org.springframework.security.access.prepost.PreAuthorize;

//New annotation and where it could go in the annotation order
@RequestMapping()
@PreAuthorize("hasRole('ROLE_A') AND hasRole('ROLE_B')")
default ResponseEntity<Pet> addPet() {}
```

### Final Note

I might have the time to also work on a pull request to implement this, but wanted to submit this issue to get feedback on the idea first before anything is started. Thanks!
