### ISSUE TITLE
[BUG][Scala][scala-sttp] Schema with enums as reserved "names" get a bad variable name

### ISSUE THREAD

**Issue by yuvalshi0** [OpenAPITools/openapi-generator#12226]
##### Description

When I generate a client for this schema (using circe for json library):
```yml
   PaginationInfo:
      type: object
      properties:
        type:
          type: string
          enum:
            - foo
            - bar

```

I get the following variable names for the JSON decoders and encoders:
```scala
  implicit val PaginationInfo`Type`Decoder: Decoder[PaginationInfoEnums.`Type`] = Decoder.decodeEnumeration(PaginationInfoEnums.`Type`)
  implicit val PaginationInfo`Type`Encoder: Encoder[PaginationInfoEnums.`Type`] = Encoder.encodeEnumeration(PaginationInfoEnums.`Type`)
```

Causing a compilcation error

##### openapi-generator version

5.4.0
