### ISSUE TITLE
[REQ] Extension to override generated parameter name

### ISSUE THREAD

**Issue by OJFord** [OpenAPITools/openapi-generator#12273]
### Is your feature request related to a problem? Please describe.

I'd like to have, for example, `?foobar=123` in the query, but `foobarId` as the generated variable name

## Describe the solution you'd like

Something like:
```yaml
parameters:
  - name: foobar
    in: query
    x-openapi-generator-var-name: foobarId
```

## Describe alternatives you've considered

Use the same name?
