### ISSUE TITLE
Rust: unexpected character 'v' while parsing major version number for key `package.version`

### ISSUE THREAD

**Issue by dsyer** [OpenAPITools/openapi-generator#12271]
Example spec:

```json
{
  "swagger": "2.0",
  "info": {
    "title": "Kubernetes",
    "version": "v1.19.11"
  },
  "paths": {},
  "definitions": {}
}
```

The generated `Cargo.toml` has `package.version = v1.19.11`:

```toml
[package]
name = "openapi"
version = "v1.19.11"
authors = ["OpenAPI Generator team and contributors"]
edition = "2018"

[dependencies]
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
url = "^2.2"
[dependencies.reqwest]
version = "^0.11"
features = ["json", "multipart"]

[dev-dependencies]
```

and `cargo check` fails with

```
...
Caused by:
  unexpected character 'v' while parsing major version number for key `package.version`
```
