### ISSUE TITLE
[BUG][dart-dio] syntax error stopping build_runner from completing

### ISSUE THREAD

**Issue by lukepighetti** [OpenAPITools/openapi-generator#12306]
`dart-dio` fails to generate the Twitter v2 API spec. The outputted code has syntax errors that does not allow `build_runner` to generate the final pieces of code

https://api.twitter.com/2/openapi.json

[openapi.json.zip](https://github.com/OpenAPITools/openapi-generator/files/8644191/openapi.json.zip)

```
openapi-generator-cli 5.4.0
  commit : 4a36be7
  built  : 2022-01-31T05:31:36Z
  source : https://github.com/openapitools/openapi-generator
  docs   : https://openapi-generator.tech/
```

```
openapi-generator generate -i spec.json -g dart-dio -o dart_dio_client
cd dart_dio_client
dart pub get
dart run build_runner build --delete-conflicting-outputs
```

```
[SEVERE] built_value_generator:built_value on test/spaces_api_test.dart:

Bad state: Unexpected diagnostics:
/Users/lukepighetti/development/flutter/flutter/bin/cache/dart-sdk/lib/core/int.dart:167:18 - Operator declarations must be preceded by the keyword 'operator'.
/Users/lukepighetti/development/flutter/flutter/bin/cache/dart-sdk/lib/core/int.dart:167:16 - Methods must have an explicit list of parameters.
/Users/lukepighetti/development/flutter/flutter/bin/cache/dart-sdk/lib/core/int.dart:167:18 - A function body must be provided.
```

Related to: 
- https://github.com/OpenAPITools/openapi-generator/issues/2567
- https://github.com/OpenAPITools/openapi-generator/pull/6913

**Comment by lukepighetti** [comment]
Just manually updated all deps to the following:

```yaml
name: openapi
version: 1.0.0
description: OpenAPI API client
homepage: homepage

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  dio: ^4.0.6
  built_value: ^8.2.3
  built_collection: ^5.1.1

dev_dependencies:
  built_value_generator: ^8.2.3
  build_runner: ^2.1.10
  test: ^1.21.1
```

This allowed build_runner to complete, but there are numerous syntax issues. It looks like the implementing classes are not overriding methods with appropriate arguments or return types resulting in static analysis errors.

<img width="950" alt="Screen Shot 2022-05-06 at 9 32 46 PM" src="https://user-images.githubusercontent.com/666539/167232705-96d1ecea-b67a-484f-b016-b92c20fc0897.png">

**Comment by Milou6** [comment]
Can confirm that I was previously using `dart_dio_next` without issues, but now trying to switch to the new `dart-dio` the generator is stuck on building.

I tried @lukepighetti 's suggestion of updating deps, but I get the following : 
```
Running "flutter pub get" in brand-service-sdk...                   5.0s
Failed to build build_runner:build_runner:
Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

 - package:args
 - package:build_runner_core
 - package:io
 - package:logging
 - package:build_runner
 - package:build
 - package:glob
 - package:crypto
 - package:watcher
 - package:build_config
 - package:build_resolvers
 - package:timing
 - package:graphs
 - package:package_config
 - package:yaml
 - package:code_builder
 - package:dart_style
 - package:build_daemon
 - package:http_multi_server
 - package:shelf
 - package:pub_semver
 - package:pubspec_parse
 - package:analyzer
 - package:convert
 - package:built_value
 - package:built_collection
 - package:http_parser
 - package:shelf_web_socket
 - package:web_socket_channel
 - package:_fe_analyzer_shared
 - package:checked_yaml
 - package:matcher
 - package:quiver
 - package:fixnum
 - package:cli_util

For solutions, see https://dart.dev/go/unsound-null-safety
../../../../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/build_runner-1.11.1+1/bin/build_runner.dart:89:9: Warning: Operand of null-aware operation '?.' has type 'StreamSubscription<dynamic>' which excludes null.
 - 'StreamSubscription' is from 'dart:async'.
  await logListener?.cancel();
        ^
pub finished with exit code 1
```

**Comment by hanayashiki** [comment]
I have changed my pubspec.yaml into the following, because of incompatibilities with sdk 2.12.0 

```
name: gkcoin_apis
version: 1.0.0
description: OpenAPI API client
homepage: homepage

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  dio: '^4.0.0'
  built_value: '>=8.0.0 <9.0.0'
  built_collection: '>=5.0.0 <6.0.0'

dev_dependencies:
  built_value_generator: '>=8.0.0 <9.0.0'
  build_runner: any
  test: '>=1.21.1 <2.0.0'
  analyzer: 4.1.0
dependency_overrides:
  meta: 1.8.0
```

It finally generates the code, but Dio 4.x.x simple doesn't work with this library:

```dart
    final _response = await _dio.request<dynamic>(
      _request.path,
      data: _bodyData,
      options: _request,
    );

```

<img width="1096" alt="image" src="https://user-images.githubusercontent.com/26056783/170186486-19681e52-14cc-4152-a1b1-be1aba2da2d2.png">

This library seems out-of-date and cannot work with the latest version of Dio and dart sdk anymore
