### ISSUE TITLE
[BUG] Description

### ISSUE THREAD

**Issue by Smibser** [OpenAPITools/openapi-generator#12326]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

We have the language-specific-primitive NodaTime.LocalDate. Since the upgrade to v5.4.0 a model NodaTime.LocalDate is created which is not the expected output. The expected output is that no LocalDate model is created because we use the .NET library. In v5.3.0 everything works

##### openapi-generator version

5.4.0

##### OpenAPI declaration file content or URL

config:
```yaml
aspnetCoreVersion: 5.0
isLibrary: true
newtonsoftVersion: 5.0.6
operationIsAsync: false
packageName: Brokkoli.Api
sourceFolder: ""
useDateTimeOffset: false
useDefaultRouting: false
useSwashbuckle: false
operationResultTask: true
operationModifier: abstract
classModifier: abstract
nullableReferenceTypes: true
importMappings:
  LocalDate: NodaTime.LocalDate
typeMappings:
  LocalDate: NodaTime.LocalDate
```

excerpt from specification:
```yaml
...
        shippingDate:
          $ref: "#/components/schemas/LocalDate"
...
    LocalDate:
      x-csharp-value-type: true
      type: object
...
```

##### Generation Details

`openapi-generator generate -i api.yml -t aspnetcore-generator-template -g aspnetcore -c openapi-server-generator.yml --model-name-suffix Dto --language-specific-primitives=NodaTime.LocalDate`
