### ISSUE TITLE
How to stop open API from initialising list variables in java

### ISSUE THREAD

**Issue by kirankumar114** [OpenAPITools/openapi-generator#12370]
openapi version 3.0.2

I'm using the below Yaml for our code generation

```
  Order:
    type: "object"
    properties:
      LineItems:
        type: "array"
        items:
          type: "string"
      Pricing:
        type: "array"
        items:
          type: "string"
```

While generating the pojo, it is getting initialized to null.

`private List<String>  LineItems = null;`

What should I do if I don't want a list to be initialsed at all.

example: What  I need is

`private List<String>  LineItems;`

What I don't want is
`private List<String>  LineItems = null;
`
or

`private List<String>  LineItems = new ArrayList();`
