### ISSUE TITLE
If the member variable in yaml is required, will the generated code verify whether the parameter is passed?

### ISSUE THREAD

**Issue by shifpeng** [OpenAPITools/openapi-generator#12447]
If the member variable in yaml is required, will the generated code verify whether the parameter is passed?

For example, the following is a section in my yaml, in which the three parameters of GroupId, Members_Account, ShutUpTime are required, but after the code is actually generated, I test the request and find that even if I do not pass these three parameters, the request will be sent
```
    ForbidSendMsgRequest:
      type: object
      required:
        - GroupId
        - Members_Account
        - ShutUpTime
      properties:
        GroupId:
          type: string
          description: 需要查询的群组 ID
        Members_Account:
          type: array
          description: 需要禁言的用户帐号，最多支持500个帐号
          maxItems: 500
          items:
            type: string
```
