### ISSUE TITLE
A primitive type schema with enum values in top-level components shemas will generate a complex data type model

### ISSUE THREAD

**Issue by lspvic** [OpenAPITools/openapi-generator#1255]
##### Description
In the next example, `Color` will generate a model class file while `WeekDay` and `Month` won't. 
In my python case, the generated `Color` class is actually an `BaseModel` object class and lead to code failure.
```yaml
components:
  schemas:
    Color:
      type: string
      enum:
        - black
        - white
        - red
        - green
        - blue
    WeekDay:
         type: string
    obj:
         type: object
         properties:
            Month:
              type: string
              enum:
                - Jan
                - Feb
```

##### openapi-generator version

3.3.1
