### ISSUE TITLE
[BUG] kotlin-spring, spring-boot code generator creates invalid enums

### ISSUE THREAD

**Issue by mbogner** [OpenAPITools/openapi-generator#12553]
##### Description

Generated enum case is unusable:

```kotlin
    enum class RequiredActions(val value: kotlin.String) {

        @JsonProperty("update_user_locale") updateUserLocale("update_user_locale"),
        @JsonProperty("CONFIGURE_TOTP") cONFIGURETOTP("CONFIGURE_TOTP"),
        @JsonProperty("VERIFY_EMAIL") vERIFYEMAIL("VERIFY_EMAIL"),
        @JsonProperty("UPDATE_PASSWORD") uPDATEPASSWORD("UPDATE_PASSWORD"),
        @JsonProperty("UPDATE_PROFILE") uPDATEPROFILE("UPDATE_PROFILE")
    }
```

Using RequiredActions.valueOf will of course fail when trying to translate something like CONFIGURE_TOTP to cONFIGURETOTP.

##### openapi-generator version

6.0.0

##### OpenAPI declaration file content or url

in an object as property:

```yaml
        requiredActions:
          type: array
          items:
            type: string
            enum:
              - update_user_locale
              - CONFIGURE_TOTP
              - VERIFY_EMAIL
              - UPDATE_PASSWORD
              - UPDATE_PROFILE
```

##### Generation Details

```json
openApiGenerate {
    // https://openapi-generator.tech/docs/generators/kotlin-spring
    generatorName.set("kotlin-spring")
    library.set("spring-boot")

    inputSpec.set(openAPISpecFile)
    outputDir.set("$buildDir/$openAPIGenOutBase")

    packageName.set(openAPIBasePackage)
    apiPackage.set("$openAPIBasePackage.api")
    invokerPackage.set("$openAPIBasePackage.client")
    modelPackage.set("$openAPIBasePackage.model")

    modelNameSuffix.set("Dto")
    typeMappings.set(
        mapOf(
            "DateTime" to "Instant"
        )
    )
    importMappings.set(
        mapOf(
            "Instant" to "java.time.Instant"
        )
    )
    configOptions.set(
        mapOf(
            "useBeanValidation" to "true",
            "delegatePattern" to "true",
            "useTags" to "true",
            "exceptionHandler" to "false",
            "gradleBuildFile" to "false",
            "reactive" to "false",
            "serviceInterface" to "false",
            "sortModelPropertiesByRequiredFlag" to "true",
            "sortParamsByRequiredFlag" to "true",
            "swaggerAnnotations" to "true",
        )
    )
}
```

##### Steps to reproduce

 - create simple object containing the property above.
 - use kotlin-spring, spring-boot generator to create kotlin code

##### Suggest a fix

Keep upper/lower case as it is.

**Comment by orolhawion** [comment]
I have a similar issue with a string based enum generation. My expectation is that the generated `@JsonProperty("<value>")` should not contain the value but the var name, shouldn't it?

My enum definition looks basically like this:

```
MyEnum:
  type: string
  enum:
    - eins
    - zwei
  x-enum-varnames:
    - one
    - two
```

and generation results in this:
`@JsonProperty("eins") ONE("eins"), [...]` 

where I would have expected
`@JsonProperty("ONE") ONE("eins"), [...]`
