### ISSUE TITLE
[BUG] [GO] ReadOnly fields are marshaled into json

### ISSUE THREAD

**Issue by kke** [OpenAPITools/openapi-generator#12551]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ ] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

The JSON/YAML says:

```yaml
        createdAt:
          description: The date the Secret entity was created.
          format: date-time
          readOnly: true
          type: string
```

The go struct looks like:

```go
	// The date the Resource entity was created.
	CreatedAt time.Time `json:"createdAt"`
```

And the `MarshalJSON` function:

```go
	if true {
		toSerialize["createdAt"] = o.CreatedAt
	}
```

##### openapi-generator version

The one that comes from `docker run openapitools/openapi-generator-cli`
