### ISSUE TITLE
[BUG][Spring] Fix cookie in parameters are always generated as required

### ISSUE THREAD

**Issue by jorgerod** [OpenAPITools/openapi-generator#12598]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

In the generation of Cookie type parameters, the `required` option is not being taken into account and when generating the code the @CookieValue is always required.

##### openapi-generator version

5.4.0, 6.0.0

##### OpenAPI declaration file content or url

```yaml
  /v1/product/{id}:
    get:
      tags:
        - product
      summary: 'Find product by given id'
      description: 'The user must have any permission in the application.'
      operationId: 'findProductById'
      parameters:
        - name: 'id'
          in: 'path'
          description: 'ID of product to return'
          schema:
            type: string
          required: true
        - in: 'cookie'
          name: CookieFalse
          required: false
          schema:
            type: string
        - in: 'cookie'
          name: CookieTrue
          required: true
          schema:
            type: string
        - in: 'cookie'
          name: CookieDefault
          schema:
            type: string
```

##### Generation Details

**Actual**
```java
  @ApiOperation(value = "Find product by given id", nickname = "findProductById",
      notes = "The user must have any permission in the application.", response = ProductDTO.class, authorizations = {
          @Authorization(value = "ItxApiKey")
      }, tags = {"product",})
  @ApiResponses(value = {
      @ApiResponse(code = 200, message = "OK", response = ProductDTO.class)})
  @RequestMapping(
      method = RequestMethod.GET,
      value = "/v1/product/{id}",
      produces = {"application/json"})
  public ResponseEntity<ProductDTO> findProductById2(
      @ApiParam(value = "ID of product to return", required = true) @PathVariable("id") String id,
      @NotNull @ApiParam(value = "", required = true) @CookieValue("CookieTrue") String cookieTrue,
      @ApiParam(value = "") @CookieValue("CookieFalse") String cookieFalse,
      @ApiParam(value = "") @CookieValue("CookieDefault") String cookieDefault) {
    return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
  }
```

**Expected**
```java
  @ApiOperation(value = "Find product by given id", nickname = "findProductById",
      notes = "The user must have any permission in the application.", response = ProductDTO.class, authorizations = {
          @Authorization(value = "ItxApiKey")
      }, tags = {"product",})
  @ApiResponses(value = {
      @ApiResponse(code = 200, message = "OK", response = ProductDTO.class)})
  @RequestMapping(
      method = RequestMethod.GET,
      value = "/v1/product/{id}",
      produces = {"application/json"})
  public ResponseEntity<ProductDTO> findProductById2(
      @ApiParam(value = "ID of product to return", required = true) @PathVariable("id") String id,
      @NotNull @ApiParam(value = "", required = true) @CookieValue("CookieTrue") String cookieTrue,
      @ApiParam(value = "") @CookieValue(name = "CookieFalse", required = false) String cookieFalse,
      @ApiParam(value = "") @CookieValue(name = "CookieDefault", required = false) String cookieDefault) {
    return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
  }
```

##### Suggest a fix

Modify **cookieParams.mustache** to take into account the `required` field.
