### ISSUE TITLE
[BUG] [Dart-dio-next] Enums with numbers get parsed incorrectly

### ISSUE THREAD

**Issue by glaceon2000** [OpenAPITools/openapi-generator#12626]
When I declare enums with underscore and number their name comes out incorrectly.
```yaml
    ExampleEnum:
      title: "exampleEnum"
      description: "Example enum"
      type: "string"
      enum:
        - "EXAMPLE_ENUM_1"
        - "EXAMPLE_ENUM_2"
        - "EXAMPLE_ENUM_NO_NUMBER"
```
Output:
```
  /// Example enum
  @BuiltValueEnumConst(wireName: EXAMPLE_ENUM_1')
  static const ExampleEnum eXAMPLEENUM1 = _$eXAMPLEENUM1;
  /// Example enum
  @BuiltValueEnumConst(wireName: EXAMPLE_ENUM_2')
  static const ExampleEnum eXAMPLEENUM1 = _$eXAMPLEENUM2;
  /// Example enum
  @BuiltValueEnumConst(wireName: EXAMPLE_ENUM_NO_NUMBER')
  static const ExampleEnum EXAMPLE_ENUM_NO_NUMBER = _$EXAMPLE_ENUM_NO_NUMBER;
```
