### ISSUE TITLE
BUG][Typescript Axios] Binary format for strings always generate `any` type

### ISSUE THREAD

**Issue by HappyFeedFriends** [OpenAPITools/openapi-generator#12744]
##### Description

When trying to generate a binary type for typescript, it always comes up with any

##### openapi-generator version

3.0.3

##### OpenAPI declaration file content or url

```yaml
objectTest:
  type: object
  description: 'test object'
  properties:
    file:
      type: string
      format: binary
```

##### Generation Details
Generated to:
```ts
export interface IObjectTest {
    /**
     * 
     * @type {any}
     * @memberof IObjectTest
     */
    file?: any;
}
```
##### Steps to reproduce

1. Create any field (type = string, format = binary)
2. Generate
