### ISSUE TITLE
[BUG] Kotlin generated class for `type: object` with `additionalProperties` does not compile 

### ISSUE THREAD

**Issue by tbvh** [OpenAPITools/openapi-generator#12763]
##### Description

OpenApi allows to define an open ended object (map). When generating Kotlin code for it, the class declaration contains a compile error.
`data class Metadata(...) : kotlin.collections.HashMap<String, kotlin.String>{` is generated, but it should be:
`data class Metadata(...) : kotlin.collections.HashMap<String, kotlin.String>(){`.

##### openapi-generator version

6.0.0 / 6.0.1

##### OpenAPI declaration file content or url

Spec:
```yaml
components:
  schemas:
    Metadata:
      type: "object"
      properties:
        customerIp:
          type: "string"
      additionalProperties:
        type: "string"
```
