### ISSUE TITLE
[BUG][GO] 

### ISSUE THREAD

**Issue by uri200** [OpenAPITools/openapi-generator#12920]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ ] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

We are generating client specs for go using 5g 3gpp swagger specs found here (https://raw.githubusercontent.com/jdegre/5GC_APIs/master/TS29522_TrafficInfluence.yaml)  

```
java openapi-generator-cli-6.0.0.jar generate -i https://raw.githubusercontent.com/jdegre/5GC_APIs/master/TS29522_TrafficInfluence.yaml -g go -o ./client_trafficInfluence
 ❐ 0  ↑ 27d 14h 39m   1 zsh
```

Some files like have errors (you can see them after running 
```
gofmt -s -w .

specs/client_trafficInfluence/model_ip_addr.go:20:11: expected type, found '{'
specs/client_trafficInfluence/model_ip_addr.go:25:2: expected declaration, found 'return'
specs/client_trafficInfluence/model_ip_addr.go:34:2: expected declaration, found match
specs/client_trafficInfluence/model_route_to_location.go:20:2: expected '}', found 'interface'
specs/client_trafficInfluence/model_route_to_location.go:27:2: expected declaration, found 'if'
```

For example the type `Interface{}` is used twice on the definition 

```
// IpAddr - Contains an IP adresse.
type IpAddr struct {
	Interface{} *interface{}
}

// interface{}AsIpAddr is a convenience function that returns interface{} wrapped in IpAddr
func Interface{}AsIpAddr(v *interface{}) IpAddr {
	return IpAddr{
		Interface{}: v,
	}
}

```

##### openapi-generator version

6.0.0

##### Generation Details

```
java openapi-generator-cli-6.0.0.jar generate -i https://raw.githubusercontent.com/jdegre/5GC_APIs/master/TS29522_TrafficInfluence.yaml -g go -o ./client_trafficInfluence
 ❐ 0  ↑ 27d 14h 39m   1 zsh
```

##### Steps to reproduce

Just run that command and it will generate the files

**Comment by uri200** [comment]
Using the same command I also can see that complex constructions with anyOf is not supported properly. For example, on that schema I mentioned we have something like 

```
    TrafficInfluSub:
      allOf:
      - oneOf:
        - required:
          - afAppId
        - required:
          - trafficFilters
        - required:
          - ethTrafficFilters
      - oneOf:
        - required:
          - ipv4Addr
        - required:
          - ipv6Addr
        - required:
          - macAddr
        - required:
          - gpsi
        - required:
          - externalGroupId
        - required:
          - anyUeInd
      anyOf:
      - not:
          required:
          - subscribedEvents
      - required:
        - notificationDestination
```

But when we generated the client with go we get the following object 

```

// TrafficInfluSub Represents a traffic influence subscription.
type TrafficInfluSub struct {
	OneOfAnyTypeAnyTypeAnyType                      *OneOfAnyTypeAnyTypeAnyType
	OneOfAnyTypeAnyTypeAnyTypeAnyTypeAnyTypeAnyType *OneOfAnyTypeAnyTypeAnyTypeAnyTypeAnyTypeAnyType
}
```
