### ISSUE TITLE
[BUG] Wrong yaml generation when using `anyOf`

### ISSUE THREAD

**Issue by uri200** [OpenAPITools/openapi-generator#12972]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ ] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

We use this 5g official swagger spec to generate our api https://raw.githubusercontent.com/jdegre/5GC_APIs/master/TS29522_TrafficInfluence.yaml

That spec has lots of ref, one of them is  `DnaiChangeType` that can be found here https://jdegre.github.io/editor/?url=https://raw.githubusercontent.com/jdegre/5GC_APIs/master/TS29571_CommonData.yaml

That object looks like 
```
    DnaiChangeType:
      anyOf:
      - type: string
        enum:
          - EARLY
          - EARLY_LATE
          - LATE
      - type: string
        description: >
          This string provides forward-compatibility with future
          extensions to the enumeration but is not used to encode
          content defined in the present version of this API. 
```

When running the following command 

```
java  -jar openapi-generator-cli-7.0.0-20220719.043604-2.jar generate -i https://raw.githubusercontent.com/jdegre/5GC_APIs/master/TS29522_TrafficInfluence.yaml  -g go -o generated
```

It looks like that object is not imported properly into the main api file (the one at api folder). In that case for some reason openapi-generator creates a new object called `DnaiChangeType_anyOf`

```
    DnaiChangeType:
      anyOf:
      - $ref: '#/components/schemas/DnaiChangeType_anyOf'
      - description: "This string provides forward-compatibility with future extensions\
          \ to the enumeration but is not used to encode content defined in the present\
          \ version of this API. \n"
        type: string
      description: "Possible values are:\n- EARLY: Early notification of UP path reconfiguration.\n\
        - EARLY_LATE: Early and late notification of UP path reconfiguration. This\
        \ value shall only be present in the subscription to the DNAI change event.\n\
        - LATE: Late notification of UP path reconfiguration. \n"    
  ``` 

That seems to be confusing since it is generating a new object that didnt exist on the original
