### ISSUE TITLE
[BUG] Multiple oauth2 flows cause typescript-node generation syntax errors

### ISSUE THREAD

**Issue by philip-ellis-sp** [OpenAPITools/openapi-generator#13118]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?

##### Description

When generating SDK code using the `generate` command, typescript-node implementation has syntax errors in the API code when there are two or more oauth2 flows defined in the securitySchema

##### openapi-generator version

```bash
java -jar openapi-generator-cli.jar version
6.0.1
```

##### OpenAPI declaration file content or url

```yaml
components:
  securitySchemes:
    oauth2:
      type: oauth2
      description: simple authentication
      flows:
        clientCredentials:
          tokenUrl: https://oauth/token
          scopes: 
            all: 'access to all scopes'
        authorizationCode:
          authorizationUrl: https://oauth/authorize
          tokenUrl: https://oauth/token
          scopes: 
            all: 'access to all scopes'
```

full file can be found here: [example-api.yaml](https://gist.github.com/philip-ellis-sp/0fbff440059cb2eab9d2e570506ff248)

##### Generation Details
`java -jar openapi-generator-cli.jar generate -i example-api.yaml -g typescript-node -o sdk`

##### Steps to reproduce

after generating the source files, you will see the following in the defaultApi.ts:

```typescript
    protected authentications = {
        'default': <Authentication>new VoidAuth(),
        'oauth2': new OAuth(),
        'oauth2': new OAuth(),
    }
```
which prevents `tsc` from being able to build the file. 

##### Related issues/PRs
I have not found a related issue
