### ISSUE TITLE
[JAVA] incorrect import mapping of DateTime

### ISSUE THREAD

**Issue by guidoschreuder** [OpenAPITools/openapi-generator#1312]
##### Description

Generation of java components fails when joda is not used due to incorrect mapping of imports

##### openapi-generator version

3.3.2-SNAPSHOT

##### OpenAPI declaration file content or url

```yaml
---
components:
  schemas:
    Dummy:
      type: object
      properties:
        dt:
          type: date
        ts:
          type: date-time
```
##### Steps to reproduce

Generate with any Java generator with dateLibrary other then joda
