### ISSUE TITLE
[BUG] java-micronaut-client generator creates OAuth configuration despite it being disabled

### ISSUE THREAD

**Issue by rapasoft** [OpenAPITools/openapi-generator#13144]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

OpenAPI generator configuration for `java-micronaut-client` generates wrong configuration for application.yml. It is clear, that in file [application.yml.mustache](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/java-micronaut/common/configuration/application.yml.mustache) the block that should be conditionally generated (controlled by `configureAuth`) is adding configuration that requires setting up additional properties.

```
{{#configureAuth}}
  security:
    oauth2:
      clients:{{#oauthMethods}}
        {{#lambda.replaceDotsWithUnderscore}}{{{name}}}{{/lambda.replaceDotsWithUnderscore}}:
          grant-type: {{#isCode}}authorization_code{{/isCode}}{{#isImplicit}}implicit{{/isImplicit}}{{#isPassword}}password{{/isPassword}}{{#isApplication}}client_credentials{{/isApplication}}
          scopes: [{{#scopes}}"{{{scope}}}"{{^-last}}, {{/-last}}{{/scopes}}]{{!authorization url}}{{#authorizationUrl}}
          authorization:
            url: "{{{authorizationUrl}}}"{{/authorizationUrl}}{{!token url}}{{#tokenUrl}}
          token:
            auth-method: client_secret_basic
            url: "{{{tokenUrl}}}"{{/tokenUrl}}{{!refreshUrl is not used}}
          # TODO Fill in the parameters for {{{name}}} authorization if needed
          # client-id:
          # client-secret:{{/oauthMethods}}{{/configureAuth}}{{!
  do not configure authorization, but leave hints for user
  }}{{^configureAuth}}
  # TODO configure security features
  security:
    oauth2:
      clients:
        # An example of how oauth client is filled
        # name:
        #   grant-type: authorization_code | client_credentials
        #   scopes: []
        # token:
        #     auth-method: client_secret_basic
        #     url: "https://"
        # client-id:
        # client-secret:
    # An example of how to apply other authorization methods
    # authentication: bearer | cookie | session{{/configureAuth}}
```

I believe, that the second block that hints: `do not configure authorization, but leave hints for user` should have the `security.auth2.clients:` property commented out.

##### openapi-generator version

6.0.0

##### Generation Details

The gradle plugin configuration does not enable OAuth2 (`configureAuth` is `false` by default, so explicitly setting it to false in config does nothing as well):

```
openApiGenerate {
    generatorName.set("java-micronaut-client")
    inputSpec.set(oasYamlFileLocation)
    outputDir.set("$buildDir/generated/openapi")
    apiPackage.set("$oasClientBasePackage.api")
    modelPackage.set("$oasClientBasePackage.model")
    configOptions.set(
        mapOf(
            "serializationLibrary" to "jackson",
            "openApiNullable" to "false",
            "micronautVersion" to "${project.properties["micronautVersion"]}",
            "reactive" to "false",
            "artifactId" to oasClientArtifactId,
            "artifactVersion" to "${project.properties["version"]}",
        )
    )
}
```

##### Suggest a fix

All lines of code should be commented out:

```
  # TODO configure security features
  # security:
    # oauth2:
      # clients:
        # An example of how oauth client is filled
        # name:
        #   grant-type: authorization_code | client_credentials
        #   scopes: []
        # token:
        #     auth-method: client_secret_basic
        #     url: "https://"
        # client-id:
        # client-secret:
    # An example of how to apply other authorization methods
    # authentication: bearer | cookie | session{{/configureAuth}}
```
