### ISSUE TITLE
[JAVA] Could not generate java classes when response does have headers but no content

### ISSUE THREAD

**Issue by bilak** [OpenAPITools/openapi-generator#1318]
##### Description
Hello,
I'm using **openapi-generator-maven-plugin** in version **3.3.1**. When I want to generate java files from within yaml I have issue when there exists response which contains headers but no content. The exception is same asi in #1155 so if you change those sources to contain response decribed like below it should fail.

##### openapi-generator version

3.3.1

##### OpenAPI declaration file content or url

```yaml
    E401:
      description: Unauthorized
      headers:
        WWW-Authenticate:
          description: Contains base of URL for creation of authentication request
          schema:
            type: string
```

##### Related issues/PRs
#1155
