### ISSUE TITLE
[BUG] [JAVA] optional attribute becomes mandatory when a pattern is specified

### ISSUE THREAD

**Issue by BenjaminBusvel** [OpenAPITools/openapi-generator#13220]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Optional attribute becomes mandatory when a pattern is specified and we have set to true on open api generator maven plugin the useBeanValidation parameter. 

##### openapi-generator version

6.0.0

##### OpenAPI declaration file content or url

<plugin>
    <groupId>org.openapitools</groupId>
    <artifactId>openapi-generator-maven-plugin</artifactId>
    <version>${openapi-generator-plugin.version}</version>
    <executions>
        <execution>
            <id>dev-api</id>
            <phase>generate-sources</phase>
            <goals>
                <goal>generate</goal>
            </goals>
            <configuration>
                <inputSpec>${project.basedir}/src/main/resources/swagger/voice-api-spec.yaml</inputSpec>
                <generatorName>spring</generatorName>
                <library>spring-boot</library>
                <apiPackage>com.orange.vapi.swagger.api</apiPackage>
                <modelPackage>com.orange.vapi.swagger.model</modelPackage>
                <modelNameSuffix>Dto</modelNameSuffix>
                <configOptions>
                    <hateoas>true</hateoas>
                    <dateLibrary>java8</dateLibrary>
                    <useBeanValidation>true</useBeanValidation>
                    <interfaceOnly>true</interfaceOnly>
                    <booleanGetterPrefix>is</booleanGetterPrefix>
                </configOptions>
            </configuration>
        </execution>
    </executions>
</plugin>

```yaml
Contract:
      type: "object"
      properties:
        maxSimultaneousCalls:
          type: "integer"
          format: "int32"
          minimum: 1
          description: "Maximum number of simultaneously active calls. An active call\
            \ is a non terminated call. If the number of active calls has reached\
            \ maxSimultaneousCalls, it will not be possible to create a new call,\
            \ until one of the active calls is terminated."
          example: 5
        maxCallDuration:
          type: "integer"
          format: "int32"
          minimum: 1
          maximum: 86400
          description: "Maximum duration (in seconds) for calls created within this\
            \ contract."
          example: 3600
        maxMonthlyMinutes:
          type: "integer"
          format: "int32"
          description: "Maximum amount of minutes that can be consumed in a month\
            \ for this contract. Calls are not created if the monthly consumption\
            \ is higher than the maxMonthlyMinutes."
          example: 2000
        trunkGroupIdentifier:
          type: "string"
          pattern: "^[0-9]{7}"
          description: "the tgrp parameter of the trunk group identifier, as defined\
            \ in IETF RFC 4904"
      description: "AdditionalContract model"
```
