### ISSUE TITLE
[REQ] [aspnetcore] Separate controller for each route and/or model

### ISSUE THREAD

**Issue by mahgo** [OpenAPITools/openapi-generator#13284]
### Is your feature request related to a problem? Please describe.

I'm not sure if this is a bug or if it is simply not implemented, but it would be good to be able to have one controller generated per model and/or route, instead of all controller actions going into one controller (`DefaultApiController`, in `DefaultApi.cs`)

## Describe the solution you'd like
For example, if my models were `Foo` and `Bar`, then I'd want something like `FoosController` and `BarsController` to be generated

**Comment by afokt** [comment]
what about introducing a 'useTags' additional property?
(as done to split/partition/group into API classes based on tags specified for the operations, e.g. with the generator for java spring: https://openapi-generator.tech/docs/generators/spring/)

**Comment by afokt** [comment]
> Oh, well, as I tried out with using tags in the openapi spec, it already seems working fine
   ( --> produces controller files named according to tag placed on operation).

**Comment by mahgo** [comment]
Hi @afokt,

What do I have to do on my end to do this as well?

**Comment by afokt** [comment]
> Hi @afokt,
> 
> What do I have to do on my end to do this as well?

Hi @mahgo,

I mean I am happy with the way it already works.

First I thought that this aspnetcore generator had not been prepared so far for producing custom-named controllers (other than the `DefaultApiController` you also mentioned) or more than one classes as output.

But then I realized that it's already solved (still it does not seem advertised in the documentation, at least I did not find there).

Using tags as below in the openapi spec yaml provided as input, the generator produces two separate controllers, prefixed according to the tag assigned to the (set of) operations specified:

```
tags:
  - name: foo
    description: <my operations related to stuff Foo>
  - name: bar
    description: <my operations related to stuff Bar>

...
paths:
  /myFirstOp:
    get:
      tags:
        - foo
      ...

  /myFirstOp/{param}:
    put:
      tags:
        - bar
      ...
```
