### ISSUE TITLE
[BUG] [Kotlin] Missing support for multiple apikey security

### ISSUE THREAD

**Issue by mszan** [OpenAPITools/openapi-generator#13394]
##### Description

With the following spec:
```yaml
...
components:
  securitySchemes:
    Apikey:
      type: apiKey
      in: header
      name: apikey
    Loginkey:
      type: apiKey
      in: header
      name: loginkey
...
```

Kotlin generator produces this:
```
import org.openapitools.client.auth.ApiKeyAuth
import org.openapitools.client.auth.ApiKeyAuth
```

References:
- https://swagger.io/docs/specification/authentication/api-keys/ (Multiple API Keys section)
- https://swagger.io/specification/
##### openapi-generator version

Tested both on 5.4.0 and 6.0.1.
