### ISSUE TITLE
[REQ][dart] Support deepObject style query parameter

### ISSUE THREAD

**Issue by kaz080** [OpenAPITools/openapi-generator#13584]
### Is your feature request related to a problem? Please describe.

We need to use deepObject style query parameter.

```yaml
  /v3/hashtags:
    get:
      tags:
        - Hashtag
      operationId: getHashtags
      parameters:
        - name: suggest_option
          in: query
          description: Suggest option
          style: deepObject
          explode: true
          schema:
            type: object
            properties:
              q:
                type: string
                description: Keyword for suggest
              input_text:
                type: string
                description: Entire comment
```

But generated dart client results unexpected query parameter URI:

`https://.../v3/hashtags?suggest_option=GetHashtagsSuggestOptionParameter%5Bq%3Da%2C+inputText%3Daaa%5D`

`openapi-generator-cli 6.1.0`
`openapi-generator generate -i ./openapi.yaml -g dart -o ./client`

## Describe the solution you'd like

If I modified `api_helper.dart` like this, it produced URI with query parameters as we expected:

`https://.../v3/hashtags?suggest_option%5Bq%5D=a&suggest_option%5Binput_text%5D=aaa`

```dart
Iterable<QueryParam> _queryParams(
  String collectionFormat,
  String name,
  dynamic value,
) {
  // Assertions to run in debug mode only.
  assert(name.isNotEmpty, 'Parameter cannot be an empty string.');

  final params = <QueryParam>[];

  if (value is List) {
    if (collectionFormat == 'multi') {
      return value.map(
        (dynamic v) => QueryParam(name, parameterToString(v)),
      );
    }

    // Default collection format is 'csv'.
    if (collectionFormat.isEmpty) {
      collectionFormat = 'csv'; // ignore: parameter_assignments
    }

    final delimiter = _delimiters[collectionFormat] ?? ',';

    params.add(QueryParam(
      name,
      value.map<dynamic>(parameterToString).join(delimiter),
    ));
  } else if (value is num ||
      value is String ||
      value is bool ||
      value is Enum) {
    params.add(QueryParam(name, parameterToString(value)));
  } else if (value != null) {
    return value
        .toJson()
        .entries
        .where((e) => e.value != null)
        .map(
          (e) => QueryParam('${name}[${e.key}]', parameterToString(e.value)),
        )
        .toList()
        .cast<QueryParam>();
  }

  return params;
}
```

But I am new to both Open API generator and Dart, so I don't know if this is a good way...
