### ISSUE TITLE
[BUG][PYTHON] Generated python-flask server stub enum strings don't have quotes

### ISSUE THREAD

**Issue by renxinhe** [OpenAPITools/openapi-generator#13689]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Generated python server stub doesn't have quotes around the enum values. This generates python code with syntax errors.

**OpenAPI 3.0 YAML input:**
```yaml
status:
    type: string
    description: status
    enum:
      - local
      - invited
      - accepted
      - confirmed
      - rejected
```

**Generated python model stub code:**
```python
    @status.setter
    def status(self, status):
        """<omitted>
        """
        allowed_values = [None,local, invited, accepted, confirmed, rejected]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"
                .format(status, allowed_values)
            )

        self._status = status
```

Notice that the line `allowed_values = ...` isn't valid python code. The enum values need to be surrounded by quotes because they are string types.

##### openapi-generator version

6.2.0

##### OpenAPI declaration file content or url

```yaml
status:
    type: string
    description: status
    enum:
      - local
      - invited
      - accepted
      - confirmed
      - rejected
```

##### Generation Details

```bash
 java -jar openapi-generator-cli.jar generate -g python-flask -i '/tmp/api.yaml' -o '/tmp/codegen_test'
```

##### Steps to reproduce

Simply run the codegen CLI and check the output file to see the missing quotes in the stub.

##### Related issues/PRs

This issue is similar to https://github.com/OpenAPITools/openapi-generator/issues/3196, but the opposite direction. Here we have manually defined an OpenAPI 3.0 YAML, and want to generate python server stub.

##### Suggest a fix

I'd imagine this bug is specific to the python flask server generator. I'm not too familiar with the code base to navigate to the culprit.
