### ISSUE TITLE
[BUG][KOTLIN] Enum generation not compiling

### ISSUE THREAD

**Issue by mikezilla** [OpenAPITools/openapi-generator#14017]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [X] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When an enum with the same name as the class name that it resides in is generated, the generator produces an output that does not compile. 

##### openapi-generator version

generator version [6.2.1](https://mvnrepository.com/artifact/org.openapitools/openapi-generator/6.2.1)

##### OpenAPI declaration file content or url
[link to the json gist](https://gist.github.com/mikezilla/f2a065a67349feef1d8807ea4bdd659a)

##### Generation Details

```yaml
generatorName: kotlin
outputDir: generated/src/main/kotlin
library: jvm-okhttp4
inputSpec: modules/openapi-generator/src/test/resources/helloWorld.json
templateDir: modules/openapi-generator/src/main/resources/Java
additionalProperties:
  serializationLibrary: jackson
  apiSuffix: SafeClient
  enumPropertyNaming: PascalCase
  sortModelPropertiesByRequiredFlag: true
  sortParamsByRequiredFlag: true
  packageName: com.sofi.invest.ams.generated

```

##### Steps to reproduce
1. Generate the source using the provided generation details and schema above
2.  Navigate to the HelloWorldGreeting.kt file
3. Notice the compilation error on the enum member variable named _helloWorldGreeting_
```java
@field:JsonProperty("HelloWorldGreeting")
    val helloWorldGreeting: HelloWorldGreeting.HelloWorldGreeting? = null  // <-- compilation error on qualified enum
```
4. removing the class name qualifier works
```java
@field:JsonProperty("HelloWorldGreeting")
    val helloWorldGreeting: HelloWorldGreeting? = null  // <-- no compilation error on qualified enum
```

##### Related issues/PRs

https://github.com/OpenAPITools/openapi-generator/issues/13496

##### Suggest a fix

Our theory is that there is an issue with the mustache generation template
