### ISSUE TITLE
[BUG] Description

### ISSUE THREAD

**Issue by creyD** [OpenAPITools/openapi-generator#14042]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ ] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Using the rest_framework_jwt module (i.e.) you get a serializer like this:
![Screenshot 2022-11-16 at 18 27 54](https://user-images.githubusercontent.com/15138480/202250985-232c2f77-9fc0-47e3-99ca-0c86fa38d5eb.png)

This get's generated in codegen to this: 
![Screenshot 2022-11-16 at 18 28 40](https://user-images.githubusercontent.com/15138480/202251158-c6303c3b-f231-4c4b-b26d-9ca4fb76fcf6.png)

The problem here is that `token` is still required on POST request, even though it shouldn't even be part of the POST request.

##### openapi-generator version

We are using `"@openapitools/openapi-generator-cli": "^2.4.26",` with `"generator-cli": {
    "version": "5.2.0"
  }` specified.

##### Generation Details

Code gets generated for Angular/ Typescript

##### Steps to reproduce

Use this yaml code to generate an API with the generator cli

```yaml
"JSONWebToken": {
                "type": "object",
                "description": "Serializer class used to validate a username and password.\n\n'username' is identified by the custom UserModel.USERNAME_FIELD.\n\nReturns a JSON Web Token that can be used to authenticate later calls.",
                "properties": {
                    "password": {
                        "type": "string",
                        "writeOnly": true
                    },
                    "token": {
                        "type": "string",
                        "readOnly": true
                    },
                    "email": {
                        "type": "string",
                        "writeOnly": true
                    }
                },
                "required": [
                    "email",
                    "password",
                    "token"
                ]
            },
```

##### Suggest a fix

To be honest, I am not even quite sure if this is a bug, so I can't suggest a fix.
