### ISSUE TITLE
[BUG][RUST] Description

### ISSUE THREAD

**Issue by mattoni** [OpenAPITools/openapi-generator#14069]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Query parameters with deep object and specific properties are not being fully qualified in the api function in Rust. Here is a snippet of what's causing the issue:

```
name: page
in: query
required: false
description: "In a list return, the data associated with the page number and size returned. 20 results per page, page 2 would be `page[size]=20&page[number]=2`"
explode: true
style: deepObject
schema:
  type: object
  properties:
    number:
      type: number
      description: The page to jump to
    size:
      type: number
      description: The number of resources returned per page.
```

This generates the following error:
![image](https://user-images.githubusercontent.com/5110855/202862606-51680afa-5fe6-4b72-9e5f-45854eacd39a.png)

This struct is properly generated, it's just not fully qualified

##### openapi-generator version

6.0.0

##### OpenAPI declaration file content or url

https://drive.google.com/file/d/16DDHJZrBgT0OrVbwO85VtmX4RAr54Qoi/view?usp=sharing

##### Generation Details

`./run-in-docker.sh generate -i /gen/public-api.yml -g rust -o /gen/out/openapi`

##### Steps to reproduce

Run the generator, and attempt to compile the code with the rust compiler.

##### Suggest a fix

It appears the bug is caused here:

modules/openapi-generator/src/main/resources/rust/reqwest/api.mustache -> line 20 col 386

It appears that it only sets up the fully qualified import if it's a body parameter, not a query parameter. In the case of explicit parameters however, it assumes that it would be a core type. I'm not sure how to detect if something is a generated parameter or not however.

cc @nshaaban-cPacket since I know you're working on some rust generator code right now.
