### ISSUE TITLE
[REQ] Add externalDocs to @Operation

### ISSUE THREAD

**Issue by arey** [OpenAPITools/openapi-generator#14141]
### Is your feature request related to a problem? Please describe.

I'm using the `openapi-generator-maven-plugin` `6.2.1` and its `spring-boot` library with `springdoc-openapi-ui` `1.6.6`.
I'm configuring an `externalDocs` at operation level like below:
```
paths:
  /hello/{name}:
    get:
      description: "Say Hello to somebody"
      externalDocs:
        url: "https://wiki.mycompany.com"
        description: "API Wiki Specification"
      operationId: hello
```
The `url` and `description` are used in the generated javadoc:
```
    /**
     * GET /hello/{name}
     * Say Hello to somebody
     *
     * @param name The person&#39;s name (required)
     * @return The greeting (status code 200)
     * API Wiki Specification
     * @see <a href="https://wiki.mycompany.com"> Documentation</a>
     */
    @Operation(
        operationId = "hello",
        responses = {
            @ApiResponse(responseCode = "200", description = "The greeting", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = MessageResource.class))
            })
        }
    )
    @RequestMapping(
```
## Describe the solution you'd like

I would like a `@ExternalDocumentation` will be generated:
```
    @Operation(
        operationId = "hello",
        externalDocs = @ExternalDocumentation(
            description = "API Wiki Specification",
            url = "https://wiki.mycompany.com"
        ),
        responses = {
            @ApiResponse(responseCode = "200", description = "The greeting", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = MessageResource.class))
            })
        }
    )
    @RequestMapping(
```
Thus Springdoc could add an external link:

![image](https://user-images.githubusercontent.com/838318/204561189-bc7a2c8c-f247-4bfd-98f4-126d4fe7c183.png)

## Describe alternatives you've considered

N/A

## Additional context

If you want, I could try to contribute on this feature.
