### ISSUE TITLE
[QUESTION] python - Instantiate child object (derived from allOf)

### ISSUE THREAD

**Issue by shinnokdisengir** [OpenAPITools/openapi-generator#14151]
Hi, I'm a TS developer and I've a question about python client, cause I've to make some tests: 
how can I create an object derived from another?

MigrationRequest.yaml
```
type: object
additionalProperties: false
required:
    - srcAccount
    - srcBucketName
    - dstAccount
    - dstBucketName
properties:
    srcAccount:
        $ref: "./Account.yaml"
    srcBucketName:
        $ref: "./BucketName.yaml"
    dstAccount:
        $ref: "./Account.yaml"
    dstBucketName:
        $ref: "./BucketName.yaml"
    skipCertValidation:
        type: boolean
        description: If set, create bucket if doesn't exist
        default: false
        example: false
xml:
    name: migrationRequest
```

Migration.yaml
```
type: object
additionalProperties: false
allOf:
    - $ref: "./MigrationRequest.yaml"
    - type: object
      additionalProperties: false
      required:
          - id
      properties:
          id:
              $ref: "./Uuid.yaml"
xml:
    name: migration
```

In TS I can simply:
```
const migrationRequest = { *fields* }
const migration = {...migrationRequest, id: 'blabla' }
```

I've already tried with this solution for another struct:
```

def sample_account_request() -> AccountRequest:
    """
    Create a valid sample account request
    """
    return AccountRequest(
        vendor='VENDOR',
        endpoint='https://blabla.com',
        access_key='***',
        secret_key='***'
    )


def sample_account() -> Account:
    """
    Create a valid sample account
    """
    return Account(**sample_account_request().to_dict(), id=Uuid(str(uuid4())))
```
but if there are tree structs that doesn't work 

thanks
