### ISSUE TITLE
[BUG] [TypeScript-Axios] Generated enum object keys are empty by non-ascii charactor.

### ISSUE THREAD

**Issue by morioka-neopa** [OpenAPITools/openapi-generator#14155]
#### Bug Report Checklist

- [ x ] Have you provided a full/minimal spec to reproduce the issue?
- [ x ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ x ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ x ] Have you searched for related issues/PRs?
- [ x ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When I use enum in property type with non-ascii characters, output ts code is syntax broken. Because generator can't create object key by non-ascii character.

##### openapi-generator version

v6.2.1

##### OpenAPI declaration file content or url

input
```yaml
components:
  schemas:
    MyRequest:
      type: object
      properties:
        myEnumProperty:
          type: string
          enum:
            - 日本語
            - english
            - 한국어
```

output

```typescript
export const MyEnumPropertyEnum = {
    : '日本語',
    English: 'english',
    : '한국어'
} as const;
```

##### Suggest a fix

I think if contains non-ascii character in enum value, key would be same as value like this.

```typescript
export const MyEnumPropertyEnum = {
    '日本語': '日本語',
    English: 'english',
    '한국어': '한국어'
} as const;
```
