### ISSUE TITLE
[BUG] [Java] Redundant "import java.time.OffsetDateTime" when using typeMappings

### ISSUE THREAD

**Issue by emeraldhieu** [OpenAPITools/openapi-generator#14164]
##### Description

Replacing OffsetDateTime with LocalDateTime doesn't remove the import of OffsetDateTime.
```xml
<typeMappings>
    <typeMapping>string+date-time=LocalDateTime</typeMapping>
</typeMappings>

<importMappings>
    <importMapping>LocalDateTime=java.time.LocalDateTime</importMapping>
</importMappings>
```

##### openapi-generator version

openapi-generator-maven-plugin version 6.0.1

##### OpenAPI declaration file content or url

```yaml
components:
  schemas:
    Foo:
      type: object
      properties:
        createdAt:
          type: string
          format: date-time
          example: '2022-11-27T01:02:03Z'
```

##### Steps to reproduce

Use the Open API with the typeMapping and importMapping above

##### Suggest a fix

Remove the fixed OffsetDateTime import at https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/JavaSpring/model.mustache#L13
