### ISSUE TITLE
[BUG] Variables in allOf are always not required

### ISSUE THREAD

**Issue by ttyniwa** [OpenAPITools/openapi-generator#14163]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Variables in allOf are always not required.
So generated code is unexpectedly optional.

###### actual output

```
        getCountry: async (country?/*not required*/: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
```

###### expected output

```
        getCountry: async (country/*required*/: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
```

##### openapi-generator version

6.2.1

##### OpenAPI declaration file content or url

```yaml
{
  "openapi": "3.0.1",
  "info": {
    "title": "country",
    "version": "0.0.0"
  },
  "paths": {
    "/country": {
      "post": {
        "operationId": "getCountry",
        "requestBody": {
          "content": {
            "application/x-www-form-urlencoded": {
              "schema": {
                "allOf": [
                  {
                    "required": ["country"],
                    "type": "object",
                    "properties": {
                      "country": {
                        "type": "string"
                      }
                    }
                  }
                ]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    }
  }
}
```

##### Steps to reproduce

1. add following code to [apiInner.mustache](https://github.com/OpenAPITools/openapi-generator/blob/d8bed42/modules/openapi-generator/src/main/resources/typescript-axios/apiInner.mustache#L50)
```
{{#isNullable}}/*nullable*/{{/isNullable}}{{^isNullable}}{{#required}}/*required*/{{/required}}{{^required}}/*not required*/{{/required}}{{/isNullable}}
```
1. generate code
```
docker run --rm -v `pwd`/:/local openapitools/openapi-generator-cli:v6.2.1 generate --skip-validate-spec -g typescript-axios -i /local/country.json -o /local/client/
```

##### Related issues/PRs

Following PR fixes "allOf to not always be nullable", but not "allOf to not always be not required".
https://github.com/OpenAPITools/openapi-generator/pull/12861
cc. @devhl-labs
