### ISSUE TITLE
[BUG][PYTHON] Basic Auth does not work with "python_prior"

### ISSUE THREAD

**Issue by gtorrance-bw** [OpenAPITools/openapi-generator#14165]
##### Description

I have generated a "python_prior" client, but when I pass a "username" and "password" to the Configuration constructor in order to configure basic authentication, it seems to be ignored. Any subsequent requests to the API return 401/Unauthorized.

A `get_basic_auth_token` method exists, but appears to never be called. Also, `auth_settings` appears to return an empty result.

```
    def get_basic_auth_token(self):
        """Gets HTTP basic authentication header (string).

        :return: The token for basic HTTP authentication.
        """
        username = ""
        if self.username is not None:
            username = self.username
        password = ""
        if self.password is not None:
            password = self.password
        return urllib3.util.make_headers(
            basic_auth=username + ':' + password
        ).get('authorization')

    def auth_settings(self):
        """Gets Auth Settings dict for api client.

        :return: The Auth Settings information dict.
        """
        auth = {}
        return auth
```

##### openapi-generator version

Tested using openapi-generators/openapitools-generator-action@v1.3.0
This defaults to using the "latest" [Docker image](https://hub.docker.com/r/openapitools/openapi-generator-cli/tags) for  openapi-generator-cli.
This has been tested with the file with digest 3652a56ea9a5 or 790055994c96 (not sure which, but both are currently "latest").

##### Generation Details

GitHub Actions workflow contains:
```
      - name: Generate Client Library w/ the OpenAPITools Generator
        uses: openapi-generators/openapitools-generator-action@v1.3.0
        with:
          generator: python-prior
          generator-tag: latest
          config-file: clientPropsPython.yaml
          openapi-file: maestro-provisioning/target/maestroProvisioningOpenApi.json
```

clientPropsPython.yaml contains:
```
packageName: bw_maestro_provisioning_api
projectName: bw-maestro-provisioning-api
```
