### ISSUE TITLE
[BUG] Parameter Schemas are generated but not imported

### ISSUE THREAD

**Issue by Foorack** [OpenAPITools/openapi-generator#14171]
##### Description

Rust generator generates correct code, but simply forgets to import, schemas when a named schema (string) is used as query parameter to endpoint.

Planning to make PR later, just documenting this so there is a track record and it's not forgotten.

##### openapi-generator version

6.2.1

##### Generation Details

```yaml
messageType:
  name: messageType
  in: path
  required: true
  schema:
    $ref: ./schemas/InviteMessageType.yaml
  description: 'The type of message to fetch, must be a valid InviteMessageType.'
```

where InviteMessageType is a string enum:

```yaml
type: string
default: message
description: ''
enum:
  - message
  - response
  - request
  - requestResponse
title: InviteMessageType
```

##### Related issues/PRs

Incoming PR.

##### Suggest a fix

Import the struct.
