### ISSUE TITLE
[BUG] oneOf with enum values is not properly parsed for response body.

### ISSUE THREAD

**Issue by wtrocki** [OpenAPITools/openapi-generator#14256]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When schema  contains multiple enum string values `oneOf` with enums. For example:
```
        actionType:
          type: object 
          oneOf:
            - type: string
              enum:
              - Max
              - Min
              - Top
```

Parsing response from backend fail as field is represented by number of structures but parser expects string. 
I think template would need to be changed to support this use case specifically.

Workaround for that would be to use swagger-core allowedValues - however when we do that and list those inline to the response OpenAPI generator ignores them and sets type as *string.

##### openapi-generator version

Master/Latest

##### OpenAPI declaration file content or url

If you post the code inline, please wrap it with
```yaml
        actionType:
          type: object 
          oneOf:
            - type: string
              enum:
              - Max
              - Min
              - Top
```
(for YAML code) or
```json
(here your code)
```
(for JSON code), so it becomes more readable. If it is longer than about ten lines,
please create a Gist (https://gist.github.com) or upload it somewhere else and
link it here.
  -->
