### ISSUE TITLE
[BUG] [JAVA] Missing Validation Annotations of Array items in generated Classes

### ISSUE THREAD

**Issue by JonathanTietz** [OpenAPITools/openapi-generator#14269]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [X] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When generating schemas from am a yaml-file, that contain arrays with items that have validation properties (e.g. ```maxLength: 4```), it appears that the generated classes are missing the associated Annotations (e.g. ```@Size(max=4)```).

Using this specification as an example:
```yaml
components:
  schemas:
    BrokenValidation:
      properties:
        stringWithValidation:
          description: 'String validation should look like this'
          type: string
          maxLength: 4
        brokenArray:
          description: 'Why no validation'
          type: array
          items:
            type: string
            maxLength: 4
```

We get a correct Annotation for `stringWithValidation`:
```java
/**
   * String validation should look like this
   * @return stringWithValidation
  */
  @Size(max = 4) 
  @Schema(name = "stringWithValidation", description = "String validation should look like this", required = false)
  public String getStringWithValidation() {
    return stringWithValidation;
  }
```

But for the `brokenArray` this Annotation is missing:
```java
/**
   * Why no validation
   * @return brokenArray
  */
  
  @Schema(name = "brokenArray", description = "Why no validation", required = false)
  public List<String> getBrokenArray() {
    return brokenArray;
  }
```

The correct generation would be:
```java
/**
   * Why no validation
   * @return brokenArray
  */
  
  @Schema(name = "brokenArray", description = "Why no validation", required = false)
  public List<@Size(max=4) String> getBrokenArray() {
    return brokenArray;
  }
```

##### openapi-generator version

6.0.0

##### OpenAPI declaration file content or url
```yaml
components:
  schemas:
    BrokenValidation:
      properties:
        stringWithValidation:
          description: 'String validation should look like this'
          type: string
          maxLength: 4
        brokenArray:
          description: 'Why no validation'
          type: array
          items:
            type: string
            maxLength: 4
```

##### Steps to reproduce

Copy paste the given extract (specs) in a YAML file and use it as input.

##### Suggest a fix

Since adding the necessary Annotations to the generated classes is possible, I suggest the code-generator should be adjusted to account for these types of properties.

**Comment by tlvlp** [comment]
We had the same problem when trying to add a `pattern` validation on the collection elements.

**Comment by icod** [comment]
Us too! The following gives no validation annotations on the integer.

```yaml
days:
  description: 'Days of the week (numbered)'
  type: array
  item: 
    type: integer
    minimum: 1
    maximum: 7 
```
