### ISSUE TITLE
[JavaScript] Parameters naming in functions, documentation and file name is wrong

### ISSUE THREAD

**Issue by advance512** [OpenAPITools/openapi-generator#1435]
##### Description

Code generated creates some parameters as inline objects, some with bad names like NULLUNIQUENAME, and with parameter names in functions called "opts" instead of their proper name.

##### openapi-generator version

openapi-generator-cli-3.3.3-20181113.090410-41.jar 

##### OpenAPI declaration file content or url

Not complete, but you get the point:

```
  /companies/{companyId}/oath_groto/integration:

    parameters:
      - $ref: '#/parameters/companyId'

    post:
      x-swagger-router-controller: api.companies
      operationId: addCompanyOathGrotoIntegration
      summary: Adds the Oath Groto integration for a company account.
      description: Adds the Oath Groto integration for a company account.
      parameters:
        - $ref: '#/parameters/oathIntegrationSettings'
      responses:
        '201':
          description: An Integration object
          schema:
            $ref: '#/definitions/Integration'
        '404':
          $ref: '#/responses/EntityDoesNotExistWithError'
        '400':
          $ref: '#/responses/BadRequest'
        '403':
          $ref: '#/responses/Forbidden'
        '500':
          $ref: '#/responses/InternalServerError'
        default:
          $ref: '#/responses/TotallyUnexpectedResponse'

  oathIntegrationSettings:
    name: oathIntegrationSettings
    in: body
    required: true
    description: Settings of the Oath integration.
    schema:
      type: object
      required:
        - oathAuthCode
      properties:
        oathAuthCode:
          description: The Oath auth code to use for the integration, as returned from Oath OAuth.
          type: string
```

Diffing, compared to swagger-codegen-cli-2.4.0-20181113.142213-347.jar shows:

DefaultApi.md

```
 <a name="addCompanyOathGrotoIntegration"></a>
 # **addCompanyOathGrotoIntegration**
-> Integration addCompanyOathGrotoIntegration(companyId, oathIntegrationSettings)
+> Integration addCompanyOathGrotoIntegration(companyId, opts)
 
... more stuff

-var oathIntegrationSettings = new Fizzle.OathIntegrationSettings(); // OathIntegrationSettings | Settings of the Oath integration.
-
-apiInstance.addCompanyOathGrotoIntegration(companyId, oathIntegrationSettings).then(function(data) {
+var opts = {
+  'inlineObject3': new Fizzle.InlineObject3() // InlineObject3 | 
+};
+apiInstance.addCompanyOathGrotoIntegration(companyId, opts).then(function(data) {
```

DefaultApi.js

```
@@ -234,22 +232,19 @@
      * Adds the Oath Groto integration for a company account.
      * Adds the Oath Groto integration for a company account.
      * @param {Number} companyId A company identifier
-     * @param {module:model/OathIntegrationSettings} oathIntegrationSettings Settings of the Oath integration.
+     * @param {Object} opts Optional parameters
+     * @param {module:model/InlineObject3} opts.inlineObject3 
      * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Integration} and HTTP response
      */
-    this.addCompanyOathGrotoIntegrationWithHttpInfo = function(companyId, oathIntegrationSettings) {
-      var postBody = oathIntegrationSettings;
+    this.addCompanyOathGrotoIntegrationWithHttpInfo = function(companyId, opts) {
+      opts = opts || {};
+      var postBody = opts['inlineObject3'];
 
       // verify the required parameter 'companyId' is set
       if (companyId === undefined || companyId === null) {
         throw new Error("Missing the required parameter 'companyId' when calling addCompanyOathGrotoIntegration");
       }
 
-      // verify the required parameter 'oathIntegrationSettings' is set
-      if (oathIntegrationSettings === undefined || oathIntegrationSettings === null) {
-        throw new Error("Missing the required parameter 'oathIntegrationSettings' when calling addCompanyOathGrotoIntegration");
-      }
-
 
       var pathParams = {
         'companyId': companyId
@@ -279,11 +274,12 @@
      * Adds the Oath Groto integration for a company account.
      * Adds the Oath Groto integration for a company account.
      * @param {Number} companyId A company identifier
-     * @param {module:model/OathIntegrationSettings} oathIntegrationSettings Settings of the Oath integration.
+     * @param {Object} opts Optional parameters
+     * @param {module:model/InlineObject3} opts.inlineObject3 
      * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Integration}
      */
-    this.addCompanyOathGrotoIntegration = function(companyId, oathIntegrationSettings) {
-      return this.addCompanyOathGrotoIntegrationWithHttpInfo(companyId, oathIntegrationSettings)
+    this.addCompanyOathGrotoIntegration = function(companyId, opts) {
+      return this.addCompanyOathGrotoIntegrationWithHttpInfo(companyId, opts)
         .then(function(response_and_data) {
           return response_and_data.data;
         });
```

The files `/model/OathIntegrationSettings.spec.js` have been deleted. Instead, you have many InlineObject.spec.js and InlineObject.js files.

Also, there are several NULLUNIQUENAME.spec.js and NULLUNIQUENAM.js files which were generated by the inline part of the array in this YAML:
(i.e. the element inside the items key)

```
  oathGrotoAssetsForLarping:
    name: oathGrotoAssetsForLarping
    in: body
    required: true
    description: List of Oath Groto assets for larping
    schema:
      type: array
      items:
        type: object
        required:
          - integrationId
          - managerAccountId
        properties:
          integrationId:
            description: An Integration identifier
            type: integer
            format: int64
          managerAccountId:
            description: Id of Oath Groto manager account
            type: string
          clientAccountId:
            description: Id of Oath Groto client account
            type: string
```

##### Command line used for generation

java -jar ~/Downloads/openapi-generator-cli-3.3.3-20181113.090410-41.jar generate -i ../fizzle.yaml -l javascript --additional-properties usePromises=true -o ./javascript/

##### Steps to reproduce

Generate a JavaScript client for any Swagger file that has parameters.

##### Related issues/PRs

None that I know of.

##### Suggest a fix/enhancement

-

**Comment by demonfiddler** [comment]
Looks like the regression occurred in commit 53597764c344fb45283891da2c4c60300c9db726
Author: Jeremie Bresson <dev@jmini.fr>
Date:   Tue Apr 17 09:19:10 2018 +0200
in which the code that hitherto preserved the body parameter name was commented out (lines 2593-2675, specifically line 2675 p.paramName = toParamName(bp.getName());). These lines are still present in the latest swagger-codegen version of DefaultCodegen.java, which **does** emit the correct names for OpenAPI 2.0 body parameters.

**Comment by advance512** [comment]
@jmini
Coule you handle this regression, fix it back?

**Comment by wing328** [comment]
> There's a workaround: place extension property x-codegen-request-body-name on the containing operation to specify the body parameter name. It works - I've tried it.

That's the correct approach at the moment as there's no "body" parameter in OpenAPI spec 3.0 any more.

**Comment by demonfiddler** [comment]
> 
> 
> > There's a workaround: place extension property x-codegen-request-body-name on the containing operation to specify the body parameter name. It works - I've tried it.
> 
> That's the correct approach at the moment as there's no "body" parameter in OpenAPI spec 3.0 any more.

Although... this issue refers to OpenAPI 2.0, where you would expect the body parameter name to be preserved without having to resort to extension properties.

**Comment by advance512** [comment]
Sadly, this makes OpenAPI Generator much harder to use for OpenAPI 2.0 and JavaScript clients, and it loses lots of information that assists in development - like parameter naming.

Can we fix this regression?

BTW, I placed a bounty on this regression:
https://www.bountysource.com/issues/66124155-javascript-parameters-naming-in-functions-documentation-and-file-name-is-wrong

**Comment by wing328** [comment]
> Although... this issue refers to OpenAPI 2.0, where you would expect the body parameter name to be preserved without having to resort to extension properties.

I agree that's the ideal case done by the Swagger Parsers to prevent information loss.

**Comment by demonfiddler** [comment]
@advance512 I'd like to point out that optional parameters are placed in an object parameter named 'opts'. This is by design and although I don't particularly like the pattern, we need to preserve it otherwise it will break all the clients that have been generated to date. For this reason any change to this pattern would need to be enabled by a new configuration parameter that is off by default.

**Comment by advance512** [comment]
@demonfiddler 

1. As you can see by looking above, these parameters are NOT optional - they are required. Please have another look:
```
  oathIntegrationSettings:
    name: oathIntegrationSettings
    in: body
    required: true
    description: Settings of the Oath integration.
    schema:
      type: object
      required:
        - oathAuthCode
      properties:
        oathAuthCode:
          description: The Oath auth code to use for the integration, as returned from Oath OAuth.
          type: string
```

2. This is not a pattern that is to be preserved - this is a regression from a pattern that existed before, which was both right *and* should be preserved. This pattern was 

This regression is, in fact, breaking the usage of existing clients.

```
      * Adds the Oath Groto integration for a company account.
      * Adds the Oath Groto integration for a company account.
      * @param {Number} companyId A company identifier
-     * @param {module:model/OathIntegrationSettings} oathIntegrationSettings Settings of the Oath integration.
+     * @param {Object} opts Optional parameters
+     * @param {module:model/InlineObject3} opts.inlineObject3 
      * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Integration} and HTTP response
      */
-    this.addCompanyOathGrotoIntegrationWithHttpInfo = function(companyId, oathIntegrationSettings) {
-      var postBody = oathIntegrationSettings;
+    this.addCompanyOathGrotoIntegrationWithHttpInfo = function(companyId, opts) {
+      opts = opts || {};
+      var postBody = opts['inlineObject3'];
 
       // verify the required parameter 'companyId' is set
       if (companyId === undefined || companyId === null) {
         throw new Error("Missing the required parameter 'companyId' when calling addCompanyOathGrotoIntegration");
       }
 
-      // verify the required parameter 'oathIntegrationSettings' is set
-      if (oathIntegrationSettings === undefined || oathIntegrationSettings === null) {
-        throw new Error("Missing the required parameter 'oathIntegrationSettings' when calling addCompanyOathGrotoIntegration");
-      }
-
```

Swagger-codegen does this properly, as did OpenAPI-Generator until the regression that you pointed out, in April 17. The fact that this was not brought up is alarming, but does not mean that OpenAPI-Generator should default to a broken behavior. If anything, you can add a flag to allow keeping this broken behavior.

3. The workaround `x-codegen-request-body-name` is obviously not a long-term solution.

--

To put things in context - we are users of swagger-codegen and wanted to start using openapi-generator instead. We also sponsored some bug fixes for that reason, e.g. https://github.com/OpenAPITools/openapi-generator/issues/1429 and also this one. This issue is a deal breaker for us though - we will not modify our code to be *less* clear and readable, for the sake of a regression that makes no sense, nor will we add hundreds of `x-codegen-request-body-name` attributes to all of our OpenAPI files..

**Comment by advance512** [comment]
@wing328 

As OpenAPI-Generator is supposed to support OpenAPI v2, do you think someone could look into this? We'd love to begin using this project, but right now - we are blocked from doing so..

**Comment by demonfiddler** [comment]
@advance512 oh... my apologies then, I misunderstood the point you were making. I hadn't realised you're saying that required params are ending up in opts. That is definitely wrong. We are still using swagger-codegen for JavaScript (to which I have contributed in the past) and much as I'l like to migrate to OpenAPI Generator (which we _are_ using for JAX-RS/CXF, and to which I have a pending contribution) but this defect is a deal-breaker for us too. So yes, I'm in full agreement with you - this stuff needs to be fixed.

**Comment by advance512** [comment]
@demonfiddler No worries. And I am glad you also see it as imperative to fix. 

@jmini Any chance to get your inputs on this?

**Comment by advance512** [comment]
BTW, I noticed that a workaround would be, instead of:

```
parameters:
  oathIntegrationSettings:
    name: oathIntegrationSettings
    in: body
    required: true
    description: Settings of the Oath integration.
    schema:
      type: object
      required:
        - oathAuthCode
      properties:
        oathAuthCode:
          description: The Oath auth code to use for the integration, as returned from Oath OAuth.
          type: string
```

```
definitions:
   OathIntegrationSettings:
      type: object
      required:
        - oathAuthCode
      properties:
        oathAuthCode:
          description: The Oath auth code to use for the integration, as returned from Oath OAuth.
          type: string

parameters:
  oathIntegrationSettings:
    name: oathIntegrationSettings
    in: body
    required: true
    description: Settings of the Oath integration.
    schema:
      $ref: '#/definitions/OathIntegrationSettings'
```
This generates the code as expected.
