### ISSUE TITLE
[BUG] generator ignores format on objects

### ISSUE THREAD

**Issue by tbatchlear** [OpenAPITools/openapi-generator#14431]
## Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [X] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

### Description

According to the [JSON Schema Specification Draft 2020-12](https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-00#section-4.2.1), valid instance data models are `null`, `boolean`, `object`, `array`, `number`, and `string`.  Furthermore, according to the [openapi specification](https://spec.openapis.org/oas/v3.1.0#data-types), all OAS datatypes are based on the types supported by the aforementioned specification, and can have an optional modifier property: `format`.  The [JSON Schema Specification defines several formats for datatypes](https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-validation-00#section-7.3), as does the [openapi specification](https://spec.openapis.org/oas/v3.1.0#data-types).

The generator supports additional format options via `importMappings` and `typeMappings`.  However, when a schema identified as a `type: object` is defined, the `format` is ignored by the validator.

When using a custom format for a custom object, it should be defined as a `type: object`.  This way tools such as Postman can properly validate a schema against a response (it will fail on `format` as unknown format, however this can be ignored so long as it matches the type of `object`.  However, defining as a `type: string` will always cause schema validation tools to fail because the received object is not of `type: string`.

### openapi-generator version

6.2.1

### OpenAPI declaration file content or url
```yaml
openapi: 3.0.3
info:
  title: My-API
  version: 0.0.1
servers:
  - url: 'https://localhost:8080'
paths:
  /dates:
    get:
      operationId: getDates
      responses:
        "200":
          $ref: '#/components/responses/DateResponse'
        "5XX":
          description:  Unknown error has occured
      summary: get dates
      tags:
        - Dates
components:
  schemas:
    DateCollection:
      type: object
      properties:
        name:
          type: string
        objectDate:
          type: object
          format: instant
        stringInstant:
          type: string
          format: instant
        stringInstantRemappedDate:
          type: string
          format: date-time
  responses:
    DateResponse:
      description: OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DateCollection'
```

  -->

### Generation Details

I am using the gradle plugin.  Using the above yaml, I run the generator with these settings.
```groovy
    generatorName = "spring"
    inputSpec = "$projectDir/src/main/resources/static/object-format-example.yml"
    outputDir = "$projectDir"
    apiPackage = "com.generated.api.spring"
    invokerPackage = "com.generated.invoker.spring"
    modelPackage = "com.generated.model.spring"
    typeMappings = [
            OffsetDateTime: "Instant",
            instant: "Instant"
    ]
    importMappings = [
            Instant: "java.time.Instant"
    ]
    configOptions = [
            dateLibrary: "java8",
            serializableModel: "true"
    ]
```

The resulting generated model from the above configuration looks like this

```java
  @JsonProperty("objectDate")
  private Object objectDate;

  @JsonProperty("stringInstant")
  private Instant stringInstant;

  @JsonProperty("stringInstantRemappedDate")
  @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME)
  private Instant stringInstantRemappedDate;
```

### Steps to reproduce

Step 1.  Use the yaml above
Step 2.  Use the mappings above
Step 3.  generate models

### Related issues/PRs

None that I could find

##### Suggest a fix

[Line 808 of the InlineModelResolver](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/InlineModelResolver.java#L808) explicitly sets the format of an object model.  However, the format is only used if the type is `type: string`.  

Suggest updating the `DefaultCodegen.java` to allow models with a defined format to be processed similarly to strings.   Specifically, [these lines](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java#L2364) should be updated to the following:
```java
        } else if (ModelUtils.isStringSchema(schema)) {
            if (typeMapping.containsKey(schema.getFormat())) {
                // If the format matches a typeMapping (supplied with the --typeMappings flag)
                // then treat the format as a primitive type.
                // This allows the typeMapping flag to add a new custom type which can then
                // be used in the format field.
                return schema.getFormat();
            }
            return "string";
        } else if (isFreeFormObject(schema)) {
            // Allows typeMapping flag to add a new custom type instead of an Object.
            // By defining a format for an object, objects can pass most schema validators
            // even if the format is unknown.
            if (typeMapping.containsKey(schema.getFormat())) {
                return schema.getFormat();
            }
            // Note: the value of a free-form object cannot be an arbitrary type. Per OAS specification,
            // it must be a map of string to values.
            return "object";
```
This would allow the schema to generate a custom object without defining a custom `schema-mapping`, and allow the schema to pass validation.

**Comment by Kalliser** [comment]
Hello, in our project we experimenting the same problem, format is ignored in our case this in number formatting, integer is asked but ignored by generator so we receive double, which is causing crashes on our backend : 
```
/v1/stats/addPasDeposit/{contractId}/{geoHash}/{userId}:
    put:
      operationId: StatsController_depotPas
      parameters:
        - name: contractId
          required: true
          in: path
          schema:
            type: string
        - name: geoHash
          required: true
          in: path
          schema:
            type: string
        - name: userId
          required: true
          in: path
          schema:
            type: string
        - name: earnedPoints
          required: false
          in: query
          schema:
            type: number
            format: integer
```

**Comment by tbatchlear** [comment]
This is because [integer is a type, not a format](https://swagger.io/docs/specification/data-models/data-types/#numbers).  
```yaml
 - name: earnedPoints
          required: false
          in: query
          schema:
            type: integer
```
or to force integer generation
```yaml
 - name: earnedPoints
          required: false
          in: query
          schema:
            type: integer
            format: int32
```
or to force `long` generation
```yaml
 - name: earnedPoints
          required: false
          in: query
          schema:
            type: integer
            format: int64
```
