### ISSUE TITLE
[typescript-axios] Generating bearerAuth create Basic auth instead

### ISSUE THREAD

**Issue by chattersley** [OpenAPITools/openapi-generator#1446]
##### Description

Attempting to generate from an openapi definition with bearerAuth marked as the security schema. When it generates using axios-typescript it generates Basic auth security instead? It does generate a comment referencing Bearer auth but no code to add the header.

##### openapi-generator version

"@harmowatch/openapi-generator-cli": "0.0.3-3.3.2"

##### OpenAPI declaration file content or url

```yaml
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
```

This generates
```typescript
            // authentication bearerAuth required
            // http basic authentication required
            if (
                configuration &&
                (configuration.username || configuration.password)
            ) {
                localVarHeaderParameter["Authorization"] =
                    "Basic " +
                    btoa(configuration.username + ":" + configuration.password);
            }
```

##### Command line used for generation

Generating through npm.
npm=6.2.0
node=v10.9.0
"generate": "openapi-generator generate -i api/myapi.yaml -g typescript-axios -o generated-sources/myapi"

##### Steps to reproduce

Running generate commmand.

**Comment by mbayou** [comment]
Hi,

This issue exists for typescript-angular too.

```
components
  securitySchemes:
    bearerAuth:            
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
```
And my generated code:

```
// authentication (bearerAuth) required
if (this.configuration.username || this.configuration.password) {
    headers = headers.set('Authorization', 'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password));
}
```
