### ISSUE TITLE
[BUG] Order of securitySchemes not respected

### ISSUE THREAD

**Issue by gcatanese** [OpenAPITools/openapi-generator#14531]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

The original order of the securitySchemes is lost during the code generation and replaced with an alphabetical order.

When parsing the following OpenAPI file the outcome is a list of `List<CodegenSecurity>` sorted alphabetically, in this case `[api_key, petstore_auth]`

```
  securitySchemes:
    petstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'http://petstore.swagger.io/api/oauth/dialog'
          scopes:
            'write:pets': modify pets in your account
            'read:pets': read your pets
    api_key:
      type: apiKey
      name: api_key
      in: header

```

The code generation should not alter the order from the OpenAPI specs (this order is relevant for tools and applications that work with the securityScheme).

The expected output is a`List<CodegenSecurity>` with the original order`[petstore_auth, api_key]`

##### openapi-generator version

Found on `6.3.0-SNAPSHOT`.

##### Generation Details

It can be reproduced with an OpenAPI specs defining multiple `securitySchemes`, see `DefaultCodegenTest.testOauthMultipleFlows`
