### ISSUE TITLE
[BUG][csharp-netcore] Conflict with method parameter name

### ISSUE THREAD

**Issue by kYann** [OpenAPITools/openapi-generator#14553]
##### Description

When one of the property of the model is names "options" we have a conflict with a generated function parameter name.

##### openapi-generator version

6.3.0-20230125.125049-89

##### OpenAPI declaration file content or url

https://gist.github.com/kYann/9bccb4cbe852adc682b676d2f3557488

##### Generation Details

java -jar ..\openapi-generator-cli-6.3.0-20230125.125049-89.jar generate -i ..\admin-swagger.json -c ..\config.yaml

Config
```yaml
generatorName: csharp-netcore
library: generichost
additionalProperties:
  artifactId: PublicClient
  packageName: PublicClient
  targetFramework: net6.0
  useDateTimeOffset: true
  nullableReferenceTypes: true
  packageDescription: Public client to access rest api
  packageTitle: "Api Client"
```

##### Steps to reproduce

Generate the project using the provided swagger and config

##### Suggest a fix

On the json converter, the Read function have a `JsonSerializerOptions` parameter named `options`, it should be renamed.
```csharp
// Generated code
public override BillingInvoicePostInput Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
{
  int currentDepth = reader.CurrentDepth;

  if (reader.TokenType != JsonTokenType.StartObject && reader.TokenType != JsonTokenType.StartArray)
    throw new JsonException();

  JsonTokenType startingTokenType = reader.TokenType;

  DateTimeOffset date = default;
  BillingInvoiceFromApi from = default;
  BillingCreateInvoiceOptions options = default;
  // ...
}

// Could be a fix
public override BillingInvoicePostInput Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions )
{
  int currentDepth = reader.CurrentDepth;

  if (reader.TokenType != JsonTokenType.StartObject && reader.TokenType != JsonTokenType.StartArray)
    throw new JsonException();

  JsonTokenType startingTokenType = reader.TokenType;

  DateTimeOffset modelDate = default;
  BillingInvoiceFromApi modelFrom = default;
  BillingCreateInvoiceOptions modelOptions = default;
  // ...
}
```
