### ISSUE TITLE
[BUG][csharp-netcore] Cannot serialize nullable guid

### ISSUE THREAD

**Issue by kYann** [OpenAPITools/openapi-generator#14552]
##### Description

When a model contains nullable guid the generated code does not compile. csharp-netcore

##### openapi-generator version

6.3.0-20230125.125049-89

csharp-netcore

##### OpenAPI declaration file content or url

https://gist.github.com/kYann/23eab426be79fd2cb93c2ddb902a8ecd

##### Generation Details

`java -jar ..\openapi-generator-cli-6.3.0-20230125.125049-89.jar generate -i ..\swagger.json -c ..\config.yaml``

config
```yaml
generatorName: csharp-netcore
library: generichost
additionalProperties:
  artifactId: PublicClient
  packageName: PublicClient
  targetFramework: net6.0
  useDateTimeOffset: true
  nullableReferenceTypes: true
  packageDescription: Public client to access rest api
  packageTitle: "Api Public Client"
```

##### Steps to reproduce

Run generate command on the provided swagger file.

##### Suggest a fix

```csharp
// Issue is for nullable guid
writer.WriteString("evseId", chargingSessionsEvseApi.EvseId);

// We could write
if (chargingSessionsEvseApi.EvseId.HasValue)
  writer.WriteString("evseId", chargingSessionsEvseApi.EvseId.Value);
else
  writer.WriteNull("evseId");
```
