### ISSUE TITLE
[Kotlin][Spring] Incorrect generated class types when signature for two fields is the same

### ISSUE THREAD

**Issue by martinformi** [OpenAPITools/openapi-generator#14570]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ ] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description
Yaml:

```
    Testing:
      title: Testing
      x-stoplight:
        id: i4nhdvxy75d5w
      type: object
      properties:
        field1:
          type: object
          additionalProperties: false
          properties:
            name:
              type: string
        field2:
          type: object
          additionalProperties: false
          properties:
            name:
              type: string
```

Generated domain class:
```
/**
 * 
 * @param field1 
 * @param field2 
 */
data class Testing(

    @field:Valid
    @field:JsonProperty("field1") val field1: TestingField1? = null,

    @field:Valid
    @field:JsonProperty("field2") val field2: TestingField1? = null
) {

}
```

##### openapi-generator version

6.3.1

##### Generation Details

```
// The values oasPackage, oasSpecLocation, oasGenOutputDir are defined earlier
tasks.register("generateServer", org.openapitools.generator.gradle.plugin.tasks.GenerateTask::class) {
    input = project.file(oasSpecLocation).path
    outputDir.set(oasGenOutputDir.toString())
    modelPackage.set("$oasPackage.model")
    apiPackage.set("$oasPackage.api")
    packageName.set(oasPackage)
    generatorName.set("kotlin-spring")
    configOptions.set(
        mapOf(
            "exceptionHandler" to "false",
            "annotationLibrary" to "none",
            "documentationProvider" to "none",
            "dateLibrary" to "java8",
            "interfaceOnly" to "true",
            "reactive" to "false",
            "useTags" to "true",
            "useSpringController" to "false"
        )
    )
}
```

##### Steps to reproduce

Just generate the class based on YAML.
