### ISSUE TITLE
[BUG] [kotlin-spring] Bigdecimal generation with default value is not working

### ISSUE THREAD

**Issue by pdione** [OpenAPITools/openapi-generator#14584]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ ] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When we generate the code in Kotlin language  with a Bigdecimal default value, the code doesn't compile.

##### openapi-generator version

I'm using the 6.2.1 version of openapi-generator.
##### OpenAPI declaration file content or url

Please find below a sample of the affected class from my yaml file :
```yaml
LoanType:
  type: object
  properties:
    projectTotalAmount:
      type: number
      description: |
        #### Total amount of the project
      default: -9999999999.99
    downpaymentAmount:
      type: number
      description: |
       #### Downpayment amount
      default: -9999999999.99
```
##### Generation Details
The expected generated code for the class fields should be :
```kotlin
data class LoanType(
	var projectTotalAmount: java.math.BigDecimal?= BigDecimal(-9999999999.99)
	var downpaymentAmount: java.math.BigDecimal?= BigDecimal(-9999999999.99)
)
```
Instead of the actual result that doesn't compile :
```kotlin
data class LoanType(
	var projectTotalAmount: java.math.BigDecimal?= -9999999999.99
	var downpaymentAmount: java.math.BigDecimal?= -9999999999.99
)
```
