### ISSUE TITLE
[REQ] Specify folder for API and Model files

### ISSUE THREAD

**Issue by dragorosson** [OpenAPITools/openapi-generator#14658]
### Is your feature request related to a problem? Please describe.

The docs for [user defined templates](https://openapi-generator.tech/docs/customization/#user-defined-templates) show `folder` being provided to control the directory a supporting file goes:

```
templateDir: my_custom_templates
additionalProperties:
  artifactId: kotlin-petstore-client
  serializableModel: "true"
  dateLibrary: java8
files:
  AUTHORS.md: {}
  api_interfaces.mustache:
    templateType: API
    destinationFilename: Interface.kt
  api.mustache:
    templateType: API
    destinationFilename: Impl.kt
  other/check.mustache:
    folder: scripts            <--------- FOLDER
    destinationFilename: check.sh
    templateType: SupportingFiles
```

This is really useful. However, `folder` cannot be specified for any other template types (I've only tried `API` and `Model`). The generator I'm using creates a whole project and I don't want to follow its directory structure, but I'm forced to right now.

## Describe the solution you'd like

It would be great to be able to control the destination `folder` of all files specified in the config!

## Describe alternatives you've considered

I don't see any complete workarounds. The `aspnetcore` generator, for example, puts API files in `{output dir}/src/{packageName}/Controllers/`. I have my own project and want generated files to go in `{my project dir}/Generated/`. I've used `.openapi-generator-ignore` to skip generating project files, set the output dir to be the project root, and configured `src` to be `Generated`. This means my API files are put in `{my project dir}/Generated/{packageName}/Controllers`. This is better, but I'd really like `{output dir}` to be `Generated/` and have API files go into `API/` not `Controllers/` so overall my API files would go in `{my project dir}/Generated/API/`. Same for all of the other template types.
