### ISSUE TITLE
[BUG] [Javascript] When creating a Enum in a Query Path, it is being generated as model/String and cant be used.

### ISSUE THREAD

**Issue by TheSilentHorizon** [OpenAPITools/openapi-generator#14857]
##### Description

I have an enum in my path which can be of the values "CLUB" or "EVENT". Definition:

```

 parameters:
    ClubElementType:
      name: ClubElementType
      in: path
      required: true
      schema:
        type: string
        enum:
          - CLUB
          - EVENT
      description: The type of Element to handle.
```

When used in a api function, it gets defined as this type:

`@param {module:model/String} clubElementType The type of Element to handle.`

Which is obviously wrong, since there is no class "model/String".

##### openapi-generator version

6.4.0

##### OpenAPI declaration file content or url

```

 parameters:
    ClubElementType:
      name: ClubElementType
      in: path
      required: true
      schema:
        type: string
        enum:
          - CLUB
          - EVENT
      description: The type of Element to handle.
```

##### Generation Details

just use the "javascript" generator.

##### Steps to reproduce

create a schema with an string enum and use it in a method. Works also inline.

##### Related issues/PRs

nothing found
