### ISSUE TITLE
[BUG][Typescript] Invalid type for the enum array

### ISSUE THREAD

**Issue by wtrocki** [OpenAPITools/openapi-generator#14892]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ ] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

 
##### Description

Array of enums causes compilation error:
```yaml
        index:
          type: array
          items:
              type: string
              enum:
                - "1"
                - "1"
                - "-1"
```

error:
```
public property ''index'' of exported class has or is using private name 'InnerEnum'.

31     'index'?: Array<{ [key: InnerEnum]: InnerEnum; }>;
```
##### Generation Details

 Generator typescript.
 
##### Steps to reproduce

Run generator for schema above.
