### ISSUE TITLE
[BUG][Java] Multipart request model not generated on Java feign library

### ISSUE THREAD

**Issue by mdipsan** [OpenAPITools/openapi-generator#14976]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ ] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

The code generated for a request body of type "multipart/form-data" that contains a reference to an object model as well as the file property(binary format) is missing the object model.

##### openapi-generator version

6.4.0

##### OpenAPI declaration file content or url

```yaml
{
  "openapi": "3.0.1",
  "info": {
    "title": "Issue example",
    "description": "Issue example",
    "version": "1.0",
    "contact": {}
  },
  "servers": [
    {
      "url": "https://example-url.com"
    }
  ],
  "paths": {
    "/example/path": {
      "post": {
        "summary": "Example summary",
        "operationId": "ExampleOperation",
        "responses": {
          "204": {
            "description": "No Content"
          }
        },
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "properties": {
                    "$ref": "#/components/schemas/not-generated-object"
                  },
                  "file": {
                    "type": "string",
                    "format": "binary",
                    "description": "A file example."
                  }
                },
                "required": [
                  "properties",
                  "file"
                ]
              }
            }
          },
          "description": ""
        }
      }
    }
  },
  "components": {
    "schemas": {
      "not-generated-object": {
        "title": "Not Generated Request Model",
        "type": "object",
        "description": "",
        "properties": {
          "type": {
            "type": "string",
            "description": "The type string example",
            "enum": [
              "value1",
              "value2"
            ]
          },
          "someExampleId": {
            "type": "string",
            "description": "The example identifier."
          }
        },
        "required": [
          "type"
        ]
      }
    }
  }
}
```

##### Generation Details

Generated using the openapi-generator-maven-plugin as follows:

```xml
<plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>6.4.0</version>
                <configuration>
                    <inputSpec>${project.basedir}/src/main/resources/ApiSpec.yml</inputSpec>
                    <configOptions>
                        <sourceFolder>src/gen/java/main</sourceFolder>
                        <interfaceOnly>true</interfaceOnly>
                        <dateLibrary>joda</dateLibrary>
                    </configOptions>
                    <output>${project.build.directory}/generated-sources</output>
                    <language/>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <generatorName>java</generatorName>
                            <library>feign</library>
                            <modelPackage>model</modelPackage>
                            <apiPackage>api</apiPackage>
                            <invokerPackage>invoker</invokerPackage>
                            <generateApiTests>false</generateApiTests>
                            <generateModelTests>false</generateModelTests>
                            <inputSpec/>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

##### Steps to reproduce

1. Run `mvn clean compile` on a maven project that has the plugin mentioned above.
2. Observe that the `not-generated-object` related class is not generated and the compilation fails with the following errors:
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] {projectDir}/target/generated-sources/src/gen/java/main/api/DefaultApi.java:[8,13] cannot find symbol
  symbol:   class NotGeneratedObject
  location: package model
[ERROR] {projectDir}/target/generated-sources/src/gen/java/main/api/DefaultApi.java:[31,46] cannot find symbol
  symbol:   class NotGeneratedObject
  location: interface api.DefaultApi
[ERROR] {projectDir}/target/generated-sources/src/gen/java/main/api/DefaultApi.java:[45,71] cannot find symbol
  symbol:   class NotGeneratedObject
  location: interface api.DefaultApi
