### ISSUE TITLE
[BUG][Java] Enums with non english language use underscore _ as an identifier

### ISSUE THREAD

**Issue by ooraini** [OpenAPITools/openapi-generator#15024]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ ] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

The following enum:

```
                properties:
                  id:
                    type: integer
                    format: int32
                    example: 1
                  name:
                    type: string
                    enum:
                      - هجري
                      - ميلادي
                    maxLength: 7
                    example: هجري
```

results in:
```
  public enum NameEnum {
    _("هجري"),
    
    _("ميلادي");

    private String value;
```

Which in invalid for two reason, 1) underscore is not a valid identifier, 2) The invalid name is repeated.   

Solution used by another generator:
```
  public enum NameEnum {
    _1("هجري"),
    
    _2("ميلادي");

    private String value;

```

##### openapi-generator version

6.4

##### Generation Details

spring
