### ISSUE TITLE
[BUG] [JAVA] When adding examples for parameters in the openApi definition this is not added to the delegate interface. 

### ISSUE THREAD

**Issue by juan-conca** [OpenAPITools/openapi-generator#15093]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When adding examples of usages of parameters, the code is not copied to the interface of the delegate.

##### openapi-generator version

Version: 6.2.1

##### OpenAPI declaration file content or url

```yaml
    Size:
      in: query
      name: size
      required: false
      schema:
        type: integer
      description: size of the page
    Page:
      in: query
      name: page
      required: false
      schema:
        type: integer
      description: page number
    Sort:
      in: query
      name: sort
      required: false
      explode: false
      schema:
        type: array
        items:
          type: string
      description: sort by field and direction (asc or desc)
      examples:
        simple-default-order:
          value: [ companyName ]
          summary: Sort by companyName in ascending order
        simple:
          value: [ companyName,desc ]
          summary: Sort by companyName in descending order
        multiple:
          value: [ companyName,asc,companyStatus,desc ]
          summary: Sort by companyName in ascending order and companyStatus in descending order
        wrong:
          value: [ companyName,companyStatus,asc,desc ]
          summary: WRONG - Sort by fields and then all directions
```

##### Generation Details

The output has nothing related to the examples
```java
    default ResponseEntity<FooEntityDto> getAllFooEntity(
        @Parameter(name = "size", description = "size of the page") @Valid @RequestParam(value = "size", required = false) Integer size,
        @Parameter(name = "page", description = "page number") @Valid @RequestParam(value = "page", required = false) Integer page,
        @Parameter(name = "sort",  description = "sort by field and direction (asc or desc)" @Valid @RequestParam(value = "sort", required = false) List<String> sort
    ) {
        return getDelegate().getAllCompanyRegistrations(size, page, sort);
    }
```

Expected something like this to be generated.
```java
    default ResponseEntity<FooEntityDto> getAllFooEntity(
        @Parameter(name = "size", description = "size of the page") @Valid @RequestParam(value = "size", required = false) Integer size,
        @Parameter(name = "page", description = "page number") @Valid @RequestParam(value = "page", required = false) Integer page,
        @Parameter(name = "sort",
                description = "sort by field and direction (asc or desc)",
        examples = {
                @ExampleObject(name="simple-default-order", summary = "Sort by companyName in ascending order", value = "[companyName]"),
                @ExampleObject(name="simple", summary = "Sort by companyName in descending order", value = "[companyName,desc]"),
                @ExampleObject(name="multiple", summary = "Sort by companyName in ascending order and companyStatus in descending order",
                        value = "[companyName,asc,companyStatus,desc]"),
                @ExampleObject(name="wrong", summary = "WRONG - Sort by fields and then all directions",
                        value = "[companyName,companyStatus,asc,desc]")
        })
        @Valid @RequestParam(value = "sort", required = false) List<String> sort
    ) {
        return getDelegate().getAllCompanyRegistrations(size, page, sort);
    }
```

To match the output of the original openApi UI output form the definition:

![Screenshot 2023-03-31 at 14 20 01](https://user-images.githubusercontent.com/104761231/229121575-fb3cf367-7495-4f8a-a157-a81e894285c9.png)

And not something like this, based on the JAVA code generated:
![Screenshot 2023-03-31 at 14 37 27](https://user-images.githubusercontent.com/104761231/229122009-4239c1e1-988a-4322-a57e-3095916ddef1.png)

##### Steps to reproduce

Create a component parameter, that contain an example or examples, and review the definition of Api interface to see if the code there has none of elements example or examples defined in the Swagger file.

##### Related issues/PRs

I not found anything similar or related.
