### ISSUE TITLE
[Question] OAuth2 implicit flow is outdated, should we update the spec in samples?  

### ISSUE THREAD

**Issue by makru86** [OpenAPITools/openapi-generator#15111]
##### Description

Since few months OAuth 2.0 flow _Implicit Grant_ is not recommended to use, and considered insecure.
Recommended to change to Authorization Code flow, with PKCE extension. https://oauth.net/2/grant-types/implicit. 

Question - should we update our petstore.yaml files accordingly?

##### OpenAPI declaration file content or url

 https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/test/resources/3_1/petstore.yaml#L597

```yaml
 petstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'http://petstore.swagger.io/api/oauth/dialog'
          scopes:
            'write:pets': modify pets in your account
            'read:pets': read your pets
 ```

##### Note

Authorization Code flow is specified in openapi 3, but PKCE extension is not supported.
https://swagger.io/specification/#oauth-flow-object
