### ISSUE TITLE
[BUG] openapi-generator typescript-axios generated model properties optional

### ISSUE THREAD

**Issue by OSRSBlue** [OpenAPITools/openapi-generator#15152]
#### Bug Report Checklist

- [ X] Have you provided a full/minimal spec to reproduce the issue?
- [ X ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [  X ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ X ] Have you searched for related issues/PRs?
- [ X ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When I generate a typescript-axios client from my APIs written in GoLang all of the models properties are optional. I would expect all the fields to be non optional unless specified.

##### openapi-generator version

Library: @openapitools/openapi-generator-cli: 2.5.2

##### OpenAPI declaration file content or url

GoLang Model
```
// Account model info
// @Description User account information
// @Description with user id, username, nickname, avatar, roles, guild avatar, and rank
type Account struct {
	ID          string   `json:"id"`
	Username    string   `json:"username"`
	Nick        string   `json:"nick"`
	Avatar      string   `json:"avatar"`
	Roles       []string `json:"roles"`
	GuildAvatar string   `json:"guildAvatar"`
	Rank        string   `json:"rank"`
}
```

Generated swag model from yaml file:
```
definitions:
  models.Account:
    description: User account information with user id, username, nickname, avatar,
      roles, guild avatar, and rank
    properties:
      avatar:
        type: string
      guildAvatar:
        type: string
      id:
        type: string
        x-nullable: "false"
      nick:
        type: string
      rank:
        type: string
      roles:
        items:
          type: string
        type: array
      username:
        type: string
    type: object
```

typescript-axios generated model from yaml file definition:
```
/**
 * User account information with user id, username, nickname, avatar, roles, guild avatar, and rank
 * @export
 * @interface ModelsAccount
 */
export interface ModelsAccount {
    /**
     * 
     * @type {string}
     * @memberof ModelsAccount
     */
    'avatar'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsAccount
     */
    'guildAvatar'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsAccount
     */
    'id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ModelsAccount
     */
    'nick'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsAccount
     */
    'rank'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ModelsAccount
     */
    'roles'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ModelsAccount
     */
    'username'?: string;
}
```

##### Generation Details

Building a typescript axios client using the command:
`
openapi-generator-cli generate -i specFile -g typescript-axios -o outputDir -p packageName
`

results in all my produced models from my GoLang swag generated definition to be optional. I would expect them to not be optional unless specified.

##### Steps to reproduce

1. Build API Spec with user defined Golang struct.
2. Build an typescript axios client via: openapi-generator-cli generate -i specFile -g typescript-axios -o outputDir -p packageName
3. Check produced models to verify all the properties are all optioanl (? next to the property name)

##### Suggest a fix
I may be describing my models incorrectly, so this could just be user error. If it is not I would expect to be able to describe a field as optional so that I can set my fields manually instead of the typescript-axios generated making them all optional.
