### ISSUE TITLE
[BUG][typescript-axios] generates incorrect boolean enum from V2 spec

### ISSUE THREAD

**Issue by ssukienn** [OpenAPITools/openapi-generator#15178]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Incorrect generation of model for boolean enum type. It is similar problem to linked similar issue/pr

##### openapi-generator version

latest docker image, `6.6.0-SNAPSHOT` at the time of writing

##### OpenAPI declaration file content or url

```yaml
{
  "swagger": "2.0",
  "info": {
    "title": "",
    "version": ""
  },
  "host": "test.com",
  "basePath": "/api",
  "paths": {},
  "definitions": {
    "Commodity": {
      "type": "object",
      "properties": {
        "active": {
          "type": "boolean",
          "format": "boolean",
          "enum": [
            "true",
            "false"
          ]
        }
      }
    }
  }
}
```

##### Generation Details

Config can be seen below. Generated output creates: 
```ts
/**
    * @export
    * @enum {string}
    */
export enum CommodityActiveEnum {
    TRUE = true,
    FALSE = false
}
```

which is incorrect. Should be smth like `type = true | false` or normalize to strings

##### Steps to reproduce

1. Create some dir for docker volume with `config.yaml`, `schema.yaml` (content above), and `generate.sh` script (or run inline)
```sh
#!/bin/bash

docker run --rm \
  -v "${VOLUME_PATH}":/openapi openapitools/openapi-generator-cli generate \
  -i /openapi/schema.yaml \
  -g typescript-axios \
  -o /openapi/output" \
  -c /openapi/config.yaml \
  --skip-operation-example
```
config.yaml:
```yaml
snapshot: false
supportsES6: true
allowUnicodeIdentifiers: true
apiPackage: api
modelPackage: model
withSeparateModelsAndApi: true
enumPropertyNaming: UPPERCASE
stringEnums: true
useSingleRequestParameter: true
```

2. run `./generate.sh`
##### Related issues/PRs

Related to https://github.com/OpenAPITools/openapi-generator/issues/9024
