### ISSUE TITLE
[BUG] [dart-dio] Cannot convert Date type using json_serializer

### ISSUE THREAD

**Issue by AAkira** [OpenAPITools/openapi-generator#15182]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

The dart-dio doesn't convert the Date type using json_serializer but the dart-dio can convert the Date type using built_value.

##### openapi-generator version

v6.5.0

##### OpenAPI declaration file content or URL

* openapi.yaml

```yaml
...
        binary:
          description: None
          format: binary
          type: string
        date:
          description: None
          format: date
          type: string
        dateTime:
          description: None
          format: date-time
          type: string
...
```

##### Generation Details

* samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake-json_serializable/lib/src/api/fake_api.dart
 
```dart
...

 Future<Response<void>> testEndpointParameters({ 
    required num number,
    required double double_,
    required String patternWithoutDelimiter,
    required String byte,
    int? integer,
    int? int32,
    int? int64,
    double? float,
    String? string,
    MultipartFile? binary,
    DateTime? date,                     // <= Scheme type is Date but here is DateTime.
    DateTime? dateTime,
    String? password,
    String? callback,
    CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    ValidateStatus? validateStatus,
    ProgressCallback? onSendProgress,
    ProgressCallback? onReceiveProgress,
  }) async {
    final _path = r'/fake';

...
```

##### Suggest a fix

Conversion of date type is only done with bulit_value.

https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/DartDioClientCodegen.java#L298-L304
