### ISSUE TITLE
[BUG] validation error in command line tool

### ISSUE THREAD

**Issue by jjjessen** [OpenAPITools/openapi-generator#15216]
##### Description
I'm using the command line tool to generate dart code like this

java -jar openapi-generator-cli-6.5.0.jar generate -i sphinx.yaml -g dart -o generated

and I get the following error:

Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
 | Error count: 1, Warning count: 0
Errors:
	-attribute info.license.identifier is missing

The first lines of my openapi file looks like this:
openapi: 3.1.0
info:
  title: Bullet Train API
  description: |
    The baseline API of a new Bullet Train application.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: "V1"

From the openapi specification (license section) I see this regarding identier

identifier : An [SPDX](https://spdx.org/spdx-specification-21-web-version#h.jxpfx0ykyb60) license expression for the API. The identifier field is mutually exclusive of the url field.

When I paste the file content to https://apitools.dev/swagger-parser/online/ the file parses, but the command line tool fails.

I believe the validator in the command line tool, should implement the "mutual exclusive part" from the specification regarding license information.

##### OpenAPI declaration file content or url

```yaml
info:
  title: Bullet Train API
  description: |
    The baseline API of a new Bullet Train application.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: "V1"
```
