### ISSUE TITLE
[REQ] [java] [templates] setter properties should also 

### ISSUE THREAD

**Issue by elonderin** [OpenAPITools/openapi-generator#15267]
### Is your feature request related to a problem? Please describe.

in my IDE (intellij) i want to see the jdoc also on setters of properties

## Describe the solution you'd like

add the jdoc derived from the property's description also to the setters 

## Describe alternatives you've considered

n/a

## Additional context

given the model
```yaml
    Foo:
      type: object
      properties:
        bar:
          description: bar comment
          type: string
```

the java/spring generator produces:
```java

  public Foo bar(String bar) {
    this.bar = bar;
    return this;
  }

  /**
   * bar comment
   * @return bar
  */
  
  @Schema(name = "bar", description = "bar comment", requiredMode = Schema.RequiredMode.NOT_REQUIRED)
  @JsonProperty("bar")
  public String getBar() {
    return bar;
  }

  public void setBar(String bar) {
    this.bar = bar;
  }
...
```
i want the generated jdoc on `getBar()` also on `setBar()` and `bar(String)`

Note: this ticket could also be applicable to other languages
