### ISSUE TITLE
[BUG] [JAVA] OkHttpClient: deprecated property only generates a deprecated getter

### ISSUE THREAD

**Issue by gcatanese** [OpenAPITools/openapi-generator#15286]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

During the OkHttpClient generation, a deprecated property only generates a deprecated getter, while the model attribute, the setter method and the builder method are not deprecated

##### openapi-generator version

Verified with `6.6.0-SNAPSHOT`

##### OpenAPI declaration file content or url

For the `declawed` property only the getter method is deprecated
```yaml
          properties:
            dogType:
              type: string
            declawed:
              deprecated: true
              type: boolean
```

##### Steps to reproduce

Deprecate attribute `declawed` in model
Generate code for OkHttpClient

**Current output**

Only getter method is deprecated 

**Expected output**

Deprecate property, setter and builder methods
