### ISSUE TITLE
[BUG] String enum of '08' and '09 ' are wrong packaged

### ISSUE THREAD

**Issue by AlfaCoder** [OpenAPITools/openapi-generator#15329]
##### Description

I need enums of strings, but in the builded openapi.yaml I get an incorrect enum-values for '08' and '09'.
The apostrophe in the packaged openapi.yaml is removed for this values... I have no idea

##### openapi-generator version

6.4.0

##### OpenAPI declaration file content or url

any-title-here.yml
```yaml
title: AnyTitleHere
type: string
example: 70
enum:
  - '02'
  - '03'
  - '04'
  - '05'
  - '06'
  - '07'
  - '08'
  - '09'
  - '10'
  - '11'
  - '12'
  - '13'
  - '15'
  - '16'
```

generated openapi.yaml
```yaml
title: AnyTitleHere
type: string
example: 70
enum:
  - '02'
  - '03'
  - '04'
  - '05'
  - '06'
  - '07'
  - 08
  - 09
  - '10'
  - '11'
  - '12'
  - '13'
  - '15'
  - '16'
```
