### ISSUE TITLE
[BUG] [dart-dio] Enum class does not implement toString using json_serializer 

### ISSUE THREAD

**Issue by AAkira** [OpenAPITools/openapi-generator#15382]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Enum class doesn't implement toString using json_serializer.

```dart
enum PetStatusEnum {
  @JsonValue(r'available')
  available,
  @JsonValue(r'pending')
  pending,
  @JsonValue(r'sold')
  sold,
  @JsonValue(r'unknown_default_open_api')
  unknownDefaultOpenApi,
}
```

https://github.com/OpenApiTools/openapi-generator/blob/master/samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake-json_serializable/lib/src/model/pet.dart#L139-L148

The generator using json_serialization converts the Enum class directly into a String.
The string sent to the server side will look like this.

```dart
final status = PetStatusEnum.available;
print(status); // PetStatusEnum.available
```

This is the generated conversion code.

```dart
final _queryParameters = <String, dynamic>{
  r'status': status,
};
```

https://github.com/OpenApiTools/openapi-generator/blob/master/samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake-json_serializable/lib/src/api/pet_api.dart#L187-L189

Therefore, this will result in an Enum parsing error on the server side. 

BuiltValue has the[EnumClass](https://pub.dev/documentation/built_value/latest/built_value/EnumClass-class.html).

```dart
class PetStatusEnum extends EnumClass {

  /// pet status in the store
  @BuiltValueEnumConst(wireName: r'available')
  static const PetStatusEnum available = _$petStatusEnum_available;
  /// pet status in the store
  @BuiltValueEnumConst(wireName: r'pending')
  static const PetStatusEnum pending = _$petStatusEnum_pending;
  /// pet status in the store
  @BuiltValueEnumConst(wireName: r'sold')
  static const PetStatusEnum sold = _$petStatusEnum_sold;
  /// pet status in the store
  @BuiltValueEnumConst(wireName: r'unknown_default_open_api', fallback: true)
  static const PetStatusEnum unknownDefaultOpenApi = _$petStatusEnum_unknownDefaultOpenApi;

  static Serializer<PetStatusEnum> get serializer => _$petStatusEnumSerializer;

  const PetStatusEnum._(String name): super(name);

  static BuiltSet<PetStatusEnum> get values => _$petStatusEnumValues;
  static PetStatusEnum valueOf(String name) => _$petStatusEnumValueOf(name);
}
```

https://github.com/OpenApiTools/openapi-generator/blob/master/samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/src/model/pet.dart#L200-L221

##### openapi-generator version

v6.5.0

##### OpenAPI declaration file content or url

```yaml
apiVersion: 1.0.0
swaggerVersion: "1.2"
basePath: "http://localhost:8002/api"
resourcePath: /pet
produces: 
  - application/json
  - application/xml
  - text/plain
  - text/html
apis: 
  - path: /pet/findByStatus
    operations: 
      - method: GET
        summary: Finds Pets by status
        notes: Multiple status values can be provided with comma separated strings
        type: array
        items: 
          $ref: Pet
        nickname: findPetsByStatus
        produces: 
          - application/json
          - application/xml
        parameters: 
          - name: status
            description: Status values that need to be considered for filter
            defaultValue: available
            required: true
            allowMultiple: true
            type: string
            paramType: query
            enum: 
              - available
              - pending
              - sold
        responseMessages: 
          - code: 400
            message: Invalid status value
```

https://github.com/OpenApiTools/openapi-generator/blob/master/samples/yaml/pet.yml

##### Generation Details

```dart
enum PetStatusEnum {
  @JsonValue(r'available')
  available,
  @JsonValue(r'pending')
  pending,
  @JsonValue(r'sold')
  sold,
  @JsonValue(r'unknown_default_open_api')
  unknownDefaultOpenApi,
}
```

https://github.com/OpenApiTools/openapi-generator/blob/master/samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake-json_serializable/lib/src/model/pet.dart#L139-L148

##### Suggest a fix

Implement Enum toString available from Dart 2.17.
