### ISSUE TITLE
[BUG] [SPRING] incorrect generation of add*Item methods for List-fields in 6.5.0

### ISSUE THREAD

**Issue by arandth** [OpenAPITools/openapi-generator#15402]
##### Description

Migrating from 6.2.1 to 6.5.0 we run into an issue with list fields which might be defined as

    AdditionalProperties:
      properties:
        additional_properties:
          type: array
          default: []
          items:
            type: string

The generator will generate a add a addAdditionalPropertiesItem method wich is wrong:

  public AdditionalProperties addAdditionalPropertiesItem(String additionalPropertiesItem) {
    if (this.additionalProperties == null) {
      this.additionalProperties = null;     // **here is the bug**
    }
    this.additionalProperties.add(additionalPropertiesItem);
    return this;
  }

##### openapi-generator version

6.5.0 (maven plugin)

##### OpenAPI declaration file content or url

see above

**Comment by m-kay** [comment]
I'm having the same issue, however removing the `default: []` makes things even worse. Without the default the generated code looks like this:
```java
public AdditionalProperties addAdditionalPropertiesItem(String additionalPropertiesItem) {
   if (this.additionalProperties == null) {
      this.additionalProperties = ; // this does not even compile
   }
   this.additionalProperties.add(additionalPropertiesItem);
   return this;
}
```

**Comment by arandth** [comment]
I'm asking myself whether there are no regression tests for the generator that could avoid these kind of errors. It's annoying having a feature that used to work for so long, and suddenly, with a new version, something is broken.

**Comment by wing328** [comment]
@arandth agreed we can do better to catch regressions.

I filed a fix or 2 like 2 weeks ago. 

Can you please give it a try with the latest master?

**Comment by wing328** [comment]
>       default: []

the default behaviour is to initialise an empty list as the default.

setting `nullable: true` will use `null` as the default.

**Comment by arandth** [comment]
totally right. But as explained, it doesn't work so

**Comment by m-kay** [comment]
With version `6.6.0-SNAPSHOT` the problem still exists.

**Comment by wing328** [comment]
generated with the latest master with `./bin/configs/spring-boot-3.yaml`
```
generatorName: spring
outputDir: samples/openapi3/server/petstore/springboot-3
inputSpec: modules/openapi-generator/src/test/resources/3_0/petstore.yaml
templateDir: modules/openapi-generator/src/main/resources/JavaSpring
additionalProperties:
  groupId: org.openapitools.openapi3
  documentationProvider: springdoc
  artifactId: springboot
  snapshotVersion: "true"
  useSpringBoot3: true
  useBeanValidation: true
  hideGenerationTimestamp: "true"
```
added the following to `modules/openapi-generator/src/test/resources/3_0/petstore.yaml`

and got the following new java file partially shown below:
```java
@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
public class AdditionalProperties {

  @Valid
  private List<String> additionalProperties;

  public AdditionalProperties additionalProperties(List<String> additionalProperties) {
    this.additionalProperties = additionalProperties;
    return this;
  }

  public AdditionalProperties addAdditionalPropertiesItem(String additionalPropertiesItem) {
    if (this.additionalProperties == null) {
      this.additionalProperties = new ArrayList<>();
    }
    this.additionalProperties.add(additionalPropertiesItem);
    return this;
  }
```

in other words I cannot reproduce the issue  you reported.

can you please give it another try with the latest master?
