### ISSUE TITLE
[BUG] [Java] incorrect generation of add*Item methods for List-fields in 6.5.0

### ISSUE THREAD

**Issue by m-kay** [OpenAPITools/openapi-generator#15425]
The newest version 6.5.0 of the generator produces uncompilable add*Item methods when default is not specified. This was happenging the the spring generator as well and was already fixed there as you can see from the discussion in #15402 

```yaml
AdditionalProperties:
  properties:
    additional_properties:
      type: array
      items:
        type: string
```
produces
```java
public AdditionalProperties addAdditionalPropertiesItem(String additionalPropertiesItem) {
   if (this.additionalProperties == null) {
      this.additionalProperties = ; // this does not compile
   }
   this.additionalProperties.add(additionalPropertiesItem);
   return this;
}
```
