### ISSUE TITLE
Cannot find symbol for a custom annotation on when using x-field-extra-annotation

### ISSUE THREAD

**Issue by hajjoujti** [OpenAPITools/openapi-generator#15432]
##### Description
I want to add a field annotation to the generated field models via `x-field-extra-annotation: '@CustomAnnotation'`.
Now my annotation is custom and is in myproject `com.project.annotation.CustomAnnotation`

I tried to use schemaMappings:
```xml
<configuration>
  <schemaMappings>
    <schemaMapping>IHubStaticData=com.bdl.ihubapi.annotation.IHubStaticData</schemaMapping>
  </schemaMappings>
</configuration>
```

But I am having the following error after packagin:
```java
cannot find symbol
[ERROR]   symbol:   class CustomAnnotation
[ERROR]   location: class com.project.model.Test
```

##### openapi-generator version
`v6.4.0`

##### OpenAPI declaration file content or url

```yaml
    Test:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
          x-field-extra-annotation: '@CustomAnnotation'
```

##### Command line used for generation
`mvn clean install`

##### Steps to reproduce
Create a custom annotation interface and add it to the yaml filed `x-field-extra-annotation: '@CustomAnnotation'`.
```java
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.FIELD)
public @interface IHubStaticData {
    String id() default "";
}
```
