### ISSUE TITLE
[BUG] [swift] oneOf handling for form-url encoded requestBodies 

### ISSUE THREAD

**Issue by Jonas1893** [OpenAPITools/openapi-generator#15511]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [X] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When specifying a `requestBody` using `application/x-www-form-urlencoded; charset=utf-8` encoding, oneOf does not work as expected. Instead of generating a model for each of the oneOf types as it is the case when using `application/json`, the generated API method just expects all parameters from all the oneOf types together. 
This was a problem even before 6.3.0, but with 6.4.0 and above it got worse as parameters that are only present in some and not in  all of the oneOf types are now being generated non-optional which does not make sense. 

##### openapi-generator version

- broken in 6.4.0 - current
- workaround with nilabel parameters in < 6.3.0

##### OpenAPI declaration file content or url
https://gist.github.com/Jonas1893/baf6076647cc302e4eb7014025977663

##### Generation Details

Used config
```yaml
generatorName: swift5
outputDir: ./
library: alamofire
projectName: AuthClient
generateModelAdditionalProperties: false
additionalProperties:
  responseAs: Combine
  readonlyProperties: true
  nonPublicApi: false
  modelNamePrefix: API
  removeMigrationProjectNameClass: true

```

##### Steps to reproduce

Using the provided spec and config perform the generation. Also try a second generation run with `application/json` content-type for the requestBody and observe the behavior described above

##### Suggest a fix

Content-Type `application/x-www-form-urlencoded; charset=utf-8` should use the same approach of handling oneOfs in generated APIs as `application/json`
