### ISSUE TITLE
[BUG][GO] OpenAPI gen seems to generate incorrect interface for a list of maps/dicts

### ISSUE THREAD

**Issue by vlad-rosu** [OpenAPITools/openapi-generator#15582]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ ] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

```yaml
    Response:
      type: object
      properties:
        size:
          type: integer
          format: int32
        next:
          type: string
        resources:
          type: array
          items:
            type: object
            additionalProperties:
              type: object
```
I have the above yaml spec
generated from the Java code:
```java
public class Response {
  private int size;
  private String next;
  private List<Map> resources = new ArrayList<>();
}
```

The go-client generated based on my full yaml spec has this definition of the `Response` interface:
```go
// Response struct for Response
type Response struct {
	Size *int32 `json:"size,omitempty"`
	Next *string `json:"next,omitempty"`
	Resources []map[string]map[string]interface{} `json:"resources,omitempty"`
}
```

The type that is generated for `Resources` seems incorrect for me;
My Java code is a `List<Map>`, and the equivalent generated go code is: `List<Map<String, Map<String, Object>>`.

Is this a bug? Am I misinterpreting what is happening?

##### openapi-generator version

`6.4.0`

Could anyone please advise if this is a bug or something is defined incorrectly on my side?
