### ISSUE TITLE
[REQ] Add ability to not unalias schemas for OpenAPIGenerator and OpenAPIYamlGenerator

### ISSUE THREAD

**Issue by plamentotev** [OpenAPITools/openapi-generator#15591]
### Is your feature request related to a problem? Please describe.

Currently if you use `OpenAPIGenerator` or `OpenAPIYamlGenerator` the schemas are always unaliased. For example in the following fragment:

```yaml
components:
  schemas:
    Category:
      type: string
      example: dogs
    Pet:
      type: object
      properties:
        name:
          type: string
          example: doggie
        category:
          "$ref": "#/components/schemas/Category"
```

`Category` will be _unaliased_ in `Pet` and the result would be:

```yaml
components:
  schemas:
    Category:
      example: dogs
      type: string
    Pet:
      example:
        name: doggie
        category: dogs
      properties:
        name:
          example: doggie
          type: string
        category:
          example: dogs
          type: string
```

Although `Category` is indeed an alias for `string` and both fragments are equivalent, I would like to keep the reference as it serves as kind of documentation. 

## Describe the solution you'd like

It would be great to have configuration parameter that controls this behaviors. For example both classes may override `Schema unaliasSchema(Schema schema)`:

```java
@Override
public Schema unaliasSchema(Schema schema) {
    return shouldUnaliasSchemas ? super.unaliasSchema(schema) : schema;
}
```

## Describe alternatives you've considered

An alternative is to just subclass `OpenAPIYamlGenerator` but it would be more convenient if we have this functionality in the build-in generators.
