### ISSUE TITLE
[BUG] Multiple parameter examples are not available

### ISSUE THREAD

**Issue by gcatanese** [OpenAPITools/openapi-generator#15645]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

The OpenAPI standard allows specifying [parameter](https://spec.openapis.org/oas/v3.0.3#parameter-object) examples with either (single) `example` or (multiple) `examples`, but during the code generation only the single `example` is provided.

##### openapi-generator version

7.0.0-SNAPSHOT

##### OpenAPI declaration file content or URL

See below an example of a parameter including multiple `examples`
```
      parameters:
        - description: Unique identifier of the user
          name: userId
          in: path
          required: true
          examples:
            get-transaction:
              value: 1000
              summary: An example
            get-transaction-not-found:
              value: 1001
              summary: Another example
          schema:
            type: string
```

##### Steps to reproduce
Define spec with parameter examples (see above) and generate code (any language).
