### ISSUE TITLE
[BUG] example values from DateTime / string properties in C# XML comments wrong

### ISSUE THREAD

**Issue by tualatin** [OpenAPITools/openapi-generator#15652]
##### Description

Create a OpenApi specification, declare a DateTime or string property, set the description and example clause. Let generate the AspNetCore dist, take a look into the created C# files, create a AspCore solution, built it and start the AspCore app. Open the swagger documentation of your API.
All example values are missing, when the property is a type of string, datetime or object.

##### openapi-generator version

openapi-generator 2.6 (6.6.jar)

##### OpenAPI declaration file content or url

```yaml
      createTime:
        description: Timestamp when this entity was created.
        type: "string"
        format: "date-time"
        example: 2017-07-21T17:32:28Z
      calculation:
        description: Calculation value
        type: "string"
        example: 12 * PI
      calculationPostFix:
        description: Calculation PostFix
        type: "string"
        example: 0

```

##### Generation Details

Call the generator tool with -g parameter.

##### Steps to reproduce

Let generate your API specification and take a look into your C# files

```c#
        /// <summary>
        /// Timestamp when this entity was created.
        /// </summary>
        /// <value>Timestamp when this entity was created.</value>
        /// <example>&quot;2017-07-21T17:32:28Z&quot;</example>
        [DataMember(Name="createTime", EmitDefaultValue=false)]
        public DateTime CreateTime { get; set; }

        /// <summary>
        /// Calculation value
        /// </summary>
        /// <value>Calculation value</value>
        /// <example>&quot;12 * PI&quot;</example>
        [DataMember(Name = "calculation", EmitDefaultValue = false)]
        public string Calculation { get; set; }

        /// <summary>
        /// Calculation PostFix
        /// </summary>
        /// <value>Calculation PostFix</value>
        /// <example>&quot;0&quot;</example>
        [DataMember(Name="calculationPostFix", EmitDefaultValue=false)]
        public string CalculationPostFix { get; set; }
```

Add the swashbuckle nuget packages into your C# AspCore solution and build it. Start the application and take a look into the swagger documentation. All example values are missing, when the properties are string, object or DateTime. Number, boolean, enum properties are OK, because there are no \&quot; in the example XML comment.

Remove the \&quot; declaration in the example clause. Rebuild your solution, start the AspCore app and take a look into the swagger documentation. All example values available.

##### Related issues/PRs

https://github.com/OpenAPITools/openapi-generator/issues/14905

##### Suggest a fix

Remove the \&quot; declaration in all example XML comments, the C# file have to look like this

```c#
        /// <summary>
        /// Timestamp when this entity was created.
        /// </summary>
        /// <value>Timestamp when this entity was created.</value>
        /// <example>2017-07-21T17:32:28Z</example>
        [DataMember(Name="createTime", EmitDefaultValue=false)]
        public DateTime CreateTime { get; set; }

        /// <summary>
        /// Calculation value
        /// </summary>
        /// <value>Calculation value</value>
        /// <example>12 * PI</example>
        [DataMember(Name = "calculation", EmitDefaultValue = false)]
        public string Calculation { get; set; }

        /// <summary>
        /// Calculation PostFix
        /// </summary>
        /// <value>Calculation PostFix</value>
        /// <example>0</example>
        [DataMember(Name="calculationPostFix", EmitDefaultValue=false)]
        public string CalculationPostFix { get; set; }
```
