### ISSUE TITLE
[BUG] PHP Client Incosistent Unserialize behavior between object and array

### ISSUE THREAD

**Issue by nadar** [OpenAPITools/openapi-generator#15803]
##### Description

We have created a PHP SDK using the OpenAPI Generator (openapi-generator-cli generate -i https://api.flyo.cloud/nitro/v1/openapi -g php), and we have noticed inconsistent behavior regarding the parsed results. The results for accessing data is sometimes either an object or an array. It is possible that this inconsistency is related to how the OpenAPI description is defined, although we are not entirely sure.

##### openapi-generator version

6.6.0

##### OpenAPI declaration file content or url

```yaml
block:
      title: Block
      type: object
      properties:
        items:
          title: BlockItems
          type: array
          items: {}
          description: Mapping Items
          example:
            - title: Hello
              teaser: Great!
            - title: Hallo
              teaser: Toll!
        content:
          title: BlockContent
          type: object
          description: Text Contents
          example:
            title: Hello World
```

I cut out the relevant part, but here is the full reference: https://api.flyo.cloud/nitro/v1/openapi

##### Generation Details

The screenshot below demonstrates the inconsistency, with the content section sometimes being represented as an array and sometimes as an object:

![image](https://github.com/OpenAPITools/openapi-generator/assets/3417221/dd5bf41b-d559-419e-83f4-9f4b14bf28e1)

As observed in the OpenAPI file, the content section is defined with type: object. Therefore, one would expect to access its values using $block->getContent()->someVariable. However, the actual access method is $block->getContent()['someVariable']. On the other hand, in the items property, which is an array of objects, the array access method works as expected: foreach ($block->getContents() as $item) { $item->someVariable }.

##### Suggested Fix

To ensure consistent behavior, it is recommended to either use objects (stdClass in the PHP world) or arrays consistently throughout the SDK.
