### ISSUE TITLE
[BUG][csharp-netcore] Cannot instantiate request

### ISSUE THREAD

**Issue by kYann** [OpenAPITools/openapi-generator#15848]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [x] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When calling a method, it expect a request object that has an internal constructor
I cannot call it.

```csharp
public partial class PostInvoiceRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PostInvoiceRequest" /> class.
        /// </summary>
        /// <param name="billingInvoicePostInput"></param>
        [JsonConstructor]
        internal PostInvoiceRequest(BillingInvoicePostInput billingInvoicePostInput)
        {
            BillingInvoicePostInput = billingInvoicePostInput;
            OnCreated();
        }
}

public async Task<ApiResponse<BillingInvoice>> PostInvoiceAsync(PostInvoiceRequest? postInvoiceRequest = null, System.Threading.CancellationToken? cancellationToken = null)
{
}
```

##### openapi-generator version

6.6.0

##### OpenAPI declaration file content or url

https://gist.github.com/kYann/2e49f890ef4685853e7d29d738e9e877

##### Generation Details

Config
```yaml
generatorName: csharp-netcore
library: generichost
additionalProperties:
  artifactId: Bump.AdminClient
  packageName: Bump.AdminClient
  targetFramework: net6.0
  useDateTimeOffset: true
  nullableReferenceTypes: true
  packageAuthors: Bump
  packageCompany: Bump
  packageDescription: Admin client to access bump rest api
  packageTitle: "Bump Api Admin Client"
```

##### Steps to reproduce

```bash
java -jar ..\openapi-generator-cli-6.6.0.jar generate -i http://localhost:5127/swagger/admin-v1/swagger.json -c config.yaml
```

##### Suggest a fix

Make *Request with a public constructor. Or directly have a Method that takes the property of the request in parameter.
