### ISSUE TITLE
[BUG] Not adding the correct javax.validation imports with a specific configuration

### ISSUE THREAD

**Issue by CatKinKitKat** [OpenAPITools/openapi-generator#15849]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [X] What's the actual output vs expected output? (If it was the same I wouldn't be here)
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178)) (_Je suis very poor, señorita._ **Maybe one day.**)

##### Description

OpenAPI Java (Spring) generator is not adding the correct _javax.validation_ imports with this specific configuration _(Reactor, Spring, Optional-wrapped, etc check bellow)_. I believe is a bug with this **specific** configuration, because it _usually_ works fine with some _slightly similar_ configurations.

##### openapi-generator version

Spring Java Generator
Version **6.6.0**

##### File

Yaml:
```
...
components:
  parameters:
    PageParameter:
      name: page
      in: query
      description: Page number
      required: false
      schema:
        type: integer
        format: uint32
        minimum: 1
        default: 1
    SizeParameter:
      name: size
      in: query
      description: Page size
      required: false
      schema:
        type: integer
        format: uint32
        minimum: 1
        default: 10
    SortParameter:
      name: sort
      in: query
      description: Sort
      required: false
      schema:
        type: string
        enum: [ id, name, surname, birthDate, phoneNumber, email ]
        default: id
    SortDirectionParameter:
      name: direction
      in: query
      description: Direction
      required: false
      schema:
        type: string
        enum: [ asc, desc ]
        default: asc
```

Pom XML:
```
...
            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>${openapi-generator.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>
                                ${project.basedir}/src/main/resources/static/api.yaml
                            </inputSpec>
                            <generatorName>spring</generatorName>
                            <apiPackage>eu.catkinkitkat.presentation.generated.api</apiPackage>
                            <modelPackage>eu.catkinkitkat.presentation.generated.model</modelPackage>
                            <configOptions>
                                <reactive>true</reactive>
                                <useLombok>true</useLombok>
                                <library>spring-boot</library>
                                <useOptional>true</useOptional>
                                <dateLibrary>java8</dateLibrary>
                                <useJakartaEe>false</useJakartaEe> <!-- use javax.* annotations instead of jakarta.* -->
                                <delegatePattern>true</delegatePattern>
                                <useBeanValidation>true</useBeanValidation>
                                <annotationLibrary>swagger2</annotationLibrary>
                                <documentationProvider>springdoc</documentationProvider>
                                <disallowAdditionalPropertiesIfNotPresent>false
                                </disallowAdditionalPropertiesIfNotPresent>
                            </configOptions>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
...
```

Generated:
```
...
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;
...
    default Mono<ResponseEntity<PersonSearchResponse>> searchPeople(Optional<String> name,
        Optional<String> surname,
        Optional<Integer> age,
        Optional<String> phoneNumber,
        Optional<String> email,
        Optional<String> address,
        Optional<@Min(1) Integer> page,
        Optional<@Min(1) Integer> size,
        Optional<String> sort,
        Optional<String> direction,
        ServerWebExchange exchange) {
        Mono<Void> result = Mono.empty();
        exchange.getResponse().setStatusCode(HttpStatus.NOT_IMPLEMENTED);
        for (MediaType mediaType : exchange.getRequest().getHeaders().getAccept()) {
            if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                String exampleString = "{ \"persons\" : [ { \"phoneNumber\" : \"phoneNumber\", \"address\" : \"address\", \"surname\" : \"surname\", \"name\" : \"name\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"birthDate\" : \"2000-01-23\", \"email\" : \"email\" }, { \"phoneNumber\" : \"phoneNumber\", \"address\" : \"address\", \"surname\" : \"surname\", \"name\" : \"name\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"birthDate\" : \"2000-01-23\", \"email\" : \"email\" } ], \"pagination\" : { \"total\" : 1, \"size\" : 6, \"page\" : 0 } }";
                result = ApiUtil.getExampleResponse(exchange, mediaType, exampleString);
                break;
            }
        }
        return result.then(Mono.empty());

    }
...
```

##### Generation Details

Everything expected generates **EXCEPT** the ``import javax.validation.constraints.Min;`` line, breaking the maven compile goal because of unimported ``@Min`` annotation.

##### Steps to reproduce

Use ``mvn -U -T 1C clean install`` or IntelliJ's GUI IntelliJ's GUI with similar file contents.
