### ISSUE TITLE
[BUG] [java/spring] x-YYY-extra-annotation doc is misleading

### ISSUE THREAD

**Issue by elonderin** [OpenAPITools/openapi-generator#15858]
##### Description

the current java/spring doc reads:

> List of custom annotations to be added to YYYY

So i was thinking: ok, i can write a yaml list if all my annotations that i want to add. eg.

```
      properties:
        foo:
          type: string
          x-field-extra-annotation:
            - "@MyCustomAnnotation1"
            - "@MyCustomAnnotation2"
```
WRONG

First one needs to understand that _annotation_ in the xtension name x-field-extra-annotation has nothing to do with java annotations even though the description suggests that IMO.

Second, there is no "List" here in a syntactical yaml/json sense, rather this extension may be used to add a list of java annotation there, but also a myriad of other things.

What this really does, is:

1. create a json-ish string from the value of `x-field-extra-annotation` (ie drop the quotes, replace : -> = )
2. put that as a text above the field

Hence, a more fitting name to the current behavior would be `x-field-extra-text-above`.

example:
```
        value:
          x-field-extra-annotation:
            foo:
              bar:
                 - 123
                 - ASDASD
```
will do this: 

```
  {foo={bar=[123, ASDASD]}}
  private String value;
```

##### openapi-generator version

6.6.0
