### ISSUE TITLE
[BUG][csharp-netcore] useDateTimeOffset is ignored

### ISSUE THREAD

**Issue by kYann** [OpenAPITools/openapi-generator#15886]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?

##### Description

When generating a client with the option useDateTimeOffset it is generated with `DateTime` instead of `DateTimeOffset`.

##### openapi-generator version

openapi-generator-cli-7.0.0-20230620.092101-123

It's a regression

##### OpenAPI declaration file content or url

https://gist.github.com/kYann/2e49f890ef4685853e7d29d738e9e877

##### Generation Details

`java -jar ..\openapi-generator-cli-7.0.0-20230620.092101-123.jar generate -i http://localhost:5127/swagger/public-v1/swagger.json -c config.yaml`

##### Steps to reproduce

Generate the client and check the `PostInvoiceRequest` model.

```csharp
        [JsonConstructor]
        public PostInvoiceRequest(DateTime date, BillingInvoiceStatus status, BillingInvoiceFromApi? from = default, Guid? groupId = default, string? invoiceNumber = default, List<BillingInvoiceItemApi>? items = default, BillingCreateInvoiceOptions? options = default, BillingInvoiceToApi? to = default)
        {
            Date = date;
            Status = status;
            From = from;
            GroupId = groupId;
            InvoiceNumber = invoiceNumber;
            Items = items;
            Options = options;
            To = to;
            OnCreated();
        }
```

##### Suggest a fix

Use DateTimeOffset when option is set.

**Comment by kYann** [comment]
@devhl-labs forgot to give you the configuration

```yaml
generatorName: csharp-netcore
library: generichost
additionalProperties:
  artifactId: Bump.AdminClient
  packageName: Bump.AdminClient
  targetFramework: net6.0
  useDateTimeOffset: true
  nullableReferenceTypes: true
  packageAuthors: Bump
  packageCompany: Bump
  packageDescription: Admin client to access bump rest api
  packageTitle: "Bump Api Admin Client"
```
