### ISSUE TITLE
[BUG][csharp] Validation throw ArgumentNullException for nullable argument

### ISSUE THREAD

**Issue by kYann** [OpenAPITools/openapi-generator#15965]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?

##### Description

The validation function for the input of an api call will check if a nullable argument is not null.
As the API authorize the argument to be null it should 

##### openapi-generator version

openapi-generator-cli 7.0.0-SNAPSHOT
  commit : fac04cf

##### OpenAPI declaration file content or url

https://gist.github.com/kYann/ce6487359587f255dfc6b8b188ff59e4

Config
```yaml
templateDir: ./
generatorName: csharp
library: generichost
additionalProperties:
  artifactId: Bump.PublicClient
  packageName: Bump.PublicClient
  targetFramework: net6.0
  useDateTimeOffset: true
  nullableReferenceTypes: true
  packageAuthors: Bump
  packageCompany: Bump
  packageDescription: Public client to access bump rest api
  packageTitle: "Bump Api Public Client"
```

##### Generation Details

`java -jar ..\openapi-generator-cli.jar generate -i ..\public-swagger.json -c config.yaml`

##### Steps to reproduce

Generate client

Call GetInvoices without status

```csharp
var result = await publicApiClient.GetInvoicesAsync(from: DateTime.Now.AddDays(-1), to: DateTime.Now.AddDays(1));
```

Exception in ValidateGetInvoices
```csharp
private void ValidateGetInvoices(BillingInvoiceStatus? status, DateTimeOffset? from, DateTimeOffset? to, int? page, int? pageSize)
        {
            if (status == null)
                throw new ArgumentNullException(nameof(status));
            //...
         }
```

##### Suggest a fix

Remove null validation for nullable items
