### ISSUE TITLE
[BUG] Header default value set to "null"

### ISSUE THREAD

**Issue by gcatanese** [OpenAPITools/openapi-generator#15989]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When not specified the default value of a string header is set to `"null"`

##### openapi-generator version

7.0.0-SNAPSHOT

##### OpenAPI declaration file content or URL

Example of header without default value
```yaml
      parameters:
        - description: Custom HTTP header
          name: Custom-Header
          in: header
          schema:
            type: string

```

during the code generation the default value of the property is retrieved from the Schema default value. When the default is not defined the CodeGen returns a string with `"null"`
