### ISSUE TITLE
[BUG] [SPRING-CLOUD] Multiple Security breaks the generated code 

### ISSUE THREAD

**Issue by MelleD** [OpenAPITools/openapi-generator#16023]
If you use multiple security schemes, the spring cloud generator code generator breaks and produces non-compilable code.

```
  securitySchemes:
    oauth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: '/auth'
          tokenUrl: '/token'
          scopes: { }
        clientCredentials:
          tokenUrl: '/token'
          scopes: { }
    basicAuth:
      type: http
      scheme: basic
```

I was able to fix that so far and I would still include it in the PR.
https://github.com/OpenAPITools/openapi-generator/pull/16011

However, I have a problem for the client side when the client has no security assigned.
How to find out if a security scheme is assigned to the resource.

Example:
```
paths:
  /foo:
    ...
      security:
        - macma: [ ]

  /bar:
    get:
```
    
Bar has no security and foo has secruity. How can I get this information into the mustache?

This is the current template. 

`@FeignClient(name="${{openbrace}}{{classVarName}}.name:{{classVarName}}{{closebrace}}", {{#useFeignClientUrl}}url="${{openbrace}}{{classVarName}}.url:{{basePath}}{{closebrace}}", {{/useFeignClientUrl}}configuration = ClientConfiguration.class)`

In the end you see `configuration = ClientConfiguration.class`. 
This should only be set if security is assigned.

@borsch, @welshm and @wing328 do you have a hint for me where I can get this information?
