### ISSUE TITLE
[BUG] importMappings not working on query params [Spring]

### ISSUE THREAD

**Issue by malfoj89** [OpenAPITools/openapi-generator#16060]
Generating with settings:
```
    typeMappings = [
            OffsetDateTime: 'Instant'
    ]
    importMappings = [
            'java.time.OffsetDateTime': 'java.time.Instant'
    ]

```

on api declaration level for query parameter

```
        - in: query
          name: dateFrom
          required: false
          schema:
            type: string
            format: date-time
            example: '2017-07-21T17:32:28Z'
```

changes the field type from OffsetDateTime to Instant - but do not change import type (so field is uknown) - works properly on requestyBody model.
