### ISSUE TITLE
[BUG] Enums are treated differently with skipFormModels set to false

### ISSUE THREAD

**Issue by devhl-labs** [OpenAPITools/openapi-generator#16165]
I am attempting to add these settings to this sample

\bin\configs\csharp-generichost-latest.yaml

```yaml
globalProperties:
  skipFormModel: false
inlineSchemaOptions:
  RESOLVE_INLINE_ENUMS: true
```

With the following breakpoint set at line 798 of the DefaultCodegen you can see isEnum is false. Without the above change, it is true. Something is handled differently with these two settings in place.

`var.baseName.equals("enum_number")`

![image](https://github.com/OpenAPITools/openapi-generator/assets/29644329/9a2fb866-e1dd-4969-adf5-1263b4f6667a)
