### ISSUE TITLE
[BUG] Description

### ISSUE THREAD

**Issue by icarusfire** [OpenAPITools/openapi-generator#16245]
Openapi-generator-maven-plugin sees the property 'type' object and tries create a put Item method for it, which I dont need, also it cant create properly, and it fails to compile.

After upgrading version 6.6.0(it was 5.0. before) I see some of the created java classes (by openapi-generator) has errors, I see methods that should not be there (I compare with old version classes and this 'putTypeItem' doesn't exist in old versions). if they must be there, then they should be created properly.

Note the error in 'typeItem' in method parameters below, there is no type! And this method do not exist in jaxb version. I have compilation errors:

  ```
public GetResponse putTypeItem(String key,  **typeItem**) {
    if (this.type == null) {
      this.type = new HashMap<>();
    }
    this.type.put(key, typeItem);
    return this;
  }
```
This is my plugin config:

 ```
<plugin>
        <groupId>org.openapitools</groupId>
        <artifactId>openapi-generator-maven-plugin</artifactId>
        <version>6.6.0</version>
        <executions>
          <execution>
            <id>generate</id>
            <goals>
              <goal>generate</goal>
            </goals>
            <configuration>
              <inputSpec>${basedir}/../management-swagger.yaml</inputSpec>
              <generateApis>false</generateApis>
              <generateApiTests>false</generateApiTests>
              <generateApiDocumentation>false</generateApiDocumentation>
              <generateModelDocumentation>false</generateModelDocumentation>
              <generateModelTests>false</generateModelTests>
              <generateSupportingFiles>false</generateSupportingFiles>
              <generatorName>spring</generatorName>
              <configOptions>
                <useJakartaEe>true</useJakartaEe>
                <dateLibrary>java8</dateLibrary>
              </configOptions>
              <modelPackage>com.client.model</modelPackage>
              <typeMappings>
                <typeMapping>Double=java.math.BigDecimal</typeMapping>
              </typeMappings>
            </configuration>
          </execution>
        </executions>
      </plugin>
```
and this is how my yaml looks like:

```
GetResponse:
  properties:
    id:
      type: string
      example: 
      description: 
    type:
      type: object
      description: 
      properties:
        code:
          type: string
          description: '
        description:
          type: string
          description:
```
