### ISSUE TITLE
[BUG] Migrating from openapi-generator-maven-plugin 5.0.0 to 5.0.1+/6.x+ doesnt apply @DecimalMin and @DecimalMax anymore to string field

### ISSUE THREAD

**Issue by dhananjay12** [OpenAPITools/openapi-generator#16312]
##### Description

We had a schema with type string that contained decimal value. 
```
components:
  schemas:
    Item:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: The unique identifier for the item
        name:
          type: string
          description: The name of the item
        price:
          type: string
          minimum: -999999999999999999.99999
          maximum: 999999999999999999.99999
          description: Price
```
With 4.3.1 or 5.0.0 it use to @DecimalMax, @DecimalMin anootation based on `maximum/minimum`
![image](https://github.com/OpenAPITools/openapi-generator/assets/950278/b18aeac5-77d3-4e8a-906b-ade4d6bcc8ad)

Starting from 5.0.1, it didnt added those

<img width="820" alt="image" src="https://github.com/OpenAPITools/openapi-generator/assets/950278/9df69354-d65b-4982-b298-f896283cf552">

##### openapi-generator version

5.0.1 version (used to work in 5.0.0 and 4.3.1)
Also reproducible with the lates 6.6.0 (with spring boot 3)

##### OpenAPI declaration file content or url

Minimum example here -https://github.com/dhananjay12/learn-open-api/blob/string-decimal/sample-service/src/main/openapi/test-service-api-v1.yaml

##### Generation Details

https://github.com/dhananjay12/learn-open-api/blob/string-decimal/sample-service/pom.xml#L110

##### Steps to reproduce

In the pom.xml , with `openapi-generator-maven-plugin` version `5.0.1` generated the code to see the reproduce the issue. With `5.0.0` or `4.3.1` its fine.

##### Suggest a fix

Any workaround to achieve the same? (Add @DecimalMin and @DecimalMax annotation to string type)

**Comment by wing328** [comment]
please try 7.0.0-beta release instead.

5.x release was a while ago

**Comment by dhananjay12** [comment]
7.0.0-beta version also results the same. 

5.0.1 is just the version where we started seeing the issue. Checking the release notes, not sure what introduce this change. We are actually at 6.6.0.

**Comment by wing328** [comment]
do you mind performing a git bisect to identify the commit causing the issue?

**Comment by dhananjay12** [comment]
My analysis leads to this merge - https://github.com/OpenAPITools/openapi-generator/commit/2331432cc0f062ceff44c3d09e1a16c31abf6f57

Checking the [commits](https://github.com/OpenAPITools/openapi-generator/commits/2331432cc0f062ceff44c3d09e1a16c31abf6f57),  

**Not Working** - Adds hasValidation to all java core Schema classes (#8474) - 2331432cc0f062ceff44c3d09e1a16c31abf6f57

**Working** - [PowerShell] minor fix to API doc - 3d23b99242ad80f440d4ca3eb9f90103a4ec208b

Checked by building the project locally on these commit and testing with the minimal project provided earlier.

**Comment by wing328** [comment]
thanks for identifying the issue. let me try to come up with a fix later.

**Comment by wing328** [comment]
to fix the issue, use `number` instead of string,
```
        price:
          type: number
          minimum: -999999999999999999.99999
          maximum: 999999999999999999.99999
          description: Price
```

**Comment by dhananjay12** [comment]
Yes, it does add the annotations
<img width="515" alt="image" src="https://github.com/OpenAPITools/openapi-generator/assets/950278/d85fb272-c62c-4c09-9165-de05e1b0ac3e">

But this change the datatype from string to BigDecimal which will be a breaking change wrt to APIs forcing us to make a major release.

Can you suggest any other workaround? or a way to override the template on ourside?

**Comment by martin-mfg** [comment]
You can specify the input like this:
```yaml
price:
  type: string
  format: number
  minimum: -999999999999999999.99999
  maximum: 999999999999999999.99999
  description: Price
```
This way price will still be a string for users of your API. In the generated code, it will be represented as `BigDecimal` however and have the appropriate `@DecimalMin` and `@DecimalMax` annotations.

If you also want to change the internal representation in the generated code to String, on top of the above change you can add a type mapping to your pom.xml like this:
```xml
<generatorName>spring</generatorName>
<typeMappings>
	<typeMapping>BigDecimal=String</typeMapping>
</typeMappings>
<!-- ... -->
```

This will generate
```java
  @Valid @DecimalMin("-1.0E+18") @DecimalMax("1.0E+18") 
  @Schema(name = "price", description = "Price", requiredMode = Schema.RequiredMode.NOT_REQUIRED)
  @JsonProperty("price")
  public String getPrice() {
```
