### ISSUE TITLE
[BUG][Javascript client] OneOf including array of string conditions always fails

### ISSUE THREAD

**Issue by jmlord** [OpenAPITools/openapi-generator#16379]
##### Description

I have a few oneOf declaration. Array of strings never go through, so I have to bypass or edit the generated code that creates the objects. Here is a simplified example:

``` yaml
components:
  schemas:
    book:
      type: object
      properties:
        author:
          oneOf:
          - type: string
            example: John Doe
          - type: array
            example: ["Jane Doe", "John Doe"]
            items:
              type: string
```

The above generates the following code inside the `BookAuthor.js` class. The condition under "validate array of strings" will never succeed with an array of strings! 

``` Javascript
        try {
            // validate array data type
            if (!Array.isArray(instance)) {
                throw new Error("Invalid data type. Expecting array. Input: " + instance);
            }
            // validate array of string
            for (const item of instance) {
                if (!(typeof item === 'number' && item % 1 === 0)) {
                    throw new Error("Invalid array items. Must be string. Input: " + instance);
                }
            }
            this.actualInstance = instance;
            match++;
        } catch(err) {
            // json data failed to deserialize into [String]
            errorMessages.push("Failed to construct [String]: " + err)
        }
```

If the condition would read as `if (!(typeof item === "string")) {`, it would solve the issue.

##### openapi-generator version

7.0.0-SNAPSHOT

##### Generation Details

```sh
docker pull openapitools/openapi-generator-cli:latest
docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli generate \
   -i /local/openapi.yaml \
   -g javascript \
   -o /local/
```

##### Steps to reproduce

1. Create OpenAPI file including oneOf, as per example above.
2. Run the genreation shell script, see above.
3. Test or audit genrated conde in the class that resolves the oneOf definition.

##### Related issues/PRs

#10514
#13539

##### Suggest a fix

If the condition would read as `if (!(typeof item === "string")) {`, it would solve the issue.
