### ISSUE TITLE
[BUG] [Dart] MultipartRequest array of int not generating correctly

### ISSUE THREAD

**Issue by MichalNemec** [OpenAPITools/openapi-generator#16415]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ ] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

I am doing multipartRequest to dotnet backend.
The error i get is: 
`ApiException 400: {"errors":{"Interests":["The value '[6, 5]' is not valid."]}}`

this is whats generated:
```
/// Parameters:
  ///
  /// * [String] name (required):
  ///
  /// * [String] introduction (required):
  ///
  /// * [String] description (required):
  ///
  /// * [List<int>] interests (required):
  ///
  /// * [MultipartFile] file:
  Future<Response> apiPageCreatePostWithHttpInfo(String name, String introduction, String description, List<int> interests, { MultipartFile? file, }) async {
    // ignore: prefer_const_declarations
    final path = r'/api/page/create';

    // ignore: prefer_final_locals
    Object? postBody;

    final queryParams = <QueryParam>[];
    final headerParams = <String, String>{};
    final formParams = <String, String>{};

    const contentTypes = <String>['multipart/form-data'];

    bool hasFields = false;
    final mp = MultipartRequest('POST', Uri.parse(path));
    if (name != null) {
      hasFields = true;
      mp.fields[r'Name'] = parameterToString(name);
    }
    if (introduction != null) {
      hasFields = true;
      mp.fields[r'Introduction'] = parameterToString(introduction);
    }
    if (description != null) {
      hasFields = true;
      mp.fields[r'Description'] = parameterToString(description);
    }
    if (interests != null) {
      hasFields = true;
      mp.fields[r'Interests'] = parameterToString(interests); //HERE IS THE PROBLEM
    }
    if (file != null) {
      hasFields = true;
      mp.fields[r'File'] = file.field;
      mp.files.add(file);
    }
    if (hasFields) {
      postBody = mp;
    }

    return apiClient.invokeAPI(
      path,
      'POST',
      queryParams,
      postBody,
      headerParams,
      formParams,
      contentTypes.isEmpty ? null : contentTypes.first,
    );
  }
```

##### openapi-generator version

6.6.0

##### OpenAPI declaration file content or url
```json
"/api/page/create": {
      "post": {
        "tags": ["Page"],
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "required": [
                  "Description",
                  "Interests",
                  "Introduction",
                  "Name"
                ],
                "type": "object",
                "properties": {
                  "Name": {
                    "type": "string"
                  },
                  "Introduction": {
                    "type": "string"
                  },
                  "Description": {
                    "type": "string"
                  },
                  "Interests": {
                    "type": "array",
                    "items": {
                      "type": "integer",
                      "format": "int32"
                    }
                  },
                  "File": {
                    "type": "string",
                    "format": "binary"
                  }
                }
              },
              "encoding": {
                "Name": {
                  "style": "form"
                },
                "Introduction": {
                  "style": "form"
                },
                "Description": {
                  "style": "form"
                },
                "Interests": {
                  "style": "form"
                },
                "File": {
                  "style": "form"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/PageData"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        },
      }
    },
```

##### Generation Details

`openapi-generator-cli generate -g dart -i swagger.json -o ./lib/api/rest --additional-properties=useEnumExtensions=true,ensureUniqueParams=false`

##### Steps to reproduce

1) build
2) try to call it

##### Suggest a fix
this could probably work?
```
if (interests != null) {
  hasFields = true;
  final interestsString = interests.map((e) => e.toString()).join(',');
  mp.fields[r'Interests'] = parameterToString(interestsString);
}
```

**Comment by MichalNemec** [comment]
@yissachar @joernahrens
could you please take a look at this?
i stumbled upon this again with array of files.

**Comment by DavidTeju** [comment]
This became an issue for me with array of files. 
My specs looked like
```yaml
properties:
  caption:
    type: string
  media-files:
    description: The list of image/video binary data to upload as part of the new post. May be empty
    type: array
    maxItems: 10
    items:
      type: string
      format: binary
```
That was generating this code:
```dart
  Future<Response> postsUsernameNewPostWithHttpInfo(String username, String caption, List<MultipartFile> mediaFiles,) async {
...
    if (mediaFiles != null) {
      hasFields = true;
      mp.fields[r'media-files'] = mediaFiles.field; // The getter 'field' isn't defined for the type 'List<MultipartFile>'
      mp.files.add(mediaFiles); // The argument type 'List<MultipartFile>' can't be assigned to the parameter type 'MultipartFile'.
    }
...
```
I had to change it to have it support it:
```yaml
required:
  - caption
  - num-media-files
properties:
  caption:
    type: string
  num-media-files:
    type: integer
    minimum: 0
    maximum: 10
  # Why field names and not just an array of media files?
  # Because the dart openapi generator doesn't recognize arrays of files properly
  0:
    description: The first image/video binary data to upload as part of the new post. Only accessed if num-media-files >=1.
    type: string
    format: binary
  1:
... // copy-paste for 1 through 9
```
