### ISSUE TITLE
[BUG] For `anyOf` in open api declaration file, Kotlin generator created data class with empty parameter

### ISSUE THREAD

**Issue by kamal-github** [OpenAPITools/openapi-generator#16422]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ ] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

In case of `anyOf` in open api declaration file. The generated code is containing data class with empty parameter for **Kotlin** generator.

```
import ccs.model.AccountIdByFacilityConfiguration
import ccs.model.AccountIdByServiceConfiguration

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 */
@Serializable

data class CarrierContractBaseAccountIdConfigurationAccountIdConfigurations (
 // Must have at least parameter for primary constructor.
)
```

##### openapi-generator version

7.0.0

##### OpenAPI declaration file content or url

```
account_id_configurations:
  oneOf:
    - type: array
      description: Account Id configurations for delivery.
      items:
        $ref: '#/components/schemas/AccountIdByServiceConfiguration'
    - type: array
      description: Account Id configurations for delivery.
      items:
        $ref: '#/components/schemas/AccountIdByFacilityConfiguration'

```

##### Generation Details

`./gradlew assemble`

**Comment by wing328** [comment]
I don't think Kotlin supports anyOf yet. Java client generator has better support for anyOf and you can give it a try to see if the anyOf implementation looks to you.

If it does, would you like to contribute a PR to implement anyOf support in the Kotlin client generator?

**Comment by kamal-github** [comment]
@wing328 @jimschubert Is there any chance or plan that Kotlin generators(esp. with jvm-ktor librabrt) also supports this features in near future?

**Comment by wing328** [comment]
Would you or your company like to sponsor the enhancement?

**Comment by david-kubecka** [comment]
I've run into a similar issue. In my case the input spec is 
```
    BadRequestError_errors:
      type: object
      properties:
        parameters:
          type: object
          additionalProperties:
            oneOf:
            - type: string
              description: The actual value of the parameter.
            - type: array
              description: The array with the collection of parameter values.
              items:
                type: string
```
and the generated kotlin classes are
```
data class BadRequestErrorErrors (
    @field:JsonProperty("parameters")
    val parameters: kotlin.collections.Map<kotlin.String, BadRequestErrorErrorsParametersValue>? = null
)

data class BadRequestErrorErrorsParametersValue ()
```

I've also tried to generate the java classes but they are basically the same, except of course there's no `data` modifier. So while the generated Java code compiles I wouldn't claim that it's correct because it completely ignores the `parameters` data.
