### ISSUE TITLE
[BUG] ON/OFF Enum values generated as boolean for scharp

### ISSUE THREAD

**Issue by RomanSoloweow** [OpenAPITools/openapi-generator#16444]
I have 3.0.1 Open api Spec with enum which constains ON/OFF values

``` YAML
    PowerState:
      type: string
      enum:
      - ON
      - OFF
```

It's generated as True/False for scharp rest client
