### ISSUE TITLE
Generator for typescript-axios generates primitive types (string, number, etc) as any

### ISSUE THREAD

**Issue by calebpitan** [OpenAPITools/openapi-generator#16442]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

The types generated by the generator, generates `string`, `int`, and other types that qualify as primitives in the target language (typescript/axios) as `any` rather than their corresponsding types. Enums are also generated as empty interfaces

##### openapi-generator version

6.6.0, 7.0.0

##### OpenAPI declaration file content or url

https://gist.github.com/calebpitan/9f988e14b0b567bc54ee6043d1f1dfe2

##### Generation Details

**Script**

```bash
#!/usr/bin/env bash

openapi-generator-cli generate --skip-validate-spec\
  -i http://localhost:3780/openapi.json\
  -g typescript-axios\
  -o client\
  -p useSingleRequestParameter=true,supportsES6=true,ensureUniqueParams=true\
  -c ./openapi-gen.config.yml\
  -t ./client/templates
```

**Config** (`openapi-gen.config.yml`)

```yaml
additionalProperties:
  ensureUniqueParams: true
  supportsES6: true
  useSingleRequestParameter: true
  enumPropertyNaming: UPPERCASE
  stringEnums: true
  withoutPrefixEnums: false
globalProperties:
  apiDocs: true
  modelDocs: true
```

##### Steps to reproduce

- Create the config file with the contents above in the cwd as the script
- Run the script provided above on the schema uploaded to the GH Gist linked above
- Open the `client` folder where the artifacts are generated and check the `api.ts` file for type defs

##### Related issues/PRs

None

##### Suggest a fix

None
