### ISSUE TITLE
[BUG][Typescript] Unique array of enum values is handled incorrectly

### ISSUE THREAD

**Issue by t3hk0d3** [OpenAPITools/openapi-generator#16458]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [X] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Unique Array of Enum properties are not generated properly. Instead of `Set<Enum>` they are exposed just as `Enum`:

```typescript
export class TestRequest {
   'testProperty'?: TestRequestTestPropertyEnum
}
```

Expected behaviour:
```typescript
export class TestRequest {
   'testProperty'?: Set<TestRequestTestPropertyEnum>
}
```

##### openapi-generator version

7.0.0

##### OpenAPI declaration file content or url

```yaml
definitions:
  TestRequest:
    type: object
    properties:
      test_property:
        type: array
        uniqueItems: true
        items:
          type: string
          enum:
            - foo
            - bar
            - baz
            - dar

```

##### Steps to reproduce

1. Generate any typescript client with following set of enums property
3. Expected generated property type is `Set<TestRequestTestPropertyEnum>`, but currently it is `TestRequestTestPropertyEnum` instead

##### Related issues/PRs

Kinda related issue #14892 (with dead fix PR #15272)
