### ISSUE TITLE
[BUG][Rust] Nullable array generates invalid constructor syntax

### ISSUE THREAD

**Issue by casimcdaniels** [OpenAPITools/openapi-generator#16472]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Nullable arrays result in the generation of invalid Rust struct field value syntax. The type of a nullable array is generated as `Option<Option<Vec<String>>>`, so I suspect there may be some tokenization issue going on.

```rust
impl Object {
    pub fn new() -> Object {
        Object {
            bad: None: None, // <---- this is not valid Rust syntax (should be `bad: None,`)
            good: None,
        }
    }
}
```

##### openapi-generator version
```
openapi-generator-cli 7.0.0
commit : c37fa8a
```

##### OpenAPI declaration file content or url

```yaml
components:
  schemas:
    Object:
      type: object
      properties:
        bad:
          type: array
          nullable: true
          items:
            type: string
        good:
          type: string
          nullable: true
```
##### Steps to reproduce

```openapi-generator generate -i test.yaml -g rust```

##### Suggested Fix
The issue appears to be in the mustache template for modules [here](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/rust/model.mustache#L85). This line allows for multiple `: None` entries when field is not required and `isArray` and `isNullable` are true. Instead, this line (and others like it) should be updated to only allow for one `: None` to be inserted into the line. Alternatively, a template function could be introduced to determine whether to render `Option` value or not based on schema type, so the line can be less error-prone.
