### ISSUE TITLE
[REQ] Generate  @HeaderParam("Authorization") for OAuth2.0 authentication securitySchemes.

### ISSUE THREAD

**Issue by hkawa608** [OpenAPITools/openapi-generator#16583]
### Is your feature request related to a problem? Please describe.

Problem:
When we write the following open API definition and generate code for Java, `@HeaderParam("Authorization")` is not included in the arguments of the API.
```
components:
  securitySchemes:
    oAuthSample:    # <---- arbitrary name
      type: oauth2
      description: This API uses OAuth 2 with the implicit grant flow. [More info](https://api.example.com/docs/auth)
      flows:
		authorizationCode:
		          authorizationUrl: https://slack.com/oauth/authorize
		          tokenUrl: https://slack.com/api/oauth.access
		          scopes:
		            read_pets: read your pets
            	   write_pets: modify pets in your account

paths:
  /pets:
    patch:
      summary: Add a new pet
      security: 
        - oAuthSample: 
          - write_pets
          - read_pets
```

## Describe the solution you'd like

Add `@HeaderParam("Authorization")` to the arguments of the API method generated by openapi-codegen.

## Describe alternatives you've considered

Define `Authorization` as header param like below.

paths:
  /pets:
    patch:
	  summary: Add a new pet
      security: 
        - oAuthSample: 
          - write_pets
          - read_pets
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
          required: true

## Additional context

N/A
