### ISSUE TITLE
[BUG] [JAVA][Client][RestTemplate] '+' in query parameters is not properly URL-encoded

### ISSUE THREAD

**Issue by blaghed** [OpenAPITools/openapi-generator#16733]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ ] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

This is a re-occurrence of the below issue, where `date-time` field is not properly encoded on the `+` character.
https://github.com/OpenAPITools/openapi-generator/issues/644

In my humble opinion, this is actually an issue with Spring Framework, so I opened a ticket there, but it doesn't seem to be accepted as an issue on that side, so I can only think of fixing it here instead.
https://github.com/spring-projects/spring-framework/issues/31363

##### openapi-generator version

I've managed to reproduce it with 6.x and 7.x.
This is technically a regression, and I believe it started to happen again once Spring Framework 5.x was adopted here, since that is where they made their change to the processing of `+` character in particular.

##### OpenAPI declaration file content or url

```yaml
  /pets:
    get:
      summary: List all pets
      operationId: listPets
      tags:
        - pets
      parameters:
        - name: soldAfter
          in: query
          description: If specified, only pets sold after the given date and time will be returned.
          required: false
          schema:
            type: string
            format: date-time
```
(copied over from original ticket)

##### Related issues/PRs

- https://github.com/OpenAPITools/openapi-generator/issues/644
- https://github.com/spring-projects/spring-framework/issues/31363

##### Suggest a fix

https://github.com/OpenAPITools/openapi-generator/pull/16732
