### ISSUE TITLE
[BUG] [typescript-axios] Handling of explode query causes TS error and breaks enums

### ISSUE THREAD

**Issue by ckoegel** [OpenAPITools/openapi-generator#16896]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

With the implementation of #16435, non-primitive types query parameters are exploded via [this line](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/typescript-axios/apiInner.mustache#L136). The usage of `param` as the index causes the TypeScript Error: `Element implicitly has an 'any' type because expression of type 'string' can't be used to index type... ts(7053)`. This causes SDKs generated with this line to have build errors.

This implementation also breaks enum query parameters, since they are recognized as non-primitive. Enums exploded this way cause the TypeScript Error: `Element implicitly has an 'any' type because index expression is not of type 'number'.ts(7015)` and  show as `?0=R&1=E&2=C&3=E&4=I&5=V&6=E&7=D`, causing HTTP errors when the request is sent. The logic in the mustache template should be updated to exclude enum query parameters from this object explosion, and the object explosion should be updated to remove the index error.

##### openapi-generator version

This is on the [OpenAPITools:master](https://github.com/OpenAPITools/openapi-generator/tree/master) branch and is yet to be released.

##### OpenAPI declaration file content or url
Spec Snippets:

`components/parameters`:
```yaml
messageStatus:
    in: query
    name: messageStatus
    required: false
    description: >-
      The status of the message. One of RECEIVED QUEUED SENDING SENT FAILED
      DELIVERED ACCEPTED UNDELIVERED.
    schema:
      $ref: '#/components/schemas/messageStatusEnum'
messageDirection:
    in: query
    name: messageDirection
    required: false
    description: The direction of the message.
    explode: true
    schema:
      $ref: '#/components/schemas/listMessageDirection'
```

`components/schemas`:
```yaml
messageStatusEnum:
    type: string
    description: >-
      The status of the message. One of RECEIVED QUEUED SENDING SENT FAILED
      DELIVERED ACCEPTED UNDELIVERED.
    enum:
      - RECEIVED
      - QUEUED
      - SENDING
      - SENT
      - FAILED
      - DELIVERED
      - ACCEPTED
      - UNDELIVERED
    example: RECEIVED
listMessageDirection:
    type: object
    description: The direction of the message.
    properties:
      propA:
        type: string
      propB:
        type: string
```

`paths`:
```yaml
/users/{accountId}/messages:
    get:
      summary: List Messages
      description: Returns a list of messages based on query parameters.
      operationId: listMessages
      tags:
        - Messages
      parameters:
        - $ref: '#/components/parameters/messageStatus'
        - $ref: '#/components/parameters/messageDirection'
```

The above snippets result in:

```ts
if (messageStatus !== undefined) {
    for (let param of Object.keys(messageStatus)) {
        localVarQueryParameter[param] = messageStatus?.[param];
    }
}

if (messageDirection !== undefined) {
    for (let param of Object.keys(messageDirection)) {
        localVarQueryParameter[param] = messageDirection?.[param];
    }
}
```
##### Generation Details

This was generated using the master branch of the project and the `typescript-axios` generator with the following  config:

```yaml
withSeparateModelsAndApi: true
modelPackage: models
apiPackage: api
```

##### Steps to reproduce

Generate an SDK using master and a spec containing exploded object query parameters as well as enum query parameters. 

##### Related issues/PRs

#15633, #16435

##### Suggest a fix

I'll be opening a PR shortly to update the mustache logic and fix the index error.
