### ISSUE TITLE
Support for enum descriptions (x-enum-descriptions)

### ISSUE THREAD

**Issue by jmini** [OpenAPITools/openapi-generator#1693]
With https://github.com/OpenAPITools/openapi-generator/issues/893#issuecomment-416617460 we have introduced support for the `x-enum-varnames` extension.

In a similar way `x-enum-descriptions` should be supported:

```yaml
  weather:
    type: object
    properties:
      type:
        type: integer
        format: int32
        enum:
          - 1
          - 2
          - 3
        x-enum-descriptions:
          - 'Blue sky'
          - 'Slightly overcast'
          - 'Take an umbrella with you'
        x-enum-varnames:
          - Sunny
          - Cloudy
          - Rainy
```

The java generator could add some Javadoc on top of the enum value.
