### ISSUE TITLE
Question: How to add accept or contentType header as method parameter in generated webclient method?

### ISSUE THREAD

**Issue by metalpalo** [OpenAPITools/openapi-generator#17012]
Hi

We have defined our OAS(openapi.yml)  with one GET operation where response can different contents for status 200 like this:
```
    DummyResponse:
      description: Dummy response
      content:
        "application/json":
          schema:
            $ref: "#/components/schemas/DummyObject"
        "application/json;version=2":
          schema:
            $ref: "#/components/schemas/DummyObjectV2"
        "application/json;version=3":
          schema:
            $ref: "#/components/schemas/DummyObjectV3"
``` 

When springboot application starts and swagger page is opened we are able to choose concrete value from combobox like this:
![image](https://github.com/OpenAPITools/openapi-generator/assets/34547964/453a77e3-2760-4336-9996-205921eb194e)

Now we want to generate apiclient via openapi-generator-maven-plugin(4.3.1) with following config:
```
<interfaceOnly>false</interfaceOnly>
<useOptional>true</useOptional>
<skipDefaultInterface>true</skipDefaultInterface>
<dateLibrary>java8</dateLibrary>
<java8>true</java8>
<library>webclient</library>
```

with result that method will contains accept header as parameter: 

Object getDummy(List<String> accept) or Object getDummy(String accept)

Of course we can define accept header in yaml file and put it as parameter but then we have duplicated field in rendered swagger
```
components:
  parameters:
    Accept:
      name: accept
      in: header
      required: false
      schema:
        type: array
        items:
          type: string
        default: ["application/json"]
``` 

Can somebody help me how to call our generated method via webclient with full control which accept header to be passed?

thanks
brpalo
