### ISSUE TITLE
[core] support for 'x-enum-varnames' for enums in arrays

### ISSUE THREAD

**Issue by jmini** [OpenAPITools/openapi-generator#1701]
##### Description

While I was working on #1693 I have discovered an other case that is not working with `x-enum-varnames`: when the enum is defined in a list.

##### openapi-generator version

4.0.0-SNAPSHOT

##### OpenAPI declaration file content or url

```yaml
    SomeObject:
      type: object
      properties:
        someProperty:
          type: array
          items:
            type: integer
            format: int64
            enum:
              - 20
              - 30
              - 40
            x-enum-varnames:
              - TWENTY
              - THIRTY
              - FORTY
```
