### ISSUE TITLE
[Swift4] enum cases are disappeared

### ISSUE THREAD

**Issue by d-date** [OpenAPITools/openapi-generator#1702]
##### Description

All of enum cases are disappeared.

##### openapi-generator version

4.0.0 (master)

##### OpenAPI declaration file content or url

```yaml
Order:
    type: object
    properties:
      id:
        type: integer
        format: int64
      petId:
        type: integer
        format: int64
      quantity:
        type: integer
        format: int32
      shipDate:
        type: string
        format: date-time
      status:
        type: string
        description: Order Status
        enum:
          - placed
          - approved
          - delivered
      complete:
        type: boolean
        default: false
    xml:
      name: Order
```

##### Command line used for generation

./bin/swift4-all.sh

##### Steps to reproduce

<img width="291" alt="screen shot 2018-12-18 at 19 04 46" src="https://user-images.githubusercontent.com/20222809/50146869-18a32200-02f8-11e9-98e1-4e799671b009.png">
