### ISSUE TITLE
[REQ] [Java][Spring] Bean validation for primitive type for container

### ISSUE THREAD

**Issue by MelleD** [OpenAPITools/openapi-generator#17150]
Currently no bean validation is set for primitive data types in a container. “Only” the bean validation is set for the container.

Example:

```
    Foo:
      type: object
      properties:
        bars:
          type: array
          items:
            type: string
            minLength: 1
            maxLength: 10
          maxItems: 10
```
Generator currently
```
  @Size(max = 10) 
  @JsonProperty("labels")
  public Set<String> getBars() {
    return bars;
  }
```

Expected:

```
  @Size(max = 10) 
  @JsonProperty("labels")
  public Set<@Size(min=1, max = 10) String>getBars() {
    return bars;
  }
```

I saw here the beanvalidation. But i have no idea how trigger this inner items for the bean validation

https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/JavaSpring/beanValidation.mustache

@borsch @welshm could give me a hint how i can fix this inner item thing then i can prepare a PR.

Thanks
