### ISSUE TITLE
[REQ] OpenAPI 3.1.0 Add support for Schema types

### ISSUE THREAD

**Issue by gcatanese** [OpenAPITools/openapi-generator#17187]
When working with OAS 3.1 version the `Schema` object no longer populates `type`, but instead provides `types` to support multiple values, in line with JSON Schema.  
The OpenAPI code generator should be able to support the multiple values, and always populate the single `type` for backward compatibility.

Given the following OpenAPI v3.1 file
```
      properties:
        code:
          type: integer
          format: int32
```
schema.type should be `integer` instead of `oas_any_type_not_mapped`.
