### ISSUE TITLE
[REQ] Add an enum for api key names

### ISSUE THREAD

**Issue by devhl-labs** [OpenAPITools/openapi-generator#17204]
Please consider adding an enum for api key baseName properties. For example, the code generated for https://raw.githubusercontent.com/plaid/plaid-openapi/master/2020-09-14.yml would container an enum of PLAID-CLIENT-ID, PLAID-SECRET, and Plaid-Version.  This would enable users to register their token with the generated code and associate it to the appropriate header without using a string.

```yaml
components:
  securitySchemes:
    clientId:
      type: apiKey
      in: header
      name: PLAID-CLIENT-ID
    secret:
      type: apiKey
      in: header
      name: PLAID-SECRET
    plaidVersion:
      type: apiKey
      in: header
      name: Plaid-Version
```
