### ISSUE TITLE
[BUG] [typescript] lacks support for parameters serialization with array and object values

### ISSUE THREAD

**Issue by a-ignatov-parc** [OpenAPITools/openapi-generator#17283]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Current implementation of `path`, `query` and `header` parameters serialization has support only for primitive values.

##### openapi-generator version

Tested 7.1.0 and `master`. Not a regression.

##### OpenAPI declaration file content or url

```yaml
paths:
  /some-path/{foo}/{bar}:
    parameters:
      - in: path
        name: foo
        required: true
        schema:
          type: array
          items:
            type: string
      - in: path
        name: bar
        required: true
        schema:
          type: object
          properties:
            baz:
              type: string
      - in: query
        name: qux
        required: true
        schema:
          type: array
          items:
            type: string
      - in: query
        name: quux
        required: true
        schema:
          type: object
          properties:
            baz:
              type: string
      - in: header
        name: quux
        required: true
        schema:
          type: object
          properties:
            baz:
              type: string
```

##### Generation Details

```shell
openapi-generator-cli generate --generator-name="typescript" --additional-properties="enumPropertyNaming=original,modelPropertyNaming=original"
```

##### Related issues/PRs

- https://github.com/OpenAPITools/openapi-generator/issues/12329
- https://github.com/OpenAPITools/openapi-generator/issues/9003

##### Suggest a fix

Properly implement spec with proper support for `style` and `explode` options.
