### ISSUE TITLE
[BUG] [JAVA] combining properties and additionalProperties generates broken Model class

### ISSUE THREAD

**Issue by Mettbrot** [OpenAPITools/openapi-generator#17361]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?

##### Description
Combining required properties with additionalProperties: true generates a Model class that extends HashMap. On deserialization, the given Properties are not filled, instead all properties (required and additional) are part of the Hashmap. According to https://github.com/FasterXML/jackson-databind/issues/3173 this is expected behavior for Jackson so the generated Model is wrong.
This was fixed for the spring generator in https://github.com/OpenAPITools/openapi-generator/pull/11572 but its still happening in the java generator.

##### openapi-generator version

7.1.0

##### OpenAPI declaration file content or url
```yaml
    additionalPropertiesWithRequiredData:
      type: object
      additionalProperties: true
      properties:
        propA:
          type: integer
          format: int64
        propB:
          type: string
      required:
        - propA
        - propB
```

##### Related issues/PRs
https://github.com/OpenAPITools/openapi-generator/issues/1466
https://github.com/OpenAPITools/openapi-generator/pull/11572

##### Suggest a fix
The model generation should not extend HashMap, instead put additionalProperties as a HashMap inside the class and annotate it with `@JsonAnySetter` / `@JsonAnyGetter`.

**Comment by throwable** [comment]
Thank you for pointing out that the bug had already been fixed in the Spring generator. This enabled me to create a simple workaround consisting of two steps:

1. Generate the client as-is using the Java + WebClient generator.
2. Replace the original model with the one generated by the Spring + Spring HTTP Interface generator.

Ugly, but it happened to work.

**Comment by lesteenman** [comment]
It seems worse for me - even setting `additionalProperties: false` in the model will result in the model explicitly extending HashMap. 

We explicitly set this property to false to make sure our validation correctly fails if our examples have unknown types, as the default of openapi 3.1 is to allow additional properties.

Example:

```
  schemas:
    DemoNested:
      type: object
      required:
        - textField
      properties:
        textField:
          type: string
```

Result:

```java
/**
 * ReproductionDemoNested
 */
@JsonPropertyOrder({
  ReproductionDemoNested.JSON_PROPERTY_TEXT_FIELD
})
@JsonTypeName("DemoNested")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-09-23T11:41:21.482102+02:00[Europe/Amsterdam]", comments = "Generator version: 7.8.0")
public class ReproductionDemoNested {
  public static final String JSON_PROPERTY_TEXT_FIELD = "textField";
  private String textField;
```

versus:

```yaml
  schemas:
    DemoNested:
      type: object
      additionalProperties: false
      required:
        - textField
      properties:
        textField:
          type: string
```

resulting in

```java
/**
 * ReproductionDemoNested
 */
@JsonPropertyOrder({
  ReproductionDemoNested.JSON_PROPERTY_TEXT_FIELD
})
@JsonTypeName("DemoNested")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-09-23T11:41:09.715975+02:00[Europe/Amsterdam]", comments = "Generator version: 7.8.0")
public class ReproductionDemoNested extends HashMap<String, Object> {
  public static final String JSON_PROPERTY_TEXT_FIELD = "textField";
  private String textField;
```
