### ISSUE TITLE
[BUG] AbstractPythonCodegen: setMapNumberTo Exception Message is Incongruent.

### ISSUE THREAD

**Issue by wolginm** [OpenAPITools/openapi-generator#17433]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists? (Validated w/7.0.1 and manually checked that it is still in Master (12/19/2023))
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Encountered when using Openapi Generator 7.0.1 when I was extending the AbstractPythonCodegen class.  When testing all possible parameters as apart of unit testing, I put in an incorrect value for the property 'mapNumberTo'.  This resulted in an exception with the message being thrown "mapNumberTo value must be Union[StrictFloat, StrictInt], StrictStr or float".  The issue is that the code checks for the following,
``` java
    public void setMapNumberTo(String mapNumberTo) {
        if ("Union[StrictFloat, StrictInt]".equals(mapNumberTo)
                || "StrictFloat".equals(mapNumberTo)
                || "float".equals(mapNumberTo)) {
            this.mapNumberTo = mapNumberTo;
        } else {
            throw new IllegalArgumentException("mapNumberTo value must be Union[StrictFloat, StrictInt], StrictStr or float");
        }
    }
```
It looks to me that either the message needs to change, or the logical OR needs to be updated.

##### openapi-generator version

7.0.1

##### OpenAPI declaration file content or url

Not related to any one schema file per se.

##### Generation Details

```yaml
generatorName: python
outputDir: samples/openapi3/client/petstore/python
inputSpec: modules/openapi-generator/src/test/resources/3_0/python/petstore-with-fake-endpoints-models-for-testing.yaml
templateDir: modules/openapi-generator/src/main/resources/python
additionalProperties:
  packageName: petstore_api
  useOneOfDiscriminatorLookup: "true"
  disallowAdditionalPropertiesIfNotPresent: false
  **mapNumberTo: StrictFloat**
nameMappings:
  _type: underscore_type
  type_: type_with_underscore
```

##### Steps to reproduce

Try to follow the exception as listed, and put in StrictStr as a possible parameter.
```yaml
generatorName: python
outputDir: samples/openapi3/client/petstore/python
inputSpec: modules/openapi-generator/src/test/resources/3_0/python/petstore-with-fake-endpoints-models-for-testing.yaml
templateDir: modules/openapi-generator/src/main/resources/python
additionalProperties:
  packageName: petstore_api
  useOneOfDiscriminatorLookup: "true"
  disallowAdditionalPropertiesIfNotPresent: false
  **mapNumberTo: StrictStr**
nameMappings:
  _type: underscore_type
  type_: type_with_underscore
```
or 
``` java
final CodegenConfigurator configurator = new CodegenConfigurator()
              .setGeneratorName("python") // use this codegen library
              .setInputSpec("modules/openapi-generator/src/test/resources/3_0/python/petstore-with-fake-endpoints-models-for-testing.yamll") // sample OpenAPI file
              .setPackageName("custom_package_name")
              .setAdditionalProperties(new HashMap(1){{put("mapNumberTo", "StrictStr");}})
              .setOutputDir("target/out/mapNumberToExample"); // output directory
```

##### Related issues/PRs

N/A

##### Suggest a fix

I think the best option is to update the exception message to accurately reflect the logical or.
