### ISSUE TITLE
[BUG] Exception Thrown for Missing Non-Required Query Parameters in C# Generated Code

### ISSUE THREAD

**Issue by alecjames** [OpenAPITools/openapi-generator#17451]
I am encountering an issue where the C# server code generated by OpenAPI Generator (version 7.1.0) throws exceptions when non-required query parameters are absent in a request. This problem arises despite these parameters not being marked as required in my OpenAPI document, which I created using Stoplight Studio (version 2.10.0).

**Steps to Reproduce:**
1. **OpenAPI Document Creation:**
   - Using Stoplight Studio 2.10.0, I created an OpenAPI document. In this document, I have several query parameters not marked as required.
   - Example snippet from the YAML file:
     ```yaml
     parameters:
        - schema:
            type: string
            nullable: true
          in: query
          name: data
          description: 'For more information, refer to ....'
          allowEmptyValue: true
     ```
   - Stoplight Studio does not set these parameters as nullable, I have added nullable manually..

2. **OpenAPI Generator Usage:**
   - I used the OpenAPI Generator CLI (version 7.1.0) with the following command to generate the C# server code:
     ```bash
     openapi-generator-cli generate -i [path-to-myDoc.yaml] -g aspnetcore -o [output-directory] --additional-properties=aspnetCoreVersion=6.0,buildTarget=library,packageName=MyRestSvr,operationIsAsync=true,operationResultTask=true
     ```

3. **Encountered Issue:**
   - In the generated C# server code, the absence of these query parameters (which are not required as per the OpenAPI document) leads to exceptions.

**Workaround Implemented:**
- I manually modified the generated code to define these query parameters as nullable in C#. This resolved the issue.

**Expected Behaviour:**
- The generated code should handle non-required query parameters without throwing exceptions when they are missing.
