### ISSUE TITLE
[BUG] swift-combine doesn't escape '#' in enum variables

### ISSUE THREAD

**Issue by BeryJu** [OpenAPITools/openapi-generator#17464]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Some of the enums values we have are full URLs, from which the `swift5` generator correctly replaces `#` with `Hash`, however the `swift-combine` generator does not replace them.

##### openapi-generator version

7.2.0

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.3
info:
  title: authentik
  version: 2023.10.4
  description: Making authentication simple.
  contact:
    email: hello@goauthentik.io
  license:
    name: MIT
    url: https://github.com/goauthentik/authentik/blob/main/LICENSE
paths: {}
components:
  schemas:
    DigestAlgorithmEnum:
      enum:
      - http://www.w3.org/2000/09/xmldsig#sha1
      - http://www.w3.org/2001/04/xmlenc#sha256
      - http://www.w3.org/2001/04/xmldsig-more#sha384
      - http://www.w3.org/2001/04/xmlenc#sha512
      type: string
```

##### Generation Details

```
docker run \
	-v $(pwd):/local \
	docker.io/openapitools/openapi-generator-cli:v7.2.0 generate \
	-i /local/schema.yml \
	-g swift-combine \
	-o /local \
	-c /local/config.yaml
```

Config being 

```yaml
templateDir: /local/templates/
additionalProperties:
  disallowAdditionalPropertiesIfNotPresent: false
  enumUnknownDefaultCase: true
  projectName: authentikClient
  podAuthors: authentik Team
  podHomepage: https://goauthentik.io/
  podSummary: authentik Swift API Client
files:
  README.mustache:
    templateType: SupportingFiles
    destinationFilename: README.md
```

##### Steps to reproduce

Run the command above with the supplied schema, which will generate this swift file:

```swift
public enum DigestAlgorithmEnum: String, Codable, CaseIterable {
    case _200009xmldsig#sha1 = "http://www.w3.org/2000/09/xmldsig#sha1"
    case _200104xmlenc#sha256 = "http://www.w3.org/2001/04/xmlenc#sha256"
    case _200104xmldsigMore#sha384 = "http://www.w3.org/2001/04/xmldsig-more#sha384"
    case _200104xmlenc#sha512 = "http://www.w3.org/2001/04/xmlenc#sha512"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
```
, which is not syntactically correct.

##### Suggest a fix

```diff
--- a/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/SwiftCombineClientCodegen.java
+++ b/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/SwiftCombineClientCodegen.java
@@ -589,7 +589,7 @@ public class SwiftCombineClientCodegen extends DefaultCodegen implements Codegen
             String startingNumbers = startWithNumberMatcher.group(0);
             String nameWithoutStartingNumbers = name.substring(startingNumbers.length());

-            return "_" + startingNumbers + camelize(nameWithoutStartingNumbers, LOWERCASE_FIRST_LETTER);
+            return this.toEnumVarName("_" + name, datatype);
         }

         // for symbol, e.g. $, #
```
