### ISSUE TITLE
[BUG] OpenApi contract with objects having no properties and a parent get wrong generated equals() 

### ISSUE THREAD

**Issue by vero-magnussen** [OpenAPITools/openapi-generator#17486]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description
Whenever an OpenApi model specification has an allOf, but does not contain any properties of it's own, the openAPI generator fails calling super.equals(). 

##### openapi-generator version
7.0.0

##### OpenAPI declaration file content or url

```yaml
SomeObject:
  allOf:
    - $ref: 'parent-object.yml#/ParentObject'
  type: object
  description: |
    some description
```
```yaml
ParentObject:
  type: object
  discriminator:
    propertyName: some_type
  description: |
    some more description.
  required:
    - property_1
    - value
  properties:
    property_1:
      $ref: 'property-1.yml#/Property1'
    value:
      type: string
      description: Some other description
    some_type:
      type: string
```
##### Steps to reproduce

When running openApi generator for objects using allOf, but not having properties of it's own, call to super.equals is missing.

##### Suggest a fix

Always call super.equals when using allOf.
