### ISSUE TITLE
[BUG][dart-dio] Model generated with $ even if not abstract

### ISSUE THREAD

**Issue by marinkobabic** [OpenAPITools/openapi-generator#17517]
This issue exists in the latest version and it doesn't seem to be a regression bug according to my understanding

Imagine the following class is a request in any of the api calls

```yaml
Pet:
  type: object
  required:
    - id
    - name
  properties:
    id:
      type: integer
      format: int64
    name:
      type: string
    tag:
      type: string
```
Then we have a response defined as following
```yaml
PetResponse:
  description: |
    Pet Response
  allOf:
    - $ref: '#/components/schemas/Pet'
    - type: object
      properties:
        referenceId:
          type: string
```

They only way in dart to instantiate the Pet Model class is to use the $PetModel. The reason is that the flag
https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/dart/libraries/dio/serialization/built_value/class_header.mustache#L12

`x-is-parent` 

is set https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/DartDioClientCodegen.java#L447

This happens as soon as allOf is used https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/DartDioClientCodegen.java#L347

Expected behaviour would be when the class used in allOf is also used as request or response somewhere else is not marked as `instantiable: false` as this is not correct. Class should be instantiable.
