### ISSUE TITLE
[BUG] [Dart] Enums with numeric constant values will generate syntatically incorrect Dart code

### ISSUE THREAD

**Issue by 0xNF** [OpenAPITools/openapi-generator#17547]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Numeric enums, such as:

```yaml
    DeviceStatus:
      required:
        - Online
      type: object
      properties:
        Online:
          type: integer
          description: |
            0 Unknown 1 Online 2 Offline
          default: 0
          enum:
            - 0
            - 1
            - 2
```

will generate uncompilable dart files:

```dart
  /// Returns a new [DeviceStatus] instance.
  DeviceStatus({
    this.online = const DeviceStatusOnlineEnum._(DeviceStatusOnlineEnum.number0),
  });
```

```dart
  DeviceStatusOnlineEnum? decode(dynamic data, {bool allowNull = true}) {
    if (data != null) {
      switch (data.toString()) {
        case 0: return DeviceStatusOnlineEnum.number0;
        case 1: return DeviceStatusOnlineEnum.number1;
        case 2: return DeviceStatusOnlineEnum.number2;
        default:
          if (!allowNull) {
            throw ArgumentError('Unknown enum value to decode: $data');
          }
      }
    }
    return null;
  }
```

##### openapi-generator version

7.3.0-snapshot

##### Steps to reproduce

No special reproduction steps, just generate a regular dart sdk using any numeric enum definition like from above
```bash
java -jar openapi-generator-cli.jar generate -i .\errors.yaml -g dart -o with_errors
```
