### ISSUE TITLE
[BUG][Kotlin][Multiplatform] Support for date format is missing for kotlinx-datetime library

### ISSUE THREAD

**Issue by ggajews** [OpenAPITools/openapi-generator#17597]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

For the input data in Schema:
```
        shipDate:
          type: string
          format: date-time
```

generator produces
```
@SerialName(value = "shipDate") val shipDate: java.time.LocalDate? = null
```
Which is incorrect for multiplatform, and breaks the build

##### openapi-generator version

`7.2.0`

##### OpenAPI declaration file content or url

Just edit the original [petstore.yaml ](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/test/resources/2_0/petstore.yaml) and change shipDate to date:

```yaml
Order:
    title: Pet Order
    description: An order for a pets from the pet store
    type: object
    properties:
      id:
        type: integer
        format: int64
      petId:
        type: integer
        format: int64
      quantity:
        type: integer
        format: int32
      shipDate:
        type: string
        format: date
      status:
        type: string
        description: Order Status
        enum:
          - placed
          - approved
          - delivered
      complete:
        type: boolean
        default: false
    xml:
      name: Order
```

##### Generation Details

Just run sample generator

##### Steps to reproduce

Generate [kotlin-multiplatform-kotlinx-datetime](https://github.com/OpenAPITools/openapi-generator/tree/69e72203aeca023cb2f3bd392d3c080af6e2a0fe/samples/client/petstore/kotlin-multiplatform-kotlinx-datetime) sample

##### Related issues/PRs

none

##### Suggest a fix

Probably registering a date type in KotlinClientCodegen.java should be enough
```
private void processKotlinxDate() {
        additionalProperties.put(DateLibrary.KOTLINX_DATETIME.value, true);

       typeMapping.put("date", "kotlinx.datetime.LocalDate");

        typeMapping.put("date-time", "kotlinx.datetime.Instant");
        typeMapping.put("DateTime", "Instant");
        importMapping.put("Instant", "kotlinx.datetime.Instant");
    }
```
