### ISSUE TITLE
[BUG] [JAVA] Missing importing @Valid cause compilation issue on client creation

### ISSUE THREAD

**Issue by valerioponte** [OpenAPITools/openapi-generator#17617]
#### Bug Report Checklist

- [v] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [v] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [v] Have you searched for related issues/PRs?
- [v] What's the actual output vs expected output?
  - Actual output: Compilation issue -  cannot find symbol [ERROR]   symbol:   class Valid
  - Expected output: Valid API client code
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When the query parameter type is declare in a different yaml file but imported as reference and when the type is Array of Enum, it was notice that the client generation produces a not compiling java code.
In the client code, the method argument matching the query parameter is now annotated with @Valid (this was introduced in the openapi version 7.2.0) however the class does not import the annotation resulting in a "cannot find symbol" compilation issue.

##### openapi-generator version

The version 7.2.0 introduced this issue.

##### OpenAPI declaration file content or url

Content of first.yaml file
```yaml
...
paths:
  /resource:
    get:
      parameters:
        - in: query
          name: queryParamListOfEnum
          required: false
          schema:
            type: array
            items:
              $ref: './second.yaml#/components/schemas/QueryParamListOfEnum'
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Resource'
...
```

Content of second.yaml file
```yaml
...
components:
  schemas:
    
    LocationEnum:
      description: "The location code."
      type: string
      enum:
        - "PHX"
        - "ASH"
...
```

##### Generation Details

openapi-generator-maven-plugin

configuration:
```xml
<useJakartaEe>true</useJakartaEe>
<library>webclient</library>
<useTags>true</useTags>
<dateLibrary>java8</dateLibrary>
<hideGenerationTimestamp>true</hideGenerationTimestamp>
<apiPackage>${api.package}.client</apiPackage>
<modelPackage>${api.package}.client.models</modelPackage>
```

##### Suggest a fix

Include the missing "import jakarta.validation.Valid;" import in the generated client class.

**Comment by wing328** [comment]
can you please file a PR with the suggested fix?

**Comment by arburk** [comment]
I also experienced this issue. But it is not valid for all generated files. The import for `jakarta.validation.Valid;` was missing in one file only while other generated files contained this import.

**Comment by wsdng** [comment]
The same issue applies to using patterns on the strings in an array parameter, e.g.:

 ```
parameters:
        - name: foos
          in: query
          required: true
          schema:
            type: array
            items:
              type: string
              pattern: ^[A-Z]{1}[A-Z0-9 ]{1,4}$
```
The generated Code includes a @Pattern annotation but no import.
Note that I've been using config options useSpringBoot3 and useJakartaEe.
