### ISSUE TITLE
[BUG][JAVA] Missing dependency for bean validation with Resttemplate library

### ISSUE THREAD

**Issue by nathcouret** [OpenAPITools/openapi-generator#17752]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [X] What's the actual output vs expected output?

##### Description

I've been attempting to generate a Java client with the Resttemplate library but I can't build the client when using the useBeanValidation and performBeanValidation properties because of missing dependencies in the generated pom.xml file.

##### openapi-generator version

7.2.0

##### OpenAPI declaration file content or url

Use the API declaration from the [sample Petstore](https://github.com/OpenAPITools/openapi-generator/blob/master/samples/client/petstore/java/resttemplate-jakarta/api/openapi.yaml)

##### Generation Details

```yml
generatorName: java
outputDir: samples/client/petstore/java/resttemplate-jakarta
library: resttemplate
inputSpec: modules/openapi-generator/src/test/resources/3_0/petstore.yaml
templateDir: modules/openapi-generator/src/main/resources/Java
additionalProperties:
  artifactId: petstore-resttemplate
  hideGenerationTimestamp: "true"
  java8: true
  useJakartaEe: true
  useBeanValidation: true
  performBeanValidation: true
```

##### Steps to reproduce

* Generate a Java client with Resttemplate library and bean validation enabled using the configuration above
* Run mvn compile 
* There should compilation errors: "package jakarta.validation does not exist"

##### Suggest a fix

I have a fix ready, I just need to push it and have it reviewed.
