### ISSUE TITLE
[JAVA] Add CodegenProperty.isEnumModel for Model of Enum

### ISSUE THREAD

**Issue by lubinson** [OpenAPITools/openapi-generator#1783]
##### Description

I found there has no property to identify a field is Model (isModel=true) and also Enum. For example:

```
public enum AccountType{
...
}
```

##### openapi-generator version

openapi-generator-cli-4.0.0-20181124.163833-43

##### OpenAPI declaration file content or url

```yaml
    AccountType:
      type: string
      enum:
        - VIP
        - VVIP
```

##### Command line used for generation

NA
##### Steps to reproduce

1, run code generate
2, add {{isEnum}}, {{isModel}} in pojo.mustache to see the print

##### Related issues/PRs
NA
##### Suggest a fix/enhancement
NA
