### ISSUE TITLE
[REQ] Ability to add new parameters to be used in templates

### ISSUE THREAD

**Issue by rohrit** [OpenAPITools/openapi-generator#17971]
### Is your feature request related to a problem? Please describe.

Is it possible to add bindings using moustache templates to work with go-gin-server generator? gin-gonic supports go-playground/validator based bindings for example

```go
type Foo struct {
    Addr string `json:"addr" binding:"ipv4"
}
```

from corresponding OpenAPI specification of

```yaml
addr:
          description: Unique identifier of the exclusion.
          format: ipv4
          type: string
```

Mustache based templates does not allow for matching based on values of format. Template code would have lot of if-else logic even if it allowed it. If there is the possibility of defining a new variable for the template (say, binding) that can then be used in the template, it could solve the problem. I am not familiar with openapi-generator enough to know what would be the best way to accomplish it and am looking for suggestions on how this can be accomplished.
