### ISSUE TITLE
[BUG][Go][Client] Invalid syntax for nullable binary

### ISSUE THREAD

**Issue by dtrunk90** [OpenAPITools/openapi-generator#18006]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

The generated code has invalid syntax and produces the following error:
`syntax error: unexpected * in struct type; possibly missing semicolon or newline or }`

##### openapi-generator version

7.3.0

##### OpenAPI declaration file content or url

```yaml
    content:
      type: string
      format: binary
      nullable: true
```

Spec from https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/api-reference/v2.0/dynamics-open-api#download-business-central-openapi-specification

Generates following go struct field:
```go
Content Nullable*os.File `json:"content,omitempty"`
```

##### Generation Details

`openapi-generator-cli generate -c config.yaml --skip-operation-example`

```yaml
generatorName: go
inputSpec: bcoas1.0.yaml
outputDir: ./lib
packageName: businesscentral
withGoMod: false
```

##### Steps to reproduce

Try to use and compile the code. It will fail.
