### ISSUE TITLE
[BUG] Field declare as Date is not Recognize as isDate is mustache

### ISSUE THREAD

**Issue by ananddwivediDev** [OpenAPITools/openapi-generator#18038]
Field declare as Date is not Recognize as isDate is mustache. 

1) Spec has field of type Date .
2) we have written our own converter by extends SpringCodegen implements CodegenConfig
3) Once we run generator we are noticing that the model json is not update isDate property as true for "openApiType" : "Date",

**yaml**
```yaml
        generatorTime:
          deprecated: true
          format: date-time
          type: string
```

**model json** 

```json
      "openApiType" : "Date",
      "baseName" : "generatorTime",
      "isDate" : false,
      "isDateTime" : false,
      
```
**Mustache** 

```
{{#isDate}}
  @JsonProperty("{{baseName}}")
 {{/isDate}}
```

now above mustache condition failed since isDate is false. right now i am using openapi-generator-5.4.0 version .
