### ISSUE TITLE
[BUG][Spring] Too many quotes in generated spring annotation (4.0.0-beta)

### ISSUE THREAD

**Issue by ftes** [OpenAPITools/openapi-generator#1805]
##### Description

Same issue as described for v3 in #1697, which was fixed for v3 in #708.

##### openapi-generator version

4.0.0-beta

##### OpenAPI declaration file content or url

[Spec](https://github.com/ftes/openapi-generator-v4-default-value-bug/blob/master/src/main/resources/default-string-value-in-header.yaml):
```yaml
paths:
  /pet:
    get:
      operationId: addPet
      parameters:
      - in: header
        name: with-default
        type: string
default: string
```

[Generated source](https://github.com/ftes/openapi-generator-v4-default-value-bug/blob/master/target/generated-sources/openapi/src/main/java/org/openapitools/api/PetApi.java#L43):
```
default ResponseEntity<Void> addPet(@ApiParam(value = "" , defaultValue=""string"")
```

##### Command line used for generation

`maven clean install`

##### Steps to reproduce

Add header parameter of type string with default value and build the spring server sources.

##### Related issues/PRs

#1697
#708
