### ISSUE TITLE
[BUG][TypeScript-Axios] Boolean field not correctly serialized in FormData

### ISSUE THREAD

**Issue by dvacca-onfido** [OpenAPITools/openapi-generator#18083]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [X] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Generated TypeScript-Axios client is not properly serializing boolean fields part of a multipart/form-data payload, throwing the error _TypeError: data should be a string, Buffer or Uint8Array_

##### openapi-generator version

Issue found in version 7.3.0+

##### OpenAPI declaration file content or url

https://github.com/onfido/onfido-openapi-spec/blob/f600387ed926407964d3aed6beed0f00480d11d4/generated/artifacts/openapi-yaml/openapi/openapi.yaml#L2282-L2285

##### Generation Details

```yaml
inputSpec: openapi.yaml
generatorName: typescript-axios
useOneOfDiscriminatorLookup: true
disallowAdditionalPropertiesIfNotPresent: false
npmName: "@onfido/api"
enumUnknownDefaultCase: true
supportsES6: true
apiPackage: api
modelPackage: model
withNodeImports: true
withSeparateModelsAndApi: true
```

##### Steps to reproduce

```typescript
import { createReadStream } from "fs";
import { DefaultApi, Configuration } from "../onfido-node";

const onfido = new DefaultApi(
  new Configuration({
    apiToken: process.env.API_KEY
  })
);
(async () => {

  let live_photo_file:any = createReadStream("live_photo.jpg")
  let live_photo = await onfido.uploadLivePhoto('random-uuid', live_photo_file, false)
})();
```

Logs:

```
onfido-node/node_modules/follow-redirects/index.js:125
    throw new TypeError("data should be a string, Buffer or Uint8Array");
    ^
```

##### Related issues/PRs

N/A

##### Suggest a fix

Boolean should be casted to a valid type, `String` perhaps (PR coming soon):

```typescript
# Actual output
localVarFormParams.append('advanced_validation', advancedValidation as any);

# Expected output
localVarFormParams.append('advanced_validation', String(advancedValidation as any));
```
