### ISSUE TITLE
[BUG][JAVA] Model generation of array with uniqueItems=true is not working

### ISSUE THREAD

**Issue by MelleD** [OpenAPITools/openapi-generator#18102]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Currently no more sets are generated if uniqueItems=true is set.

##### openapi-generator version

7.4.0/latest

##### OpenAPI declaration file content or url

If you post the code inline, please wrap it with
```yaml
        stringSet:
          type: array
          uniqueItems: true
          items:
            type: string
        stringDefaultSet:
          type: array
          uniqueItems: true
          default:
            - A
            - B
          items:
            type: string
        stringEmptyDefaultSet:
          type: array
          uniqueItems: true
          default: []
          items:
            type: string
```
Out put is

```java
  @Valid
  private List<String> stringSet = new ArrayList<>();

  @Valid
  private List<String> stringDefaultSet = new ArrayList<>(Arrays.asList("A", "B"));

  @Valid
  private List<String> stringEmptyDefaultSet = new ArrayList<>();
```

##### Generation Details

Spring Boot Cloud
