### ISSUE TITLE
[BUG] templateOutputDirs config option is ignored

### ISSUE THREAD

**Issue by tyler-mairose-sp** [OpenAPITools/openapi-generator#18155]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [X] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

I wanted to use different folders for saving my api and model documentation to. I saw that this was implemented here https://github.com/OpenAPITools/openapi-generator/pull/15561/files. When I include config below the template files still get saved in the same directory as before.

```yaml
templateDir: ./sdk-resources/resources
packageName: Package
packageVersion: 1.2.3
apiVersion: v3
companyName: Company Name
packageGuid: a14925fb-44fb-447d-8708-6fbdf2762efa
commonVerbs: Delete=Remove:Cancel=Suspend:Patch=Update:List=Get:Query=Search:Run=Start:Validate=Confirm:Make=Select
discardReadOnly: true
templateOutputDirs:
  api_doc.mustache: ./methods
  model_doc.mustache: ./models
```

I would expect all api documentation to be in a root folder `methods` and model documentation to be in a root folder `models`

##### OpenAPI declaration file content or url

N/A

##### Generation Details

```bash
java -jar openapi-generator-cli.jar generate -i api-specs/v3.yaml -g powershell -o v3 --global-property skipFormModel=false --config sdk-resources/v3-config.yaml
```

##### Steps to reproduce

* Run the generator with templateOutputDirs key specified in the config.yaml
* The particular generator I am using is powershell

##### Related issues/PRs

https://github.com/OpenAPITools/openapi-generator/pull/15561/files

**Comment by martin-mfg** [comment]
Hi,
the config file has to be a bit different from what you posted. Here's a working version (only the "templateOutputDirs"/"files" section changed):
```yaml
templateDir: ./sdk-resources/resources
packageName: Package
packageVersion: 1.2.3
apiVersion: v3
companyName: Company Name
packageGuid: a14925fb-44fb-447d-8708-6fbdf2762efa
commonVerbs: Delete=Remove:Cancel=Suspend:Patch=Update:List=Get:Query=Search:Run=Start:Validate=Confirm:Make=Select
discardReadOnly: true
files:
  api_doc.mustache:
    templateType: Model
    folder: methods
    destinationFilename: .md
  model_doc.mustache:
    templateType: Model
    folder: models
    destinationFilename: .md
```

(templateType "APIDocs" and "ModelDocs" would be more appropriate, but when using those values, the "folder" setting was ignored in my tests.)
