### ISSUE TITLE
[BUG] [Spring] Compile error in ClientPropertiesConfiguration

### ISSUE THREAD

**Issue by MelleD** [OpenAPITools/openapi-generator#18231]
If 2 OAuth flows are defined as Security Scheme, incomptible code is generated

#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

7.4.0

##### OpenAPI declaration file content or url

If you post the code inline, please wrap it with
```yaml
  securitySchemes:
    test:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: '/openid-connect/auth'
          tokenUrl: '/openid-connect/token'
          scopes: { }
        clientCredentials:
          tokenUrl: '/openid-connect/token'
          scopes: { }
```
