### ISSUE TITLE
[BUG] [JAVA] 3.1 specs generates String instead of enum value in query params

### ISSUE THREAD

**Issue by AlinaKZN** [OpenAPITools/openapi-generator#18234]
##### Description

While migrating from openapi 3.0 to 3.1 we've found the bug.

##### openapi-generator version

 openapi-generator is 7.3.0 , but it works the same with 7.2.0 

##### OpenAPI declaration file content or url

```yaml
get:
  tags:
    - tag
  description: desc
  parameters:
    # query
    - $ref: '../../parameters/Codes.yml'

...
Codes.yml
description: Code
name: codes
in: query
required: true
schema:
  type: array
  items:
    $ref: './CodesEnum.yml'
...

CodesEnum.yml
type: string
enum:
  - Code1
  - Code2
  - Code3
  - Code4
```

##### Generation Details

if open-api is 3.0 everything is ok and the query parameter generates as ``` List<CodeEnum> ```, but when version is 3.1 it id genererated as ``` List<String>``` 
It causes some problem.
