### ISSUE TITLE
[BUG] []

### ISSUE THREAD

**Issue by alfechner** [OpenAPITools/openapi-generator#18394]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ ] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

**Comment by wing328** [comment]
```
 MyObject:
  type: object
  properties:
    retentionTimeInDays:
      type: integer
      nullable: false
```

if you remove `nullable: false`, does it work correctly?
