### ISSUE TITLE
[BUG] [aspnetcore] - models are generated with an invalid constructor (v7.5.0)

### ISSUE THREAD

**Issue by rshacham** [OpenAPITools/openapi-generator#18424]
##### Description

My models get generated with a constructor that lacks parameter names. It looks something like this:
```c#
        public SomeModel(
            DateTime ,
            double
        )
        {
            this.Time = ;
            this.Value = ;
        }

``` 

This is the model .yaml filel:
```
title: SomeModel
type: object
properties:
  time:
    type: string
    format: date-time
  value:
    type: number
    format: double
required:
  - time
  - value
``` 

##### openapi-generator version

v7.5.0

##### Suggest a fix

I believe [This](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/aspnetcore/3.0/model.mustache) is the template file used to generate the class. I'm not sure where does the constructor come from as it's not explicitly declared in this .mustache file.
