### ISSUE TITLE
[BUG] [aspnetcore] - models are generated with an invalid constructor (v7.5.0)

### ISSUE THREAD

**Issue by roishacham** [OpenAPITools/openapi-generator#18425]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ ] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

My models get generated with a constructor that lacks parameter names. It looks something like this:
```c#
        public SomeModel(
            DateTime ,
            double
        )
        {
            this.Time = ;
            this.Value = ;
        }

``` 

This is the mode .yaml filel:
```
title: SomeModel
type: object
properties:
  time:
    type: string
    format: date-time
  value:
    type: number
    format: double
required:
  - time
  - value
``` 

##### openapi-generator version

v7.5.0

##### Suggest a fix

I believe [This is](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/aspnetcore/3.0/model.mustache) the template used for generating the class. I'm not sure where does the constructor come from as it's not explicitly declared in this .mustache file.
