### ISSUE TITLE
[BUG] [JAVA] Cannot use oneOf as query parameter

### ISSUE THREAD

**Issue by lollol155** [OpenAPITools/openapi-generator#18543]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### openapi-generator version

7.6.0-SNAPSHOT

##### OpenAPI declaration file content or url

```yaml
    parameters:
        name: myParameter
        in: query
        required: false
        schema:
          oneOf:
            - type: number
            - type: string
```
will result in name of  openapi class as actual query parameter instead of my string or number
```
org.openapitools.client.model.myParameter
```

**Comment by wing328** [comment]
as a workaround, what about simplifying the schema to the following instead?

```
    parameters:
        name: myParameter
        in: query
        required: false
        schema:
          - type: string
```

as number and string make no difference in the query parameter in most cases.
