### ISSUE TITLE
[BUG] [PYTHON] Model property: required AND default NOT combinable

### ISSUE THREAD

**Issue by Poolmann** [OpenAPITools/openapi-generator#18540]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

I want to have a required property with a default value. When I require it in the model spec, it loses the `default=` parameter in the `Field()` constructor. I need it to be required since, if it isn't, it could be `None`.

Firstly, is this intended? If so how am I supposed to set up the property? If not, please help :)

##### openapi-generator version

master/7.5.0

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.0
info:
  title: Title
  description: Title
  version: 1.0.0
paths:
  '/user':
    get:
      responses:
        200:
          description: "success"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequiredProperties'

components:
  schemas:
    RequiredProperties:
      type: object
      required:
        - requiredWithDefault
        - requiredWithoutDefault
      properties:
        requiredWithoutDefault:
          type: string
        requiredWithDefault:
          type: string
          default: "4.5.0"
        notRequiredWithDefault:
          type: string
          default: "4.5.0"
        notRequiredWithoutDefault:
          type: string
```

##### Generation Details

`java -jar openapi-generator-cli.jar generate -i required.yaml -g python -o object --additional-properties packageName=object_client`

##### Steps to reproduce

1. Generate from provided spec
2. See Model class

```python
class RequiredProperties(BaseModel):
    """
    RequiredProperties
    """ # noqa: E501
    required_with_default: StrictStr = Field(alias="requiredWithDefault")
    required_without_default: StrictStr = Field(alias="requiredWithoutDefault")
    not_required_with_default: Optional[StrictStr] = Field(default='4.5.0', alias="notRequiredWithDefault")
    not_required_without_default: Optional[StrictStr] = Field(default=None, alias="notRequiredWithoutDefault")
    __properties: ClassVar[List[str]] = ["requiredWithDefault", "requiredWithoutDefault", "notRequiredWithDefault", "notRequiredWithoutDefault"]
```
Interestingly enough, the default shows up in the `from_dict()` classmethod:
```python
        _obj = cls.model_validate({
            "requiredWithDefault": obj.get("requiredWithDefault") if obj.get("requiredWithDefault") is not None else '4.5.0',
            "requiredWithoutDefault": obj.get("requiredWithoutDefault"),
            "notRequiredWithDefault": obj.get("notRequiredWithDefault") if obj.get("notRequiredWithDefault") is not None else '4.5.0',
            "notRequiredWithoutDefault": obj.get("notRequiredWithoutDefault")
        })
  ```

##### Suggest a fix

I haven't quite found the problem yet, I'm pretty sure this is the part that's causing it: https://github.com/OpenAPITools/openapi-generator/blob/a4cf255dce69b74fabe49161d75bdc39851d1d95/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPythonPydanticV1Codegen.java#L914

**Comment by wing328** [comment]
a required property cannot have a default value because it's "required" which means users must provide a value

**Comment by Poolmann** [comment]
How should I prevent users from passing `None`? Because if it's not "required" it becomes an `typing.Optional`.

**Comment by Poolmann** [comment]
But as one can see above, the property then becomes an `typing.Optional`. How should I signal to users to not pass `None` to it?

**Comment by andiikaa** [comment]
Also stumbled over that issue.
We have a `oneOf` with explicit mapping.
I think the discriminator should be a field which is "required" but not necessarily required to be set by the developer.
As mentioned by @Poolmann "required" should ensure, that the value cannot be omitted (which might cause issues in the deserialization).

With the following setting, there is no default set for the message and the user needs to explicitly set the "message_type".
This does not sound really convenient.

Any suggestions @wing328 ?

```yaml
title: InitializeMovementRequest
required:
  - trajectory
type: object
properties:
  message_type:
    type: string
    enum: [InitializeMovementRequest]
    default: InitializeMovementRequest
  trajectory:
    oneOf:
      - $ref: ./TrajectoryId.yaml
      - $ref: ./TrajectoryData.yaml
    discriminator:
      propertyName: message_type
      mapping:
        TrajectoryId: ./TrajectoryId.yaml
        TrajectoryData: ./TrajectoryData.yaml
```

```yaml
title: TrajectoryId
required:
  - id
  - message_type
type: object
properties:
  message_type:
    type: string
    enum: [TrajectoryId]
    default: "TrajectoryId"
  id:
    type: string
```

When following the suggestions and setting the discriminator field to "required" and omit the default, the type information is missing and the user has to set it manually otherwise there will be runtime issues with the autogenerated python code.
