### ISSUE TITLE
[BUG][Java][Spring] JsonNullable generated for schemas using oneOf/anyOf

### ISSUE THREAD

**Issue by pvdbosch** [OpenAPITools/openapi-generator#18683]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [X] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

References to some types are unnecessarily wrapped in JsonNullable, even though `nullable: true` isn't used. This happens for types generated from schemas that use oneOf or anyOf to list allowed combinations of required properties like this:
```YAML
      type: object
      properties:
         # ....
      oneOf:
        - required: [propertyA]
        - required: [propertyB]
```
A workaround for this problem is to add `type: object` to each of the oneOf subschemas.

##### openapi-generator version

Since version 7.x including 7.6.0-SNAPSHOT, doesn't occur in 6.x versions.

##### OpenAPI declaration file content or url

reproducer OpenAPI (+ extract of generated code):
https://gist.github.com/pvdbosch/1f26142fd9df792f7cba6cdff88dbc29

##### Generation Details

```YAML
generatorName: spring
inputSpec: src/main/resources/openapi.yaml
additionalProperties:
  useSpringBoot3: true
  useBeanValidation: true
  interfaceOnly: true
  skipDefaultInterface: true
  dateLibrary: java8
```
Also occurs when using java generator with spring library. Doesn't reproduce for jaxrs-spec generator.

##### Steps to reproduce

1) Generate code using openapi.yaml 
2) generated ReferencingSchema.java has an unneccessary JsonNullable wrapper for its `content` attribute.

##### Suggest a fix

My guess is that the generator sets `isNullable` to `true` on the schema in [this code](
https://github.com/OpenAPITools/openapi-generator/blob/7e94c873f7ab2aa59bb1712d829299674dff528f/modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java#L3848) because the type is missing in the oneOf subschemas ; though I haven't been able to confirm this yet.

This shouldn't be done however because there is a type defined in the schema that includes the oneOf.
