### ISSUE TITLE
[BUG][JAVA] Regression in v7.6.0 creating incorrect `generateName=spring` code

### ISSUE THREAD

**Issue by alexec** [OpenAPITools/openapi-generator#18739]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

I've just upgrade from v6.2.1 to v7.6.0 and I've encountered a problem where a path parameter that is a string has generated code that is an `Object` (incorrect) when in v6.2.1 it was a `String` (correct).

##### openapi-generator version

v7.6.0, this is a regression.

##### OpenAPI declaration file content or url

```yaml
  /v1/documents/{id}:
    get:
      summary: Get document
      description: Get a document by providing its unique ID in the path parameter.
      operationId: getDocument
      tags:
        - documents
      parameters:
        - description: The unique identifier of the document
          name: id
          required: true
          in: path
          schema:
            # IDs MUST be strings.
            type: string
            # 36 is the size of a RFC4122 UUID.
            maxLength: 36
          example: abc123
```

```xml

            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>7.6.0</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>${project.basedir}/api/openapi/openapi.yaml</inputSpec>
                            <skipValidateSpec>true</skipValidateSpec>
                            <generatorName>spring</generatorName>
                            <generateApis>true</generateApis>
                            <generateApiDocumentation>false</generateApiDocumentation>
                            <generateModels>true</generateModels>
                            <generateModelDocumentation>false</generateModelDocumentation>
                            <supportingFilesToGenerate>false</supportingFilesToGenerate>
                            <configOptions>
                                <modelPackage>{{packageName}}.models</modelPackage>
                                <apiPackage>{{packageName}}.rest.controllers</apiPackage>
                                <!-- do not generate implementations -->
                                <interfaceOnly>true</interfaceOnly>
                                <!-- do not annotate with custom nullable annotation -->
                                <openApiNullable>false</openApiNullable>
                                <!-- don't generate stub implementations, you always must implement them -->
                                <skipDefaultInterface>true</skipDefaultInterface>
                                <!-- generate one interface per tag -->
                                <useTags>true</useTags>
                                <documentationProvider>none</documentationProvider>
                                <useSwaggerUI>false</useSwaggerUI>
                                <useJakartaEe>true</useJakartaEe>
                                <useSpringBoot3>true</useSpringBoot3>
                            </configOptions>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

The incorrect generated code (where `id` is `Object` not `String`:

```java
    ResponseEntity<Void> updateDocument(
        @Size(max = 36)  @PathVariable("id") Object id,
         @Valid @RequestBody(required = false) Document document
    );
```

##### Generation Details

```bash
mvn generate-sources
```

##### Steps to reproduce

This is a internal code base. I'd have to create a new code base to test. This isn't my top priority right now, but I'm I can't be the only person affected.

##### Related issues/PRs

Old (2022) issue might be related:

https://github.com/OpenAPITools/openapi-generator/issues/9976

##### Suggest a fix

TODO
