### ISSUE TITLE
[JAVA]: Add @com.fasterxml.jackson.annotation.JsonProperty when @lombok.Data is used

### ISSUE THREAD

**Issue by nokhod** [OpenAPITools/openapi-generator#18794]
##### Description

When using `@lombok.Data` in `additionalModelTypeAnnotations`, the getters for fields are not generated. While `@com.fasterxml.jackson.annotation.JsonProperty` is only placed on getter methods, this causes a problem when the property name is in kebab-case rather than the default camel-case.

##### openapi-generator version

7.6.0

##### OpenAPI declaration file content or URL

[pojo.mustache](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/JavaSpring/pojo.mustache)

##### Command line used for generation

Regular maven build.

##### Steps to reproduce

Configuring maven plugin using following configOptions:
`<configOptions>
    <library>spring-cloud</library>
    <useSpringBoot3>true</useSpringBoot3>
    <useResponseEntity>false</useResponseEntity>
    <bigDeciamlAsString>true</bigDeciamlAsString>
    <dateLibrary>java8-localdatetime</dateLibrary>
    <useEnumCaseInsensitive>true</useEnumCaseInsensitive>
    <configPackage>com.kbakhtiari</configPackage>
    <generatedConstructorWithRequiredArgs>false</generatedConstructorWithRequiredArgs>
    <additionalModelTypeAnnotations>
        @lombok.Data
        @lombok.NoArgsConstructor
        @lombok.AllArgsConstructor
        @lombok.Builder(toBuilder = true)    
    </additionalModelTypeAnnotations>
</configOptions>`

##### Related issues/PRs

N/A

##### Suggest a fix/enhancement

Adding the following code snippet to pojo.mustache:
`{{#lombok.Data}}
  @JsonProperty("{{baseName}}")
  {{/lombok.Data}}`

**Comment by dabdirb** [comment]
@nokhod, you just need set `x-field-extra-annotation`, for example the User object in OpenAPI spec 3.0
```yaml
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        username:
          type: string
          example: theUser
        firstName:
          type: string
          example: John
          x-field-extra-annotation: |-
            @JsonProperty("first_name")
        lastName:
          type: string
          example: James
          x-field-extra-annotation: |-
            @JsonProperty("last_name")          
        email:
          type: string
          example: john@email.com
        password:
          type: string
          example: '12345'
        phone:
          type: string
          example: '12345'
        userStatus:
          type: integer
          description: User Status
          format: int32
          example: 1
      xml:
        name: user
```
the generated model is 
```java
/**
 * User
 */
@lombok.Data
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
@lombok.Builder(toBuilder = true)

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.7.0-SNAPSHOT")
public class User {

  private Long id;

  private String username;

  @JsonProperty("first_name")
  private String firstName;

  @JsonProperty("last_name")          
  private String lastName;

  private String email;

  private String password;

  private String phone;

  private Integer userStatus;

}
```
