### ISSUE TITLE
[BUG][RUST] json parser expects quotes with integer enum

### ISSUE THREAD

**Issue by ErikDaVinci** [OpenAPITools/openapi-generator#18840]
Hello,

my swagger.yaml contains following lines:

```yaml
TypesResponse:
type: object
properties:
Types:
format: int32
enum:
- 0
- 1
- 2
- 3
type: integer
```

I used the generator v7.6.0 to generate a rust client.
The client throws an error when parsing the response.
The response is like 
```json
{"Types":2}
```
. 
It seems serde_json throws - it expects a response like 
```json
{"Types":"2"}
```
.
So the client expects the 2 be in quotes.
But the yaml states "type:integer".

For me it seems like a bug in the generator - or do I misuse the generator?
Thank you.
