### ISSUE TITLE
[BUG] Kotlin-retrofit2-gson-coroutines CollectionsFormat.CSVParams default value is set to arrayListOf()

### ISSUE THREAD

**Issue by fvlahov** [OpenAPITools/openapi-generator#18864]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ ] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Open api generator where the code generated gives parameter of type `CSVParams` gives wrong default implementation, it should create the `CSVParams` class but instead it is `@Query("sort") sort: CSVParams? = arrayListOf("date:desc")`

##### openapi-generator version

7.5.0
##### OpenAPI declaration file content or url

```yaml
    SortSchema:
      type: array
      description: |
        ...
      default: [ 'date:desc' ]
      items:
        type: string
        pattern: '^(date|name|popularity|trend)(:(asc|desc))?$'
      example: [ 'date:desc', 'name' ]
```

##### Generation Details

```groovy
        generatorName = "kotlin"
        inputSpec = "$rootDir/data/src/main/assets/openapi/${spec.value}"
        outputDir = "$buildDir/generated/openapi"
        configOptions = [
                dateLibrary         : "java17",
                library             : "jvm-retrofit2",
                serializationLibrary: "gson",
                useCoroutines       : "true"
        ]
        nameMappings = [
                "identifier": "id"
        ]
        modelNamePrefix = "Api"
        apiNameSuffix = "Api"
        generateModelTests = false
        generateApiTests = false
```

##### Steps to reproduce

 - Generate retrofit API and classes with `openApiGenerate {}`
 - Build fails due to compilation error

##### Suggest a fix

Default value of `CSVParams` should create an instance of `CSVParams` class instead of `ArrayList`
