### ISSUE TITLE
[REQ] Update boundary for http package in dart generator

### ISSUE THREAD

**Issue by Plinzen** [OpenAPITools/openapi-generator#18875]
### Is your feature request related to a problem? Please describe.
The dependency section from the `pubspec.yaml` file of the dart generator is looking like that:

```
dependencies:
 http: '>=0.13.0 <0.14.0'
 intl: any
 meta: '^1.1.8'
```

Since May 2023 the version 1.0.0 and higher is available for the `http` package. But I can't use newer `http` versions due to the upper boundary specified from the openapi-generator. 

## Describe the solution you'd like
I'd like to remove the upper boundary so that the newer version of the `http` package can be used. 

```
dependencies:
 http: '>=0.13.0'
 intl: any
 meta: '^1.1.8'
```

I have checked the `http` package version 1.2.1 and it was working without issues on my project.

## Describe alternatives you've considered

Possible workaround is e.g. using a `dependency-override` in the app's `pubspec.yaml` file or manually modify the `pubspec.yaml` of the generated project.
