### ISSUE TITLE
[REQ] Support OpenAPI 3.1 prefixItems

### ISSUE THREAD

**Issue by estyrke** [OpenAPITools/openapi-generator#18911]
### Is your feature request related to a problem? Please describe.

My schema contains `prefixItems` properties, which do not seem to be supported currently.

## Describe the solution you'd like

Add support for `prefixItems` (https://json-schema.org/understanding-json-schema/reference/array#tupleValidation)

## Describe alternatives you've considered

N/A

## Additional context

N/A

**Comment by simon-dew** [comment]
I'd also like to see this enhancement.

```yaml
      value-guard-entry:
        title: Value-Guard Entry
        type: array
        description: An array containing two elements: an integer and a string.
        minItems: 2
        maxItems: 2
        prefixItems:
          - type: integer
            description: A vBucket's sequence number.
          - type: string
            format: UUID
            description: A vBucket's UUID.
```
