### ISSUE TITLE
[BUG][SPRING] execution with configuration file does not apply

### ISSUE THREAD

**Issue by AdriaBergeAguilar** [OpenAPITools/openapi-generator#18937]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

The main problem that occurs to me is that the generation command does not use the properties that it applied with a yml file, it is assumed that all the properties are those that are documented for Spring and there is no way for them to be applied.

##### openapi-generator version

```yml
services:
  openapi-generator-version:
    image: openapitools/openapi-generator-cli
    command: version
```

openapi-generator-version-1  | 7.7.0-SNAPSHOT
openapi-generator-version-1 exited with code 0

##### OpenAPI declaration file content or url

I am using the example file petstore.yaml for the open api definition, since my current intention is to configure the tool to generate the client and the server as I am interested.

[petstore.yaml](https://github.com/user-attachments/files/15846488/petstore.txt)

##### Generation Details
I have prepared the following configuration file but not all the characteristics indicated in the documentation apply to me.

[Spring-doc](https://openapi-generator.tech/docs/generators/spring)

I have put some characteristics of one of the examples to see if it reads my file and see how it applies the changes

[example see](https://github.com/OpenAPITools/openapi-generator/blob/master/bin/configs/spring-boot-lombok-data.yaml)

Then I see that the entire lombok theme applies them but does not apply all the Spring options, such as those of scm or those of develop.

##### Steps to reproduce

execute command docker.

docker-compose.yml
```yml
services:
  openapi-generator-api-v2:
    image: openapitools/openapi-generator-cli
    volumes:
      - ./config\api-config.yaml:/local/api-config.yaml
      - ./data/out:/local/out
      - ./data/petstore.yaml:/local/petstore.yaml
    command: generate -i /local/petstore.yaml -o /local/out/api -c /local/api-config.yaml 
```
[petstore.yaml](https://github.com/user-attachments/files/15846488/petstore.txt)
[api-config.txt](https://github.com/user-attachments/files/15846505/api-config.txt)
