### ISSUE TITLE
[BUG, Spring, JAVA]: $ref to external components is not generating code

### ISSUE THREAD

**Issue by maxl2287** [OpenAPITools/openapi-generator#18964]
##### Description
I cannot generate my code when the specification is referencing to external components.

##### openapi-generator version

7.5.0
##### OpenAPI declaration file content or url

```yaml
    SubscriptionDetail:
      description: The detail of the requested event subscription
      type: object
      required:
        - type
        - device
      properties:
        device:
          $ref: "https://raw.githubusercontent.com/maxl2287/<project>/draft/test-referencing-common-yaml/artifacts/common.yaml#/components/schemas/Device"


##### Generation Details

```
Errors: 
	-Unable to load URL ref: https://github.com/maxl2287/<project>/blob/draft/test-referencing-common-yaml/artifacts/CAMARA_common.yaml

```
