### ISSUE TITLE
[BUG] Java: Not able to pass dictionary in query parameters

### ISSUE THREAD

**Issue by siddhsql** [OpenAPITools/openapi-generator#19019]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [ x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x ] Have you searched for related issues/PRs?
- [x ] What's the actual output vs expected output?
- [ x] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

I want to be able to pass a dictionary in the query params of an endpoint. To do this, I created following spec as example:

```
- name: metadata
          in: query
          required: false
          style: deepObject
          explode: true
          schema:
            type: object
            additionalProperties:
              type: string      
```

when I run the openapi-codegenerator it produces the same output irrespective of whether

```
          style: deepObject
          explode: true
```

is present or not in the yaml file. The generated Java code is this:

```
@Parameter(name = "metadata", description = "", in = ParameterIn.QUERY)
          @Valid
          @RequestParam(value = "", required = false)
          Map<String, String> metadata
```

Further in swagger-ui _**I do not see any UI element corresponding to the `metadata` variable in above**_.

##### openapi-generator version

7.4.0

##### Related issues/PRs

I am not sure if this is same issue as [this](https://github.com/OpenAPITools/openapi-generator/issues/14790). Reading that issue it seemed like it is w.r.t. client code whereas my issue is w.r.t. server code.
