### ISSUE TITLE
[BUG] Incorrect ENUM generation

### ISSUE THREAD

**Issue by Noed** [OpenAPITools/openapi-generator#19066]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

ENUM is being generated with additional "_" character when there's a number on the ENUM name.

##### openapi-generator version

Issue started on 7.7.0, works fine on 7.7.6.

##### OpenAPI declaration file content or url

Example ENUM attribute in the YAML spec:

```
        myAttribute:
          description: this is a ENUM            
          type: string
          enum:
          - MOVE2STOCK
          - MOVE2SHELF
          - KEEP
```

##### Generation Details

Java 17, Gradle build.

##### Steps to reproduce

Add ENUM attribute to the spec that has numbers in the attribute name.
Generate java model using openapi generator 7.7.0.
Look into the source code generated, the ENUM attribute names will have an "_" after the number.

For example:

```
  public enum MyAttributeEnum {
    MOVE2_STOCK("MOVE2STOCK"),
    MOVE2_SHELF("MOVE2SHELF"),
    KEEP("KEEP"),
```
