### ISSUE TITLE
[java-micronaut-client] Add @JsonProperty anotation to enums

### ISSUE THREAD

**Issue by leosprikryl** [OpenAPITools/openapi-generator#19131]
##### Description

I use java-micronaut-client generator to generate Micronaut HTTP Client. I want to reuse the generated enums in the DTOs that are returned by my server. 

The generated enum looks like this:

```java
public enum SurveyAddressType {
    DOMAIN("domain"),
    PATH("path");

    private String value;

    SurveyAddressType(String value) {
        this.value = value;
    }

    @JsonValue
    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }

    @JsonCreator
    public static SurveyAddressType fromValue(String value) {
        for (SurveyAddressType b : SurveyAddressType.values()) {
            if (b.value.equals(value)) {
                return b;
            }
        }
        throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
}
```

If I use this enum in my DTO, the generated OpenAPI documentation is incorrect - the `@JsonValue` is not honored. So the generated type looks like this:

```yaml
    SurveyAddressType:
      type: string
      description: Gets or Sets SurveyAddressType
      enum:
      - DOMAIN
      - PATH
```

Instead of this:

```yaml
    SurveyAddressType:
      type: string
      description: Gets or Sets SurveyAddressType
      enum:
      - domain
      - path
```

Issue https://github.com/micronaut-projects/micronaut-openapi/issues/471 explains that it is impossible to use `@JsonValue` when generating OpenAPI documentation in Micronaut. It suggest using `@JsonProperty` as a workaround.

I modified the mustache template to generate the JsonProperty annotation and it fixed my problem.

The generated enum than looks like this:

```java
public enum SurveyAddressType {
    @JsonProperty("domain")
    DOMAIN("domain"),
    @JsonProperty("path")
    PATH("path");

    private String value;

    SurveyAddressType(String value) {
        this.value = value;
    }

    @JsonValue
    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }

    @JsonCreator
    public static SurveyAddressType fromValue(String value) {
        for (SurveyAddressType b : SurveyAddressType.values()) {
            if (b.value.equals(value)) {
                return b;
            }
        }
        throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
}

```

 It is safe to add that annotation every time when Jackson is used in my opinion. 

##### openapi-generator version

7.7.0

##### Suggest a fix/enhancement

I have a fixed mustache template in my project. I can make a PR if this suggestion makes sense.
