### ISSUE TITLE
[BUG] anyOf causes incorrect import paths - openapi spec v3.0.0

### ISSUE THREAD

**Issue by smasala** [OpenAPITools/openapi-generator#1913]
##### Description

When using `$ref` with `nullable` and `anyOf` the generated output is incorrect in the sense that the imported path and definition name is prefixed with the key `anyOf`.

```typescript
import { AnyOfRuleDefinition } from './anyOfRuleDefinition';    // ruleDefinition.ts is generated not anyOfRuleDefinition.ts


export interface CustomRule { 
    ruleId?: string | null;
    definition?: AnyOfRuleDefinition | null;
}

```

##### openapi-generator version

`4.0.0-beta` and `latest/master`

##### OpenAPI declaration file content or url

```yaml
{
  "openapi": "3.0.0",
  "info": {
    "title": "My Service",
    "version": "0.0.1 alpha"
  },
  "paths": {
    "/abc": {
      "get": {
        "responses": {
          "200": {
            "description": "successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/EnvelopeOfRules"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "EnvelopeOfRules": {
        "title": "Envelope«Rules»",
        "type": "object",
        "properties": {
          "payload": {
            "$ref": "#/components/schemas/Rule"
          }
        }
      },
      "RuleDefinition": {
        "required": [
          "value"
        ],
        "type": "object",
        "properties": {
          "value": {
            "type": "string",
            "format": "uuid",
            "nullable": true
          }
        }
      },
      "Rule": {
        "properties": {
          "myCustomRules": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/CustomRule"
            }
          }
        }
      },
      "CustomRule": {
        "properties": {
          "ruleId": {
            "type": "string",
            "format": "uuid",
            "nullable": true
          },
          "definition": {
            "nullable": true,
            "anyOf": [
              {
                "$ref": "#/components/schemas/RuleDefinition"
              }
            ]
          }
        }
      }
    }
  }
}
```

##### Command line used for generation

```shell
java -jar modules\openapi-generator-cli\target\openapi-generator-cli.jar generate -i openapi.json -g typescript-angular -o C:\temp --skip-validate-spec --additional-properties ngVersion=7.0.0 -DsupportsES6=true -DwithInterfaces=true -DprovidedInRoot=true
```
