### ISSUE TITLE
[REQ] support for x-const extension

### ISSUE THREAD

**Issue by jmini** [OpenAPITools/openapi-generator#1916]
## Description

Sometimes in a Schema, you know that one of the property must be set to a specific value.
For those cases it would be great to be able to define the value as `x-const` extension in a Schema

### Example:

For a user creation call like this one:
```
POST /user/create
```

The Request Body looks like this:
```json
{
  "type": "User",
  "id": 132,
  "firstName": "John",
  "lastName": "Doe"
}
```

For the corresponding `UserBody` schema, you know that the `type` attribute must be set to `"User"`.

The OpenAPI Spec would looks like:

```yaml
components:
  schemas:
    UserBody:
      type: object
      properties:
         type:
          type: string
          x-const: User
        id:
          type: integer
        firstName:
          type: string
        lastName:
          type: string
```

The OpenAPI Spec is discussing about adding `const` as allowed keyword. Using it as extension in between allow to have something that works with OpenAPI v3.

## Alternative

My understanding is that the current best-practice is to define an `enum` attribute with a single value in the list.

```yaml
components:
  schemas:
    UserInput:
      type: object
      properties:
        type:
          type: string
          enum:
            - User
        id:
          type: integer
        firstName:
          type: string
        lastName:
          type: string
```

This is already supported by OpenAPI-Generator today, but has the drawback that the type needs explicitly to be set:

```java
UserInput u = new UserInput();
u.setType(TypeEnum.USER);
u.setId(132);
u.setFirstName("John");
u.setLastName("Doe");
```

Swagger UI interprets this pattern correctly and display the value in the UI:

<img width="316" alt="screenshot 2019-01-15 at 14 21 23" src="https://user-images.githubusercontent.com/1222165/51183228-e5d95300-18d0-11e9-83a1-a4346930ac3b.png">

## Additional context

Related OpenAPI Spec discussions:

* https://github.com/OAI/OpenAPI-Specification/issues/1313
* https://github.com/OAI/OpenAPI-Specification/issues/681

**Comment by wing328** [comment]
@jmini the suggestion sounds good to me to start with 👍

**Comment by jmini** [comment]
I have discovered that in combination with the `default` attribute, OpenAPI-Generator is producing the expected output.

```yaml
  type:
    type: string
    enum:
    - User
    default: User
```

With the rest-assured client:

```java
User u = new User().firstName("John").lastName("Doe");

JSON j = new JSON();
String s = j.serialize(u);
```

Is producing the expected output:

```json
{"type":"User","firstName":"John","lastName":"Doe"}
```

I think there is no need to introduce a new extension for this.


This issue can be closed for now, as I have a way to solve my requirement.
