### ISSUE TITLE
[BUG] [JAVA] Generator incorrectly altering enum values 

### ISSUE THREAD

**Issue by daoudsleiman** [OpenAPITools/openapi-generator#19204]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ ] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

There are 2 places where i observed this bug. One of which was with an array of `camelCase` values being changed to `snake_case` and the other with an enum value that contains a number.

S4A -> S4_A but expected S4A
or  
middleAgeFemale -> MIDDLE_AGE_FEMALE but expected MIDDLEAGEFEMALE

##### openapi-generator version

version >7.4.0. This issue does not occur in 7.4.0 

##### OpenAPI declaration file content or url

```yaml
    Schema1
      type: string
      enum:
        - S4A
        - ENUM_VALUE_ONE
        - ENUM_VALUE_TWO
        - ENUM_VALUE_THREE
```
or

```yaml
    Schema1:
      type: string
      example: "middleAgeFemale"
      enum:
        - "middleAgeFemale"
        - "middleAgeMale"
        - "seniorFemale"
        - "seniorMale"
        - "teenageBoy"
        - "teenageGirl"
        - "youngAdultFemale"
        - "youngAdultMale"
```

##### Generation Details

Java OpenAPI Generator in Spring Boot application

##### Steps to reproduce

1. Create a schema with an enum value of type string. 
2. Include a number in one of the enum values or create camelCase values only
3. run the code generator
4. results for the number will look like this:
S4A -> S4_A but expected S4A
or  
middleAgeFemale -> MIDDLE_AGE_FEMALE but expected MIDDLEAGEFEMALE
