### ISSUE TITLE
[BUG] [typescript-axios] allOf is not compatible with enum query params

### ISSUE THREAD

**Issue by s-xu-wafios** [OpenAPITools/openapi-generator#19247]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [✅ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [✅ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ ✅] Have you searched for related issues/PRs?
- [ ✅] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description
When I use "allOf" in a query parameter (enum), the generated "AxiosParamCreator" uses the enum value in a wrong manner.

##### openapi-generator version

7.7.0

##### OpenAPI declaration file content or url

The following definition will cause the error
```yaml
CustomFieldTypeEnum:
  type: string
  enum:
    - asset
    - work_order
    - spare_part

CustomFieldsTypeQuery:
  name: type
  in: query
  description: Custom Field Type to filter, possible values are in schema CustomFieldTypeEnum
  schema:
    allOf:
      - $ref: ../../enums/CustomFieldTypeEnum.yaml
      - example:
          asset

get:
  tags:
    - Custom Fields
  summary: Fetch custom fields
  description: Fetch custom fields
  operationId: fetchCustomFields
  parameters:
    - $ref: ../components/parameters/custom-fields/CustomFieldsTypeQuery.yaml
```
  -->

##### Generation Details

generate `
-g typescript-axios `
-i C:\Visualstudio\connectavo-api-cmms-openapi\openapi-api-cmms-v2\openapi-api-cmms-bundled.yaml `
-o C:\Visualstudio\experiment\v2-typescript-axios `
--additional-properties=npmName=v2-axios `
--additional-properties=npmVersion=0.0.0-alpha

The code would be generated:

```typescript
            if (type !== undefined) {
                for (const [key, value] of Object.entries(type)) {
                    localVarQueryParameter[key] = value;
                }
            }
```

When the user calls the method and passes in `CustomFieldTypeEnum.WorkOrder`, the code above will split each character in the enum and result in `{0=w&1=o&2=r&3=k&4=_&5=o&6=r&7=d&8=e&9=r}`

##### Steps to reproduce
Call the generated method by running:
```typescript
      const customFieldsApi = new CustomFieldsApi(config);
      customFieldsApi
        .fetchCustomFields(CustomFieldTypeEnum.WorkOrder)
```
It will generate a wrong request UR (see following screenshot)

![image](https://github.com/user-attachments/assets/752fc84b-52e2-4a35-99db-98b2adeb1a0e)

##### Suggest a fix

In the generate code, the enum should be generate in the same way (as if "allOf" was not being used):

```typescript
            if (type !== undefined) {
                localVarQueryParameter['type'] = type;
            }
```
