### ISSUE TITLE
[BUG] OneOf not working with null

### ISSUE THREAD

**Issue by devhl-labs** [OpenAPITools/openapi-generator#19258]
Generating this client results in bad output. The type is showing as OneOf when it should be ApplicationTypes.

![image](https://github.com/user-attachments/assets/96a1713a-198c-4728-b9c0-9f854bf64f85)

```yaml
generatorName: csharp
library: generichost
outputDir: 'C:\Users\devhl\repos\openapi-generator-sample-output\Discord\generated'
inputSpec: 'https://raw.githubusercontent.com/discord/discord-api-spec/main/specs/openapi.json'
additionalProperties:
  modelPropertySorting: default
  operationParameterSorting: default

```

The model looks like this

```json
      "BasicApplicationResponse": {
        "type": "object",
        "properties": {
          ...
          "type": {
            "oneOf": [
              {
                "type": "null"
              },
              {
                "$ref": "#/components/schemas/ApplicationTypes"
              }
            ]
          },
```

It looks like the issue starts in the DefaultCodegen, but I don't see an easy way to fix it.
![image](https://github.com/user-attachments/assets/610b0e13-c52b-449b-bf52-d47fc643a3a8)

#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))
