### ISSUE TITLE
[BUG] Helidon MP generators incorrect apply `@Pattern` to `byte[]` property

### ISSUE THREAD

**Issue by tjquinno** [OpenAPITools/openapi-generator#19345]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description
The Helidon MP generators incorrectly add a `@Pattern` annotation to a property of type `byte[]` whereas `@Pattern` only applies to `String`.

This causes runtime errors.

##### openapi-generator version
7.7.0

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.0
servers:
  - url: 'http://format.helidon.io:8080/format'
info:
  description: >-
    This spec is mainly for testing Petstore server and contains fake endpoints,
    models. Please do not use this for any other purpose. For this sample, you can use the api key
    `special-key` to test the authorization filters. Special characters: "
    \
  version: 1.0.0
  title: OpenAPI Formatter
  license:
    name: Apache-2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: format
    description: Format tester
paths:
  /format:
    get:
      operationId: simple
      responses:
        "200":
          content: {}
          description: success
      tags:
        - format

components:
  schemas:
    format_test:
      properties:
        byte:
          format: byte
          pattern: "^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$"
          type: string
```

##### Generation Details
Here is the generation set-up in the project's automated sample generation format for Helidon v3:
```yaml
generatorName: java-helidon-server
library: mp
outputDir: samples/server/others/java-helidon-server/v3/mp-format-test
inputSpec: modules/openapi-generator/src/test/resources/3_0/helidon/format-test.yaml
templateDir: modules/openapi-generator/src/main/resources/java-helidon/server
additionalProperties:
  helidonVersion: 3.2.7
  artifactId: format-helidon-server-mp
  hideGenerationTimestamp: "true"
  fullProject: "true"
```

And for Helidon v4:
```yaml
generatorName: java-helidon-server
library: mp
outputDir: samples/server/others/java-helidon-server/v4/mp-format-test
inputSpec: modules/openapi-generator/src/test/resources/3_0/helidon/format-test.yaml
templateDir: modules/openapi-generator/src/main/resources/java-helidon/server
additionalProperties:
  helidonVersion: 4.0.11
  artifactId: format-helidon-server-mp
  hideGenerationTimestamp: "true"
  fullProject: "true"
```

##### Steps to reproduce
1. Add the two above configuration yaml files as `bin/configs/java-helidon-server-mp-X_format_test.yaml` where the `X` in the middle is 3 for the first yaml file and 4 for the second. 
2. Run `./bin/generate-samples.sh ./bin/configs/java-helidon-server-mp_3_format_test.yaml ./bin/configs/java-helidon-server-mp_4_format_test.yaml`. 
3. `cat samples/server/others/java-helidon-server/v3/mp-format-test/src/main/java/org/openapitools/server/model/FormatTest.java` and see the `@Pattern` annotation on `getByte()`.
4. Repeat in `v4` instead of `v3`.

##### Related issues/PRs
See also #7153

##### Suggest a fix
Same fix as in the referenced PR.
