### ISSUE TITLE
[BUG][Go] Invalid code generated for default values of array parameters

### ISSUE THREAD

**Issue by ctreatma** [OpenAPITools/openapi-generator#19394]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ ] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Given a parameter of type array with a default value defined, the Go generator produces invalid code:

```go
else {
    var defaultValue []string = [port, virtual_network]
    r.include = &defaultValue
}
```

A valid form of the above code would look like this:

```go
else {
    var defaultValue []string = []string{"port", "virtual_network"}
    r.include = &defaultValue
}
```

##### openapi-generator version

v7.8.0, but this issue was introduced by https://github.com/OpenAPITools/openapi-generator/pull/15127 and has existed since roughly v7.0.1.

##### OpenAPI declaration file content or url

```yaml
  - in: query
    name: include
    schema:
      default:
      - port
      - virtual_network
      items:
        type: string
      type: array
    style: form
```
