### ISSUE TITLE
[BUG] [typescript-axios] oneOf leads to NULL_SCHEMA_ERR while generating interface

### ISSUE THREAD

**Issue by SyedAhkam** [OpenAPITools/openapi-generator#19552]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Using oneOf in the schema and generating code using `typescript-axios` generator leads to it injecting `NULL_SCHEMA_ERR` in the interface declaration.

Moreover, it sends a warn log message:

```
[[rootLedger] assets/openapi/rootledger.yaml] [main] WARN  o.o.codegen.DefaultCodegen - Null schema found. Default type to `NULL_SCHEMA_ERR`
```

##### openapi-generator version

7.8.0 stable

##### OpenAPI declaration file content or url

```
LedgerFilterBody:
      type: object
      oneOf:
        - required:
            - ledgerId
          properties:
            ledgerId:
              type: string
              description: Filter by ledger ID.
              example: "10120323"
        - required:
            - ledgerName
          properties:
            ledgerName:
              type: string
              description: Filter by ledger name.
              example: "myledger"
```

##### Generation Details

```sh
{
  "$schema": "./node_modules/@openapitools/openapi-generator-cli/config.schema.json",
  "spaces": 2,
  "generator-cli": {
    "version": "7.8.0",
    "generators": {
      "rootLedger": {
        "generatorName": "typescript-axios",
        "inputSpec": "assets/openapi/rootledger.yaml",
        "output": "src/gen/rootledger",
        "additionalProperties": {
          "supportsES6": "true",
          "withInterfaces": true
        }
      }
    }
  }
}
```

Generates a problematic interface:

```ts
/**
 * 
 * @export
 * @interface LedgerFilterBody
 */
export interface LedgerFilterBody {
    [key: string]: NULL_SCHEMA_ERR; // -- why????

}
```

This leads to a build error because `NULL_SCHEMA_ERR` isn't defined.

##### Steps to reproduce

1. Create a schema file containing LedgerFilterBody (can probably copy-paste)
2. Try to generate code using above config.

##### Related issues/PRs

Found a few, but none of them lead to `NULL_SCHEMA_ERR`

##### Hint

If I restructure my schema like below, it starts generating code fine:

```yaml
LedgerFilterBody:
  type: object
  properties:
    ledgerId:
      type: string
      nullable: true
      description: Filter by ledger ID.
    ledgerName:
      type: string
      nullable: true
      description: Filter by ledger name.
  anyOf:
    - required: [ledgerId]
    - required: [ledgerName]
```

```ts
/**
 * 
 * @export
 * @interface LedgerFilterBody
 */
export interface LedgerFilterBody {
    /**
     * Filter by ledger ID.
     * @type {string}
     * @memberof LedgerFilterBody
     */
    'ledgerId'?: string | null;
    /**
     * Filter by ledger name.
     * @type {string}
     * @memberof LedgerFilterBody
     */
    'ledgerName'?: string | null;
}
```
