### ISSUE TITLE
[BUG] Description

### ISSUE THREAD

**Issue by veqryn** [OpenAPITools/openapi-generator#19596]
#### Bug Report Checklist
- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description
I have an OpenAPI v2 yaml that is being converted to v3 by openapi-generator-cli, and it ends up changing the behavior of my models from allowing any freeform additional properties of any type, to only allowing properties of type object.
Basically, it should be treating `additionalProperties: {}` just like it treats `additionalProperties: true`, but instead it converts `additionalProperties: {}` incorrectly.

##### openapi-generator version
v7.8.0

##### OpenAPI declaration file content or url
My [openapi v2 yaml](https://github.com/veqryn/awesome-go-api/blob/b7251b13af2bad90c593302d83036b5dac6a1149/protobufv3/openapiv2/gen/awesome.swagger.yaml#L147) includes:
```yaml
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
```

##### Generation Details
`openapi-generator generate -i ./awesome.swagger.yaml -g openapi-yaml -o ./openapiv3`

This is converted by openapi-generator into this yaml:
```yaml
components:
  schemas:
    protobufAny:
      additionalProperties:
        type: object
      properties:
        '@type':
          type: string
      type: object
```

Instead it should be generating this following:
```yaml
components:
  schemas:
    protobufAny:
      additionalProperties: true
      properties:
        '@type':
          type: string
      type: object
```

##### Steps to reproduce
openapi-generator generate -i ./awesome.swagger.yaml -g openapi-yaml -o ./openapiv3
Using this [openapi v2 yaml](https://github.com/veqryn/awesome-go-api/blob/b7251b13af2bad90c593302d83036b5dac6a1149/protobufv3/openapiv2/gen/awesome.swagger.yaml)

##### Suggest a fix
This should be generated instead:
```yaml
components:
  schemas:
    protobufAny:
      additionalProperties: true
      properties:
        '@type':
          type: string
      type: object
```
