### ISSUE TITLE
The model cannot be created. If the properties section of the object corresponding to the model in the yaml file is empty ?

### ISSUE THREAD

**Issue by haliltprkk** [OpenAPITools/openapi-generator#19610]
##### Description

The model is not created while using the `Kotlin` generator if properties is empty in the yaml file, and For the models using this object assigned as `kotlin.Any`, For example,

Created model ⤵️
```
data class RandomRequest(
    @SerializedName("currency") val currency: kotlin.Any,
    .
    .
    .
)

```
yaml ⤵️
```
components:
  schemas:
    Currency:
      type: object
      description: |
        This is an empty class map it as you wish
```

But if I add a properties for the yaml object it gets created without an error, For example,

Created model ⤵️
```
data class RandomRequest(
    @SerializedName("currency") val currency: Currency,
    .
    .
    .
)

```
yaml ⤵️
```
components:
  schemas:
    Currency:
      type: object
      properties:
        amount:
          type: number
      description: |
        This is an empty class map it as you wish
```

**it should be represented as an object in the yaml file cause different clients want to map it as they wish by using `typeMappings`.**

##### openapi-generator version

classpath "org.openapitools:openapi-generator-gradle-plugin:7.5.0" (But its same with the v7.8.0 as well)

**Comment by Shmalikov** [comment]
I am experience same behaviour using python generator.

**Comment by haliltprkk** [comment]
btw it was working with the **swaggerCodegen** with following yaml ⤵️

```
definitions:
  Currency:
    type: object
    description: |
      This is an empty class map it as you wish
```
