### ISSUE TITLE
[REQ][Java][Spring] Add "@Deprecated" annotation to enum value in java code if enum value is deprecated in contract

### ISSUE THREAD

**Issue by jorgerod** [OpenAPITools/openapi-generator#19615]
### Is your feature request related to a problem? Please describe.

I would like to propose an improvement for the generated java sources based on the API contract.

I think it would be very interesting to give the possibility to add the `@Deprecated` annotation to an enum value.

## Describe the solution you'd like

For this, you could add a new extension, e.g. x-deprecated and add the value to deprecated.

```yml
    SaleBasePeriodType:
      type: string
      enum:
        - ACCUMULATED_CAMPAIGN
        - YESTERDAY
        - FISCAL_YEAR
        - LAST_FISCAL_YEAR
      x-deprecated: # new custom extension
        - ACCUMULATED_CAMPAIGN
```

Desired code:
```java
public enum SaleBasePeriodTypeDTO {

  @Deprecated // <- annotation added
  ACCUMULATED_CAMPAIGN("ACCUMULATED_CAMPAIGN"),

  YESTERDAY("YESTERDAY"),

  FISCAL_YEAR("FISCAL_YEAR"),

  LAST_FISCAL_YEAR("LAST_FISCAL_YEAR");

  private String value;

  SaleBasePeriodTypeDTO(String value) {
    this.value = value;
  }
```
