### ISSUE TITLE
[BUG][JAVA] Enum array are no longer validated

### ISSUE THREAD

**Issue by hqrd** [OpenAPITools/openapi-generator#19798]
##### Description

For enum array, the use of validation field doesn't add the validation to the java class.

For example, this
```yml
closing_days:
  type: array
  minItems: 1
  items:
    type: string
    enum: [ MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY, SUNDAY ]
```
Does not add a validation `@Size(min = 1)` annotation with useBeanValidation.

In fact, this looks like since https://github.com/OpenAPITools/openapi-generator/pull/18658, any validation is skipped for enums.

##### openapi-generator version

7.8.0 

##### Related issues/PRs

https://github.com/OpenAPITools/openapi-generator/pull/18658
