### ISSUE TITLE
[REQ] Add Authorize and bearer roles/scopes support to aspnetcore

### ISSUE THREAD

**Issue by MBcom** [OpenAPITools/openapi-generator#1983]
### Is your feature request related to a problem? Please describe.
* on generating the aspnetcore server package - (bearer) authentication are ignored and roles/scopes specfied for each operation are ignored too
* it would be time saving if the generator would generate the missing annotations

## Describe the solution you'd like

* add an `[Authorize]` Annotation for each route
* if there is an bearer auth (e.g. with JWT) or an OATUH authentication then annotate with `[Authorize(Roles = "...")]`

## Describe alternatives you've considered

-

## Additional context

see the linked pull request for my suggestions

**Comment by tmakin** [comment]
@MBcom I'm trying to implement Role based authorization via the `aspnetcore` generator. However, I can't work out how to define the scopes for this mustache block
```
{{#isBasicBearer}}
        [Authorize{{#scopes}}{{#-first}}(Roles = "{{/-first}}{{scope}}{{^-last}},{{/-last}}{{#-last}}"){{/-last}}{{/scopes}}]
{{/isBasicBearer}}
```
Can you point me towards a working examaple?

**Comment by MBcom** [comment]
@tmakin you can add the needed scopes in the security part of each route as an array  
e.g.
```yaml
delete:
      summary: Remove a sth
      operationId: removeSth
      security:
          - bearerAuth: #<- the name of your security scheme
            - scope1
            - scope2
            ....
```  
this should generate the following annotated route
```yaml
        [HttpDelete]
        [Route("/api/v1/example")]
        [Authorize(Roles = "scope1,scope2")]
        [ValidateModelState]
        [SwaggerOperation("removeSth")]
        public virtual IActionResult RemoveSth() ...
```
I did not tested it again with upstream version - so let me know if you are experiencing any errors
