### ISSUE TITLE
[REQ][Java][Spring] Support BigInteger type

### ISSUE THREAD

**Issue by jorgerod** [OpenAPITools/openapi-generator#19956]
Hi

Currently to support the **BigInteger** type you have to do it by defining your own typeMapping.

![image](https://github.com/user-attachments/assets/5b03e0f6-e20a-4c56-b192-74f145cc9e94)

Is there any reason why BigInteger is not supported without doing that? For example, Bigdecimal is supported.

Maybe it could be defined like this:

```yml
          schema:
            type: integer
            format: bigint
```

Thank you
