### ISSUE TITLE
[BUG] Functions described in documentation but not present in code

### ISSUE THREAD

**Issue by smutel** [OpenAPITools/openapi-generator#20007]
[BUG] Functions described in documentation but not present in code

#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

After generation some functions are explained in the documentation but they does not exist in the code. 
Unfortunately I need these functions.

_After generation:_

```
$ grep -R SetDefaultNil docs/*
docs/CustomField.md:### SetDefaultNil
docs/CustomField.md:`func (o *CustomField) SetDefaultNil(b bool)`
docs/CustomField.md: SetDefaultNil sets the value for Default to be an explicit nil
docs/CustomFieldRequest.md:### SetDefaultNil
docs/CustomFieldRequest.md:`func (o *CustomFieldRequest) SetDefaultNil(b bool)`
docs/CustomFieldRequest.md: SetDefaultNil sets the value for Default to be an explicit nil
docs/PatchedWritableCustomFieldRequest.md:### SetDefaultNil
docs/PatchedWritableCustomFieldRequest.md:`func (o *PatchedWritableCustomFieldRequest) SetDefaultNil(b bool)`
docs/PatchedWritableCustomFieldRequest.md: SetDefaultNil sets the value for Default to be an explicit nil
docs/WritableCustomFieldRequest.md:### SetDefaultNil
docs/WritableCustomFieldRequest.md:`func (o *WritableCustomFieldRequest) SetDefaultNil(b bool)`
docs/WritableCustomFieldRequest.md: SetDefaultNil sets the value for Default to be an explicit nil
$ grep -R SetDefaultNil *.go
$
```
##### openapi-generator version

`v7.9.0`

I don't think that it's a regression.

##### OpenAPI declaration file content or url

```yaml
default:                                                                                    
  nullable: true                                                                            
  description: Default value for the field (must be a JSON value). Encapsulate strings with double quotes (e.g. "Foo").
```

Complete file: https://raw.githubusercontent.com/netbox-community/go-netbox/refs/tags/v4.0.3-0/api/openapi.yaml

##### Steps to reproduce

```
$ git clone git@github.com:netbox-community/go-netbox.git
$ git checkout v4.0.3-0
$ make
$ make build
```
##### Related issues/PRs

I tried to look at the current issues but there is so much issues, perhaps some of them are related to this issue ...

##### Suggest a fix

Not able to fix the issue for the moment.
