### ISSUE TITLE
[BUG] [python-fastapi] Generated requirements.txt does not build on Python 3.13 due to outdated dependencies

### ISSUE THREAD

**Issue by micolous** [OpenAPITools/openapi-generator#20058]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

The `python-fastapi` module's generated `requirements.txt` pins some direct and transitive dependencies to old versions.

This causes `pip` to select `pydantic-core` (2.18.4) and `uvloop` (0.19.0), which do not build on Python 3.13.

##### openapi-generator version

7.9.0

##### OpenAPI declaration file content or url

https://raw.githubusercontent.com/OpenAPITools/openapi-generator/refs/heads/master/modules/openapi-generator/src/test/resources/3_0/python-fastapi/petstore.yaml

##### Generation Details

```yaml
# petstore.yaml
additionalProperties:
  generateSourceCodeOnly: true
globalProperties:
  apiDocs: false
  modelDocs: false
  apiTests: false
  modelTests: false
inputSpec: https://raw.githubusercontent.com/OpenAPITools/openapi-generator/refs/heads/master/modules/openapi-generator/src/test/resources/3_0/python-fastapi/petstore.yaml
outputDir: out
generatorName: python-fastapi
```

##### Steps to reproduce

Install Python 3.13. Then run:

```sh
openapi-generator batch petstore.yaml
cd out
python3.13 -m venv venv
. ./venv/bin/activate
pip install -r requirements.txt
```

Alternatively, you could use [the already-generated `requirements.txt` in the OpenAPI Generator samples directory](https://github.com/OpenAPITools/openapi-generator/blob/2c38d0de35dbad9b0b7ea743601aa272c8deaf5a/samples/server/petstore/python-fastapi/requirements.txt), because that has old dependencies too.

##### Suggest a fix

In https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/python-fastapi/requirements.mustache:

* Replace `uvloop==0.19.0` with `uvloop>=0.19.0`
* Remove `typing-extensions==4.8.0`. This allows `pip` to select `pydantic-core` 2.23.4, which supports Python 3.13.
