### ISSUE TITLE
[BUG][JAVA][webclient] query param of type array handled as non explode

### ISSUE THREAD

**Issue by virgilsb** [OpenAPITools/openapi-generator#20127]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Wrapping query params in a containing object so that the generated client method only has one param instead of X params, but when the query param is an array, the generated code always builds a CSV with the contents of the array, instead of handling it as "multi".

##### openapi-generator version

It's not a regression. Wrapping object were supported after 7.2.0 thanks to [this PR](https://github.com/OpenAPITools/openapi-generator/pull/17441) but it is not working correctly when having array properties.

##### OpenAPI declaration file content or url

```yaml
paths:
  /api/search:
    get:
      operationId: Search
      parameters:
        - name: object-param
          in: query
          required: true
          schema:
            type: object
            properties:
              someArray:
                type: array
                items:
                  type: string
```
- The example is an adaptation from `modules/openapi-generator/src/test/resources/3_0/java/explode-query-parameter.yaml`
##### Generation Details

Java language, WebClient library, but also with RestTemplate.

##### Steps to reproduce

By adapting the upper mentioned file, execute the following test
`JavaClientCodegenTest.shouldProperlyExplodeWebClientQueryParameters`
adding
```
.bodyContainsLines("queryParams.putAll(apiClient.parameterToMultiValueMap(ApiClient.CollectionFormat.valueOf(\"multi\".toUpperCase(Locale.ROOT)), \"someArray\"," + " objectParam.getSomeArray()));");
```
Expected would be to handle the array query param as "multi" since explode defaults to true.
Actual: it's treated as csv because the collectionFormat param is null.

##### Related issues/PRs

https://github.com/OpenAPITools/openapi-generator/pull/17441
