### ISSUE TITLE
[BUG][Python] python-fastapi 7.9.0 generator fails to generate types for enum schemas

### ISSUE THREAD

**Issue by al3ad** [OpenAPITools/openapi-generator#20151]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### openapi-generator version

7.9.0

##### OpenAPI declaration file content or url

```yaml
components:
  schemas:
    uuid:
      title: UUID
      type: string
    contentformat:
      title: Content Format
      type: string
      description: Identifies the content format for a flow or source using a URN string.
      enum:
        - 'urn:x-nmos:format:video'
        - 'urn:x-nmos:format:audio'
        - 'urn:x-nmos:format:data'
        - 'urn:x-nmos:format:multi'
```

##### Generation Details
This is the output I get in the functions generated using `contentformat` schema:
```
format:  = Query(None, description="Filter on flow format.", alias="format"),
```
whereas I would expect
```
format: str = Query(None, description="Filter on flow format.", alias="format"),
```.

It also doesn't declare the type anywhere else in the generated function. If you get rid of the enum property from the schema it generates as expected.
##### Steps to reproduce
```
build-server-local-fastapi:
	docker run --user ${USER}:${GROUP} --rm \
                   -v ${PWD}:/local openapitools/openapi-generator-cli:v${GEN_VER} generate \
				   --additional-properties=apiNameSuffix=controller_impl \
                   -t /local/.templates/7.9.0/python_fastapi/.openapi-generator-server/ \
                   -i /local/openapi.yaml \
                   -g python-fastapi \
                   -o /local/python_fastapi/
```
