### ISSUE TITLE
[BUG][Python] python-fastapi 7.9.0 generates wrong imports

### ISSUE THREAD

**Issue by al3ad** [OpenAPITools/openapi-generator#20153]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

An import is generated that does not exist.

##### openapi-generator version

7.9.0

##### OpenAPI declaration file content or url

The code for the yaml spec can be found here: https://github.com/bbc/tams/tree/main/api

##### Generation Details

This is a snippet of the file it generates with the relevant to the issue imports:
```
from pydantic import ConfigDict, Field
from openapi_server.models.object import object
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class MediaBucketObjectStore(object):
    ...
```
The issue is the imported `object`, which doesn't exist.

I believe the generated file should be this:
```
from pydantic import ConfigDict, Field, BaseModel
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class MediaBucketObjectStore(BaseModel):
    ...
```

##### Steps to reproduce

```
build-server-local-fastapi:
	docker run --user ${USER}:${GROUP} --rm \
                   -v ${PWD}:/local openapitools/openapi-generator-cli:v${GEN_VER} generate \
				   --additional-properties=apiNameSuffix=controller_impl \
                   -t /local/.templates/7.9.0/python_fastapi/.openapi-generator-server/ \
                   -i /local/openapi.yaml \
                   -g python-fastapi \
                   -o /local/python_fastapi/
```

**Comment by claudiadpp** [comment]
Hi, I have the same problem. 

**summary**

When generating Python FastAPI server code with OpenAPI Generator, the generated models import object from a non-existent module and inherit from object


**openapi-generator version**

v7.15.0
Generator: python-fastapi

**description**
For the API specification 
```
    Configuration:
      type: object
      additionalProperties: true
      properties:
        acceptedOutputModes:
          type: array
          maxItems: 100
          description: "Accepted output modes"
          items:
            type: string
            maxLength: 100
            example: "text"
            enum:
              - "text"
              - "text/plain"
```
The generated code is 

```
from pydantic import ConfigDict, Field, field_validator
from <module_name>.models.object import object

class Configuration(object):
    ...
```

The generated could should be

```
from pydantic import ConfigDict, Field, field_validator, BaseModel

class Configuration(BaseModel):
    ...
```
where `BaseModel` is added to pydantic import and the `object` import is removed.
