### ISSUE TITLE
[BUG] Dart. Null field for propertyName when discriminator used in deserializer

### ISSUE THREAD

**Issue by andreykud** [OpenAPITools/openapi-generator#20177]
#### Bug Report Checklist

- [+] Have you provided a full/minimal spec to reproduce the issue?
- [+] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [+] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [+] Have you searched for related issues/PRs?
- [+] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When discriminator used in api specification it seems common fields for inherited objects not filled in dart generator implementation

##### openapi-generator version

openapi_generator: ^6.0.0
openapi_generator_annotations: ^6.0.0

##### OpenAPI declaration file content or url

If you post the code inline, please wrap it with
test.yml:
```yaml
type: object
oneOf:
  - $ref: './a.yml'
  - $ref: './b.yml'
discriminator:
  propertyName: type
required:
  - type
properties:
  type:
    $ref: './testType.yml'
```

testType.yml:
```yaml
type: string
enum:
  - a
  - b
```

a.yml:
```yaml
type: object
properties:
  optionA1:
    type: string
```

b.yml:
```yaml
type: object
properties:
  optionB1:
    type: string
```

##### Steps to reproduce

create something like this object definition and try to deserialize simple string:

{"type": "a", "optionA1":"optionA1"}

##### Suggest a fix

It seems generated dart code does not calls method named '_deserializeProperties' in method 'deserialize' (in test.dart).
So in generated test.g.dart when _build calls it throws an Exception, because type was not parsed and it is null.
