### ISSUE TITLE
[BUG] [Dart] Nullable values are still in required list, and fail on assertion in the serializer

### ISSUE THREAD

**Issue by isaac-merkos** [OpenAPITools/openapi-generator#20296]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?

##### Description

I am expecting nullable fields to allow values, my spec allows for nullable values in certain fields but when I actually run the queries I am getting an assertion error

**Comment by uchijo** [comment]
Hi, I'm facing exactly same issue.
After seeing the generated code, I figured out that it might be caused by **required but nullable** value as you mention.
The tool generates code like this in `fromJson` method:

```dart
      assert(() {
        requiredKeys.forEach((key) {
          assert(json.containsKey(key), 'Required key "SomeModel[$key]" is missing from JSON.');
          assert(json[key] != null, 'Required key "SomeModel[$key]" has a null value in JSON.'); // this code is not good. it ignores exisitence of required but nullable value.
        });
        return true;
      }());
```

I will look into generator code and see if I can fix it.

**Comment by nktknshn** [comment]
I have the same issue:

```yaml
JobOutput:
    type: object
    required:
      - description
      - companyLogo
    properties:
      description:
        type: string
      companyLogo:
        type: string
        nullable: true
```

> Required key "JobOutput[companyLogo]" has a null value in JSON
