### ISSUE TITLE
[BUG][Rust] Request trait library does not compile with keyword parameters 

### ISSUE THREAD

**Issue by ranger-ross** [OpenAPITools/openapi-generator#20329]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Function parameters are properly escaped with `r#` but with the new reqwest-trait client we introduced lifetime parameters that reused to the parameter name.
`#` is not valid in lifetime names.

Error
```
115 |     async fn find_pets_by_status<'r#type>(&self, r#type: Option<&'r#type str>) -> Result<Vec<models::Pet>, Error<FindPetsByStatusError>> {
    |                                    ^ expected one of `,`, `:`, or `>`
```

##### openapi-generator version

build from source Git Hash cc40f40eade66657c3557debb2f2f0b9d8208a7e

##### OpenAPI declaration file content or url

```yaml
# ...
  /pet/findByStatus:
    get:
      tags:
        - pet
      summary: Finds Pets by status
      description: Multiple status values can be provided with comma separated strings
      operationId: findPetsByStatus
      parameters:
        - name: type # <------- This is a Rust keyword
          in: query
          description: Status values that need to be considered for filter
          required: false
          explode: true
          schema:
            type: string
            default: available
            enum:
              - available
              - pending
              - sold
# ...
```

##### Generation Details

```yaml
generatorName: rust
library: reqwest-trait
additionalProperties:
  supportMiddleware: true
  preferUnsignedInt: true
  topLevelApiClient: true
  useBonBuilder: true
  mockall: true

```

##### Steps to reproduce

1. Create an openapi spec with query param with the name of any Rust keyword
2. Generate the client with the config above
3. Run `cargo build`

##### Suggest a fix

This can be fixed by simply replacing the `r#` with a `r_` as that is a valid lifetime name.
