### ISSUE TITLE
[BUG] Interface is typed as enum instead of string for type string with enum in typescript-nestjs

### ISSUE THREAD

**Issue by dikue** [OpenAPITools/openapi-generator#20395]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

I am using the openapi-cli tool to generate client code for typescript-nestjs application. But I have an issues with the typing of enums. They seem to be defined as string but the generated code types them as enum. Might not be a bug, but rather my lack of knowledge. 

##### openapi-generator version

7.10.0

##### OpenAPI declaration file content or url

(Link to file)[https://pastebin.com/NBpRp5U5]

```yaml
geometry:
          type: object
          properties:
            type:
              type: string
              enum:
                - Point
                - Multipoint
                - Polygon
```

##### Generation Details

openapi-generator-cli generate -g typescript-nestjs -i assets/swagger.yml  -o <output-dir> --skip-validate-spec

i had to use --skip-validate-spec, because there are some issues on the swagger definition. It's not mine it's a decleration file i got.

##### Steps to reproduce

use above commands to generate a client -> type of enum is declared as enum instead of string
