### ISSUE TITLE
[BUG] [JAVA] Missing allowed enum values of query parameters

### ISSUE THREAD

**Issue by marcomartino22** [OpenAPITools/openapi-generator#20487]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apitools.dev/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Running the following command, the interface classes created don't contain the list of allowed values of the enum parameters in query string.

`java -jar openapi-generator-cli-7.10.0.jar generate -i swaggerAnagrafe.yaml -g spring --api-package it.realeites.anagrafe.api --model-package it.realeites.anagrafe.model --group-id it.realeites.anagrafe --artifact-id APIAnagrafeRealeItes --artifact-version 1.0 -o APIAnagrafeRealeItes-SERVER --openapi-normalizer REF_AS_PARENT_IN_ALLOF=true,REFACTOR_ALLOF_WITH_PROPERTIES_ONLY=true  --skip-validate-spec --additional-properties=useSpringBoot3=true,java.version=21`

You can find below a portion of my swagger file containing a GET API with an enum query param (codiceCompagnia) and also the java code generated. As you can see the allowed values of the param codiceCompagnia (RMA and ITA) are not described in the java code.

**Java code generated**
```
    default ResponseEntity<RispostaAmministratoreCondomini> elencoCondominiV10(@NotNull @Parameter(name = "codiceCompagnia", description = "Codice della compagnia", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "codiceCompagnia", required = true) String codiceCompagnia) {
```

The right code should something like this: I have only add the string ", in = ParameterIn.QUERY,schema=@Schema(allowableValues={ "RMA", "ITA" })" after the parameter "required = true".

    public ResponseEntity<RispostaAmministratoreCondomini> elencoCondominiV10(@NotNull @Parameter(name = "codiceCompagnia", description = "Codice della compagnia", required = true, in = ParameterIn.QUERY,schema=@Schema(allowableValues={ "RMA", "ITA" })) @Valid @RequestParam(value = "codiceCompagnia", required = true) String codiceCompagnia) {

This issue does not trigger the check of the value entered in the input parameter.

##### openapi-generator version

7.11.0

##### OpenAPI declaration file content or url

```
  /condomini/v1.0:
    get:
      description: Restituisce l'elenco dei condomini associati all'amministratore
      operationId: elencoCondomini_v10
      parameters:
      - name: canale
        in: query
        description: Canale di richiamo del servizio
        required: true
        schema:
          type: string
      - name: codiceCompagnia    
        in: query
        description: Codice della compagnia
        required: true
        schema:
          type: string
          enum:
          - RMA
          - ITA
```
