### ISSUE TITLE
[BUG] JAXRS-SPEC

### ISSUE THREAD

**Issue by JM92103** [OpenAPITools/openapi-generator#20488]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apitools.dev/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ ] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When using JAXRS-SPEC, the x-enum-varnames and x-enum-descriptions do not seem to work together. 

##### openapi-generator version

7.10.0

##### OpenAPI declaration file content or url

```yaml
type: integer
format: int32
enum:
  - 1000
  - 900
  - 30
  - 20
  - 10
  - 0
x-enum-descriptions:
  - 'UNEXPECTED ERROR'
  - 'REJECT'
  - 'REFER EXCEPTION'
  - 'REFER'
  - 'REFER OVERRIDE'
  - 'NONE'
x-enum-varnames:
  - UNEXPECTED_ERROR
  - REJECT
  - REFER_EXCEPTION
  - REFER
  - REFER_OVERRIDE
  - NONE
```

##### Steps to reproduce

Using the above YAML, I would expect the generated enum to look something like
```java
public enum Severity {

    UNEXPECTED_ERROR(1000, "UNEXPECTED ERROR"),
    REJECT(900, "REJECT"),
    REFER_EXCEPTION(30, "REFER EXCEPTION"),
    REFER(20, "REFER"),
    REFER_OVERRIDE(10, "REFER OVERRIDE"),
    NONE(0, "NONE");
   
    ...
}
```
Whereas it is being generated as 
```java
public enum Severity {

  UNEXPECTED_ERROR(1000),
  REJECT(900),
  REFER_EXCEPTION(30),
  REFER(20),
  REFER_OVERRIDE(10),
  NONE(0);

...

}
```
