### ISSUE TITLE
[BUG] Invalid code generated for enums of type number for Jackson JSON-libraries: inserted BigDecimal.valueOf is invalid

### ISSUE THREAD

**Issue by wienczny** [OpenAPITools/openapi-generator#20506]
Code generation for generator java with a Jackson JSON library changed between 7.9.0 and 7.10.0 for enums. In 7.10.0 the generated code is invalid.
When an enum is type number there is an additional BigDecimal.valueOf inserted. This has been testet with serveral libraries:

affected:
* apache-httpclient
* restclient 
* native

not affected
* okhttp-gson

Degression is between 7.9.0 and 7.10.0

An example can be found here:
https://developer.dhl.com/sites/default/files/2025-01/dpdhl-express-api-2.12.1_swagger_0.yaml

```yaml
        outputImageProperties:
          description: 'Here you can modify label, waybillDoc, invoice and shipment receipt properties'
          type: object
          minProperties: 1
          properties:
            printerDPI:
              description: >-
                Printer DPI Resolution for X-axis and Y-axis (in DPI) for transport
                label and waybill document output
              type: number
              enum:
                - 200
                - 300
              example: 300
```

In 7.10.0 this generates to

```java
  public enum PrinterDPIEnum {
    NUMBER_200(BigDecimal.valueOf(new BigDecimal("200"))),
    
    NUMBER_300(BigDecimal.valueOf(new BigDecimal("300")));
```

In 7.9.0 this used to be:

```java
  public enum PrinterDPIEnum {
    NUMBER_200(new BigDecimal("200")),
    
    NUMBER_300(new BigDecimal("300"));
```

##### Generation Details

```
docker run --rm -v "/tmp/foo:/local" openapitools/openapi-generator-cli:v7.10.0 generate \
                                       -i https://developer.dhl.com/sites/default/files/2025-01/dpdhl-express-api-2.12.1_swagger_0.yaml \
                                       -g java --library=native \
                                       -o /local/out/java
```
