### ISSUE TITLE
[BUG][SPRING] Wrong java import in generated class

### ISSUE THREAD

**Issue by sacps001119** [OpenAPITools/openapi-generator#20609]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apitools.dev/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When the property of the main model is a other model named "File", the generator will generate the java class for the main model using `java.io.File` class instead of the class under package defined in "modelPackage". 

##### openapi-generator version

7.11.0

##### OpenAPI declaration file content or url

OpenAPI Generate Task in `build.gradle`:
```yaml
openApiGenerate {
    inputSpec = "$rootDir\\src\\main\\resources\\json\\openapi\\test-java-import-issue-openapi.json".replace('\\', '/')
    modelPackage = "test.dto"
    // JavaSpring generator with custom template - disable fluent setter methods.
    generatorName = "spring"
    templateDir = "$rootDir\\openapi-gererate-template\\JavaSpring".replace('\\', '/')
    globalProperties = [
            verbose   : "true",
            models    : "",
            apis      : "false",
            modelDocs : "false",
            modelTests: "false"
    ]
    // Spring
    configOptions = [
            dateLibrary                         : "java8-localdatetime",
            documentationProvider               : "source",
            annotationLibrary                   : "none",
            useBeanValidation                   : "true",
            useSpringBoot3                      : "true",
            generateConstructorWithAllArgs      : "false",
            generatedConstructorWithRequiredArgs: "false",
            containerDefaultToNull              : "true",
            // Add lombok annotations
            additionalModelTypeAnnotations      : "@lombok.ToString;@lombok.EqualsAndHashCode;@lombok.NoArgsConstructor;@lombok.AllArgsConstructor;@lombok.experimental.SuperBuilder(toBuilder = true)",
    ]

    openapiNormalizer = [
            REF_AS_PARENT_IN_ALLOF : "true",
    ]
}
```

The testing openapi file, generator template and output java class:
https://gist.github.com/sacps001119/a64c6ece5477358e7441283005ba7716
