### ISSUE TITLE
[BUG] [Client: C#] Extra Extensions generated causing project using openapitools/openapi-generator-cli:v7.12.0

### ISSUE THREAD

**Issue by hideintheclouds** [OpenAPITools/openapi-generator#20794]
##### Description

When generating the C# clients from a JSON OpenApi specification and using a config.yaml (using default restsharp library), extra Extensions folder is generated even though it is not configured to do so
The openapitools/openapi-generator-cli:v7.12.0 seems to have broken it.

The extra generated code is the Extensions directory with the following 3 files:
- IHttpClientBuilderExtensions.cs
- IHostBuilderExtensions.cs
- IHostBuilderExtensions.cs

Due to these extra files, the generated solution does not compile (please note that a custom/trimmed solution is generated without tests and documentation).

**The code is generated correctly using the openapitools/openapi-generator-cli:v7.11.0 docker image**

The config.yaml has the following properties:

```
generatorName: csharp
templateDir: /local/CustomTemplates/
globalProperties:
  skipFormModel: false
  modelDocs: false
  modelTests: false
  apiDocs: false
  apiTests: false
additionalProperties:
  targetFramework: net8.0
  useDateTimeOffset: true
  validatable: false
  useCollection: false
  nullableReferenceTypes: true
```

##### openapi-generator version
openapitools/openapi-generator-cli:v7.12.0
