### ISSUE TITLE
[BUG] Logic to simplify any type represented with oneof/anyof doesn't work 100%

### ISSUE THREAD

**Issue by drej1** [OpenAPITools/openapi-generator#20873]
##### Description

This bug relates to https://github.com/OpenAPITools/openapi-generator/issues/18125. The fix for the mentioned bug is working 90%, but there is a specific case, when the `integer` is not present in the `anyOf` but the `number` type is.

The `integer` type should be optional for this functionality, because:
https://swagger.io/docs/specification/data-models/data-types/
<img width="705" alt="image" src="https://github.com/OpenAPITools/openapi-generator/assets/31669116/0f7596b2-c591-4a8f-90ab-cb5263a48ff5">

I mean replacing the anyOf/oneOf with the any type should work also for:
```yaml
oneOf:
  - type: string
  - type: number
  - type: boolean
  - type: array
    items:
      type: object
  - type: object
```

##### openapi-generator version

7.5

##### Related issues/PRs

- https://github.com/OpenAPITools/openapi-generator/issues/18125
- https://github.com/OpenAPITools/openapi-generator/pull/18268

##### Suggest a fix

Make the integer type optional in the "6 sub-schemas" check.

**Comment by wing328** [comment]
any type can be represent with `anyOf` according to https://swagger.io/docs/specification/v3_0/data-models/data-types/#any-type

what about updating your openapi doc to use the suggested definition instead?

```
components:
  schemas:
    AnyValue:
      anyOf:
        - type: string
        - type: number
        - type: integer
        - type: boolean
        - type: array
          items: {}
        - type: object
```
