### ISSUE TITLE
[BUG] Java gradle.properties

### ISSUE THREAD

**Issue by Treenity** [OpenAPITools/openapi-generator#21123]
##### Description

When generating java client, it seem its not possible to use `gradleProperties` to set `gradle.properties` values.
tries with java.yaml config file, and directly as argument using CLI, nothing work

the generated gradle.properties is EMPTY.
using the `openapi-generator-cli author template -g java -o ./templates/java` and editing the gradle.properties templates, specifying this directory in my CLI command does not change anything

I'm actually using the npm library on a OSX environement

##### openapi-generator version

@openapitools/openapi-generator-cli : 2.19.1

##### OpenAPI declaration file content or url
```yaml
generatorName: java
additionalProperties:
  library: native
  dateLibrary: java8-localdatetime
  developerName: MyName
  developerEmail: "support@MyCompany.fr"
  developerOrganization: MyCompany
  developerOrganizationUrl: "https://MyCompany.fr"
  annotationLibrary: "swagger2"
  hideGenerationTimestamp: "true"
  gradleProperties:
    - "spotless_java_formatter=../format/eclipse-java-formatter-1.0.0.xml"
    - "spotless_java_importorder=../format/eclipse-java-importorder-1.0.0.importorder"
    - "spotless_gradle_formatter=../format/eclipse-groovy-formatter-1.0.0.properties"
```

##### Generation Details

using preview config file and a swagger.json i use:
` openapi-generator-cli generate -i ./dist/swagger.json -g java -o dist/clients/petstore-core-sdk-client-java -c ./src/configs/java.yaml`

Client is generated using most of the yaml settings, except `gradleProperties` which remain empty.

##### Steps to reproduce

1. use the previous yaml, or use the `gradleProperties` directly from the CLI
2. generate the client using, as example: `openapi-generator-cli generate -i ./dist/swagger.json -g java -o dist/clients/petstore-core-sdk-client-java -c ./src/configs/java.yaml`
3. look for dist/clients/petstore-core-sdk-client-java/gradle.properties content
4. it's empty, it must contain the `gradleProperties` array from the yaml, 1 item per line

##### Suggest a fix

I dont know how to fix it actually, but maybe it could be a nice idea to add it to the tests

**Comment by wing328** [comment]
what about using customized templates, e.g. -t via CLI?

**Comment by Treenity** [comment]
Hi, 

i tried, as said, but nothing:
`openapi-generator-cli author template -g java -o ./templates/java`
to get the original template, the gradle.properties file look like:
```
# This file is automatically generated by OpenAPI Generator (https://github.com/openAPITools/openapi-generator).
# To include other gradle properties as part of the code generation process, please use the `gradleProperties` option.
#
# Gradle properties reference: https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_configuration_properties
# For example, uncomment below to build for Android
#target = android

THIS IS MY OVERRIDE

{{#gradleProperties}}
{{{.}}}
{{/gradleProperties}}
```
then i used ` openapi-generator-cli generate -i ./dist/swagger.json -g java -o dist/clients/petstore-core-sdk-client-java -c ./src/configs/java.yaml -t ./templates/java`

but gradle.properties still empty, no comments, no `THIS IS MY OVERRIDE`. it seem the file is created, but that's all

**Comment by wing328** [comment]
> # To include other gradle properties as part of the code generation process, please use the `gradleProperties` option.

according to the comment, looks like you can simply use the `gradleProperties` option directly without using customized templates

**Comment by Treenity** [comment]
Hi, yeah i know, here is what i've found
using my generation command like before, i can reproduce the problem:
```yaml
additionalProperties:
  library: native
  dateLibrary: java8-localdatetime
  developerName: MyCompany
  developerEmail: "support@MyCompany.fr"
  developerOrganization: MyCompany
  developerOrganizationUrl: "https://MyCompany.fr"
  annotationLibrary: "swagger2"
  hideGenerationTimestamp: "true"
  gradleProperties: |
    spotless_java_formatter=../format/eclipse-java-formatter-1.0.0.xml
    spotless_java_importorder=../format/eclipse-java-importorder-1.0.0.importorder
    spotless_gradle_formatter=../format/eclipse-groovy-formatter-1.0.0.properties
```
result is: client is generated, code is customized etc... but NO CONTENT in gradle.properties

BUT, when i use:
```yaml
additionalProperties:
  #library: native <-- note the commented library
  dateLibrary: java8-localdatetime
  developerName: MyCompany
  developerEmail: "support@MyCompany.fr"
  developerOrganization: MyCompany
  developerOrganizationUrl: "https://MyCompany.fr"
  annotationLibrary: "swagger2"
  hideGenerationTimestamp: "true"
  gradleProperties: |
    spotless_java_formatter=../format/eclipse-java-formatter-1.0.0.xml
    spotless_java_importorder=../format/eclipse-java-importorder-1.0.0.importorder
    spotless_gradle_formatter=../format/eclipse-groovy-formatter-1.0.0.properties
```

it's working as it should.

it seem that library properties make the template ignore gradle.properties, i'm going to investigate into that
