### ISSUE TITLE
[BUG][Java] default value in referenced Enum produces corrupted code

### ISSUE THREAD

**Issue by fujigon** [OpenAPITools/openapi-generator#2127]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] What's the version of OpenAPI Generator used?
- [ ] Have you search for related issues/PRs?
- [ ] What's the actual output vs expected output?

##### Description
Refed Enum with default value causes build break in `jaxrs-jersey` generator.

##### openapi-generator version
current master (4e8599349094ebc47a38baf7a60c4e1712c268d7)

probably since c871e3bc8168c8a9cba5af413d4cc06783320a1a

Build break is a regression.
I known that old version also didn't generate a suitable output (cf https://github.com/OpenAPITools/openapi-generator/issues/1323).

##### OpenAPI declaration file content or url

bug can be reproduced with
https://github.com/fujigon/openapi-generator/commit/e80828468593eab9d614cb09861b195b04d4a413

##### Command line used for generation
re-generate samples with `bin/openapi3/jaxrs-jersey-petstore.sh` (https://github.com/fujigon/openapi-generator/commit/cab6857d908c436b78622c68335b40da727d732c)

##### Related issues/PRs

- https://github.com/OpenAPITools/openapi-generator/issues/1323

**Comment by jmini** [comment]
For me this is a duplicate of https://github.com/OpenAPITools/openapi-generator/issues/1927

With the path:
```yaml
  /change:
    get:
      tags:
        - Some
      operationId: changeGet
      parameters:
        - name: color
          in: query
          required: false
          schema:
            $ref: "#/components/schemas/BasicColor"
```

And following schema:
```yaml
    BasicColor:
      type: string
      default: Red
      enum:
        - "Red"
        - "Blue"
        - "Green"
```

With the latest `4.0.0-SNAPSHOT` the current status is that the `@DefaultValue` is generated, but it contains the value `@DefaultValue("Red")` where the enum name should be used `@DefaultValue("RED")` to match the enum value name: `org.openapitools.model.BasicColor.RED("Red")`

**Comment by fujigon** [comment]
Thanks for reply.
The problem is that 
[here](https://github.com/fujigon/openapi-generator/commit/cab6857d908c436b78622c68335b40da727d732c#r32279593) causes build break.

**Comment by jmini** [comment]
Thank you for the analysis. I knew that PR #2001 was not sufficient in some corner cases... but the situation is worse than I thought.

If you have following enum Schemas:

```yaml
components:
  schemas:
    IntEnum:
      type: integer
      format: int32
      default: 2
      enum:
        - 1
        - 2
        - 3

    LongEnum:
      type: integer
      format: int64
      default: 30
      enum:
        - 20
        - 30
        - 40

    StringEnum:
      type: string
      default: "b"
      enum:
        - "c"
        - "b"
        - "a"

    EnumWithCustomName:
      type: integer
      format: int32
      default: 2
      enum:
        - 1
        - 2
      x-enum-varnames:
        - FOO
        - BAR
```

And following schema:

```yaml
    ObjWithEnumProperties:
      type: object
      properties:
        iprop:
            $ref: "#/components/schemas/IntEnum"
        lprop:
            $ref: "#/components/schemas/LongEnum"
        sprop:
            $ref: "#/components/schemas/StringEnum"
        custom:
            $ref: "#/components/schemas/EnumWithCustomName"
```

Then only the string case is correctly managed.
I have the feeling that almost all java generator are affected by the issue.

Let me change the title of this issue.
