### ISSUE TITLE
[BUG] Vendor extensions aka custom properties not available when property type is a $ref with Java code generator

### ISSUE THREAD

**Issue by silkentrance** [OpenAPITools/openapi-generator#2135]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] Have you a PR ready for this?

##### Description

When having custom properties/aka vendor extensions in the specification such as the excerpt below.

x-custom will be available on the vendorProperties of SomeType and the Bar property, but for the Car property, the vendorProperties will be empty. 

##### openapi-generator version

3.4.3

- not a regression, swagger 2.4.0-SNAPSHOT also has this issue

##### OpenAPI declaration file content or url

```
...
definitions:
  SomeType:
    type: object
    x-custom:
      foobar: true
    properties:
      Bar:
        type: string
        x-custom:
           foobar: false
       Car:
         $ref: 'someRef'
         x-custom:
           foobar: true
```

##### Command line used for generation

We used the maven plugin

##### Steps to reproduce

1. have a schema like the above
1. generate (java) code

##### Suggest a fix

I will try to come up with a PR for this. This should not be too difficult to fix.
