### ISSUE TITLE
[REQ] Suppress creation of empty files

### ISSUE THREAD

**Issue by Krishnanand136** [OpenAPITools/openapi-generator#21383]
### Title:
Suppress creation of empty files.

### Description:

I'm customizing the code generation process by extending the `DefaultCodegen` class. My goal is to generate different types of output (e.g., service classes or enum classes) based on a custom boolean flag defined in each schema in the OpenAPI spec. Below are the details of the issue:

---

### Use Case:

1. I want to:
   - Generate a **service class** for the `Pet` schema.
   - Generate an **enum class** for the `PetType` schema.
2. I am using a custom boolean flag in the OpenAPI schema definition to indicate what kind of class should be generated.

   ```
   Pet:
     type: object
     x-generate-service: true

   PetType:
     type: string
     enum: [DOG, CAT]
     x-generate-enum: true```


### What I’ve Tried:

1. I extended `DefaultCodegen` and added logic to detect the flags and pass them to the Mustache templates via `additionalProperties`.
2. Since I need both `Pet` and `PetType` models for different templates, I cannot filter them out in `fromModel` method.
3. Instead, I added a conditional block in the Mustache templates like:

   ```
   {{#x-generate-service}}
   // generate service class here
   {{/x-generate-service}}```

### Problem:

1. The generator creates empty files when the Mustache condition fails (i.e., the content block is skipped).
2. However, the file itself is still created, which results in empty or invalid files in the output.
3. I want to **prevent the file from being generated at all** when a schema-specific condition (like `x-generate-service: false`) is not met.

### Feature Request / Help Needed:

1. **Is there a way in OpenAPI Generator to**:
   - Skip template execution (and file generation) based on schema-level flags?

2. Alternatively, can we just suppress creation of empty mustache file?
