### ISSUE TITLE
[BUG] Golang - When using import mappings, import mapping is not properly generated when using composition plus slice type

### ISSUE THREAD

**Issue by chaslain** [OpenAPITools/openapi-generator#21448]
Hi, I am reporting this issue from a personal computer as I cannot contribute from my corporate account.
Please excuse any protocol shortcomings as this looks like an easy fix.
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ ] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description
one.yaml
```
schemas:
  Thing:
          type: object
          properties:
           Property: value
  Example:
    properties:
      Thing
        type: array
        items: $ref "#/components/schemas/Thing"
          
```
two.yaml
```
schemas:
   MyThing:
     allOf:
       - $ref: "one.yaml#/components/schemas/Example'
       - type: object
          properties: # whatever one might add here...
```

Output when generating two.yaml:
```
type MyThing struct {
    Thing *[]Thing
}
```
Expected output generating two.yaml:
```
type MyThing struct {
    Thing *[]externalRef0.Thing
}
```
