### ISSUE TITLE
[BUG] [Go] Server/Client query parameters of type array, Only first element in the query parameter is honored.

### ISSUE THREAD

**Issue by sks** [OpenAPITools/openapi-generator#21475]
Given a spec like this

```
/v1/resources:
    get:
      parameters:
        - name: ids
          in: query
          required: false
          schema:
            type: array
            items:
              type: string
              format: uuid
```

The generated server code uses [`query.Get`](https://github.com/OpenAPITools/openapi-generator/blob/6b5fd6e622af4b460cd327f2eb43bb71800efc0a/modules/openapi-generator/src/main/resources/go-server/controller-api.mustache#L498) which makes the client and server unusable in this case.

Any suggestions?

Wanted to create a Pull request with [this suggested change](https://github.com/OpenAPITools/openapi-generator/compare/master...sks:openapi-generator:patch-1), But this might make the generated code backward incompatible, Any suggestions ?
