### ISSUE TITLE
[BUG] [Python] Inline model with references are not generated (or incorrectly generated)

### ISSUE THREAD

**Issue by dojeda** [OpenAPITools/openapi-generator#2172]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

When declaring the object of a response, if one property is declared as a reference to a property in a schema, the Python model incorrectly points to a model that does not exist.

In the example provided, the key elements are:
```
          content:
            application/json:    
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Pet'
                  page:
                    $ref: '#/components/schemas/PaginationEnvelope/properties/page'
                  pages:
                    $ref: '#/components/schemas/PaginationEnvelope/properties/pages'
                  total:
                    $ref: '#/components/schemas/PaginationEnvelope/properties/total'
```
which references properties of a schema:
```
  schemas:
    PaginationEnvelope:
      type: object
      title: Paginated response template type
      required:
        - pages
        - page
        - total
        - data
      properties:
        pages:
          type: integer
          description: Number of pages available in the collection
          readOnly: true
        page:
          type: integer
          description: Current page number
          readOnly: true
        total:
          type: integer
          description: Total number of items in the collection
          readOnly: true
        data:
          type: array
          description: Array of objects with the results of the current page
          readOnly: true
          items:
            type: object
```

While this is a useful or expressive idiom may be contested, I found no claim or rule on the specification that disallows such references. Linode's API https://developers.linode.com/api/v4/openapi.yaml uses this approach heavily to reuse a pagination response template.

##### openapi-generator version

Version: 4.0.0-SNAPSHOT
Docker image version: latest (`eb900042daa7`)

##### OpenAPI declaration file content or url

https://gist.github.com/dojeda/14151390478b19a1fda94a156c1fccaf

##### Command line used for generation

```
docker run --rm -v ${PWD}:/local openapitools/openapi-generator-cli generate \
    -i /local/openapi.yaml \
    -g python \
    -o /local/out/python
```

##### Steps to reproduce

1. Download example YAML.
2. Run docker image to generate Python client code.
3. Examine the `openapi_client/models/inline_response200.py` file and find a reference to models that do not exist:
```
    openapi_types = {
        'data': 'list[Pet]',
        'page': 'Page',
        'pages': 'Pages',
        'total': 'Total'
    }
```
4. Optionally, try the client with a server that generates a valid response; there will be an exception while deserializing the response.

##### Related issues/PRs

https://github.com/OpenAPITools/openapi-generator/issues/1991

##### Suggest a fix

I have managed to workaround this by dereferencing the specification using Python module `jsonref`. When there are no `$ref` elements on the specification, the generated code is correct.
