### ISSUE TITLE
[BUG] Generator is merging nested models

### ISSUE THREAD

**Issue by leonshaw** [OpenAPITools/openapi-generator#2178]
##### Description

When multiple nested models have identical contents, the generator automatically merges them and generates only one model. This is not expected because these models are unrelated. Need an option to disable merging.

##### openapi-generator version

4.0.0-beta2

##### OpenAPI declaration file content or url

```yaml
definitions:
  outer1:
    type: object
    properties:
      inner1:
        type: object
        properties:
          foo:
            type: string
  outer2:
    type: object
    properties:
      inner2:
        type: object
        properties:
          foo:
            type: string
```

##### Command line used for generation

` java -jar openapi-generator-cli-4.0.0-beta2.jar generate -i api.yaml -g jaxrs-spec`

##### Steps to reproduce

Generate code. Inner1 is generated as `Outer1Inner1`, but inner2 is not being generated. `Outer2` now has a field `Outer1Inner1 inner2`, which is not expected.
This issue not language-specific.

**Comment by wing328** [comment]
@leonshaw what about using "title" to name the inline model as a workaround? e.g.
```
definitions:
  outer1:
    type: object
    properties:
      inner1:
        title: "inner1_title"
        type: object
        properties:
          foo:
            type: string
  outer2:
    type: object
    properties:
      inner2:
        title: "inner2_title"
        type: object
        properties:
          foo:
            type: string
```
