### ISSUE TITLE
[PHP] nullable attribute with value null gets removed

### ISSUE THREAD

**Issue by githubERIK** [OpenAPITools/openapi-generator#2199]
##### Description

_Given_ a nullable field in OpenAPI object

```yaml
    SomeObject:
      type: object
      properties:
        someProperty:
          type: string
          nullable: true
```

_When_ HTTP Request has the object and it includes `someProperty=null`

_Then_ the generated php client code does not include `someProperty` in the response.

##### openapi-generator version

master branch (version 3.3.4)

##### OpenAPI declaration file content or url

See the description

##### Command line used for generation

`openapi-generator generate -g php`

##### Suggest a fix/enhancement

Remove null-check if-block `if ($value !== null)` from https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php/ObjectSerializer.mustache#L68

by changing this

```php
if ($value !== null) {
    $values[$data::attributeMap()[$property]] = self::sanitizeForSerialization($value, $openAPIType, $formats[$property]);
}
```

to this

```php
$values[$data::attributeMap()[$property]] = self::sanitizeForSerialization($value, $openAPIType, $formats[$property]);
```

**Comment by wing328** [comment]
@githubERIK thanks for reporting the issue and sharing the workaround.

But I think in certain use cases, the workaround may introduce additional null values in the payload, which are not present before.

I think we may need to maintain another associative array similar to [openAPITypes](https://github.com/OpenAPITools/openapi-generator/blob/master/samples/openapi3/client/petstore/php/OpenAPIClient-php/lib/Model/Pet.php#L59) to indicate if the property is nullable

**Comment by githubERIK** [comment]
Step 1. Make it so, that a constructor won't assign nulls for attributes which values are not given to the constructor via an argument array. 

For example,

```yml
    Any:
      title: 'Sir'
      description: ''
      type: object
      required:
        - name
      properties:
        id:
          type: integer
        name:
          type: string
        anything:
          type: string
```

and 

```php
$anyInstance = new Any(['name' => 'Tom']);
```

should not result in an instance of Any object which has `protected $container = [];` filled with

- 'id' => null
- 'name' => 'Tom'
- 'anything' => null

but should result in an instance of Any object which has `protected $container = [];` filled with only

- 'name' => 'Tom'.


Step 2. Apply the initial workaround only for elements which have `nullable: true`. Make ObjectSerializer->sanitizeForSerialization not filter out those nulls for responses. Outgoing requests won't have the nulls because of step 1.
