### ISSUE TITLE
[Java][Spring] inline objects not generated as types

### ISSUE THREAD

**Issue by macjohnny** [OpenAPITools/openapi-generator#222]
##### Description

When defining an object property as an object, the result is not typed, i.e. it is an `Object`
Spring Boot:
```java
public class Parameters   {
  @JsonProperty("bankParameters")
  private Object bankParameters = null;

  @JsonProperty("megaParameters")
  private Object megaParameters = null;
...
}
```
Typescript Angular:
```typescript
export interface Parameters { 
    bankParameters?: any;
    megaParameters?: any;
}
```
With swagger-codegen 2.4.0-SNAPSHOT this was the typescript-angular output:
```typescript
import { ParametersBankParameters } from './parametersBankParameters';
import { ParametersMegaParameters } from './parametersMegaParameters';

export interface Parameters { 
    bankParameters?: ParametersBankParameters;
    megaParameters?: ParametersMegaParameters;
}
```

##### openapi-generator version

3.0.0

this used to work swagger-codegen 2.4.0-SNAPSHOT

##### OpenAPI declaration file content or url
```yml
definitions:
  Parameters:
    # BankSettings
    type: object
    properties:
      bankParameters:
        type: object
        properties:
          someNumber:
            type: number
      megaParameters:
        type: object
        properties:
          megaNumber:
            type: number
```

##### Command line used for generation
maven plugin
