### ISSUE TITLE
[BUG] File upload Qt5cpp formdata

### ISSUE THREAD

**Issue by rsps-jesper** [OpenAPITools/openapi-generator#2251]
##### Description

Wrong headers in POST request due to "IsFormData" not set in generated OAIHttpRequest.cpp 

##### openapi-generator version

3.3.4

##### OpenAPI declaration file content or url

```yaml
post:
      description: Upload a file
      operationId: uploadFile
      consumes:
        - multipart/form-data
      parameters:
        - name: device_id
          in: path
          description: device serial number
          required: true
          type: string
        - name: resource_name
          in: path
          description: Filename
          required: true
          type: string
        - name: uploaded_file
          in: formData
          description: Uploaded file
          required: true
          type: file
```

##### Command line used for generation

java -jar openapi-generator-cli.jar generate -i pilot/api.yaml -g cpp-qt5 -o test

##### Suggest a fix
Not sure about the generator fix, but if you stumple across this issue, it can be fixed by setting the isFormData to true when it sets the layout.

`if (input->files.length() > 0) {
        isFormData = true;
        input->var_layout = MULTIPART;
    }`
