### ISSUE TITLE
[BUG][C#] 

### ISSUE THREAD

**Issue by sturlath** [OpenAPITools/openapi-generator#2269]
##### Description
If I try to generate _**aspnetcore**_  dto's the **nullable = false** is alwasy ignored and all the properties created are created nullable. 

If I have nullable in my api.yaml file (_**skipping allot for brevity**_)
```yaml
        expireDateOfOffer:
          type: string
          format: date
          nullable: false (toggling/skipping this doesn't change anything! )
```
and then run the following

`java -DdebugModels -jar openapi-generator-cli-4.0.0-20181226.105224-120.jar generate -i api.yaml -g aspnetcore -o  c:\Temp -t templates\aspnetcore\controller -Dapis`

I get

```csharp        
        /// <summary>
        /// Gets or Sets ExpireDateOfOffer
        /// </summary>
        [DataMember(Name="expireDateOfOffer")]
        public DateTime? ExpireDateOfOffer { get; set; }
```

I can't seem to get rid off the ? (nullable) after the DateTime. 
I **don't want it to be nullable**!

##### openapi-generator version
4.0.0-20181226.105224-120

##### Command line used for generation

`java -DdebugModels -jar openapi-generator-cli-4.0.0-20181226.105224-120.jar generate -i api.yaml -g aspnetcore -o  c:\Temp -t templates\aspnetcore\dtos -Dapis`

##### Steps to reproduce
Run the previous command line on a yaml file with property you want to have as non-nullable and see if you can make it so.

##### Related issues/PRs
Couldn't find anything except maybe [this one](https://github.com/OpenAPITools/openapi-generator/issues/579)
