### ISSUE TITLE
[BUG] [Aspnetcore2.1] Missing tag closure of StringLength attribute

### ISSUE THREAD

**Issue by sedainterxion** [OpenAPITools/openapi-generator#2275]
##### Description
I have a parameter with min/max length attributes. When I run the generator, there is a missing tag closure of StringLength attribute.

`public virtual  async Task<List<Facility>> FacilitiesList([FromQuery][StringLength(3, MinimumLength=3)string area, [FromQuery]string addressCountry)`

It can be seen in these resource files as well: https://github.com/OpenAPITools/openapi-generator/search?q=MinimumLength

##### openapi-generator version
3.0.2

##### OpenAPI declaration file content
```yaml
  parameters:
    area:
      name: area
      required: false
      schema:
        type: string
        maxLength: 3
        minLength: 3
        example: "MOO"
```
