### ISSUE TITLE
[BUG] String default wrong quotation

### ISSUE THREAD

**Issue by pohlmarcus** [OpenAPITools/openapi-generator#2358]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

We use the maven plugin to create our models and interfaces in spring boot.
I wanted to set an optional header parameter to a default value used on the server side. However, I can not define the string correctly. The output is always masked incorrectly with extra double quotes.

##### openapi-generator version

<dependency>
    <groupId>org.openapitools</groupId>
    <artifactId>openapi-generator-maven-plugin</artifactId>
    <version>3.3.4</version>
</dependency>

##### OpenAPI declaration file content or url

```
components:
    parameters:
        XConsumerId:
            in: header
            name: x-consumer-id
            description: 'filled by gateway'
            required: false
            schema:
                type: string
                default: "c1" # tried also c1 and 'c1' 
            example: c1

```

Generated code
`@ApiParam(value = "filled by gateway" , defaultValue=""c1"") @RequestHeader(value="x-consumer-id", required=false) String xConsumerId`

"" of defaultValue is not correct

##### Command line used for generation

Execute maven plugin
