### ISSUE TITLE
[BUG] [haskell-http-client]: Cannot create HTTP client for Docker

### ISSUE THREAD

**Issue by malyutinegor** [OpenAPITools/openapi-generator#2527]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

openapi-generator successfully generates HTTP client for Docker, but I can't compile it using `stack haddock`. It ends with this error:
```
[ 6 of 26] Compiling DockerEngine.Model ( lib/DockerEngine/Model.hs, .stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1/build/DockerEngine/Model.o )

/home/egorcod/Документы/openapi-docker/lib/DockerEngine/Model.hs:6391:51: error:
    Not in scope: type constructor or class ‘Array’
    Perhaps you meant ‘A.Array’ (imported from Data.Aeson)
    Perhaps you want to add ‘Array’ to the import list in the import of
    ‘Data.Aeson’ (lib/DockerEngine/Model.hs:34:1-41).
     |
6391 |   , systemDataUsageResponseContainers :: !(Maybe [Array]) -- ^ "Containers"
     |
```

##### openapi-generator version

```
> docker run --rm openapitools/openapi-generator-cli version
4.0.0-SNAPSHOT
```

##### OpenAPI declaration file content or url

https://docs.docker.com/engine/api/v1.39/swagger.yaml

##### Command line used for generation

```
docker run --rm -v ${PWD}:/local openapitools/openapi-generator-cli generate -i https://docs.docker.com/engine/api/v1.39/swagger.yaml -g haskell-http-client -o /local
```

##### Steps to reproduce

```
> mkdir openapi-docker
> cd openapi-docker
> docker run --rm -v ${PWD}:/local openapitools/openapi-generator-cli generate -i https://docs.docker.com/engine/api/v1.39/swagger.yaml -g haskell-http-client -o /local
> stack haddock
```

##### Related issues/PRs

Not found any.

##### Suggest a fix

```
Perhaps you meant ‘A.Array’ (imported from Data.Aeson)
Perhaps you want to add ‘Array’ to the import list in the import of
    ‘Data.Aeson’ (lib/DockerEngine/Model.hs:34:1-41).
```

**Comment by wing328** [comment]
Thanks for reporting the issue.

cc @jonschoning

**Comment by malyutinegor** [comment]
@wing328 For an unknown reason, openapi-codegen not generates ContainerSummary model. I think, it caused this error.

**Comment by jonschoning** [comment]
```
  ContainerSummary:
    type: "array"
    items:
      type: "object"
      properties:
        Id:
          description: "The ID of this container"
          type: "string"
          x-go-name: "ID"
        Names:
          description: "The names that this container has been given"
          type: "array"
          items:
            type: "string"
        Image:
          description: "The name of the image used when creating this container"
          type: "string"
        ImageID:

```
```
[main] INFO  o.o.codegen.DefaultGenerator - Model ContainerSummary not generated since it's an alias to array (without property) and `generateAliasAsModel` is set to false (default)
```
https://github.com/OpenAPITools/openapi-generator/blob/dc78405a68f52745bdc2ad0f98b97ee82bdf283c/modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultGenerator.java#L443-L449

This occurs because DefaultGenerator.java thinks that ContainerSummary has no properties, and so it refuses to generate the model.

I do not think it's an issue with the `haskell-http-client` code but rather with the DefaultGenerator logic.
