### ISSUE TITLE
[REQ] MySql schema generator should generate SQL DEFAULT 

### ISSUE THREAD

**Issue by nmfisher** [OpenAPITools/openapi-generator#2587]
### Is your feature request related to a problem? Please describe.

MySQL allows default values for columns, so it would make sense to populate this from the "default" value of an OpenAPI schema property. It appears this property is currently ignored. 

## Describe the solution you'd like

When a default value is provided in the schema, a corresponding SQL DEFAULT statement is generated as follows:

### spec.yaml
```
...
components:
  schemas:
    Person:
      type: object
      properties:
        name:
          type: string
          default: "Bob"
...
```

### generated.sql
```
... 
ALTER TABLE Person ALTER Name SET DEFAULT 'Bob'; 
...
```

## Describe alternatives you've considered

An alternative is to to set default values in code, which duplicates effort and increases the chance of error.

## Additional context

I haven't looked into the mysql-schema generator yet or the way the DefaultGenerator handles handling "default", but there would need to be some validation logic to ensure that defaults are appropriate (e.g. match type/min/max requirements).

**Comment by ybelenko** [comment]
```yaml
Animal:
  type: object
  discriminator: className
  required:
    - className
  properties:
    className:
      type: string
    color:
      type: string
      maxLength: 100
      default: 'red'
    age:
      type: integer
      format: int32
      default: 3
    sold:
      type: boolean
      default: 0
```

Generates:
```sql
--
-- Table structure for table `Animal` generated from model 'Animal'
--

CREATE TABLE IF NOT EXISTS `Animal` (
  `className` TEXT NOT NULL,
  `color` VARCHAR(100) DEFAULT 'red',
  `age` INT DEFAULT 3,
  `sold` TINYINT(1) DEFAULT false
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
```

@nmfisher I agree with you, current generator ignores `default` value in most cases. It have only basic validation logic right now. As far as I remember generator understands default prop for these data types:
* `string` with `maxLength` <= 255
We agreed to use `TEXT` type for `string`.  MySQL `TEXT` column doesn't support `DEFAULT` statement. The only exception is string less than 256 chars which mapped to `VARCHAR`. 
* `integer` with specified `format`(`int32` or `int64`)
* `number` with specified `format`(`float` or `double`)
* `boolean` with `default: 0` or `default: 1`

**Comment by nmfisher** [comment]
Thanks @ybelenko - that's actually more support than I expected. Leaving aside datatypes with no support for DEFAULT (i.e. BLOB and TEXT), that only leaves
- date/datetime
- objects (i.e. JSON)

I'm not sure how useful DEFAULT for date/datetime will be, and it looks like DEFAULT for JSON is only supported by [MySQL >= 8.0.13](https://dev.mysql.com/doc/refman/8.0/en/json.html), which I assume is higher than the minimum version targeted by the generator.

Maybe we should treat this is a documentation issue and leave the generator as-is?

**Comment by ybelenko** [comment]
> * date/datetime

`CURRENT_TIMESTAMP` is supported.
https://github.com/OpenAPITools/openapi-generator/blob/23476fb66a5a1e47d601d111dfa15818453f7895/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/MysqlSchemaCodegen.java#L742-L745

> * objects (i.e. JSON)

It seems that at the point when I've created this codegen MySQL didn't support default constraint for `JSON` type.
https://github.com/OpenAPITools/openapi-generator/blob/23476fb66a5a1e47d601d111dfa15818453f7895/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/MysqlSchemaCodegen.java#L765-L768

> Maybe we should treat this is a documentation issue and leave the generator as-is?

I'm very interested in that and other enhancements of MySQL generator, but don't have enough free time right now. I agree that `DEFAULT` constraint requires a lot of improvements. The major concern was whether we should try to get most accurate db schema from openapi properties or rely more on vendor extensions. For example:
```yaml
Animal:
  type: object
  properties:
    created_at:
      type: string
      format: date-time
      default: CURRENT_TIMESTAMP
```
Looks weird, while:
```yaml
Animal:
  type: object
  properties:
    created_at:
      type: string
      format: date-time
      x-mysqlSchema:
        columnDefinition:
          colDefault: CURRENT_TIMESTAMP
```
looks reasonable.

I've planned to add foreign keys support, snake_case table names and other cool stuff, but it requires a lot of time and `php-slim` server generator is my highest priority right now.
