### ISSUE TITLE
[aspnetcore] new keyword on ToJson Method when inherited from Dictionary

### ISSUE THREAD

**Issue by etherealjoy** [OpenAPITools/openapi-generator#275]
##### Description

When a model is a map type and inherited from a dictionary the new keyword is added to **ToJson** method even when there is no accessible member to hide/override.

```C#
public partial class ResourceOperations : Dictionary<String, string>, 
    IEquatable<ResourceOperations>
{ 
    public  new string ToJson()
```
```sh
Warning	CS0109	The member 'ResourceOperations.ToJson()' does not hide an accessible member. 
The new keyword is not required.	
```

##### openapi-generator version

3.0.0

I detected this issue with old codebase.
In current code base the map is not working.

##### OpenAPI declaration file content or url

```yaml
  ResourceOperations:
    description: "An object describing the operations"
    type: "object"
    additionalProperties:
      type: "string"
```

##### Command line used for generation

```bash
java -jar ~/openapi-generator/modules/openapi-generator-cli/target/openapi-generator-cli.jar \
generate -i ./api.yaml -o ./genserver -l aspnetcore 
```
