### ISSUE TITLE
[C++] Escape language reserved symbols which are valid in the spec

### ISSUE THREAD

**Issue by etherealjoy** [OpenAPITools/openapi-generator#281]
##### Description

When the specification contains valid symbols which are language specific operators compilation fails.

##### openapi-generator version

3.0.0
##### OpenAPI declaration file content or url

This is a valid snippet from a spec
```yaml
  v1.HostPathType:
    type: object
    additionalProperties:
      type: string
```
Creates the following snippet of code for Qt5 for example
```C++
class OAIV1.HostPathType: public OAIObject {
```
This code will not compile for any C++ client and server.
I would suppose the same issue for other langs like C#

##### Suggest a fix/enhancement

The '.' and other valid symbols for example has to be escaped for example to '_' to make compilation pass.
