### ISSUE TITLE
[BUG] CodegenConfigurator crashing when allOf overridden

### ISSUE THREAD

**Issue by medwards** [OpenAPITools/openapi-generator#2811]
When trying to override a basic type alias with a default I get a stacktrace failure and `com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'openapi': was expecting ('true', 'false' or 'null')` and `SwaggerCompatConverter - failed to read resource listing`.

The guilty part of the spec looks something like (obviously simplified):
```yaml
SomeThing:
  properties:
    duration:
      description: "The duration of SomeThing"
      default: 0
      allOf:
        - $ref: 'Duration'
Duration:
  type: integer
  description: Duration in seconds
```

Alternative forms fail the same way:
```yaml
SomeThing:
  properties:
    duration:
      allOf:
        - $ref: 'Duration'
        - description: "The duration of SomeThing"
          default: 0
 
Duration:
  type: integer
  description: Duration in seconds
```
##### openapi-generator version

master, I think its a regression as I was using an older version of master /wo the issue

##### Command line used for generation

Occurs when I just validate. Also when generating rust /w reqwest but the bug hits way before any codegen happens

##### Steps to reproduce

Validate a spec that sets a default for an inherited schema object. Deleting the default allows it to validate.
