### ISSUE TITLE
[BUG][JAXRS-JERSEY2] No injection source found when specifying object as query param

### ISSUE THREAD

**Issue by Norbo11** [OpenAPITools/openapi-generator#2865]
##### Description

I am trying to specify an object as a query parameter, like this:

```yaml
        - name: filter_options
          description: Filter options
          in: query
          required: false
          schema:
            $ref: '#/components/schemas/FeedbackFilterOptions'
```

```yaml
    FeedbackFilterOptions:
      type: object
      properties:
        history_since_type:
          type: string
          enum: [date_time, beginning_of_version]
        history_since_date_time:
          type: string
          format: date-time
```

This generates a method which contains a `FeedbackFilterOptions` object.

Jersey complains that it cannot validate this application model, as it doesn't know how to serialise such an object (it cannot find a `ParamConverterProvider`: see [here](https://stackoverflow.com/questions/39850052/offsetdatetime-yielding-no-injection-source-found-for-a-parameter-of-type-publi/39850842#39850842).

I would have thought that openapi-codegen would generate the relevant converter and allow me to use this object. The way to fix this right now is for me to inline all of the properties of my `FeedbackFilterOptions` in the query spec, such that each parameter is generated separately as a primitive.

The full error message:

```
Caused by: org.glassfish.jersey.server.model.ModelValidationException: Validation of the application resource model has failed during application initialization.
[[FATAL] No injection source found for a parameter of type public javax.ws.rs.core.Response np1815.feedback.metricsbackend.api.MetricsApi.getFeedbackForFile(java.lang.String,java.lang.String,java.lang.String,np1815.feedback.metricsbackend.model.FeedbackFilterOptions,javax.ws.rs.core.SecurityContext) throws np1815.feedback.metricsbackend.api.NotFoundException at index 3.; source='ResourceMethod{httpMethod=GET, consumedTypes=[], producedTypes=[application/json], suspended=false, suspendTimeout=0, suspendTimeoutUnit=MILLISECONDS, invocable=Invocable{handler=ClassBasedMethodHandler{handlerClass=class np1815.feedback.metricsbackend.api.MetricsApi, handlerConstructors=[org.glassfish.jersey.server.model.HandlerConstructor@16cf05ef]}, definitionMethod=public javax.ws.rs.core.Response np1815.feedback.metricsbackend.api.MetricsApi.getFeedbackForFile(java.lang.String,java.lang.String,java.lang.String,np1815.feedback.metricsbackend.model.FeedbackFilterOptions,javax.ws.rs.core.SecurityContext) throws np1815.feedback.metricsbackend.api.NotFoundException, parameters=[Parameter [type=class java.lang.String, source=application_name, defaultValue=null], Parameter [type=class java.lang.String, source=version, defaultValue=null], Parameter [type=class java.lang.String, source=filename, defaultValue=null], Parameter [type=class np1815.feedback.metricsbackend.model.FeedbackFilterOptions, source=filter_options, defaultValue=null], Parameter [type=interface javax.ws.rs.core.SecurityContext, source=null, defaultValue=null]], responseType=class javax.ws.rs.core.Response}, nameBindings=[]}']
```

##### openapi-generator version

3.3.4

**Comment by Norbo11** [comment]
I've just replaced my `filter_options` param by the two parameters contained in my schema:

```yaml
        - name: history_since_type
          in: query
          required: false
          schema:
            type: string
            enum: [date_time, beginning_of_version]
        - name: history_since_date_time
          in: query
          required: false
          schema:
            type: string
            format: date-time
```

This now generated two parameters of types String and LocalDateTime (I have dateLibrary=java8-localdatetime set). I am now getting the same error, but with relation to the LocalDateTime - jersey doesn't know how to serialise it. I am also generating the supporting files `LocalDateProvider.java` and `OffsetDateTimeProvider.java`, but those seem to only handle `LocalDate` and `OffsetDateTime` - so why is openapi-generator generating a `LocalDateTime` parameter?
