### ISSUE TITLE
[BUG] [JAVA | JAXRS-Spec] Default value of date-time parameter causes exception

### ISSUE THREAD

**Issue by grantsunny** [OpenAPITools/openapi-generator#2907]
##### Description
When I use maven plugin 4.0.0 to generate following yaml the generator give me one unexpected error. 
```
unexpected error in Open-API generation
java.lang.RuntimeException: Could not process operation:
  Exception: java.base/java.util.Date cannot be cast to java.base/java.lang.String
    at org.openapitools.codegen.DefaultGenerator.processOperation (DefaultGenerator.java:1078)
    at org.openapitools.codegen.DefaultGenerator.processPaths (DefaultGenerator.java:969)
    at org.openapitools.codegen.DefaultGenerator.generateApis (DefaultGenerator.java:528)
    at org.openapitools.codegen.DefaultGenerator.generate (DefaultGenerator.java:922)
    at org.openapitools.codegen.plugin.CodeGenMojo.execute (CodeGenMojo.java:682)

```

##### openapi-generator version
I am using openapi-generator-maven-plugin 4.0.0 to generate the code. 
##### OpenAPI declaration file content or url
```yaml
    get:
      tags: 
        - email
      summary: list all scheduled email
      operationId: list all scheduled email 
      parameters:
        - in: query
          name: beginTime
          required: false
          schema:
            type: string
            format: date-time
            default: "1970-01-01T00:00:00Z"
        - in: query
          name: endTime
          required: false
          schema:
            type: string
            format: date-time
            default: "1970-01-01T00:00:00Z"
```

##### Command line used for generation
```xml
			<plugin>
				<groupId>org.openapitools</groupId>
				<artifactId>openapi-generator-maven-plugin</artifactId>
				<version>4.0.0</version>
				<executions>
					<execution>
						<goals>
							<goal>generate</goal>
						</goals>
						<configuration>
							<inputSpec>${project.basedir}/src/main/resources/email-api.yaml</inputSpec>
							<generatorName>jaxrs-spec</generatorName>
							<configOptions>
								<java8>true</java8>
								<dateLibrary>java8</dateLibrary>
								<interfaceOnly>true</interfaceOnly>
								<useSwaggerAnnotations>false</useSwaggerAnnotations>
								<generatPom>false</generatPom>
							</configOptions>
							<output>${project.basedir}</output>
							<apiPackage>...</apiPackage>
							<modelPackage>...</modelPackage>
						</configuration>
					</execution>
				</executions>
			</plugin>
```

##### Steps to reproduce
I were using maven to trigger the code generation and the exception will appear every time. When removed the default declaration from yaml, the exception disappear. It doesn't seem like to be an issue of maven plug-in but the generator itself. 

##### Related issues/PRs

Did not find related issues for JAX-RS spec generation after searching. 

##### Suggest a fix
@DefaultValue in JAX-RS interfaces shall be generated well according the yaml configuration.
