### ISSUE TITLE
[BUG] [Ruby] [Python] Client generation doesn't support Bearer Authentication

### ISSUE THREAD

**Issue by rhuanbarreto** [OpenAPITools/openapi-generator#2910]
#### Description

If you declare a bearer auth as security scheme and apply to the whole OpenAPI spec: 

```yaml
security:
  - bearerAuth: []
components:
  securitySchemes:
      bearerAuth:
        type: http
        scheme: bearer
```

And try to generate a ruby or python client (I didn't test on other languages), the readme generated use basic authentication as an example and if you set `config.access_token` parameter, the request sends:

```
Host: contoso.com
User-Agent: OpenAPI-Generator/1.0.0/ruby
Content-Type: application/json
Accept: application/json
Authorization: Basic Og==
```

Then you need to go manually and change the client in order to have it suitable for the application.

#### openapi-generator version

`3.3.4`

#### Fix

The solution for me was to change the method in `lib/package-name/configuration.rb` from

```ruby
def basic_auth_token
  'Basic ' + ["#{username}:#{password}"].pack('m').delete("\r\n")
end
```

to

```ruby
def basic_auth_token
  'Bearer ' + access_token
end
```

**Comment by wing328** [comment]
Can you try the latest stable version v4.0.0? I believe the issue has been addressed.

**Comment by wing328** [comment]
For Ruby, please try the latest snpashot as a PR was merged into master 2 days ago to support Bearer authentication in the Ruby API client.

**Comment by rhuanbarreto** [comment]
Thanks @wing328! Will it be released soon?

**Comment by ackintosh** [comment]
@rhuanbarreto 
The Bearer authentication support in the Ruby client will be released as `v4.0.1`, [which will be released on 31.05.2019](https://github.com/OpenAPITools/openapi-generator#11---compatibility). 😉 

If you want use it right now, please use [the SNAPSHOT version](https://github.com/OpenAPITools/openapi-generator#11---compatibility) or [the latest docker image](https://hub.docker.com/r/openapitools/openapi-generator-cli/tags).

**Comment by rhuanbarreto** [comment]
I used the snapshot, but there are some problems in the output:

If I have a RequestBody:

```yaml
components:
  requestBodies:
    LoginBody:
      description: A JSON object for user authenticate
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              username:
                type: string
                example: rune
                description: username of microsoft's active directory
              password:
                type: string
                example: abc123
                description: password of microsoft's active directory
```

I get an UNKNOWN_BASE_TYPE object that breaks the API client.

I don't want to use a model because the User model is not defined on the backend but on the Active Directory.

In order to fix this I must create an user model and declare a `$ref`:

```yaml
LoginBody:
      description: A JSON object for user authenticate
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/User'
```

Then it works.

**Comment by rhuanbarreto** [comment]
@ackintosh put the label for Ruby also.

**Comment by wing328** [comment]
> I get an UNKNOWN_BASE_TYPE object that breaks the API client.

I think that's separate issue not related to bearer authentication support. Please open a new one to track the issue instead.

Closing this one for the time being.

**Comment by lacksfish** [comment]
Not sure this can be closed yet, as it seems to be an outstanding issue.

Adding the access token like this does not work for python:
```
    confAuthed = configuration.Configuration()
    confAuthed.access_token = access_token
```

Where access token is a `Bearer` token.

What does help if in the following lines I manually go and add it:

```
    client_authed = api_client.ApiClient(confAuthed)
    client_authed.set_default_header('Authorization', 'Bearer ' + access_token)
    privateApi = private_api.PrivateApi(client_authed)
```

**Comment by lacksfish** [comment]
This issue persists on version 4.0.0

**Comment by wing328** [comment]
Does your endpoint specify the bearer authentication is required?

**Comment by lacksfish** [comment]
I specified it like this:
```
components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: Auth token # human readable string
```

I'm noticing now I might've left out this part:

```
security:
  - bearerAuth: []
```

Added that now and will check if that resolves the issue.

**Comment by lacksfish** [comment]
Yup, that fixes it.

@rhuanbarreto Perhaps consult again with https://swagger.io/docs/specification/authentication/bearer-authentication/ as this is what helped me just now find out what was missing.

**Comment by wing328** [comment]
@rhuanbarreto glad to hear the issue has been resolved for you.

**Comment by rhuanbarreto** [comment]
@wing328 thanks!

**Comment by ybelenko** [comment]
By the way `scheme` property is case-sensitive, spent few hours to investigate why:
```yaml
components:
  securitySchemes:
    BusinessProductAuthorization:
      description: ''
      type: http
      scheme: Bearer
```
doesn't work. When I change to `scheme: bearer` works as expected.
