### ISSUE TITLE
[BUG] Kotlin client: wrong code for generated enums

### ISSUE THREAD

**Issue by kroegerama** [OpenAPITools/openapi-generator#2979]
##### Description

kotlin-client generates non-compilable code

##### openapi-generator version

4.0.0

##### OpenAPI declaration file content or url

```
gender:
        format: int32
        description: "* Geschlecht (0 = neutrale Anrede, 1 = Frau, 2 = Mann, 3 = Familie)\r\n* Gender (0 = neutral salutation, 1 = Female, 2 = Male, 3 = Family)"
        enum:
          - 0
          - 1
          - 2
          - 3
        type: integer
```

##### Command line used for generation

`[...] -g kotlin [...]`

##### Generated code

```
/**
    * * Familienstand (0 = single, 1 = verheiratet, 2 = geschieden, 3 = getrennt lebend, 4 = verwitwet)  * Marital status (0 = single, 1 = married, 2 = divorced, 3 = seperated, 4 = widowed)
    * Values: _0,_1,_2,_3,_4
    */
    enum class MaritalStatus(val value: kotlin.Int){
    
        @Json(name = 0)
        _0(0),
    
        @Json(name = 1)
        _1(1),
    
        @Json(name = 2)
        _2(2),
    
        @Json(name = 3)
        _3(3),
    
        @Json(name = 4)
        _4(4);
    
    }
```

`@Json(name` <- has to be a String.
