### ISSUE TITLE
[rust-server] lacks collectionFormat support

### ISSUE THREAD

**Issue by bjgill** [OpenAPITools/openapi-generator#315]
##### Description

See https://github.com/swagger-api/swagger-codegen/issues/8173#issuecomment-388855190. I no longer remember what the problem was, but it seems as if we generate invalid Rust when faced with a `collectionFormat`. 

e.g.

```yaml
      parameters:
        - in: query
          name: color
          type: array
          collectionFormat: csv
          items:
            type: string
```

(Note: this part of a set of issues from swagger-codegen. I didn't fix this as part of the move to openapi-generator. Thus I strongly suspect rust-server in openapi-generator also suffers the same problem. I'm not planning on working on this at the moment - contributions gratefully welcomed)
