### ISSUE TITLE
[BUG] Inline model resolving failure when the model name contains dot `.`

### ISSUE THREAD

**Issue by yue9944882** [OpenAPITools/openapi-generator#3260]
running go generator using the following definitions as input:

```yaml
  io.kimmin.InlineFailure:
  #InlineFailure:
    type: object
    properties:
      spec:
        type: object
        properties:
          foo:
            type: integer
```

the generated go codes will be:

```go
package petstore

type IoKimminInlineFailure struct {
	Spec map[string]interface{} `json:"spec,omitempty"` // `map[string]interface{}` should be resolved
}
```

by debugging in my local environment, i happen to find out that everything will be happy when commenting the following code from `ModelUtils#getSimpleRef`:
 
```java
    public static String getSimpleRef(String ref) {
        if (ref.startsWith("#/components/")) {
            ref = ref.substring(ref.lastIndexOf("/") + 1);
        } else if (ref.startsWith("#/definitions/")) {
            ref = ref.substring(ref.lastIndexOf("/") + 1);
        } else {
-            LOGGER.warn("Failed to get the schema name: {}", ref);
-            //throw new RuntimeException("Failed to get the schema: " + ref);
-            return null;

        }

        return ref;
    }
```

then the correct output will be:

```
package petstore

type IoKimminInlineFailure struct {
	Spec map[string]IoKimminInlineFailureSpec `json:"spec,omitempty"` 
}
```

am not sure, if it's the correct fix but seems working for me..

@wing328 ptal
