### ISSUE TITLE
[BUG] rust-server doesn't seem to like examples

### ISSUE THREAD

**Issue by jamessewell** [OpenAPITools/openapi-generator#3313]
Hi,

I'm using `rust-server` with `4.0.1`.

I have a path which returns an schema defined as below:

```yaml
$ref: '#/components/schemas/Alert
```

This schema is a test one, and is defined as:

```yaml
Alert:
  type: object
  properties:
     name:
       type: string
       example: "Test string"
```
This renders the following code in `examples/client.rs`

```rust
 // Disabled because there's no example.
        Some("ExecuteAlert") => {
            let result = core.run(client.execute_alert(???));
            println!("{:?} (X-Span-ID: {:?})", result, (client.context() as &Has<XSpanIdString>).get().clone());
         },
```

Is this something which is meant to work when examples are set?
