### ISSUE TITLE
Improve Builds with CircleCI 2.0 Setup

### ISSUE THREAD

**Issue by philsturgeon** [OpenAPITools/openapi-generator#344]
The recent #333 was a good direct port of CircleCI 1.0 to 2.0, but it has not taken advantage of worklflows just yet, or much of the functionality offered.

### A Bigger Thing

It's tough to tell which service is doing which language from looking just at the various CI config files, but there is a list here:

<img width="751" alt="screen shot 2018-06-18 at 4 26 44 pm" src="https://user-images.githubusercontent.com/67381/41560229-783ada10-7314-11e8-96ce-9d82eccd511a.png">

The goal surely would be to get everything into one CI system, and this can easily be done with workflows. A good first step would be to roll Travis into CircleCI as a new workflow.

All of the slowness from these CI builds are down to having _all_ of the "cache" logic for all languages done together, then all of the install steps done together, then all of the test steps done together... serial is slower than parrelllel. 

![image](https://user-images.githubusercontent.com/67381/41560314-b922ff62-7314-11e8-9b74-1c3ebf79f997.png)

You need to tweak the logic here, to either make a job for each language that does each step, or to split the "dependencies" into parrallel jobs, and "build" into parrallel jobs, etc., and the final test into multiple jobs. 

### One trivial thing

Multiple docker images can be referenced, so we can pull in the swagger petstore, and [set env variables](https://circleci.com/docs/2.0/env-vars/#setting-an-environment-variable-in-a-container) on it like this:

```
version: 2
jobs:
  build:
    docker:
      - image: openapitools/openapi-generator
      - image: swaggerapi/petstore
          environment:
            SWAGGER_HOST=http://petstore.swagger.io
            SWAGGER_BASE_PATH=/v2
```

That would cut down on these sort of commands, and the sleeps and trickyness that comes with it. 

```
     - run: docker run -d -e SWAGGER_HOST=http://petstore.swagger.io -e SWAGGER_BASE_PATH=/v2 -p 80:8080 swaggerapi/petstore 
```
