### ISSUE TITLE
[BUG][Go] enum name collision

### ISSUE THREAD

**Issue by kraney** [OpenAPITools/openapi-generator#3518]
##### Description

In the generated Go client, specific values of enums are declared at package scope using only the value name. This causes name collisions between enums with overlapping value names.

##### openapi-generator version

4.1.0-SNAPSHOT

##### OpenAPI declaration file content or url

```yaml
components:
  schemas:
    monitor_action_type:
      enum:
      - TRAP
      - SYSLOG
      type: string
    csr_use:
      enum:
      - TLS
      - SYSLOG
      type: string
```
This results in two package-level variables both named "SYSLOG" causing build failure.

##### Command line used for generation

```
docker run --name oas --rm openapitools/openapi-generator-cli:latest generate -g go -i openapi.yaml
```

##### Steps to reproduce

Generate code for a schema with the two models above, and try to build it.

##### Suggest a fix

Possibly prefix the enum value name with the enum type name, e.g. `CsrUse_SYSLOG`.
