### ISSUE TITLE
[REQ][java][jackson] add @JsonPropertyOrder annotation

### ISSUE THREAD

**Issue by jmini** [OpenAPITools/openapi-generator#3629]
When the model classes are serialized to JSON the order of the JSON members are not controlled.

Given this schema:

```yaml
components:
  schemas:
    SomeObj:
      type: object
      properties:
        id:
          type: integer
          format: int64
        firstName:
          type: string
        lastName:
          type: string
```

This is not a big deal because the order is not relevant in a JSON object:

```json
{
"id" : 42,
"firstName": "John",
"lastName": "Doe"
}
```

Is the same than:
```json
{
"lastName": "Doe",
"id" : 42,
"firstName": "John"
}
```

But if the JSON objects are displayed or stored as file, it would be nice to have always the same order (the same as in the OpenAPI specification).

With Jackson the solution is to use the `@JsonPropertyOrder` property.

In my opinion this should be generated (maybe with an option to hide it for user that do not want it).
