### ISSUE TITLE
dart2 client not compiling and ignoring templateDir

### ISSUE THREAD

**Issue by alexnavratil** [OpenAPITools/openapi-generator#3655]
##### Description

The dart client generator overwrites a custom set templateDir when using dart 2.x. The default dart2 templates also fail to compile since they depend on some old and already deleted dependency (dartson).

##### openapi-generator version

<=4.1.0 and master

##### OpenAPI declaration file content or url

/

##### Command line used for generation

openapi-generator generate -o api -g dart -i openapi-backend.yml -t <path-to-custom-templates>

##### Steps to reproduce

Use the command from above with a model like this:

```yaml
SomeEnum:
      type: string
      enum:
        - left
        - right
        - center
```

##### Related issues/PRs

fixes and used some changes from https://github.com/OpenAPITools/openapi-generator/issues/2830

##### Suggest a fix/enhancement

see PR
