### ISSUE TITLE
[BUG][KOTLIN] Bug generator Kotlin client definition with multiple enums

### ISSUE THREAD

**Issue by andrewemery** [OpenAPITools/openapi-generator#3917]
##### Description

Generating a Kotlin client that contains a definition with multiple enums produces invalid output.

##### openapi-generator version

4.1.2

##### OpenAPI declaration file content or url

```yaml
definitions:
  Pet:
    required:
        - one
        - two
    properties:
      one:
        type: string
        enum:
          - 'A'
          - 'B'
      two:
        type: string
        enum:
          - 'C'
          - 'D'
```

##### Command line used for generation

```bash
openapi-generator generate -g kotlin
```

##### Output

```kotlin
data class Pet (
    @Json(name = "one")
    val one: Pet.One,
    @Json(name = "two")
    val two: Pet.Two
)

{
    /**
    * 
    * Values: a,b
    */
    
    enum class One(val value: kotlin.String){
    
        @Json(name = "A") a("A"),
    
        @Json(name = "B") b("B");
    

    }
}

{
    /**
    * 
    * Values: c,d
    */
    
    enum class Two(val value: kotlin.String){
    
        @Json(name = "C") c("C"),
    
        @Json(name = "D") d("D");
    

    }
}
```

##### Expected output

```kotlin
data class Pet (
    @Json(name = "one")
    val one: Pet.One,
    @Json(name = "two")
    val two: Pet.Two
)

{
    /**
    * 
    * Values: a,b
    */
    
    enum class One(val value: kotlin.String){
    
        @Json(name = "A") a("A"),
    
        @Json(name = "B") b("B");
    

    }
    /**
    * 
    * Values: c,d
    */
    
    enum class Two(val value: kotlin.String){
    
        @Json(name = "C") c("C"),
    
        @Json(name = "D") d("D");
    

    }
}
```
