### ISSUE TITLE
[BUG][Angular] Query parameters with additionalProperties not serialized

### ISSUE THREAD

**Issue by deroude** [OpenAPITools/openapi-generator#3935]
##### Description

Having the following spec:

```yaml
'/v1/job':
    get:
      parameters:
      ...
        - name: sort
          in: query
          required: false
          style: form
          explode: false
          schema:
            type: object
            additionalProperties:
              type: string
              enum:
                - asc
                - desc
```

The TS is correctly generated:

```typescript
    getJobs(jobType: string, search?: string, limit?: number, page?: number, sort?: {
        [key: string]: 'asc' | 'desc';
    }, observe?: 'body', reportProgress?: boolean): Observable<Page>;
```

But the item is not serialized, instead I get a query like this: `host/jobs?sort=[object Object]`

##### Command line used for generation

/bin/docker run [...] openapitools/openapi-generator-cli generate -i source.yaml -g typescript-angular -o /data/sdk/angular --additional-properties=npmName=@api,withInterfaces=true,ngVersion=7.0.0

##### Suggest a fix/enhancement

Dictionary types should be serialized according to https://swagger.io/docs/specification/serialization/
