### ISSUE TITLE
[BUG][DART] oneOf dart code generation: wrong types and html-encoded code

### ISSUE THREAD

**Issue by alevinetx** [OpenAPITools/openapi-generator#3965]
#### Bug Report Checklist

- [ Y] Have you provided a full/minimal spec to reproduce the issue?
- [ Y] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ Y] What's the version of OpenAPI Generator used?
- [Y ] Have you search for related issues/PRs?
- [ Y] What's the actual output vs expected output?
- [ -] [Optional] Bounty to sponsor the fix ([example]

##### Description

When using oneOf, with options for String or int, the generated dart code produces the class model with a few errors:

1: OneOf<string, integer>  : where "string" should be "String", and "integer" should be "int".   These are produced as expected (String or int) with other simple entries.
```dart
part of openapi.api;
class Pet {
  OneOf<string,integer> bodyText = null;
```

2: The generated code has encoded the "<>" symbols in html form `(&lt;, &gt;)`

```dart
    if (json['bodyText'] == null) {
      bodyText = null;
    } else {
      bodyText = OneOf&lt;string,integer&gt;.fromJson(json['bodyText']);
```

##### openapi-generator version

$ openapi-generator version
4.1.2

##### OpenAPI declaration file content or url
openapi: 3.0.1

```yaml
    Blob:
      required:
      - name
      type: object
      properties:
        bodyText:
          oneOf:
            - type: string
            - type: integer
```

##### Command line used for generation

openapi-generator generate   -i oneof.yaml   -g dart       -o oneof-out3a      -p browserClient=false,supportDart2=true,generateAliasAsModel=true

##### Steps to reproduce

1: Use the default pet store model at https://editor.swagger.io/
2: Add these 4 lines to a model's properties:
```yaml
        bodyText:
          oneOf:
            - type: string
            - type: integer
```
3: Generate code in the manner shown above
4: Observe lib/model/<item>.dart code

##### Related issues/PRs

#3884 

##### Suggest a fix

If I knew, I'd drop a PR :)
