### ISSUE TITLE
[BUG][KOTLIN] Kotlin client unescaped string template

### ISSUE THREAD

**Issue by andrewemery** [OpenAPITools/openapi-generator#4228]
##### Description

Property names that include a dollar sign are being interpreted by Kotlin as a string template.

##### openapi-generator version

4.1.3

##### OpenAPI declaration file content or url

```yaml
definitions:
  '$special[model.name]':
    properties:
      '$special[property.name]':
        type: integer
        format: int64
```

Expected:

```kotlin
@SerialName(value = "\$special[property.name]") 
```

Actual:
```kotlin
@SerialName(value = "$special[property.name]") 
```

##### Command line used for generation

openapi-generator generate -g kotlin
