### ISSUE TITLE
[BUG] [Kotlin Client] Incorrect pipes and csv query collection delimeter

### ISSUE THREAD

**Issue by andrewemery** [OpenAPITools/openapi-generator#4285]
##### Description

Collection query parameters using `pipes` or `csv` formats is rendered incorrectly within the query string.

##### openapi-generator version

4.1.3

##### OpenAPI declaration file content or url

```yaml
  /example:
    put:
      parameters:
        - name: pipe
          in: query
          required: true
          type: array
          items:
            type: string
          collectionFormat: pipes
```

Expected:

```text
http://example.com/example?pipe=pipe1%7Cpipe2
```

Actual:

```text
http://example.com/example?pipe=pipe1pipe2
```

##### Command line used for generation

openapi-generator generate -g kotlin

##### Related issues/PRs

https://github.com/OpenAPITools/openapi-generator/pull/4248
