### ISSUE TITLE
[BUG][Openapi-yaml] Single quotes are deleted in examples

### ISSUE THREAD

**Issue by jorgerod** [OpenAPITools/openapi-generator#4365]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

I use the generator *openapi-yaml* for merge serveral yaml files into one. The bug is that the generator remove de simple quotes in examples.

##### openapi-generator version

4.1.3, 4.2.0

##### OpenAPI declaration file content or url
Simplified input file:

```yaml
openapi: 3.0.1
info:
  title: ping test
  version: '1.0'
servers:
  - url: 'http://localhost:8000/'
paths:
  /search:
    get:
      operationId: search
      parameters:
        - name: date
          in: query
          description: The date of the document.
          example: '2019-08-06T13:40:43.449Z'
          required: true
          schema:
            type: string
            format: date-time
      responses:
        '201':
          description: OK
```

##### Command line used for generation

 java -jar openapi-generator-cli.jar generate -g openapi-yaml -i openapi.yml

##### Steps to reproduce

Run the above command
Expected output:
```yaml
...
     parameters:
        - name: date
          in: query
          description: The date of the document.
          example: '2019-08-06T13:40:43.449Z'
...
```

Actual output:
```yaml
...
     parameters:
        - name: date
          in: query
          description: The date of the document.
          example: 2019-08-06T13:40:43.449Z
...
```
