### ISSUE TITLE
[BUG] node-express-server breaks multiline YAML descriptions

### ISSUE THREAD

**Issue by theletterf** [OpenAPITools/openapi-generator#4409]
#### Bug Report Checklist

When generating a node-express-server stub from an OpenAPI 3.0 YAML spec that has multiline descriptions like this...

```yaml
paths:
  /employees/{id}:
    get:
      description: |
        First line
        Second line

```

...openapi-generator produces a YAML file inside the /api folder that has escaped multiline descriptions:

```yaml
paths:
  /employees/{id}:
    get:
      description: "First line\
       \ Second line\n"
```
This then breaks the server when trying a quick run using `npm start`:

```
error: Malformed inline YAML string
```

##### openapi-generator version

1.0.2-4.2.0

##### Command line used for generation

```openapi-generator generate -i .\openapi.yaml -g nodejs-express-server -o ./server-st
ub --additional-properties=generateAliasAsModel=true```

##### Steps to reproduce

* Create OpenAPI 3.0 YAML file with multiline descriptions.
* Generate a nodejs-express-server stub from the YAML file.
* Run the server.

Eliminating the backslashes solves the problem.

##### Suggest a fix

Can't the YAML file simply be copied as is to the /api folder?
