### ISSUE TITLE
[REQ][Java] support anyOf Enum

### ISSUE THREAD

**Issue by lwlee2608** [OpenAPITools/openapi-generator#4491]
3GPP R15 has defined a set of standards in the form of [OpenAPI specification files](https://www.3gpp.org/ftp/Specs/latest/Rel-15/OpenAPI/).

The files are often lengthy and consist of oneOf, anyOf, allOf keywords. 

The following definition that combines `anyOf` with `enum` has been consistently poping up and it will break the openapi-generator 

```yaml
    RequestTrigger:
      anyOf:
      - type: string
        enum:
          - LOC_CH
          - PRA_CH
          - SERV_AREA_CH
          - RFSP_CH
          - ALLOWED_NSSAI_CH
          - UE_AMBR_CH
```
The issue has been raised in #798 
The solution was just workaround the spec files.

 However it would be nice if we can instead add an option to the generator to simply ignore the `anyOf`. Ideally we want the generator to work without any alteration to the spec files.
