### ISSUE TITLE
[BUG] PHPSlim4 - Want only 1 authentication method out of multiple

### ISSUE THREAD

**Issue by Sroose** [OpenAPITools/openapi-generator#4513]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used? 4.2.1
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
Actual: adds all security schemes in middlewares that all get executed. 
Expected: only one security scheme should match.

##### Description

The generator does not take into account the fact that multiple security schemes are defined as 'OR'. In other words, the generated PHP Slim code will always try to perform all authentication methods simultaneously.

They are added in the middewares like this:
```
$this->addRoute(..
                $middlewares
            )->setName($operation['operationId']);
```

##### openapi-generator version

4.2.1

##### OpenAPI declaration file content or url

```yaml
        get:
            ...
            security:
                -
                    AdminToken: []
                -
                    UserJWT: []
                -
                    ExternalToken: []
```

##### Steps to reproduce

Create an OpenApi operation with multiple possible security schemes.

##### Related issues/PRs

Looks similar to https://github.com/OpenAPITools/openapi-generator/issues/3844 for Python. Also https://github.com/OpenAPITools/openapi-generator/issues/797 seems relavant.
