### ISSUE TITLE
[REQ] More items in configuration file

### ISSUE THREAD

**Issue by MartinDelille** [OpenAPITools/openapi-generator#4558]
### Is your feature request related to a problem? Please describe.

Developing in Qt, I would like to perform the same code generation on MacOS/Windows/Linux.

In order to keep this generation consistent, I would like my CI scripts use the same configuration file.

It is already almost working thanks to the `generate --config` command:

```
openapi-generator generate --input-spec api.yaml --generator-name cpp-qt5-client --config config.yaml
```

With the following `config.yaml`:

```yaml
additionalProperties:
  cppNamespace: martindelille
  modelNamePrefix: MD
```

## Describe the solution you'd like

I would like to move the command line argument to the configuration file:

```
openapi-generator --config config.yaml
```

With the following `config.yaml`:

```yaml
action: generate
inputSpec: api.yaml
generateName: cpp-qt5-client
additionalProperties:
  cppNamespace: martindelille
  modelNamePrefix: MD
```

We could event go further by considering a `openapi-generator.yaml` file in the current folder could be used as default configuration file if no file is provided as argument.

## Describe alternatives you've considered

Keep using the current implementation.

## Additional context

Nope

**Comment by MartinDelille** [comment]
Ping @jimschubert

**Comment by jimschubert** [comment]
This is supported by the new (currently undocumented) `batch` command. I know you've tried that, what other details are you looking for here? Are you suggesting that we move that same config deserialization to a top-level invocation without the `generate` or `batch` commands?

**Comment by MartinDelille** [comment]
Ok I didn't tried the `batch`, only the `generate` with the `--config` option.

It doesn't work in the last release (4.2.1) but maybe it is for the next one?

```
$ openapi-generator bash config.yaml
[error] Found unexpected parameters: [bash, config.yaml]

See 'openapi-generator help' for usage.
```

**Comment by wing328** [comment]
You need to pass the config file via `-c` or `--config`, e.g.
```
openapi-generator generate -g bash -c config.yaml -i openapi_spec.yaml -o /var/tmp/output/
```

**Comment by MartinDelille** [comment]
Ok now I understand how the `bash` works.

Since `inputSpec` is specified in the configuration, it shouldn't be needed in the command line argument then? I checked and it is ignored now while it is used in many configuration files like https://github.com/OpenAPITools/openapi-generator/blob/master/bin/ci/python-petstore.json#L3

**Comment by jimschubert** [comment]
@MartinDelille to clarify, those scripts that move args to JSON are only supported by the `batch` command, not by `generate`.

Run `help batch` for options.

**Comment by MartinDelille** [comment]
With the latest release:

```
$ openapi-generator help bash
Unknown command bash
```

I tried to compile from master but have the same result.

**Comment by jimschubert** [comment]
@MartinDelille please note that the command is `batch` (i.e. run multiple operations) and not `bash` (i.e. the Unix shell called bash).

```bash
$ openapi-generator version
4.2.1
$ openapi-generator help batch
NAME
        openapi-generator-cli batch - Generate code in batch via external
        configs.

SYNOPSIS
        openapi-generator-cli batch [--fail-fast]
                [--includes-base-dir <includes>] [(-r <threads> | --threads <threads>)]
                [--root-dir <root>] [--timeout <timeout>] [(-v | --verbose)] [--]
                <configs>...

OPTIONS
        --fail-fast
            fail fast on any errors

        --includes-base-dir <includes>
            base directory used for includes

        -r <threads>, --threads <threads>
            thread count

        --root-dir <root>
            root directory used output/includes (includes can be overridden)

        --timeout <timeout>
            execution timeout (minutes)

        -v, --verbose
            verbose mode

        --
            This option can be used to separate command-line options from the
            list of argument, (useful when arguments might be mistaken for
            command-line options

        <configs>
            Generator configuration files.
```

Given your config (plus required outputDir property, removing invalid argument `action`, updating to valid arg `generatorName`):

```yaml
inputSpec: https://raw.githubusercontent.com/OpenAPITools/openapi-generator/master/modules/openapi-generator/src/test/resources/2_0/petstore.yaml
outputDir: out/cpp
generatorName: cpp-qt5-client
additionalProperties:
  cppNamespace: martindelille
  modelNamePrefix: MD
```

You can generate as:

```bash
$ openapi-generator batch --includes-base-dir `pwd` config.yaml
[main] INFO  o.o.codegen.cmd.GenerateBatch - Batch generation using 8 threads.
Includes: /Users/jim/temp/MartinDelille
Root: /Users/jim/temp/MartinDelille
[pool-1-thread-1] Generating cpp-qt5-client (outputs to /Users/jim/temp/MartinDelille/out/cpp)…
[pool-1-thread-1] Finished generating cpp-qt5-client…
COMPLETE.
```

This produces:

```bash
$ tree out/cpp
out/cpp
└── client
    ├── CMakeLists.txt
    ├── MDApiResponse.cpp
    ├── MDApiResponse.h
    ├── MDCategory.cpp
    ├── MDCategory.h
    ├── MDEnum.h
    ├── MDHelpers.cpp
    ├── MDHelpers.h
    ├── MDHttpFileElement.cpp
    ├── MDHttpFileElement.h
    ├── MDHttpRequest.cpp
    ├── MDHttpRequest.h
    ├── MDObject.h
    ├── MDOrder.cpp
    ├── MDOrder.h
    ├── MDPet.cpp
    ├── MDPet.h
    ├── MDPetApi.cpp
    ├── MDPetApi.h
    ├── MDStoreApi.cpp
    ├── MDStoreApi.h
    ├── MDTag.cpp
    ├── MDTag.h
    ├── MDUser.cpp
    ├── MDUser.h
    ├── MDUserApi.cpp
    ├── MDUserApi.h
    └── MDclient.pri

1 directory, 28 files
```

The reason this is called `batch` is because you can pass multiple config files in a single command (and single JVM instance). For instance, if we were to create `kotlin.yaml` in the same directory:

```yaml
inputSpec: https://raw.githubusercontent.com/OpenAPITools/openapi-generator/master/modules/openapi-generator/src/test/resources/2_0/petstore.yaml
outputDir: out/kotlin
generatorName: kotlin
artifactId: kotlin-petstore-string
additionalProperties:
  dateLibrary: string
  serializableModel: "true"
```

And regenerate (notice the use of multiple threads, which we are evaluating in CI for 100+ generations):

```bash
openapi-generator batch --includes-base-dir `pwd` *.yaml
[main] INFO  o.o.codegen.cmd.GenerateBatch - Batch generation using 8 threads.
Includes: /Users/jim/temp/MartinDelille
Root: /Users/jim/temp/MartinDelille
[pool-1-thread-1] Generating cpp-qt5-client (outputs to /Users/jim/temp/MartinDelille/out/cpp)…
[pool-1-thread-2] Generating kotlin (outputs to /Users/jim/temp/MartinDelille/out/kotlin)…
[pool-1-thread-1] Finished generating cpp-qt5-client…
[pool-1-thread-2] Finished generating kotlin…
COMPLETE.
```

And new outputs:

```bash
$ tree out/kotlin
out/kotlin
├── README.md
├── build.gradle
├── docs
│   ├── ApiResponse.md
│   ├── Category.md
│   ├── Order.md
│   ├── Pet.md
│   ├── PetApi.md
│   ├── StoreApi.md
│   ├── Tag.md
│   ├── User.md
│   └── UserApi.md
├── settings.gradle
└── src
    └── main
        └── kotlin
            └── org
                └── openapitools
                    └── client
                        ├── apis
                        │   ├── PetApi.kt
                        │   ├── StoreApi.kt
                        │   └── UserApi.kt
                        ├── infrastructure
                        │   ├── ApiAbstractions.kt
                        │   ├── ApiClient.kt
                        │   ├── ApiInfrastructureResponse.kt
                        │   ├── ApplicationDelegates.kt
                        │   ├── ByteArrayAdapter.kt
                        │   ├── Errors.kt
                        │   ├── LocalDateAdapter.kt
                        │   ├── LocalDateTimeAdapter.kt
                        │   ├── RequestConfig.kt
                        │   ├── RequestMethod.kt
                        │   ├── ResponseExtensions.kt
                        │   ├── Serializer.kt
                        │   └── UUIDAdapter.kt
                        └── models
                            ├── ApiResponse.kt
                            ├── Category.kt
                            ├── Order.kt
                            ├── Pet.kt
                            ├── Tag.kt
                            └── User.kt

10 directories, 34 files
```

This is undocumented because there are user-quality things that haven't been evaluated (combinations of args, output such as `Batch generation using 8 threads` when generating less than 8 configs).

I apologize for any confusion about the above. Based on our conversation in Slack, I thought you had tried this command and determined it to be exactly what you were looking for. This is why I was confused about the additional ask in this issue.

Based on your suggested improvement, I think we could look into whether the CLI could default to batch generation if no command is specified.  For instance, adding support for this type of invocation:

```bash
$ openapi-generator *.yaml
```

**Comment by jimschubert** [comment]
And a note on shared configs. I added support to the batch command to use a directive-type property called `!include` to merge in shared configs.

You could create a file at `shared/common.yaml`:

```yaml
inputSpec: https://raw.githubusercontent.com/OpenAPITools/openapi-generator/master/modules/openapi-generator/src/test/resources/2_0/petstore.yaml
additionalProperties:
    x-ext-name: "Jim Schubert"
```

And remove `inputSpec` from the configs listed in my previous comment, in favor of `!include`. This would point to the path either relative to your "root" (current) directory, or customized. For instance:

```yaml
'!include': common.yaml
outputDir: out/cpp
generatorName: cpp-qt5-client
additionalProperties:
  cppNamespace: martindelille
  modelNamePrefix: MD
```

Here, I want to include `common.yaml`. Invoke like so:

```bash
$ openapi-generator batch --includes-base-dir `pwd`/shared *.yaml
[main] INFO  o.o.codegen.cmd.GenerateBatch - Batch generation using 8 threads.
Includes: /Users/jim/temp/MartinDelille/shared
Root: /Users/jim/temp/MartinDelille
[pool-1-thread-1] Generating cpp-qt5-client (outputs to /Users/jim/temp/MartinDelille/out/cpp)…
[pool-1-thread-2] Generating kotlin (outputs to /Users/jim/temp/MartinDelille/out/kotlin)…
[pool-1-thread-1] Finished generating cpp-qt5-client…
[pool-1-thread-2] Finished generating kotlin…
COMPLETE.
```

The include path could also be relative (`'!include': shared/common.yaml`).

This functionality allowed me to refer to existing externalized configs under `bin/*.json` which would fail deserialization if I added CLI arg properties like `artifactId` to them.  But, it also comes in handy if you're generating many clients with many shared configurations such as Java generators. This doesn't support merging multiple `!include` configs, because that's a little more complex.

Also note that this works with JSON configs and YAML config. Everything under `bin/ci` is JSON config examples.
