### ISSUE TITLE
[BUG] [GO] can't generate codes with xml tag

### ISSUE THREAD

**Issue by gold-kou** [OpenAPITools/openapi-generator#4733]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description
even though i use `withXml=true`, can't generate codes with xml tag .

actual:

```
type ResponseSample struct {

	StatusCode int64 `json:"status_code"`

	Message string `json:"message"`
}
```

expected(like this):

```
type ResponseSample struct {

        XMLName xml.Name `xml:"response"`

	StatusCode int64 `xml:"status_code"`

	Message string `xml:"message"`
}
```

My Go version: 
go version go1.12.13 darwin/amd64

##### openapi-generator version
v4.1.2

##### OpenAPI declaration file content or url
```yaml
ResponseSample:
      type: object
      properties:
        status_code:
          type: integer
          format: int64
          example: 0
        message:
          type: string
          example: 'success'
      xml:
        name: response
      required:
        - status_code
        - message
```

##### Command line used for generation
```
docker run -v ${PWD}:/local openapitools/openapi-generator-cli:v4.1.2 generate \
  -i /local/openapi/openapi.yaml \
  -g go-server \
  -p withXml=true \
  --output /local/${GENERATE_PATH}
```

##### Steps to reproduce
please paste the above yaml, then docker run.

##### Related issues/PRs
https://github.com/OpenAPITools/openapi-generator/issues/490
