### ISSUE TITLE
[BUG][TYPESCRIPT-RXJS] Format Date is converted to Date-Time

### ISSUE THREAD

**Issue by guidoknoll** [OpenAPITools/openapi-generator#4763]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?

##### Description

Hey,

when generating a parameter with the format 'date', it is falsely converted to 'date-time'. So in my case 'dateFrom' contains a time (e.g. '2019-12-10T17:56:56.999Z'), but should look like this: '2019-12-10'.

##### openapi-generator version

4.2.2

##### OpenAPI declaration file content or url
```yaml
...
- name: date_from
          in: query
          description: >-
            Date parameter to search for ... (format\: \"yyyy-MM-dd\")
          required: false
          schema:
            type: string
            format: date
...
```

##### Command line used for generation

`openapi-generator generate -i assets/api.yaml -g typescript-rxjs -o src/lib`

##### Steps to reproduce

- Generate the api
- View the dateFrom parameter

##### Suggest a fix

As in the typescript-fetch generator, write instead of `.toISOString()`:

`.toISOString().substr(0,10)` or
`.toISOString().split('T')[0]`
