### ISSUE TITLE
[BUG][Kotlin] Query params are converted from snake_case to camelCase

### ISSUE THREAD

**Issue by facundomedica** [OpenAPITools/openapi-generator#4819]
##### Description

A query param that is in snake case is converted to camelCase in the generated code, so the requests do `myendpoint?deviceId=AAAAA` instead of `myendpoint?device_id=AAAAA`

```yaml
        - name: device_id
          in: query
          description: device external ID
          type: string
```

##### openapi-generator version

```
openapi-generator-gradle-plugin:4.2.2
```

##### OpenAPI declaration file content or url

```yaml
        - name: device_id
          in: query
          description: device external ID
          type: string
```
