### ISSUE TITLE
[REQ][Java] Enum name should have underscore in case the value is pascal case

### ISSUE THREAD

**Issue by zawataki** [OpenAPITools/openapi-generator#4837]
### Is your feature request related to a problem? Please describe.
If string enum value in OpenAPI definition is pascal case, the enum name on generated Java client will be named without underscores like below:
```java
  public enum StatusEnum {
    WAITINGFORSOMETHING("WaitingForSomething"),
```

## Describe the solution you'd like
I think that should be named with underscores for readability like below:
```java
  public enum StatusEnum {
    WAITING_FOR_SOMETHING("WaitingForSomething"),
```

## Describe alternatives you've considered
Nothing.

## Additional context
Nothing.

**Comment by jmini** [comment]
> Describe alternatives you've considered

You could use `x-enum-varnames` to influence the name of the enum:

```yaml
Status:
  type: string
  enum:
    - WaitingForSomething
    - Done
  x-enum-varnames:
    - WAITING_FOR_SOMETHING
    - DONE
```
