### ISSUE TITLE
[Golang][client] Posting file limitations - MIME part name, multiple files, etc.

### ISSUE THREAD

**Issue by grokify** [OpenAPITools/openapi-generator#505]
##### Description

(1) MIME part name
Customized `multipart/form-data` `name` parameter. Right now this is hardcoded to `file`. This means APIs that expect a particular part name will not recognize the file.

https://github.com/OpenAPITools/openapi-generator/blob/a14e757059e8db02260f06263675d581dcdc33fb/modules/openapi-generator/src/main/resources/go/client.mustache#L210

(2) Multiple files

Currently, only one file is supported, required or optional given the interface for `APIClient.prepareRequest`

(3) Multiple MIME part names

Ability to have multiple part names for files.

##### openapi-generator version

3.1.0 and `master`

##### OpenAPI declaration file content or url

https://github.com/grokify/go-ringcentral/blob/master/codegen/swagger_spec.yaml

```yaml
          -
            name: "attachment"
            in: "formData"
            description: "File to upload"
            required: false
            type: "file"
```

##### Command line used for generation

Any

##### Steps to reproduce

1. Examine `client.mustache`.
1. Create client and send request.

##### Related issues/PRs

https://github.com/grokify/go-ringcentral/issues/16

##### Suggest a fix/enhancement

Simple fix for existing one file with correct MIME part name.

* Add a parameter `localVarFormFileName` to `APIClient.prepareRequest`
* Set `localVarFormFileName` in every generated API call that calls `APIClient.prepareRequest`
* Set `localVarFormFileName` to part name when present

Consider larger fix to support multiple part names and multiple files per part name.
