### ISSUE TITLE
[BUG] C "-" in Parametername is converted to "_"

### ISSUE THREAD

**Issue by axbusch** [OpenAPITools/openapi-generator#5101]
Version: 4.2.3-SNAPSHOT

```
 parameters:
      - name: x-api-token
          in: header
          description: Authorization Token
          required: false
          type: string
```

The generated code is:

```
 char* valueHeader_x_api_token;
  keyValuePair_t* keyPairHeader_x_api_token = 0;
  if (x_api_token) {
    keyHeader_x_api_token = strdup("x_api_token");
    valueHeader_x_api_token = strdup((x_api_token));
    keyPairHeader_x_api_token = keyValuePair_create(keyHeader_x_api_token, valueHeader_x_api_token);
    list_addElement(localVarHeaderParameters, keyPairHeader_x_api_token);
  }
```

but i would expect
```
keyHeader_x_api_token = strdup("x-api-token");
```
