### ISSUE TITLE
[BUG] python-flask: oneOf model class doesn't generate though imported

### ISSUE THREAD

**Issue by zhanwenchen** [OpenAPITools/openapi-generator#5187]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] What's the version of OpenAPI Generator used?
- [ ] Have you search for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

**Comment by ssYkse** [comment]
I am facing the same. In one of my models:

`from openapi_server.models.one_ofstringnumberboolean import OneOfstringnumberboolean  # noqa: E501`

however this file doesn't exist:
`
    from openapi_server.models.one_ofstringnumberboolean import OneOfstringnumberboolean
ModuleNotFoundError: No module named 'openapi_server.models.one_ofstringnumberboolean'
`

the component yaml looks as follows:

```
    pair:
      type: object
      properties:
        proba:
          type: number
        label:
          oneOf:
          - type: string
          - type: number
          - type: boolean
      required:
        - proba
        - label
```
