### ISSUE TITLE
[BUG][Typescript-Fetch] Incorrect toJSON & fromJSONTyped functions

### ISSUE THREAD

**Issue by jamesopti** [OpenAPITools/openapi-generator#5202]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] What's the version of OpenAPI Generator used?
- [X] Have you search for related issues/PRs?
- [X] What's the actual output vs expected output?

##### Description

For a property defined using `oneOf`, invalid methods are generated for `<Model>FromJSONTyped` and for `<Model>ToJSON`:

```js
export function TodosFromJSONTyped(json: any, ignoreDiscriminator: boolean): Todos {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'url': json['url'],
        'firstUrl': !exists(json, 'first_url') ? undefined : json['first_url'],
        'lastUrl': !exists(json, 'last_url') ? undefined : json['last_url'],
        'prevUrl': !exists(json, 'prev_url') ? undefined : string | UrlListFromJSON(json['prev_url']),
        'nextUrl': !exists(json, 'next_url') ? undefined : string | UrlListFromJSON(json['next_url']),
        'createUrl': !exists(json, 'create_url') ? undefined : json['create_url'],
        'findTodoUrl': json['find_todo_url'],
        'count': json['count'],
        'page': json['page'],
        'totalCount': json['total_count'],
        'totalPages': json['total_pages'],
        'items': ((json['items'] as Array<any>).map(TodoFromJSON)),
    };
}
```

```js
export function TodosToJSON(value?: Todos | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'url': value.url,
        'first_url': value.firstUrl,
        'last_url': value.lastUrl,
        'prev_url': string | UrlListToJSON(value.prevUrl),  // THIS IS INVALID TYPESCRIPT
        'next_url': string | UrlListToJSON(value.nextUrl), // THIS IS INVALID TYPESCRIPT
        'create_url': value.createUrl,
        'find_todo_url': value.findTodoUrl,
        'count': value.count,
        'page': value.page,
        'total_count': value.totalCount,
        'total_pages': value.totalPages,
        'items': ((value.items as Array<any>).map(TodoToJSON)),
    };
}
```

### The interface for the above type `Todos`
<details>
  <summary>Click to expand</summary>
  
```js
export interface Todos {
    /**
     * Link for the current page of results in the series.
     * @type {string}
     * @memberof Todos
     */
    url: string;
    /**
     * Links to first pages of results in a series.
     * @type {string}
     * @memberof Todos
     */
    firstUrl?: string;
    /**
     * Link to the last page of results in a series.
     * @type {string}
     * @memberof Todos
     */
    lastUrl?: string;
    /**
     * List of links to previous pages of results in a series.  The first element in the array is the exact previous page before the current record, etc. 
     * @type {string | UrlList}
     * @memberof Todos
     */
    prevUrl?: string | UrlList;
    /**
     * List of links to next pages of results in a series.   The first element in the array is the exact next page after the current record, etc. 
     * @type {string | UrlList}
     * @memberof Todos
     */
    nextUrl?: string | UrlList;
    /**
     * The url used to create a Todo. If not present, the current user is not authorized to create.
     * @type {string}
     * @memberof Todos
     */
    createUrl?: string;
    /**
     * A url template to be used to find a particular todo. 
     * @type {string}
     * @memberof Todos
     */
    findTodoUrl: string;
    /**
     * Number of records on the current page.
     * @type {number}
     * @memberof Todos
     */
    count: number;
    /**
     * Number of the current page. 1-index based.
     * @type {number}
     * @memberof Todos
     */
    page: number;
    /**
     * Total number of records for this series.
     * @type {number}
     * @memberof Todos
     */
    totalCount: number;
    /**
     * Total number of pages for this series.
     * @type {number}
     * @memberof Todos
     */
    totalPages: number;
    /**
     * 
     * @type {Array<Todo>}
     * @memberof Todos
     */
    items: Array<Todo>;
}
```

</details>

##### openapi-generator version

`4.2.3` via 

```
yarn list v1.21.0
└─ @openapitools/openapi-generator-cli@1.0.10-4.2.3
```

##### OpenAPI declaration file content or url

```yaml
  schemas:
    urlValue:
      type: string
      description: A single url.
    urlList:
      type: array
      description: A list of urls.
      items:
        type: string

...

# For a property

        prev_url:
          description: |
            List of links to previous pages of results in a series.

            The first element in the array is the exact previous page before the current record, etc.
          oneOf:
            - $ref: '#/components/schemas/urlValue'
            - $ref: '#/components/schemas/urlList'
```

##### Command line used for generation

`./node_modules/@openapitools/openapi-generator-cli/bin/openapi-generator generate -g typescript-fetch -i ./openapi.yaml -o .`

**CONFIG:** - `"generateAliasAsModel": true`

**Comment by fantapop** [comment]
@eriktim any thought on whats going wrong here?

**Comment by fantapop** [comment]
Thank you for the hints here. Looking closer at the open api spec, I see that the generated typescript is more like `anyOf`.  It looks like `oneOf` is intended to be an exclusive Or.  `anyOf`, however, seems to fail in the same way.

**Comment by eriktim** [comment]
@fantapop You are right. Though `anyOf` would also allow a mixture of types (e.g. two fields from type A and one field from type B). I personally favor the use case of defining union/sum types.
To fully support the exclusivity, I guess the generator should apply strict de-serialisation first.

**Comment by fantapop** [comment]
I recently had a similar conversation with one of the maintainers of the https://github.com/lukeautry/tsoa project which generates an open api spec from typescript definitions.  They are now using `anyOf` as their implementation of union which I think makes sense.  It's very important to me that the generated typescript types from the open api spec are compatible with the input types that generate them in the tsoa project.  Some of the nuances of these types are a little over my head.  @eriktim Do you agree that `anyOf` would translate best to a straight typescript union?   I was thinking `oneOf` could be something like what's arrived at here: https://timhwang21.gitbook.io/index/programming/typescript/xor-type .  Although, I'm not really seeing how TSOA would translate something like a `oneOf` from their end unless some more prescriptive type or syntax was released by the typescript project or if unless there was a documented type name that could be used for that specific purpose.  Regardless, it feels like getting the union definition working is a very important step in bringing this template along.  I wonder if the true nature of this bug is really, how should unions work vs how should `oneOf` be translated.

**Comment by fantapop** [comment]
I've been tinkering around with this for a couple of evenings now.  I was able to get something working for top level anyOf/oneOf types but there is not enough data provided by the core to build out the proper support for inline types.  That happens to be most of the use case for our current spec.  It looks like this outstanding PR get's most of the way if not all of the way there.  https://github.com/OpenAPITools/openapi-generator/pull/3162

**Comment by AntunVukicevic** [comment]
Hey 👋🏻  
Any new about this one? Atm open-api-generator is producing invalid Typescript for `toJSON` & `fromJSON` functions when `oneOf` is used with enums 😞 

Example code:
```
...
components:
  schemas:
    TopLvlEnum:
      oneOf:
        - $ref: "#/components/schemas/EnumA"
        - $ref: "#/components/schemas/EnumB"
        - $ref: "#/components/schemas/EnumC"
    EnumA:
      type: string
      enum:
        - optionA1
        - optionA2
    EnumB:
      type: string
      enum:
        - optionB1
        - optionB2
    EnumC:
      type: string
      enum:
        - optionC1
        - optionC2
...
```

**Comment by fantapop** [comment]
@AntunVukicevic It's not great but I utilize the post processing feature of open api generator cli to programmatically fix errors. Here is a copy of the node script I use for this purpose.  

```js
#!/usr/local/bin/node

const fs = require('fs').promises;
const path = require('path');

function escapeRegex(string) {
    return string.replace(/[-/\\^$*+?.()|[\]{}]/g, '\\$&');
}

// prettier-ignore
const replacementsByFile = {
    'models/MediaCollection.ts': [
      {
        source: "MediaSizeName | MediaNameFromJSON(json['media-key'])",
        replacement: "json['media-key'] as MediaSizeName | MediaName",
      },
      {
        source: "MediaSizeName | MediaNameToJSON(value.media_key)",
        replacement: 'value.media_key',
      },
    ],
    'models/JobTemplateAttributes.ts': [
      {
        source: ".map(number | stringFromJSON)",
        replacement: " as Array<number | string>",
      },
      {
        source: ".map(number | stringToJSON)",
        replacement: "",
      },
    ]
};

async function main() {
    const [, , filePath] = process.argv;
    const relativePath = path.relative(
        path.resolve(`${__dirname}/../src/generated/client/src/`),
        filePath,
    );
    const fileReplacements = replacementsByFile[relativePath] || [];
    if (fileReplacements.length) {
        let data = await fs.readFile(filePath);
        for (const { source, replacement } of fileReplacements) {
            const sourceRegex = new RegExp(escapeRegex(source), 'g');
            data = data.toString().replace(sourceRegex, replacement);
        }
        await fs.writeFile(filePath, data);
    }
}

main().then(() => process.exit(0)).catch(console.error);
```

It's triggered by using the `TS_POST_PROCESS_FILE` environment variable.  Here is the package.json script entry I'm using.
```json
        "client:gen": "rm -rf ./src/generated/client && TS_POST_PROCESS_FILE='bin/postProcess.js' yarn openapi-generator-cli generate && cd ./src/generated/client/ && yarn",
```

**Comment by tusharchutani** [comment]
@fantapop is there any progress on this? I am having similar issues.

**Comment by prince-chrismc** [comment]
I opened a PR trying to unblock this, it at least gives us a workaround...  @eriktim @jamesopti @fantapop maybe you can take a look at #10017?

**Comment by italoservio** [comment]
Based on [this comment](https://github.com/OpenAPITools/openapi-generator/issues/5202#issuecomment-618413222), I managed to solve my problem. Hopefully it may help someone, so I'll leave how I did it here.

I had to move from this implementation that was causing this issue:
```yaml
type: object
properties:
  # ...
  query:
    field:
      type: string
      description: The field to search in the version
      example: "title"
    operator:
      type: string
      description: Operator to use for the search
      enum:
        - AND
        - OR
      example: OR
    value:
      oneOf:
        - type: string
          description: The value to search for in the field
          example: "example"
        - type: integer
          description: The value to search for in the field
          example: 123
```
To this implementation:
```yaml
type: object
properties:
  # ...
  query:
      type: array
      items:
        oneOf:
          - $ref: './search/StringQuery.yaml'
          - $ref: './search/IntegerQuery.yaml'
```
This way I had to define "field", "operator" and "value" in each of the query types in order to accept multiple values and generate proper Typescript definitions:
```yaml
# StringQuery.yaml
type: object
allOf:
  - $ref: './CommonSearchFields.yaml'
  - type: object
    properties:
      value:
        type: string
        description: String value to search for in the specified field
        example: "b155b2ad-6977-4b02-9016-eb0edaeb19c7"

# IntegerQuery.yaml
type: object
allOf:
  - $ref: './CommonSearchFields.yaml'
  - type: object
    properties:
      value:
        type: integer
        description: Integer value to search for in the specified field
        example: 12

# CommonSearchFields.yaml
type: object
properties:
  field:
    type: string
    description: The field to search in the version
    example: "title"
  operator:
    type: string
    description: Operator to use for the search
    enum:
      - AND
      - OR
    example: OR
```
