### ISSUE TITLE
[Go] Support the marking of fields as XML attributes

### ISSUE THREAD

**Issue by siddharthist** [OpenAPITools/openapi-generator#523]
##### Description

When I mark a `property` as an attribute, it isn't reflected in the Go code. This: 
```yaml
    T:
      properties:
        Foo:
          type: boolean
          xml:
            attribute: true
```
should yield
```go
type T struct {
   [...]
   Foo `xml:"Foo,attr"`
}
```
but currently is missing the `attr` part.

##### openapi-generator version

Docker container
