### ISSUE TITLE
[BUG] [CORE] Don't have the inline model resolver extract composed schemas

### ISSUE THREAD

**Issue by spacether** [OpenAPITools/openapi-generator#5230]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] What's the version of OpenAPI Generator used?
- [ ] Have you search for related issues/PRs?
- [X] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

Per our conversation in https://github.com/OpenAPITools/openapi-generator/pull/4906
When parsing a composed schema, the inline model resolver should not extract composed schemas per the Openapi spec:

> Specifically, the spec at https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#discriminator-object says:

When using the discriminator, inline schemas will not be considered.

##### openapi-generator version

master branch

##### OpenAPI declaration file content or url

```
    FruitInlineDisc:
      oneOf:
        - type: object
          required:
            - seeds
            - fruitType
          properties:
            seeds:
              type: integer
            fruitType:
              type: string
        - type: object
          required:
            - length
            - fruitType
          properties:
            length:
              type: integer
            fruitType:
              type: string
      discriminator:
        propertyName: fruitType
```

##### Command line used for generation

use the python generator with this spec

##### Steps to reproduce

Debug the models and you will see that new models are created from the composed inline schemas. They should not be extracted.

##### Related issues/PRs

https://github.com/OpenAPITools/openapi-generator/pull/4906

##### Suggest a fix

Don't extract the inline schemas when a composed schema has a discriminator
