### ISSUE TITLE
[REQ] Pattern validation in Go generator

### ISSUE THREAD

**Issue by onitake** [OpenAPITools/openapi-generator#5311]
### Is your feature request related to a problem? Please describe.

The go generator currently doesn't support any form of string validation.

OpenAPI has a pattern parameter on properties that allows specifying a validation regex, and this is supported for some generators, but not Go.

## Describe the solution you'd like

There are several Go packages available that support regex validation on struct fields via annotations.

I'm using https://github.com/go-validator/validator/tree/v2 at the moment, with structs of this form:
```go
type MyObject struct {
	// An IPv4 address
	IPAddress string `json:"IPAddress" validate:"regexp=^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/[0-9]{1,2}$"`
}
```

This struct should be generated by an OpenAPI definition like this:
```yaml
MyObject:
  type: object
  properties:
    IPAddress:
      type: string
      description: An IPv4 address
      pattern: '^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/[0-9]{1,2}$'
```

## Describe alternatives you've considered

Since the `pattern` field doesn't do anything, I'm using `x-go-custom-tag` instead, but this isn't portable to other languages:
```yaml
MyObject:
  type: object
  properties:
    IPAddress:
      type: string
      description: An IPv4 address
      x-go-custom-tag: validate:"regexp=^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/[0-9]{1,2}$"
```
