### ISSUE TITLE
[JAVA] Hierarchical Code Generation

### ISSUE THREAD

**Issue by emreakca** [OpenAPITools/openapi-generator#532]
##### Description

Hello,

I want to generate fluent code. Since OpenAPI 3.0 doesn't support subtags, the openapi-generator can't achieve this. Lets take the petstore as example and extend it:

```yaml
/pets:
  get:
    tags:
      - Pets
/pets/insects:
  get:
    tags:
      - PetsInsects
/pets/insects/ants:
  get:
    tags:
      - PetsInsectsAnts
/pets/{id}/toys:
  post:
  .
  .
  .
```
As you can see, I used the Paths as Tags, so the openapi-generator generates seperate APIs (PetsApi.java, PetsInsectsApi.java,PetsInsectsAntsApi.java). With this method we achieved a more programmer-friendly generated code. But that's not exactly what we want. We want to call, for example, the get method for /pets/insects/ants via ```pets.insects.ants.list()``` or for another insect ```pets.insects.bees.list()```. 
```pets("b98195f5-93f2-4874-bb1a-70222b170913").toy.create(myToy)```

Now my question: Can you suggest us how we can achieve fluent code?
