### ISSUE TITLE
[BUG][Go] Badly formated enum name

### ISSUE THREAD

**Issue by Magicking** [OpenAPITools/openapi-generator#5357]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] What's the version of OpenAPI Generator used? => 
- [ ] Have you search for related issues/PRs?
- [ ] What's the actual output vs expected output?

##### Description

Shared type is incorrectly formated (snake_case instead of camel case) and results in a non-exported type where it's properly camel_cased in other part of the code

##### openapi-generator version

4.3.0-Snapshot (latest docker image)

##### Steps to reproduce

Run the command above

**Comment by onitake** [comment]
I'm also using the latest docker image, and don't see this bug:
```yaml
components:
  schemas:
    Status:
      type: string
      enum:
      - init
      - queued
      - running
      - done
      - error
      description: The current application status
      example: running
```
produces:
```go
package openapi
// Status The current application status
type Status string

// List of Status
const (
	INIT Status = "init"
	QUEUED Status = "queued"
	RUNNING Status = "running"
	DONE Status = "done"
	ERROR Status = "error"
)
```
While the naming concept of the enum keys is questionable (they should be namespaced and in camel case IMHO), the type identifier is how it should be.
Can you post your API spec?
