### ISSUE TITLE
[BUG] aspnetcore enum generation

### ISSUE THREAD

**Issue by damstradevelopment** [OpenAPITools/openapi-generator#5390]
Openapi Generator 4.3.0 using latest master branch as 20/02/2020.

I have setup the enum in openapi as:

```
TestEnum:
  type: integer
  enum:
    - 1
    - 2
    - 4
    - 5
  x-enum-varnames:
    - testa
    - testb
    - testc
    - testd
```

However, upon generation it still sets it as string type and does not assign the numeric values to the relative name

```
[TypeConverter(typeof(CustomEnumConverter<TestEnum>))]
[JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
public enum TestEnum
{
    [EnumMember(Value = "1")]
    testa= 1,
    [EnumMember(Value = "2")]
    testb = 2,
    [EnumMember(Value = "4")]
    testc = 3,
    [EnumMember(Value = "5")]
    testd = 4
}

```
