### ISSUE TITLE
[REQ] [Axios-Typescript] Create enumerator for parameters 

### ISSUE THREAD

**Issue by vitorcamachoo** [OpenAPITools/openapi-generator#5770]
### Is your feature request related to a problem? Please describe.
When we have some parameter which is a enum, the generator is not creating and enumerator which can be used as a model. For example, for the following parameter (imageType) which is an enumerator:

```yaml
/v1/users/settings/photo:
    get:
      operationId: getUserPhoto
      summary: Get User Photo
      tags:
        - Users
      parameters:
        - name: imageType
          in: query
          type: string
          enum:
            - b64
            - uri
```
It generates the following code:
```ts
getUserPhoto(imageType?: 'b64' | 'uri', options: any = {}): RequestArgs {
...
```

and it should generate something like this:
```ts
import { imageTypeEnum } from 'api/models' // pseudo import

getUserPhoto(imageType?: imageTypeEnum, options: any = {}): RequestArgs {
...
```
