### ISSUE TITLE
[BUG][Elm] Generated code doesn't parse

### ISSUE THREAD

**Issue by domenkozar** [OpenAPITools/openapi-generator#5878]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?

##### Description

Given the schema below, see that Elm generator has wrong behavior.

##### openapi-generator version

5.0.0 branch, 4th Feb 2020

##### OpenAPI declaration file content or url

```yaml
    uuid4:
      type: string
      # Taken from https://stackoverflow.com/a/38191078/133235
      pattern: '^[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[4][0-9A-Fa-f]{3}-[89ABab][0-9A-Fa-f]{3}-[0-9A-Fa-f]{12}$'
```

##### Command line used for generation

`openapi-generator-cli  generate --input-spec openapi.yaml --enable-post-process-file --generator-name elm --config openapi-generator.yml  --output openapi-client`

##### Steps to reproduce

Generates `encodeUuid4Pairs` with a syntax error:

```elm
encodeUuid4 : Uuid4 -> Json.Encode.Value
encodeUuid4 =
    encodeObject << encodeUuid4Pairs


encodeUuid4WithTag : ( String, String ) -> Uuid4 -> Json.Encode.Value
encodeUuid4WithTag (tagField, tag) model =
    encodeObject (encodeUuid4Pairs model ++ [ encode tagField Json.Encode.string tag ])


encodeUuid4Pairs : Uuid4 -> List EncodedField
encodeUuid4Pairs model =
    let
        pairs =
            ]
    in
    pairs
```

cc @eriktim
