### ISSUE TITLE
[BUG] go-server doesn't generate the same name of query param from the client

### ISSUE THREAD

**Issue by ReSTARTR** [OpenAPITools/openapi-generator#5896]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [x] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

```yaml
      parameters:
      - description: 'pet id'
        in: query
        name: pet_id
        required: true
        schema:
          format: int64
          type: integer
        style: form
```

When I defined query name with snake_case style, `go-server` generator generated code like this.

```go
// api_default.go

// GetPet - 
func (c *DefaultApiController) GetPet(w http.ResponseWriter, r *http.Request) { 
	query := r.URL.Query()
	petId, err := parseIntParameter(query.Get("petId"))
```

But, from the same definition, `go` generator generates code like this.

```go
// api_default.go

func (a *DefaultApiService) GetPet(ctx _context.Context, petId int64) (*_nethttp.Response, error) {
          : 
          :
	localVarQueryParams.Add("pet_id", parameterToString(petId, ""))
```

I want the server and the client to use the same name of query parameter `"pet_id"`.

##### openapi-generator version

4.3.1-SNAPSHOT

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.0
info:
  description: 'OpenAPI Petstore'
  title: OpenAPI Petstore
  version: 1.0.0
servers:
- description: The local server
  url: https://localhost:8080/{version}
paths:
  /pets:
    get:
      operationId: getPet
      parameters:
      - description: 'pet id'
        in: query
        name: pet_id
        required: true
        schema:
          format: int64
          type: integer
        style: form
      responses:
        "200":
          content: {}
          description: ""
```

##### Command line used for generation

for server 

```
docker run --rm -v ${PWD}:/local openapitools/openapi-generator-cli:latest generate \
-i /local/openapi.yaml \
-g go-server -o /local/go-server
```

for client

```
docker run --rm -v ${PWD}:/local openapitools/openapi-generator-cli:latest generate \
-i /local/openapi.yaml \
-g go -o /local/go
```

**Comment by y14a** [comment]
May this issue also occurs if specified uppercase in a name of a parameter definition.

A parameter definition excerpted from my OAS3 YAML file.
```yaml
      - explode: false
        in: header
        name: X-MS-TOKEN-AAD-ID-TOKEN
        required: true
        schema:
          type: string
        style: simple
```

Generated code by using `go-server` generator

```go
	xMSTOKENAADIDTOKEN := r.Header.Get("xMSTOKENAADIDTOKEN")
```
