### ISSUE TITLE
[BUG][MARKDOWN] Enums in model are empty

### ISSUE THREAD

**Issue by zeljkot** [OpenAPITools/openapi-generator#6097]
##### Description

Enums in a model do not show possible values; they just have an empty table like regular objects, which is not suitable here.

```yaml
components:
  schemas:
    WarningType:
      enum:
        - FORMATTED
        - DISCONTINUITY
        - SWITCH
```

```markdown
# WarningType
## Properties

Name | Type | Description | Notes
------------ | ------------- | ------------- | -------------

[[Back to Model list]](../README.md#documentation-for-models) [[Back to API list]](../README.md#documentation-for-api-endpoints) [[Back to README]](../README.md)

```

##### openapi-generator version

4.3.0

##### OpenAPI declaration file content or url

[bug.zip](https://github.com/OpenAPITools/openapi-generator/files/4550298/bug.zip)

##### Command line used for generation

```xml
<groupId>org.openapitools</groupId>
<artifactId>openapi-generator-maven-plugin</artifactId>
<version>4.3.0</version>
<executions>
  <execution>
    <id>markdown</id>
```

`mvn clean compile`

##### Steps to reproduce

Create OpenAPI yaml with enum component.

##### Suggest a fix
