### ISSUE TITLE
[BUG][ALL] HTTP Auth scheme names are (incorrectly) case-sensitive

### ISSUE THREAD

**Issue by asazernik** [OpenAPITools/openapi-generator#6184]
##### Description

The API generator does not generate authorization/authentication code when the user inserts a security scheme like so:

```yaml
components:
  securitySchemes:
    bearerToken:
      type: http
      scheme: Bearer
```

Note that "Bearer" is title-cased. It works if the scheme is instead lowercase "bearer".

Even though the spec is not clear on the subject, according to [the spec author](https://github.com/OAI/OpenAPI-Specification/pull/1880#issuecomment-584730191) HTTP auth schemes should be case-insensitive. Even if the schemes were case-sensitive, the [IANA registry](https://www.iana.org/assignments/http-authschemes/http-authschemes.xhtml#table-authschemes)'s canonical cases for the two most common schemes are "Bearer" and "Basic". 

##### openapi-generator version

4.3.0

##### OpenAPI declaration file content or url

See yaml snippet in description above

##### Command line used for generation

`openapi-generator generate -i $OAS3_YAML_FILE -g scala-akka -o /tmp/apiclient-test`

I have also tested this with ruby and bash generators

##### Suggest a fix

I've opened a PR in swagger-api/swagger-js#1531; I don't know where the relevant code is in this project, though.

**Comment by l0gicgate** [comment]
Using the following security schemes:
```yml
components:
  securitySchemes:
    bearerToken:
      type: http
      scheme: bearer

security:
  - bearerToken: []
```

I'm getting this when generating HTML2 docs:
```
curl -X GET -H "Accept: application/json" -H "Authorization: Basic [[basicHash]]"
```

No matter what the case is. What am I doing wrong?
