### ISSUE TITLE
[REQ] No replacement in server URL in URLPathUtils.java

### ISSUE THREAD

**Issue by zhangph1220** [OpenAPITools/openapi-generator#6291]
## Is your feature request related to a problem? Please describe.

We have a variable in the server url, which is a parameter that will be shared in every path, and we don't want to overwrite it with an empty value. 
To be more clarify, this is our yaml:
```yaml
servers:
  - url: http://localhost:8080/pet_store/{store_id}
paths:
  /test:
    get:
      parameters:
        - ref: '#/components/parameters/store_id'
components:
  parameters:
    store_id: ....
```
When we use the generator, it will warn us like this
`No value found for variable 'store_id' in server definition 'http://localhost:8080/pet_store/{store_id}' and no user override specified, default to empty string.`

And in the generated Spring Controller, the request mapping will be like:
`@RequestMapping("/pet_store")`

Instead, we just want to keep it as a variable in the url, we want something like this `@RequestMapping("/pet_store/{store_id}")`

## Describe the solution you'd like

I looked through the code here, can we just ignore when there is no replacement?
https://github.com/OpenAPITools/openapi-generator/blob/7f3f7063ab79dd3a58c7d5d5e9c0badb145c4129/modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/URLPathUtils.java#L103
