### ISSUE TITLE
[BUG][codegen] String enum value NO transforms to FALSE

### ISSUE THREAD

**Issue by fizzet** [OpenAPITools/openapi-generator#6295]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] What's the version of OpenAPI Generator used?
- [X] Have you search for related issues/PRs?
- [X] What's the actual output vs expected output?

##### Description

I have a YAML file that contains a string enum type:
```yaml
    countryCode:
      type: string
      enum:
        - DE
        - FR
        - NO
        ...
```

In the generated Java code (jaxrs-cxf), this transforms to
```java
public enum CountryCode {
  
  DE("DE"),
  FR("FR"),
  FALSE("FALSE"),
  ...
```
Obviously, the last entry should be `NO("NO")` instead.

##### openapi-generator version

openapi-generator-maven-plugin 4.3.1

**Comment by hleb-albau** [comment]
Also, enum value OFF transaforms to false too

**Comment by DmitrySboychakov** [comment]
Same here, OFF->false. Is there known fix/workaround?

**Comment by TheAwesomeGem** [comment]
Same here. What could be causing this?

**Comment by DmitrySboychakov** [comment]
That's actual problem with the YAML parser ( even more -  not a problem, that's valid behavior), we need to add single or double quotes to the schema to fix that.  
For example: 
```
    countryCode:
      type: string
      enum:
        - 'DE'
        - 'FR'
        - 'NO'
        ...

```
