### ISSUE TITLE
[BUG][DART] Properties included in the required list of a schema aren't generated as required fileds in the class

### ISSUE THREAD

**Issue by gysipos** [OpenAPITools/openapi-generator#6317]
#### Bug Report Checklist

- [ yes ] Have you provided a full/minimal spec to reproduce the issue?
- [ yes ] Have you validated the input using an OpenAPI validator
- [ yes ] What's the version of OpenAPI Generator used?
- [ yes ] Have you search for related issues/PRs?
- [ yes ] What's the actual output vs expected output?

##### Description

Inside the OpenApi description yaml file i declare some schemas with required fields in the components, like this:
```yaml
components:
    schemas:
        Foo:
            type: object
            required:
                - a
                - b
            properties:
                a:
                    type: object
                etc...
                b:
                    type: object
                etc...
```

But the generated class has only one, empty constructor, like this: Foo();
Nothing in the code indicates that i wanted some of the properties of Foo to be required.

##### openapi-generator version

4.3.1

##### OpenAPI declaration file content or url

```yaml
Location:
      type: object
      description: Location info
      required:
        - accessTokens
        - administrativeLevels
      properties:
        accessTokens:
          description: >-
            Reference token(s) of the location. It can be more than 1, if used,
            all tokens should be sent back to server by search.
          type: array
          items:
            type: string
        administrativeLevels:
          $ref: '#/components/schemas/AdministrativeLevels'
```
##### Command line used for generation

java -jar ../openapi-generator-cli-4.3.1.jar generate -i proppary_api_description.yaml -g dart -c open_generator_config.yaml

##### Steps to reproduce

generate client for any yaml, with some of the properties of the schemes included in the list of required fields. See generated class, no required fields appear, the only constructor is empty.
