### ISSUE TITLE
[BUG] Description

### ISSUE THREAD

**Issue by tek08** [OpenAPITools/openapi-generator#6338]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] What's the version of OpenAPI Generator used?
- [ ] Have you search for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

If you specify multiple servers with server variables in your yaml file, their URLs are not properly made available at template render time.  Instead, it shows their URLs with the non-replaced variable names.

##### openapi-generator version

Am using master @ commit 77f2a25c3d  

##### OpenAPI declaration file content or url

<!-- if it is a bug, a json or yaml that produces it.
If you post the code inline, please wrap it with
```yaml
servers:
  - url: http://127.0.0.1.nip.io:{listenPort}/{commandLineServerArg}
    description: Debug Localhost
    variables:
      listenPort:
        default: '5000'
        description: Port on which server listens
  - url: https://{username}.gigantic-server.com:{port}/{basePath}
    description: The production API server
    variables:
      username:
        # note! no enum here means it is an open value
        default: demo
        description: this value is assigned by the service provider, in this example `gigantic-server.com`
      port:
        enum:
          - '8443'
          - '443'
        default: '8443'
      basePath:
        # open meaning there is the opportunity to use special base paths as assigned by the provider, default is `v2`
        default: v5/
```

##### Command line used for generation

`./run-in-docker.sh generate -i /gen/spec.yaml -g python -o /gen/python/ --server-variables listenPort=3456`

##### Steps to reproduce

Run command above on supplied yaml.  Will see in output file `configuration.py` @ about line 338 that servers do not have template variables replaced.

##### Related issues/PRs

#6337 

##### Suggest a fix

Fix is in pull request above.   Let me know if I'm completely off-base.  Just starting learning the codebase today.
