### ISSUE TITLE
[BUG][JAVA] Generating enum NULL ends up as NULL("null")

### ISSUE THREAD

**Issue by AndreasFagschlunger** [OpenAPITools/openapi-generator#6592]
##### Description
For the following spec:
```yaml
    Position:
      type: string
      enum:
        - NULL
        - LEFT
        - RIGHT
        - CENTER
        - TOP
        - BOTTOM
        - REJECT
        - FRONT
        - REAR
```
The openapi-Generator creates the following code:

```java
public enum Position {
  
  NULL("null"),
  
  LEFT("LEFT"),
  
  RIGHT("RIGHT"),
  
  CENTER("CENTER"),
  
  TOP("TOP"),
  
  BOTTOM("BOTTOM"),
  
  REJECT("REJECT"),
  
  FRONT("FRONT"),
  
  REAR("REAR");

  private String value;

  Position(String value) {
    this.value = value;
  }

  @Override
  @JsonValue
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static Position fromValue(String value) {
    for (Position b : Position.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}
```
Which ends in and IllegalArgumentException getting thrown if a value `"position":"NULL"` is submitted, since the values must match exactly (case sensitive).

##### openapi-generator version

4.3.0

##### OpenAPI declaration file content or url
```yaml
    Position:
      type: string
      enum:
        - NULL
        - LEFT
        - RIGHT
        - CENTER
        - TOP
        - BOTTOM
        - REJECT
        - FRONT
        - REAR
```

##### Command line used for generation

```
    generatorName.set("jaxrs-spec")
    inputSpec.set("$rootDir/src/main/resources/openapi.yaml")
    outputDir.set("$buildDir/generated")
    apiPackage.set("at.o2xfs.xfs.web.api")
    modelPackage.set("at.o2xfs.xfs.web.model.cdm")
    configOptions.set(mapOf("dateLibrary" to "java8", "interfaceOnly" to "true", "returnResponse" to "true"))
```
