### ISSUE TITLE
[BUG][csharp-netcore] C# 8 code generated for netstandard2.0 target

### ISSUE THREAD

**Issue by donatwork** [OpenAPITools/openapi-generator#6615]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] What's the version of OpenAPI Generator used? 4.3.1
- [X] Have you search for related issues/PRs?
- [X] What's the actual output vs expected output? Expected that no C# 8 features are used.
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

Seeing C# 8 specific code when using targetFramework: "netcore2.0". This should not be allowed as netcore2.0 should not be using C# 8 features. More specifically I saw the use of the ?? operator which is specific to C# 8.

##### openapi-generator version
4.3.1

##### OpenAPI declaration file content or url
Schema:
<script src="https://gist.github.com/donatwork/36f27046931abcf584e273fb7e0d7702.js"></script>

Generated code:
<script src="https://gist.github.com/donatwork/8706d8dfba005bc18dcb59f6d942e69c.js"></script>

##### Command line used for generation
java -jar openapi-generator-cli.jar generate \
-i sample.json -g csharp-netcore -c config.yml -o output \
--type-mappings OffsetDateTime=string,DateTime=string 

Where config.yml is:

```yaml
packageGuid: "593f7620-7b33-4a2d-b4e9-77b527e2a178"
packageName: "A.B.C"
hideGenerationTimestamp: "true"
targetFramework: "netstandard2.0"
netCoreProjectFile: "true"
optionalMethodArgument: "false"
sortParamsByRequiredFlag: "false"
enablePostProcessFile: "true"

```

##### Steps to reproduce

Use the above options or use any schema with an object that has a required field. The constructor will show the required field setters using "??". As in:

this.Name = name **??** throw new ArgumentNullException("name is a required property for MyClass and cannot be null");

##### Related issues/PRs

Did not find any.

##### Suggest a fix

Use if/else. Please check for any other C# 8 features being used. Thanks.
