### ISSUE TITLE
[python] Paths starting with numerics 

### ISSUE THREAD

**Issue by developersteve** [OpenAPITools/openapi-generator#662]
##### Description

Paths starting with version (not ideal but supported in openapi) generate functions that cannot be called in Python. 

##### openapi-generator version

3.1.1 - Found this issue with all v3 releases

##### OpenAPI declaration file content or url
For example
```
servers:
  - url: 'https://penapi.pacnetconnect.com'
paths:
  /1.0.0/account/profile/exchange:
    get:
      summary: Get the current account's Exchange profile
      tags:
        - exchange
```
creates the following type of call when generated
```
api_response = api_instance.100_auth_generatetoken_post(grant_type, username, password)
```

##### Suggest a fix/enhancement

Digging around the template and i can see that its identifying the numeric because the process creates a file that will start with Model100 .... etc. The function and model however doesnt seem to be doing it this way.
