### ISSUE TITLE
[REQ] Java/OkHttpClient: Configure tokenUrl

### ISSUE THREAD

**Issue by naude-r** [OpenAPITools/openapi-generator#6670]
### Is your feature request related to a problem? Please describe.

Cannot configure a token url different from protected endpoints, ie not relative to the service base path. As an example:
tokenUrl: https://api.company.com/oauth-framework/generateaccesstoken
service base uri: https://api.company.com/v1/service/endpoint

## Describe the solution you'd like

Being able to specify the token url explicitly when creating the ApiClient

## Describe alternatives you've considered

Hard coded tokenUrl in yaml. While this works it does require a rebuild when switching between dev / qa / prod environments.

**Comment by 4dz** [comment]
I have exactly this issue as well.  

Locally I'm working on a small change to `Java/okhttp-gson/ApiClient.mustache` that will add an extra constructor for the tokenUrl, but it means having to clone the Java templates etc into a project.  Would be great to see this as part of the generator!

**Comment by shavo007** [comment]
Actually, i came across this also. You cannot overwrite the `tokenUrl` for the diff envs. So unfortunately I cant use the default client.  @naude-r  have you found another java client that can?

**Comment by shavo007** [comment]
Actually i believe this works. The token url just needs to be relative to the basePath

```java
        String tokenUrl = "/oauth/token";
        if (!"".equals(tokenUrl) && !URI.create(tokenUrl).isAbsolute()) {
            URI uri = URI.create(getBasePath());
            tokenUrl = uri.getScheme() + ":" +
                (uri.getAuthority() != null ? "//" + uri.getAuthority() : "") +
                tokenUrl;
            if (!URI.create(tokenUrl).isAbsolute()) {
                throw new IllegalArgumentException("OAuth2 token URL must be an absolute URL");
            }
        }
        RetryingOAuth retryingOAuth = new RetryingOAuth(tokenUrl, clientId, OAuthFlow.application, clientSecret, parameters);
```

in OAS

```yaml
components:
  securitySchemes:
    bpay_auth:
      type: oauth2
      flows:
        clientCredentials:
          # tokenUrl: https://sandbox.api.xxx.com.au/oauth/token
          tokenUrl: "/oauth/token"
          scopes:
            read:validate-payment: XXX API
```
