### ISSUE TITLE
[C++] Using generated QT Client to get Data from API?

### ISSUE THREAD

**Issue by ivnak45** [OpenAPITools/openapi-generator#6682]
##### Description
 I've been trying to use the cpp-qt5-client generator to generate a library to easily let my QT application communicate with my API. So far the communication part (sending GET, POST etc. through library functions) works totally fine. 
The request and response are defined in the API schema as follows:
```yaml
paths:
  /objectA/{id}:
    get:
      description: "GET objectA from ID"
      parameters:
        - in: path
          name: id
          description: identifier
          required: true
          schema:
            type: string
            format: uuid
      responses: 
        '200':
          description: an object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectA'
```

ObjectA itself is defined like this:

```yaml
components:
  schemas:
   ObjectA:
      type: object
      description: "placeholder"
      properties:
        name:
          type: string
          description: "shown name"
        id:
          type: string
          description: "identifier"
          format: uuid
        objectValue:
          type: integer
          description: "placeholder"
          minimum: 0
          maximum: 5
```

After bulding the library (generated with version 4.3.1) in QT I can add it to my project and use the following code to send the corresponding request to my server:
```cpp
    OpenAPI::OAITestApi apiT;
    apiT.setScheme("http");
    apiT.setHost(serverip);
    apiT.setPort(port);

    apiT.ObjectIdGet(objectID);
```
This part works without any problems. Now my question is, how can I use the data the server sends back in response (a JSON object describing an "ObjectA" ) in my client, like for example reading it into an ObjectA object which is already defined by the library? 
I know i can use the generated  ObjectA.fromJSON/fromJSONObject to read this JSON data in an ObjectA object, but how do I access this JSON data in the first place?
There seems to be a lack of documentation as to how to actually use the generated library to retrieve data/use the retrieved data. Maybe it assumes some background knowledge people (like I) don't have?
