### ISSUE TITLE
[BUG] Missed autogeneration config for php-slim4

### ISSUE THREAD

**Issue by ybelenko** [OpenAPITools/openapi-generator#6719]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))
##### Description
Long story short. We excluded PHP Slim4 server from `bin/utils/ensure-up-to-date` because we had weird uncommitted changes under Slim4 samples. Some times it was different path separators eg `/` and `./`. But most of time it was `{{modelJson}}` generation output, JSON value was the same but with different properties order.

I use this `bin/configs/php-slim4.yaml` as temporary workaround:
```yaml
generatorName: php-slim4
outputDir: samples/server/petstore/php-slim4
inputSpec: modules/openapi-generator/src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml
templateDir: modules/openapi-generator/src/main/resources/php-slim4-server
```

##### openapi-generator version

Latest master 06327da

##### Suggest a fix

I understand that we don't know how to solve uncommitted changes problem right now. Let's consider this issue just as reminder.

cc @wing328 @jimschubert
