### ISSUE TITLE
[BUG] [typescript-axios] Date format missing types

### ISSUE THREAD

**Issue by sk-** [OpenAPITools/openapi-generator#6771]
##### Description

If a `date` format is specified for a parameter, the generated code for axios will include the following:

```ts
      if (fromDate !== undefined) {
        localVarQueryParameter['fromDate'] =
          (fromDate as any) instanceof Date
            ? (fromDate as any).toISOString().substr(0, 10)
            : fromDate;
      }
```

However, the type for that argument in the generated method is `fromDate?: string`, which prevent us from actually passing a `Date` instance.

Either we remove that code, or change the type definition to be `fromDate?: string | Date`

##### openapi-generator version

4.3.1

##### OpenAPI declaration file content or url

```yaml
     parameters:
        - in: query
          name: fromDate
          schema:
            type: string
            format: date
```

##### Command line used for generation

```bash
openapi-generator \
        generate \
        -g typescript-axios \
        -i "../external-api/$name.yaml" \
        -o "generated-src/$name"
```
