### ISSUE TITLE
[BUG] [Authentication] OR'ing duplicate authMethods

### ISSUE THREAD

**Issue by nhomble** [OpenAPITools/openapi-generator#6833]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

Based off discussion in the spec in [here](https://github.com/OAI/OpenAPI-Specification/pull/1829) and the [Use Multiple Authentication Types](https://swagger.io/docs/specification/authentication/) section, I should be able to reuse authMethods in the security section of my path.

##### openapi-generator version

Off master

##### OpenAPI declaration file content or url

<!-- if it is a bug, a json or yaml that produces it.
https://github.com/nhomble/repro-multiple-authmethods

```yml
components:
  securitySchemes:
    myAuth:
      type: oauth2
      flows:
        authorizationCode:
          scopes:
            read: ability to read
            write: ability to write
            pet: ability on pet
paths:
  /pets
    get:
      summary: get pets
      security:
        - myAuth: [ read, pet ]
        - myAuth: [ write, pet ] # if you can update we'll let you read too
```
##### Command line used for generation

The investigation has lead me to the generator, but I was reproducing this off of tests in ```SpringCodegenTest```

##### Steps to reproduce

1. define oauth2 scopes in security schemes
2. use the same securityScheme on an api (with different scopes)
3. Eval the spring code generator
4. notice how we lose reference in the swagger annotations

And this has caused issues for me in https://github.com/OpenAPITools/openapi-generator/pull/6358

##### Suggest a fix

Debugging has brought us to the line

```java
Map<String, SecurityScheme> authMethods = getAuthMethods(securities, securitySchemes); 
```

in ```DefaultGenerator.java```

the loops blindly put auth methods into the authMethods map by name even if the key exists. Maybe we need to consider accumulating collisions in the value and then iterate later in generation.
