### ISSUE TITLE
[typescript-angular] Mark deprecated operations with the @deprecated JSDoc tag in typescript-angular

### ISSUE THREAD

**Issue by daiscog** [OpenAPITools/openapi-generator#6972]
When generating a client from a spec that contains deprecated operations, the generated client does not indicate to the consumer that the operations have been deprecated. 

Example deprecated operation:

```yaml
paths:
  /example:
    post:
      operationId: examplePost
      deprecated: true
```

##### Related issues/PRs

Akin to https://github.com/OpenAPITools/openapi-generator/issues/6474
