### ISSUE TITLE
support integer enum 

### ISSUE THREAD

**Issue by esoni88** [OpenAPITools/openapi-generator#701]
##### Description

Hi All,
is possible generate integer enum with alias value ? 
For i.e

```   RfqLegTypeEnum:
    type: integer
    enum:
      - Outright
      - Switch
      - Butterfly
```
The gen raise the errore
`Exception in thread "main" java.lang.IllegalArgumentException: Cannot deserialize value of type `java.lang.Number` from String "Outright": not a valid number`

The expected result ( for i.e using java) is the following:

```
public enum RfqLegTypeEnum {
  
  Outright(0),
  
  Switch(1),
  
  Butterfly(2),
```
How can obtain this result ?  

##### openapi-generator version

 3.1.2

##### OpenAPI declaration file content or url
Thnx

**Comment by jmini** [comment]
I do not think that this is possible.

```yaml
    type: integer
    enum:
      - 0
      - 1
      - 2
```

Should work, but this probably not what you want...

**Comment by jmini** [comment]
Update: there is a proposition in #917 to control the generated enum names with the `x-enum-varnames` extension. 

When the PR is merged, for your case, you should be able to do:

```yaml
    type: integer
    enum:
      - 0
      - 1
      - 2
    x-enum-varnames:
      - Outright
      - Switch
      - Butterfly
```
