### ISSUE TITLE
[REQ] proposal: rust/reqwest changes

### ISSUE THREAD

**Issue by JRAndreassen** [OpenAPITools/openapi-generator#7053]
@frol / @farcaller / @richardwhiuk / @paladinzh

In order to make the rust/reqwest api/models more flexible for use with an arbitrary/external client
I would propose the following changes...

1) Add extensions to alter generation :
 new extension attributes:  vendorExtensions.*
     x-add-dependencies          Cargo dependency additions 
     x-add-dependencies-dev  Cargo dependency-dev additions  
     x-add-use     Use statements for all files (could be added to partial header
     x-add-derive-enum  Added before all enum definitions
     x-add-derive-struct  Added before all struct definitions 

It would be used with something like this:
```yml
generatorName: rust
outputDir: xxxxx
library: reqwest
inputSpec: xxxxx/yyy.yaml
additionalProperties:
  supportAsync: true
  packageName: my_xxxx
  vendorExtensions.x-group-parameters: true
  vendorExtensions.x-add-dependencies: >
    strum = "*"

    strum_macros = "*"

    builder_macro = "*"

    derive-getters = "*"

    derive_builder = "*"

    getset    = "*"

    rand = "*"
  vendorExtensions.x-add-dependencies-dev: >
    # added dev dependencies
  vendorExtensions.x-add-use: >
    #[allow(unused_imports)]
    pub use serde::{
        Serialize, Deserialize, 
        ser::{SerializeStruct},
        de::{Visitor, MapAccess},
    };

    #[allow(unused_imports)]

    pub use derive_builder::{Builder};

    #[allow(unused_imports)]

    pub use getset::{CopyGetters, Getters, MutGetters, Setters};

    #[allow(unused_imports)]

    pub use strum_macros::{  Display, EnumMessage, EnumIter, EnumString,  AsRefStr, AsStaticStr, };
  vendorExtensions.x-add-derive-enum: >
    #[derive(Display, AsRefStr, AsStaticStr, EnumString, EnumMessage, EnumIter)]
  vendorExtensions.x-add-derive-struct: >
    #[derive(Serialize, Deserialize)]

    #[derive(Builder, Getters, Setters, MutGetters, CopyGetters)]

    #[builder(try_setter, setter(into))]
  vendorExtensions.x-other: false
```

2) Split the API methods into:
    - {{{operationId}}}_setparameters(builder, ...) 
         -- Set all parameters
    - {{{operationId}}}(config, ...) 
       - create builder
       - call {{{operationId}}}_setparameters(builder, ...)
       - execute
This change would make the integration into an external library with existing client generator easier.

3) Generate #[tests] based on examples in spec file
4) Create a trait definition that all API methods implement
  To make it easier to have a map of traits and call them generically

[I have implemented some of this already in my branch...](https://github.com/JRAndreassen/openapi-generator/tree/jrz_v500_add_extensions)

Comments thoughts ?
  Thanks
  JR
