### ISSUE TITLE
[REQ][GO] Generating unsigned integers

### ISSUE THREAD

**Issue by olvlvl** [OpenAPITools/openapi-generator#7393]
### Is your feature request related to a problem? Please describe.

Hi everyone,

The Golang generator generates `int32` and `int64` according to the integer format specified in the OpenAPI spec. Could it be possible to generate unsigned integers when `minimum` is `>= 0`?

Consider the following:

```yaml
      schema:
        type: integer
        example: 16318315
        minimum: 1
```

Could we generate a `unit32` for this?

## Describe the solution you'd like

Use the `minimum` constraint to generate unsigned integers.

## Describe alternatives you've considered

If we really want unsigned integers, we have to adjust the generated code.
