### ISSUE TITLE
[BUG] Scala Sttp Codegen generates empty case class for named enums

### ISSUE THREAD

**Issue by acgray** [OpenAPITools/openapi-generator#7431]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?

##### Description

Scala Sttp generator generates empty case class instead of enum for named (i.e., top-level) enum models.

##### openapi-generator version

4.3.1

##### OpenAPI declaration file content or url

```yaml
...
components:
  schemas:
    PetType:
      enum:
      - CAT
      - DOG
      - FROG
      type: string
...
```

##### Generation Details

* Generator: `scala-sttp`

##### Suggest a fix

PR to follow
