### ISSUE TITLE
[Discussion] Remove Dart (1)

### ISSUE THREAD

**Issue by agilob** [OpenAPITools/openapi-generator#7561]
Openapi supports dart and dart2. Language didn't have many [breaking changes between versions these](https://dart.dev/dart-2) and it can only add confusion, never seen anyone referring to Dart as dart2, it's always dart or dartlang.

* `dart` generator doesn't seem to be tested properly and it shares generator code with `dart2`
* there is no dart1 or dart2 specific schemas: `dart-jaguar-openapi-flutter_proto.yaml  dart-jaguar-openapi_proto.yaml          dart-openapi-browser-client.yaml        dart-openapi.yaml                                                                                                   
dart-jaguar-openapi-flutter.yaml        dart-jaguar-openapi.yaml                dart-openapi-flutter.yaml               dart-petstore_client_lib.yaml `
* `dart`(1) is using outdated syntax and is doing too much
* `dart` (1) doesnt have own specific documentation - `dart.md` describes `dart2` generator
* some of the schemas, specifically say not to use dart2 generator, but dart which isn't supported

```
cat bin/configs/dart-openapi-flutter.yaml
generatorName: dart
outputDir: samples/client/petstore/dart/flutter_petstore/openapi
inputSpec: modules/openapi-generator/src/test/resources/3_0/petstore.yaml
templateDir: modules/openapi-generator/src/main/resources/dart
additionalProperties:
  supportDart2: "false"
  hideGenerationTimestamp: "true"
  browserClient: "false"
```

* `dart`(1) is also trying to solve flutter (ui framework) generation adding extra external dependencies to generated code (also badly out of date, at least 3 years, language and framework changed a lot)
  * I **personally** see no need to add complexity of generating flutter-specific code, openapi should generate models what can be imported by flutter

Calling active dart contributors: @noordawod @sbu-WBT @josh-burton  @syky27
