### ISSUE TITLE
[typescript-axios] doesn't serialize deepObject query params

### ISSUE THREAD

**Issue by wamujlb** [OpenAPITools/openapi-generator#7564]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
	input: `{day: 20, year: {min: 1990, max: 2000}}`
	actual output: `?day=20&year`
	expected output: `?day=20&year[min]=1990&year[max]=2000`

##### Description

I'm using [typescript-axios] api client generator. Some of the properties I pass to it specified as `deepObject`. It looks that it doesn't support this type of args at all. Is there any possible ways to fix it? 

##### openapi-generator version

v4.3.1
v5.0.0-beta

##### OpenAPI declaration file content or url

```yaml
YearRange:
      in: query
      name: year
      required: false
      style: deepObject
      schema:
        type: object
        properties:
          min:
            type: string
            example: 2010
          max:
            type: string
            example: 2019
```
##### Generation Details

[typescript-axios] generator

##### Related issues/PRs

https://github.com/OpenAPITools/openapi-generator/pull/6075

##### Suggest a fix

Replace old deprecated url API with URLSearchParams.
