### ISSUE TITLE
[BUG][Ada] Incorrect client Ada code generated

### ISSUE THREAD

**Issue by stcarrez** [OpenAPITools/openapi-generator#7594]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

The Ada client generator generates incorrect code:

* when a `FreeFormObject` is used,
* when several path parameters are used

##### openapi-generator version

5.0.0-SNAPSHOT.

##### OpenAPI declaration file content or url

A partial example of URL with two path parameters:

```yaml
paths:
  '/converter/{format}/{target}':
    post:
      tags:
        - converter
      summary: Convert a text from one format to another
      description: ''
      operationId: convert
      parameters:
        - name: format
          in: path
          description: The source Wiki format
          required: true
          schema:
            type: string
            enum:
              - html
              - markdown
              - dotclear
              - creole
              - mediawiki
        - name: target
          in: path
          description: The target Wiki format
          required: true
          schema:
            type: string
```

##### Generation Details

* The code generator generates the same index number for both path parameters (we can access only the first path parameter!!!)
* The `FreeFormObject` generates code that does not compile.

##### Steps to reproduce

I'm using the following command:

```
openapi-generator generate --generator-name ada -i file.yaml --additional-properties projectName=todos --model-package Todos -o .
```

##### Suggest a fix

I'll submit a pull to fix the above :-)
