### ISSUE TITLE
[REQ] [typescript] Allow ParameterizedServer servers for typescript-node

### ISSUE THREAD

**Issue by mahirk** [OpenAPITools/openapi-generator#7623]
### Is your feature request related to a problem? Please describe.
Currently OAS 3 and some of its generators in this repo support `ParameterizedServer` which allows a server to be designed as follows:
```yaml
servers:
  - url: https://{environment}.example.com/v2
    variables:
      environment:
        default: api    # Production server
        enum:
          - api         # Production server
          - api.dev     # Development server
          - api.staging # Staging server

```

This feature is to track adding in the usage of parameterized servers in typescript-node.

## Describe the solution you'd like
This is likely possible by:
1. Adding a configuration object which is sent to the `constructor` of the API
2. The configuration object will refer to the servers variables as `enums` and reconstruct the URL using the variables passed in. 

If multiple servers are found, a warning can be logged.

## Describe alternatives you've considered
Open for intepretation

## Additional context
Would like advice on the best way to look into this since typescript-node still uses `basePath` which would likely have to be overwritten.
