### ISSUE TITLE
cpp-qt5-client - reserved word: slots

### ISSUE THREAD

**Issue by ivargaphotoneo** [OpenAPITools/openapi-generator#7838]
1. I have installed latest generator by steps from https://openapi-generator.tech/docs/installation
2. I used cpp-qt5-client generator and generate Qt5 files
3. Files are generated without error, but compilation fails because one of my key word in yml config file is "slots" and slot is key-word for Qt

fragment of yml file:
```
schemas:
    UpdateStatus:
      type: object
      required:
        - compatible
        - variant
        - booted
        - active
        - operation
        - lastError
        - progress
        - slots
      properties:
```
