### ISSUE TITLE
[BUG] [jaxrs-cxf-cdi] Compilation issue in generated code when there is default value set for header parameters

### ISSUE THREAD

**Issue by vithu30** [OpenAPITools/openapi-generator#7871]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When there are default values defined for header parameters the generated code is not compiling. The following is a part of my Open API definition:

``` yaml
 -    name: contentType
      in: header
      description: |
        Media type of the response. Default is application/json.
      schema:
        type: string
        default: application/json
```

It is caused because there are additional double quotation marks added to the generated code due to the bug in default mustache file - [1]. 

Expected output:

``` java
 @ApiParam(value = "Media type of the response. Default is application/json " , defaultValue="application/json")
```

Actual output:

``` java
 @ApiParam(value = "Media type of the response. Default is application/json " , defaultValue=""application/json"")
```

[1]  https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/JavaJaxRS/cxf-cdi/headerParams.mustache

##### openapi-generator version
4.3.1
