### ISSUE TITLE
[PYTHON][5.0.0beta2] Customization from config file, new supporting files not generated

### ISSUE THREAD

**Issue by sattle** [OpenAPITools/openapi-generator#7954]
##### Description
I am interested in the functionality described in [Customization](https://openapi-generator.tech/docs/customization) with the 5.0.0 version where we can specify additional files to be generated through a configuration file.

I tried to generate a python-flask server with two additional files : Author.md  and python-logging.mustache. But they don't seem to be generated.

Either I am missing something or this is not yet available.

##### openapi-generator version

openapi-generator 5.0.0beta2

##### Files used
The configuration files used
```yaml
templateDir: custom_template
additionalProperties:
  debugSupportingFiles: true
  packageName: python_com
  packageVersion: 1.0.1
  serverPort: 9090
files:
  Author.md : {}
  python-logging.mustache:
    folder: addon
    destinationFilename: python-logging.py
    templateType: SupportingFiles
```
Folder architecture

```bash
.
├── config.yaml
├── custom_template
│   ├── Author.md
│   └── python-logging.mustache
└── folder_archi

1 directory, 4 files
  
```

##### Command line used for generation
As for the command line used to generate the python-flask server.

```bash
 java -jar path/to/openapi-generator-cli-5.0.0-beta2.jar generate -g python-flask -i path/to/petstore.yaml -o outdir -c config.yaml 
```
