### ISSUE TITLE
[BUG] [typescript-axios] Query parameters do not support `explode: true, style: form`

### ISSUE THREAD

**Issue by dantman** [OpenAPITools/openapi-generator#7973]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

OpenAPI supports parameters defined with the following.

```yaml
name: color
in: query
style: form
explode: true
```
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#style-values

Parameters defined like this and given an array output query strings like `color=blue&color=black&color=brown`.

However currently a typescript-axios client made by openapi-generator would instead output `color=blue%2Cblack%2Cbrown`.

##### openapi-generator version

```
$ openapi-generator version
5.0.0-beta2
```

##### OpenAPI declaration file content or url

```yaml
parameters:
- name: color
  in: query
  style: form
  explode: true
  schema:
    type: array
    item:
      type: array
        - in: query
          name: Balance.Currency
          style: form
          explode: true
          schema:
            type: string
```
##### Generation Details

```
openapi-generator generate -i openapi.yaml -g typescript-axios -c config.yaml
```

##### Suggest a fix

I think that apiInner.mustache needs to be updated to include handling for this type of collection format.

https://github.com/OpenAPITools/openapi-generator/blob/78611b3e387128b5f768865e4dfa8b4736ba571c/modules/openapi-generator/src/main/resources/typescript-axios/apiInner.mustache#L107-L138
