### ISSUE TITLE
[BUG][Java/Spring] additionalProperties to true breaks compilation

### ISSUE THREAD

**Issue by BorjaSalazar** [OpenAPITools/openapi-generator#8003]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description
v5.0.0-beta2 and v5.0.0-beta3 do not generate correct Java putPropertiesItem method for Map fields

##### openapi-generator version

v5.0.0-beta2, v5.0.0-beta3 and latest

Works ok in  v5.0.0-beta

##### OpenAPI declaration file content or url
```yaml
openapi: 3.0.3
info:
  title: Test
  version: '1.0.0'

paths:
  /test:
    get:
      summary: Test
      description: Example
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/test'

components:
  schemas:
    test:
      type: object
      required:
        - field_A
        - field_B
      properties:
        field_A:
          type: string
          enum:
            - Feature
        field_B:
          type: integer
        properties:
          type: object
          properties:
            field_C:
              type: integer
          additionalProperties: true


```

##### Generation Details
cat out/java/src/main/java/org/openapitools/model/Test.java
Expected
```java

  public Test putPropertiesItem(String key, Object propertiesItem) {
    if (this.properties == null) {
      this.properties = new HashMap<>();
    }
    this.properties.put(key, propertiesItem);
    return this;
  }


```

vs
```java
  public Test putPropertiesItem(String key, Object propertiesItem) {
    if (this.properties == null) {
      this.properties = ;
    }
    this.properties.put(key, propertiesItem);
    return this;
  }
```

##### Steps to reproduce

```shell
docker run --rm \                                          
    -v $PWD:/local openapitools/openapi-generator-cli:v5.0.0-beta3 generate \ 
    -i /local/test.yaml \
    -g spring \
    -o /local/out/java
```

**Comment by borsch** [comment]
@BorjaSalazar if you remove this, then everything will work
```yaml
properties:
  field_C:
    type: integer
```

to be
```yaml
components:
  schemas:
    test:
      type: object
      required:
        - field_A
        - field_B
      properties:
        field_A:
          type: string
          enum:
            - Feature
        field_B:
          type: integer
        properties:
          type: object
          additionalProperties: true
```

as for me there is no sense in property `field_C` since it's not generated at all

**FYI**: this behaviour was changed with this PR https://github.com/OpenAPITools/openapi-generator/pull/6052 . Without those changes valid code is generated for your input(but still without field `field_C` 😄 )

**Comment by pcuriel** [comment]
Hi @borsch.

Yes, you are right in that `field_C` is not generated at all.

However, if you look at the OAS 3 spec, this is a valid definition intended to represent that `field_C` is a required key in the Map (see "Fixed Keys" section [here](https://swagger.io/docs/specification/data-models/dictionaries/)).

So, IMHO, even if explicit fields will never be present in the code, the generator should not fail when they are defined, them being an standard feature of the specification.

**Comment by nathan-nichols-by** [comment]
I've also hit this issue after upgrading to `5.0.0` of the generator. I have quite a few schemas that worked fine with `additionalProperties: true` along side several other explicitly defined properties in the previous version of the generator. I half-way worked around the issue by defining special component schemas for each attributes map

```
# old
components:
  schemas:
    Test:
      type: object
      properties:
        one:
          type: string
        two:
          type: integer
        attributes:
          type: object
          properties:
            explicitProp:
              type: integer
          additionalProperties: true
```
```
# new
components:
  schemas:
    Test:
      type: object
      properties:
        one:
          type: string
        two:
          type: integer
        attributes:
          $ref: '#/components/schemas/Attributes'

    Attributes:
      type: object
      properties:
        explicitProp:
          type: integer
      additionalProperties: true
```

This creates a class called `Attributes` that extends `HashMap` and adds a getter and setter for my `explicitProp` field.

The problem is that when deserializing JSON into an instance of `Attributes` it just copies all the properties into the map, even the `explicitProp` value. If I call `getExplicitProp`, `null` will be returned. If I try to assert equality in a test between an `Attributes` instance that was deserialized from JSON and one that I create manually using the setter, they will not be equal.

Is there some other approach I can try? Removing the explicit properties isn't an option.
