### ISSUE TITLE
Java generator (jersey2) does not serialize object query parameters according to OAS3

### ISSUE THREAD

**Issue by pauldwolfe** [OpenAPITools/openapi-generator#8475]
##### Description

Hello,

We'd like our generated API to use objects to store query parameters rather than a list of arguments. Mostly for readability and to avoid long argument lists with a lot of nullable string parameters (eg. `list(null, null, null, str1, null, str1, null...) vs  
list(new QueryParameters().setStr1(str1).setStr2(str2)`)

The OAS3 spec docs give examples where you can do this with an object + schema, plus having `explode=true` and `style=form` (the defaults). A la:

```
/hmf/v1/runs:
    get:
      tags:
        - run
      operationId: list
      parameters:
        - in: query
          name: params
          schema:
            type: object
            properties:
              status:
                type: string
              ini:
                type: string
          explode: true
          style: form

```

In the end this code creates the Java API we want, but under the hood creates a query parameter, params="class Parameters...".

We're using version 5.0.0.

Apologies if I've misunderstood the spec, hopefully this is supported somehow as it would lead to more elegant generated API code.

##### openapi-generator version

5.0.0

##### OpenAPI declaration file content or url

```
/hmf/v1/runs:
    get:
      tags:
        - run
      operationId: list
      parameters:
        - in: query
          name: params
          schema:
            type: object
            properties:
              status:
                type: string
              ini:
                type: string
          explode: true
          style: form

```

##### Generation Details

Maven plugin 5.0.0
