### ISSUE TITLE
Can't generate .Net5.0 project

### ISSUE THREAD

**Issue by dstepanov25** [OpenAPITools/openapi-generator#8486]
##### Description

I'm trying to generate .net 5.0 project using docker image

##### openapi-generator version

image: openapitools/openapi-generator-cli:latest

##### OpenAPI declaration file content or url

Doesn't matter. I took example from specification https://swagger.io/docs/specification/basic-structure/

##### Command line used for generation
command: docker-compose up
docker-compose.yml file:
```
version: '3'
services: 
    service:
        image: openapitools/openapi-generator-cli:latest
        command: generate -i /input/Reporting.yaml -o /data -g aspnetcore --package-name="Reporting" --additional-properties=aspnetCoreVersion="5.0" 
        volumes:
            - ./:/input 
            - ./../Reporting:/data/
        network_mode: "none"
```

##### Steps to reproduce

After running of docker-compose up I received such error:
service_1  | Exception in thread "main" java.lang.IllegalArgumentException: aspnetCoreVersion: Invalid value '5.0'. ASP.NET Core version: 3.1, 3.0, 2.2, 2.1, 2.0 (deprecated)
service_1  |    at org.openapitools.codegen.languages.AspNetCoreServerCodegen.setCliOption(AspNetCoreServerCodegen.java:480)

##### Suggest a fix/enhancement

I think /openapitools/codegen/languages/AspNetCoreServerCodegen.java file should be updated (provide support of .net 5.0)
