### ISSUE TITLE
[BUG] [scala-akka-client] Scala client does not support arbitrary query string values

### ISSUE THREAD

**Issue by ameenhaq** [OpenAPITools/openapi-generator#8606]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ ] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When generating an api with an endpoint that takes an arbitary set of query parameters, which is to be represented as `Map[String, Any]` in the client, the generated code tries to query parameter append method that does not support the `Map[String, Any]` data type.

##### openapi-generator version

Latest

##### OpenAPI declaration file content or url

```yaml
  /api/v1/query:
    get:
      summary: Get a result using some filters
      operationId: getQuery
      parameters:
        - name: filter
          in: query
          required: false
          schema:
            type: object
            additionalProperties: true
```

##### Suggest a fix
Currently, it utilises a method `withQueryParam` which cannot handle a `Map` type.
```json
def withQueryParam(name: String, value: Any): ApiRequest[U] = copy[U](queryParams = queryParams + (name -> value))
```
This can be supported by;
```json
def withQueryParam(values: Map[String, Any]): ApiRequest[U] = copy[U](queryParams = queryParams ++ values)
```
