### ISSUE TITLE
[nodejs-express-server] Handlebars Templates

### ISSUE THREAD

**Issue by manchuwook** [OpenAPITools/openapi-generator#8686]
##### Description

I'm trying to use the templates feature to generate mongoose schemas, controllers, and providers for NestJs using the templating system but the new typescript-nestjs template seems to be for remote APIs.  I'm the API owner and want to make a server that does the data thing.

When I try to use hbs and the config.yaml file, it creates a .ts file, a .js file - and whenever I'm missing the index file in the controllers folder, it complains, but if I'm also missing the controllers.hbs file... it also complains.  What would I be doing wrong?

```yaml
templateDir: node-express-template
additionalProperties:
  artifactId: nodejs-express-template
  serializableModel: "true"
  dateLibrary: java8
files:
    index.hbs:
      templateType: API
      destinationFilename: .ts
    controller.hbs:
      templateType: API
      destinationFilename: .ts
    service.hbs:
      templateType: API
      destinationFilename: .ts
    controllers/index.hbs:
      templateType: API
      destinationFilename: .ts
    services/index.hbs:
      templateType: API
      destinationFilename: .ts
```

##### openapi-generator version

`5.0.1`

##### Command line used for generation

java -jar s:\openapi-generator\openapi-generator-cli.jar generate -g nodejs-express-server -i project.player.v1.json -o out\nje-test -c config.yaml --engine=handlebars

##### Steps to reproduce

Created a folder called node-express-template and added 2 folders (controllers, services) and added 3 index files (root, controllers, services) and then added controller.hbs and service.hbs to the root.

##### Suggest a fix/enhancement

Maybe a suggestion on how to suppress creating the .js files (I'm trying to create only .ts)  or make it more clear how to prevent it from using the new templates.
