### ISSUE TITLE
[BUG] java native: oauth files not being generated

### ISSUE THREAD

**Issue by shavo007** [OpenAPITools/openapi-generator#8702]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

oauth files not generated for java native http client

##### openapi-generator version

5.0.1

##### OpenAPI declaration file content or url

```yaml
components:
  securitySchemes:
    bpay_auth:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://sandbox.api.bpaygroup.com.au/oauth/token
          scopes:
            read:validate-payment: BPAY payment validation API
```

(for YAML code) or

```yaml
# native http client supported in java 11
generatorName: java
outputDir: samples/client/bpay/java/native
library: native
additionalProperties:
  artifactId: bpay
  hideGenerationTimestamp: "true"
  dateLibrary: "java8"
  httpUserAgent: "Shane-Bpay-Java/1.0.0"
  modelPackage: "com.shane.bpay.models"
  apiPackage: "com.shane.bpay.api"
  groupId: "com.shane"

```

##### Generation Details

```bash
    $SWAGGER_CMD generate \
        --input-spec "./bpay-oas.yaml" \
        -g "$1" \
        --config "./swagger-config/config-$1.yaml"
```

##### Steps to reproduce

If i change to another client like the default, then i see the oauth files

##### Related issues/PRs
https://github.com/OpenAPITools/openapi-generator/issues/6284
