### ISSUE TITLE
[BUG] [Spring] Open-Api code generator plugin fails to escape backslash character

### ISSUE THREAD

**Issue by mlhrAnjaria** [OpenAPITools/openapi-generator#8707]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ ] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?

##### Description

Trying to generate a Java client from open api specification. 

##### openapi-generator version

 `4.3.1`

##### OpenAPI declaration file content or url

```yaml
paths:
  /sources:
    $ref: 'paths.yaml#/~1sources'
  /sources/{directorySourceId}:
    $ref: 'paths.yaml#/~1sources~1{directorySourceId}'
  /sources/{directorySourceId}/actions:
    $ref: 'paths.yaml#/~1sources~1{directorySourceId}~1actions'
```
```
openApiGenerate {
        generatorName = "spring"
        outputDir = "$buildDir/openapi".toString()
        apiFilesConstrainedTo = [""]
        modelFilesConstrainedTo = [""]
        supportingFilesConstrainedTo = ["ApiUtil.java"]
        configOptions = [delegatePattern: true, dateLibrary: "java8", useTags: true]
        typeMappings = ["OffsetDateTime" : "Instant"]
        importMappings = ["java.time.OffsetDateTime" : "java.time.Instant"]
        validateSpec = true
    }
```

#### Steps to reproduce

`./gradlew clean openApiGenerate`

It causes error with 
```
#/components/schemas/~1sources~1{directorySourceId} is not defined
#/components/schemas/~1sources~1{directorySourceId} is not defined
#/components/schemas/~1sources~1{directorySourceId} is not defined
~1sources~1{directorySourceId} (model name starts with number) cannot be used as model name. Renamed to Model1sources1directorySourceId
```
causing model names to be `Model1sources1directorySourceId` and `Model1sources1directorySourceId1actions`. 

##### Related issues/PRs

Previous PR on older versions- [1691](https://github.com/OpenAPITools/openapi-generator/issues/1691)

##### Suggest a fix
This works fine with plugin version 4.2.0
