### ISSUE TITLE
Generated java code uses invalid java parameter name (non-camelcased, separated with `-`)

### ISSUE THREAD

**Issue by flozano** [OpenAPITools/openapi-generator#886]
##### Description
Generated parameter name is not valid java for multipart file parts

##### openapi-generator version

3.2.2

##### OpenAPI declaration file content or url

```yaml
    post:
      operationId: UploadItem
      description: Upload a new item
      tags:
        - Items
      parameters:
        - name: item-name
          in: formData
          type: string
          required: false
        - name: item-data
          in: formData
          type: file
          required: true
```

##### Command line used for generation

openapi-generator generate -i /Users/flozano/Projects/golang/src/github.com/KiiCorp/varanus-frontend/server/swagger.yml -g spring

##### Steps to reproduce

Try to compile. In generated method:
```java
    default ResponseEntity<RuleInfo> uploadItem
```
the parameter has an incorrect name, separated with `-` instead of being camel-cased:

```java
default ResponseEntity<ItemInfo> uploadItem(@ApiParam(value = "file detail") @Valid @RequestPart("file") MultipartFile item-data,
```
