### ISSUE TITLE
[BUG] x-enum-varnames in parameters not work ---- dart 

### ISSUE THREAD

**Issue by godaangel** [OpenAPITools/openapi-generator#9034]
I have write like this
```
parameters:
    - name: operation_type
      in: query
      required: true
      schema:
        type: integer
        enum:
          - 0
          - 1
        x-enum-varnames:
          - Read
          - ReadAll
```
but in dart it is also int type, not enum type.

I use `openapi-generator generate -i openapi.yaml -g dart-dio -o .api_tmp` this to generate

and my `openapi-generator` version is `5.1.0`
