### ISSUE TITLE
not generated parent tag on final generated pom.xml (only works with generator spring)

### ISSUE THREAD

**Issue by danipenaperez** [OpenAPITools/openapi-generator#9078]
##### Description

Pom parent tag is not created on jax-rs/jaxrs-resteasy... on generated pom.xml , but works using generator = spring

##### openapi-generator version

last version using docker image run

##### Steps to reproduce

```
docker run --rm -v ${PWD}:/local openapitools/openapi-generator-cli generate  \
                        -i /local/openapi-spec.yaml \
                        -g spring  \
                        --api-package myapi.resource \
                        --model-package myapi.dto \
                        -o /local/generated-apis-stubs \
                        -c /local/config.yaml 
```
The config.yaml looks like this
```
additionalProperties:
  artifactId: myamazingapi
  groupId: com.me
  serializableModel: "true"
  dateLibrary: java8
  interfaceOnly: true
  parentArtifactId: myparentArfitactId
  parentGroupId: com.me
  parentVersion: 1.0.0
```

But usign spring works:
```
docker run --rm -v ${PWD}:/local openapitools/openapi-generator-cli generate  \
                        -i /local/openapi-spec.yaml \
                        -g spring  \
                        --api-package myapi.resource \
                        --model-package myapi.dto \
                        -o /local/generated-apis-stubs \
                        -c /local/config.yaml 
```
