### ISSUE TITLE
[REQ] Make sure enums are unique

### ISSUE THREAD

**Issue by Shohou** [OpenAPITools/openapi-generator#9135]
### Is your feature request related to a problem? Please describe.

I got a json with spec version 2 from the third party vendor. It contains enums in some places and some of them have duplications. Of course this is a bug in json and should be fixed by the vendor, but would be nice if the generator checked it and removed duplications before generating java enums

## Describe the solution you'd like

Check and remove duplicates from enums before generating java enums. Print a warning about duplications found

## Describe alternatives you've considered

Well, so far I wrote a gradle script which parses json and removes duplicates before running generator. It makes my gradle script big and ugly

**Comment by Shohou** [comment]
and just found that values in enums in my source json are actually unique if you take the letter case into consideration. But in java they are upped and become non unique

**Comment by GideonLeGrange** [comment]
I've also encountered this. Here is a YAML snippet that results in this problem:

```yaml 
       type:
          type: string
          description: Type of deal price.
          example: recurring
          enum:
          - TRANSFER
          - SETUP
          - RECURRING
          - RENEWAL
          - OVERUSE
          - setup
          - recurring
          - renewal
```

That leads to this Java code:

```java
  /**
   * Type of deal price.
   */
  @JsonAdapter(TypeEnum.Adapter.class)
  public enum TypeEnum {
    TRANSFER("TRANSFER"),
    
    SETUP("SETUP"),
    
    RECURRING("RECURRING"),
    
    RENEWAL("RENEWAL"),
    
    OVERUSE("OVERUSE"),
    
    SETUP("setup"),
    
    RECURRING("recurring"),
    
    RENEWAL("renewal");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<TypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return TypeEnum.fromValue(value);
      }
    }
  }

```

**Comment by oujesky** [comment]
This can also happen for enum values containing special characters (either part of the value or completely), example:
```yaml
timezone:
    type: string
    enum:
        - "Etc/GMT-1"
        - "Etc/GMT+1"
```

this will generate enum values with duplicate names:
```java
ETC_GMT_1("Etc/GMT-1"),
ETC_GMT_1("Etc/GMT+1");
```

Similar is reported for C# generator under #11265 

In case the enum value contains just non-ascii characters, this is even worse as it generates invalid Java code. For example:
```yaml
test:
    type: string
    enum: 
        - " "
        - "ěščřžýáí"
```
will result in code that won't compile:
```java
_(" "),
_("ěščřžýáí");
```

There are similar issues reported for other languages and similar use cases: #7441, #11207, #7288, #5110, https://github.com/OpenAPITools/openapi-generator/issues/535#issuecomment-404556439

**Comment by jonnekleijer** [comment]
I found a similar use case for `typescript-angular` and `csharp-netcore` client generators. 
The usecase is similar to @oujesky with non-ascii characters:

```yaml
UnitOfMeasurement:
  type: string,
  enum: 
    - "m",
    - "m²",
    - "m³"
```

Result in  `typescript-angular`:
```typescript
export enum UnitOfMeasurement {
    M = 'm',
    M = 'm²',
    M = 'm³'
};
```

Result in `csharp-netcore`:
```csharp
namespace Aquasuite.Api.Clients.Model
{
    /// <summary>
    /// Defines a magnitude of a quantity, defined and adopted by convention or by law,   that is used as a standard for measurement of the same kind of quantity.
    /// </summary>
    /// <value>Defines a magnitude of a quantity, defined and adopted by convention or by law,   that is used as a standard for measurement of the same kind of quantity.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum UnitOfMeasurement
    {
        /// <summary>
        /// Enum M for value: m
        /// </summary>
        [EnumMember(Value = "m")]
        M = 1,

        /// <summary>
        /// Enum M for value: m²
        /// </summary>
        [EnumMember(Value = "m²")]
        M = 2,

        /// <summary>
        /// Enum M for value: m³
        /// </summary>
        [EnumMember(Value = "m³")]
        M = 3
    }
}
```
