### ISSUE TITLE
[BUG] Vendor extensions on a parameter schema aren't available

### ISSUE THREAD

**Issue by jparise** [OpenAPITools/openapi-generator#9138]
##### Description

Vendor extension properties on a Parameter's Schema Object aren't available (at least with the `python-flask` generator).

##### openapi-generator version

Version 5.1.0

##### OpenAPI declaration file content or url

```yaml
param_id:
  name: param_id
  description: Unique identifier
  in: path
  required: true
  schema:
    type: string
    x-vendor-param:
      property: true
```

##### Generation Details

I inspected the debugging output (using `--global-property debugOperations=true`), and there is no `vendorExtensions` field under any of the `*Params` collections (e.g. `allParams`). I _do_ see the raw content with the parameter's `jsonSchema` field, but that's not useful from within a template.

##### Suggest a fix

It would be useful if the extension properties were available as `vendorExtensions` like they are for other schema objects.
