### ISSUE TITLE
choose authentication in python client?

### ISSUE THREAD

**Issue by jokedurnez** [OpenAPITools/openapi-generator#919]
Thank you developers ! This is a great tool !! Just a problem with multiple authentication methods...

##### Description

I have multiple ways of authenticating:

i.e. in a path:
```yaml
      security:
        - apiKey: []
        - openlattice_auth: []
```
...
```
    openlattice_auth:
        type: "http"
        scheme: "bearer"
        bearerFormat: "JWT"
    apiKey:
        type: apiKey
        in: header
        name: Authorization
```

When I only specify `-apiKey: []`, I get my data in the python client.  However, when both are there, it by default tries to use the `openlattice_auth`.  Is there a way to specify the specific authentication in the client?

##### openapi-generator version

`org.openapitools:openapi-generator-gradle-plugin:3.2.2`

##### OpenAPI declaration file content or url

Full api spec here: https://github.com/openlattice/api/blob/develop/openlattice.yaml#L985
(line = security definition)

##### Command line used for generation

In the repo posted above:
./gradlew generatePythonClient
