### ISSUE TITLE
[BUG] Cannot use Dependency Injection (DI) on generated C# code

### ISSUE THREAD

**Issue by Kiechlus** [OpenAPITools/openapi-generator#9223]
##### Description

I would like to use DI and not create Api classes myself. This enables mocking in unit testing. However, the base path then always defaults to `localhost`.

##### openapi-generator version

5.1.0

##### OpenAPI declaration file content or url

```yaml
packageName: "xxxx"
projectName: "yyyy"
packageVersion: "1.1.6"
targetFramework: netcoreapp3.1
library: httpclient
```

##### Generation Details

```bash
docker run --rm \
      --volume "${PWD}:/code" \
      -w /code \
      "openapitools/openapi-generator-cli:v5.1.0" \
      generate --config /code/clients/netcoreapp3.1_api_v2.yml -i /code/api_spec_v2.json -g csharp-netcore -o /code/clients/netcoreapp3.1/v2
```

##### Steps to reproduce

`Startup.cs`:
 
```c#
services.AddScoped<IMyApi, MyApi>();
```

In class where `MyApi` has been injected:

```c#
var configuration = new Configuration()
{
    BasePath = basePath,
    ...
};

myApi.Configuration = configuration; // This does not work, base path will always default to localhost
```
