### ISSUE TITLE
[BUG][JAVA][PLAY] An Override annotation is generated even though there is no super method.

### ISSUE THREAD

**Issue by prouzpe3** [OpenAPITools/openapi-generator#9228]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When you try to generate a client using configuration specified later, you will get uncompilable code because of overriding methods that do not exist in implemented interface.

##### openapi-generator version

it happens in the most recent master version

##### OpenAPI declaration file content or url

any api declaration file
```json
{
    "openapi": "3.0.2",
    "info": {
        "title": "New API",
        "version": "1.0.0",
        "description": "A brand new API with no content.  Go nuts!"
    },
    "paths": {}
}
```

##### Steps to reproduce

config.yaml
```yaml
generatorName: java
library: retrofit2
inputSpec: api-spec.json
minimalUpdate: true
additionalProperties:
  usePlayWS: true
  enableBuilderSupport: true
  useBeanValidation: true
  playVersion: play26
```
java -jar generator.jar batch -- config.yaml

##### Suggest a fix

class Play26CallFactory implements okhttp3.Call.Factory `@Overrides` a method `timeout()` that does not exist in the interface

I believe it can be removed along with the AsyncTimeout instance from the mustache files.
