### ISSUE TITLE
[BUG][Java] `additionalProperties: true` generates different outputs between OAS 2.0 and 3.0

### ISSUE THREAD

**Issue by ArthurFlageul** [OpenAPITools/openapi-generator#9294]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

I have an object declared as:

```yaml
Application:
      type: object

      required:
        - id
        - created
      properties:
        id:
          type: integer
          description: Unique ID for this entity.
        created:
          type: string
          format: date-time
          description: The moment this entity was created.
        modified:
          type: string
          format: date-time
          description: The moment this entity was last modified.
        attributes:
          type: object
          description: Arbitrary properties associated with this entity
          additionalProperties: true
```

In OAS3, the generated docs and object output for this object looks like:
```
**attributes** | **Map<String, Object>** | Arbitrary properties associated with this campaign |  [optional]
```

In OAS2, the generated output is:

```
**attributes** | **Object** | Arbitrary properties associated with this campaign |  [optional]
```

Why do I get a different output depending on the OAS version? I'd like to keep the OAS2 output after I've migrated to OAS3, is there a config option that I missed to prevent this?

##### openapi-generator version

[Lastest](https://hub.docker.com/layers/openapitools/openapi-generator-cli/latest/images/sha256-694906b0b47b488507eafda3a58e52022d2d25bfa24538b57e4f310511018b4d?context=explore) (docker)

##### Generation Details

cmd:

```bash
	docker run \
		--rm \
		-v "$$(pwd)/../../generated/java":/out \
		-v "$$(pwd)/../../codegen-shared/all.yaml":/tmp/src/all.yaml \
		-v "$$(pwd)/templates":/tmp/src/templates \
		-v "$$(pwd)/config.json":/tmp/src/config.json \
		-w /tmp/src \
		openapitools/openapi-generator-cli:latest generate \
		-g java \
		-i all.yaml \
		-c config.json \
		-t templates \
		-o /out \
		--artifact-version=$(artifactVersion)
```
config:

```
{
  "modelPackage": "...",
  "apiPackage": "...",
  "artifactId": "...",
  "artifactUrl": "https://github.com/talon-one/maven-artefacts",
  "library": "okhttp-gson",
  "hideGenerationTimestamp": true,
  "gitUserId": "...",
  "gitRepoId": "..."
}
```

##### Steps to reproduce

1. Use a basic OAS3/OAS2 skeleton with an object that contains `additionalProperties`
2. Run the generator.
