### ISSUE TITLE
[BUG] new.sh does not specify gen-type in templateDir path

### ISSUE THREAD

**Issue by AndersSpringborg** [OpenAPITools/openapi-generator#9320]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [x] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When generating a new template, the standard config do not specify the correct `templateDir`
Let's say you created a new client with
```
./new.sh -n test -c
```

The config created have this templateDir specified in the standard config

```yaml
generatorName: test
outputDir: samples/client/petstore/test
inputSpec: modules/openapi-generator/src/test/resources/3_0/petstore.yaml
templateDir: modules/openapi-generator/src/main/resources/test
additionalProperties:
  hideGenerationTimestamp: "true"

```

The template should have been:
```yaml
templateDir: modules/openapi-generator/src/main/resources/test-client
```

As the template as named `test-client` in resources

##### openapi-generator version

5.1.1 (source-master)

##### OpenAPI declaration file content or url
https://github.com/OpenAPITools/openapi-generator/blob/946d145d30436a9f27b5285d78090cdba6997146/new.sh#L208

##### Suggest a fix
#9321
