### ISSUE TITLE
[REQ] Openapi generator maven plugin does not support "Supporting files" configuration

### ISSUE THREAD

**Issue by zhangyuting** [OpenAPITools/openapi-generator#9335]
### Is your feature request related to a problem? Please describe.

I'm trying to use `openapi-generator maven plugin` to generate JAVA SDK based on the OAS yaml file. Apart from the API and models, I'd like to generator a utility java file with the template engine. I went through the official document that said it can be achieved by openapi-generator cli with a configuration file(https://openapi-generator.tech/docs/customization/). 

```yaml
templateDir: my_custom_templates
additionalProperties:
  artifactId: kotlin-petstore-client
  serializableModel: "true"
  dateLibrary: java8
files:
  AUTHORS.md: {}
  api_interfaces.mustache:
    templateType: API
    destinationFilename: Interface.kt
  api.mustache:
    templateType: API
    destinationFilename: Impl.kt
  other/check.mustache:
    folder: scripts
    destinationFilename: check.sh
    templateType: SupportingFiles
```

The `check.mustache` in the example is actually what I need(define a template and convert it to util file), and looks it's simple enough by adding things under the  `files` node. However, I found the openapi-generator maven plugin does not support such `files` configuration in the pom.xml.

## Describe the solution you'd like

Do some configuration in the maven pom to declare the supporting files, just like the CLI approach.

## Describe alternatives you've considered

N/A

## Additional context

N/A
