### ISSUE TITLE
[BUG][typescript-axios] string property with date-time format results in string instead of Date

### ISSUE THREAD

**Issue by abrunninger** [OpenAPITools/openapi-generator#9380]
##### Description
Using typescript-axios generator, I'm getting some undesirable behavior:

For an API with a model property defined as type string with a format of date-time, the generated interface has a type of string instead of Date.

##### openapi-generator version
@openapitools/openapi-generator-cli: 2.2.6
generator-cli: 5.1.0

##### OpenAPI declaration file content or url
This yaml 
```yaml
type: object
required:
  - timeSlotId
  - screeningstationId
  - datetime
properties:
  timeSlotId:
    $ref: "../types/id.yaml"
  screeningstationId:
    $ref: "../types/id.yaml"
  datetime:
    type: string
    format: date-time
```

results in 
```ts
/**
 * @export
 * @interface TimeSlot
 */
export interface TimeSlot {
    /**
     * @type {number}
     * @memberof TimeSlot
     */
    timeSlotId: number;
    /**
     * @type {number}
     * @memberof TimeSlot
     */
    screeningstationId: number;
    /**
     * @type {string}
     * @memberof TimeSlot
     */
    datetime: string;
}
```
##### Generation Details

This is the command used for generation
`openapi-generator-cli generate -g typescript-axios -i ..\openapi-spec\openapi.yaml -o .\api`

##### Steps to reproduce

1. Have open api document with above defined property in a schema
2. Generate typescript-axios
3. See output interfaces for undesired results.

##### Related issues/PRs

This user experienced exactly the behavior that I would assume given my specification. However, he describes it as undesirable behavior. Could it be that the behavior was changed after this issue?
[3842 typescript-axios generator string property with date-time format needs to remain a string](https://github.com/OpenAPITools/openapi-generator/issues/3842)

##### Suggest a fix
Add an option to the typescript-axios generator to choose between OpenAPI dates generating variables of datatype string and datatype date in the generated Typescript code.
