### ISSUE TITLE
[JAVA] Bug generating model when discrimator is "_type" and a property called "type" also present in response schema

### ISSUE THREAD

**Issue by ahsanfz** [OpenAPITools/openapi-generator#9444]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
##### Description

So I am posting a snippet of a message from my schema. The problem with this schema is that the discriminator begins with an underscore followed by a name that is also a property in this particular message i.e. _type and type are present in this schema. 

I can't change the discriminator to some other value as this will break existing client codes and we don't want to break existing client at the cost of being freshly able to generate open api clients.

So when I generate the code for my open-api specifications, I get an uncompilable java code.

##### openapi-generator version

openapi-generator-cli-5.1.1

##### OpenAPI declaration file content or url

Following is a cut down definition that demonstrates my problem:
 
```yaml
openapi: 3.0.1
info:
  title: Rest API
  description: "This is the Restful API server."
  version: 1.0.0
servers:
- url: http://localhost:8080/
  description: Generated server url
paths:
  /test:
    get:
      summary: Summary
      description: Description
      operationId: test
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Message'
components:
  schemas:
    Message:
      required:
      - _type
      - text
      type: object
      properties:
        type:
          type: string
          description: Type of this message.
          enum:
          - STATUS
          - TEXT
          - ERROR
          - PROGRESS
        subType:
          type: string
          description: Sub-type of this message.
          enum:
          - STATUS
          - LOCK
          - UNKNOWN
        _type:
          type: string
      discriminator:
        propertyName: _type


```

##### Command line used for generation

openapi-generator-cli generate \
   --input-spec "${DIR}"/api-docs.yaml \
   --generator-name java \
   --output "${JAVA_SRC_DIR}"/rest_client_with_resttemplate \
   --verbose \
   --config "${JAVA_CONFIG_DIR}"/resttemplate.json \
   --global-property debugModels=true 

```json
Contents of resttemplate.json: 
{
  "dateLibrary": "java8",
  "library": "resttemplate",
  "modelPackage": "model",
  "apiPackage": "api",
  "invokerPackage": "restapi.client"
}
```

##### Steps to reproduce

Generate the code given the command line and load the project in any editor. The Message.java file generated will show the problem how it is uncompilable,

##### Generated Code Description

The generated code is tripping on _type and type.

It generates wrongly as below:

```java
@JsonPropertyOrder({
  Message.JSON_PROPERTY_TYPE,
  Message.JSON_PROPERTY_SUB_TYPE,
  Message.JSON_PROPERTY_TYPE
})
  public static final String JSON_PROPERTY_TYPE = "type";
  private TypeEnum type;
  public static final String JSON_PROPERTY_TYPE = "_type";
  protected String type;

  public String getType() {
    return type;
  }
  public String getType() {
    return type;
  }
```

whereas it should be maybe something like:

```java
@JsonPropertyOrder({
  Message.JSON_PROPERTY_TYPE,
  Message.JSON_PROPERTY_SUB_TYPE,
  Message.JSON_PROPERTY__TYPE
})
  public static final String JSON_PROPERTY_TYPE = "type";
  private TypeEnum type;
  public static final String JSON_PROPERTY__TYPE = "_type";
  protected String _type;

  public TypeEnum getType() {
    return type;
  }
  public String get_Type() {
    return _type;
  }
```

##### Suggest a fix/enhancement

I looked at the moustache templates. No expert here, but maybe the "nameInSnakeCase" is the culprit in pojo.moustasche. I just searched the string "JSON_PROPERTY_" and the following lines poped up:
```java
  {{classname}}.JSON_PROPERTY_{{nameInSnakeCase}}{{^-last}},{{/-last}}
```
Must be other places also as variable is wrong at a couple of places.

Let me know if something is missing in bug report.

**Comment by ahsanfz** [comment]
Hi,

How does it look like here. Is this not a bug ?

Regards

**Comment by ahsanfz** [comment]
So I analyzed the problem as following:

`org.openapitools.codegen.utils.StringUtils.camelize(final String inputWord, boolean lowercaseFirstLetter)`

removes all underscores characters using this matcher:

`m = camelizeUnderscorePattern.matcher(word);`

If we let camelize do what it does and say that even removing the first underscore is part of its job, then one can do a more local fix in class "AbstractJavaCodegen" just for the java generators.

So toVarName()  and getterAndSetterCapitalize() could be changed with something as simple as the line below at start of methods:  
`        boolean beginsWithUnderScore = name.startsWith("_");`

And when the methods are ready to return, re-add back the underscore at the beginning. For example the toVarName could change as follows towards the end:
```

        // for reserved word or word starting with number, append _
        // for _ in start of word, put it back in, as camelize removes it totally.
        if (isReservedWord(name) || name.matches("^\\d.*") || beginsWithUnderScore ) {
            name = escapeReservedWord(name);
        }
```

And getterAndSetterCapitalize is just a little bit complicated, but doable. 

Can some one see a problem for this change ? Then we can do the second method as well.

Regards,

**Comment by JRAndreassen** [comment]
+1 on this problem (openapi-generator-cli-6.2.0.jar)
 Is there a way to work arround this ?
```yaml
    CompPatchPanelPort:   # ref: '#/components/schemas/CompPatchPanelPort'
      type: object
      properties:
        component_id:
          type: string
        label:
          type: string
        port_num:
          type: number
        conn_port_comp_id:
          type: string
        conn_port_uuid:
          type: string
        sfp_type:
          type: string
        state:
          type: string
        link_state:
          type: string
        connection_speed:
          type: number
        hw_addr:
          type: string
        media_type:
          type: string
        type:
          type: string
      required:
        - component_id
        # - label
        # - port_num
        # - conn_port_uuid
        # - sfp_type
        # - media_type
        # - type

```
```
Exception in thread "main" java.lang.RuntimeException: Could not generate model 'CompPatchPanelPort'
        at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:563)
        at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:912)
        at org.openapitools.codegen.cmd.Generate.execute(Generate.java:465)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
Caused by: java.lang.RuntimeException: reserved word type not allowed
        at org.openapitools.codegen.DefaultCodegen.escapeReservedWord(DefaultCodegen.java:1580)
```
