### ISSUE TITLE
[BUG] Spring generator: inheritance now always requires discriminator

### ISSUE THREAD

**Issue by AxelHeathnet** [OpenAPITools/openapi-generator#9516]
According to the latest [OAS3.0 specification](https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism/)  the following is a perfect fine example of inheritance:

```yaml
Animal:
      type: object
      properties:
        name:
          type: string
          
    Cat: 
      allOf:
      - $ref: '#/components/schemas/Animal'
      - type: object
        properties:
          breed:
            type: string
```

Till version 4.3.0 it works fine, the pojo is generated as:

```java
public class Cat extends Animal{
  String breed;
}
```

From version 5.0.0 I instead get:
```java
public class Cat {
  String name;
  String breed;
}
```

In order to make this work in version 5.0.x I have to edit the specification like this:

```yaml
Animal:
      type: object
     discriminator:
       propertyName: className
      properties:
        name:
          type: string

```
Is this intentional? I find it much more confusing now
