### ISSUE TITLE
swift generated client code do not support Authorization : Bearer {accesstoken}

### ISSUE THREAD

**Issue by chauchinyiu** [OpenAPITools/openapi-generator#9597]
Hello,

  I would like to generate swift5 client code with calling my API with header Authorization : Bearer {accesstoken}. I already follow the instruction to setup my yaml file as follows
  
swagger.yaml: 
```
paths:
  /resources:
    get:
security:
    - accessToken: []  
 
 components:
   securitySchemes:
    accessToken:            
      type: http
      scheme: bearer
      bearerFormat: JWT 
```
however the generated swift code is

` open class func getResources(apiResponseQueue: DispatchQueue = MyApi.apiResponseQueue, completion: @escaping ((_ data: Resources?,_ error: Error?) -> Void)) `

There is no header for accessToken.  how can i set the accessToken in this case? could you provide some in information in this case ? 

thank you
