### ISSUE TITLE
[BUG] [JAVA] A problem with anyOf deserialization when one schema is a subset of another

### ISSUE THREAD

**Issue by tandrej98** [OpenAPITools/openapi-generator#9606]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description
As seen on the simplified schema below, we are trying to use a common Response schema as an interface for two types of responses a partial and a full. The issue is that the partial response is a subset of the full response and when the generated client tries to deserialize a response it ignores the specified discriminator and fails the deserialization of a partial response on `java.io.IOException: Failed deserialization for Response: 2 classes match result, expected 1`. Based on OpenApi documentation on discriminator object, it should work in this use-case. 

##### openapi-generator version
openapi-generator-cli-5.1.0.jar tried also with 5.0.0 and 4.3.1

##### OpenAPI declaration file content or url
Simplified example
```yaml
openapi: 3.0.1
info:
  title: Github issue
  version: 1.0.0
servers:
- url: http://localhost:8080
paths: 
  /api/objects/{id}:
    get:
      parameters:
      - name: id
        in: path
        description: ID.
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Response'
components:
  schemas:
    Response: 
      oneOf: 
      - $ref: '#/components/schemas/PartialResponse'
      - $ref: '#/components/schemas/FullResponse'
      discriminator:
        propertyName: responseType
        mapping: # should not be necessary but does not work with or without mappings
          PartialResponse: '#/components/schemas/PartialResponse'
          FullResponse: '#/components/schemas/FullResponse'
    PartialResponse: 
      required:
      - responseType
      type: object
      properties: 
        propA: 
          type: string
        responseType:
          type: string
    FullResponse:
      required:
      - responseType
      type: object
      properties: 
        propA: 
          type: string
        propB: 
          type: string
        responseType:
          type: string
```

##### Generation Details
Used the CLI jar as such:
`java -jar openapi-generator-cli.jar generate -i api.yaml -g java --additional-properties library=jersey2 -o target/`

**Comment by alfredodiaz** [comment]
The same issue here. I have picked up this example as a base.
[https://github.com/OpenAPITools/openapi-generator/tree/v5.1.1/samples/openapi3/client/petstore/java/jersey2-java8](https://github.com/OpenAPITools/openapi-generator/tree/v5.1.1/samples/openapi3/client/petstore/java/jersey2-java8)

I have modified the test [testZebra](https://github.com/OpenAPITools/openapi-generator/blob/560bf7e080518f1c5e9af41acdbf3fa402d75512/samples/openapi3/client/petstore/java/jersey2-java8/src/test/java/org/openapitools/client/model/ZebraTest.java#L36) to make it deserialize a mammal instead of just a Zebra.
```
    @Test
    public void testZebra() {
        Zebra z = new Zebra();
        z.setClassName("zebra");
        Map<String, String> m = new HashMap<>();
        z.putAdditionalProperty("key1", "value1");
        z.putAdditionalProperty("key2", 12321);
        z.setType(Zebra.TypeEnum.MOUNTAIN);

        JSON j = new JSON();
        try {
            // serialize
            Assert.assertEquals(j.getMapper().writeValueAsString(z), "{\"type\":\"mountain\",\"className\":\"zebra\",\"key1\":\"value1\",\"key2\":12321}");

            // deserialize
            String zebraJson = "{\"type\":\"mountain\",\"className\":\"zebra\",\"key1\":\"value1\",\"key2\":12321}";
            Mammal mammal = j.getMapper().readValue(zebraJson, Mammal.class);
        } catch (Exception ex) {
            Assert.assertEquals(true, false); // exception shouldn't be thrown
        }
    }
```

The previous test works as expected. But if I redefine the definition of `Whale` and `Pig` so they are defined with exactly the same content as `Zebra`, the test starts failing.

[openapi.yml](https://github.com/OpenAPITools/openapi-generator/blob/v5.1.1/samples/openapi3/client/petstore/java/jersey2-java8/api/openapi.yaml#L2067)
```
    whale:
      additionalProperties: true
      properties:
        type:
          enum:
            - plains
            - mountain
            - grevys
          type: string
        className:
          type: string
      required:
        - className
      type: object
    zebra:
      additionalProperties: true
      properties:
        type:
          enum:
          - plains
          - mountain
          - grevys
          type: string
        className:
          type: string
      required:
      - className
      type: object
    Pig:
      additionalProperties: true
      properties:
        type:
          enum:
            - plains
            - mountain
            - grevys
          type: string
        className:
          type: string
      required:
        - className
      type: object
```

The test fails with the following Exception:
```
Failed deserialization for Mammal: 3 classes match result, expected 1
```
