### ISSUE TITLE
[BUG] TypeScript generate changes variable name

### ISSUE THREAD

**Issue by jrichter-svmx** [OpenAPITools/openapi-generator#9686]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output? => See Description
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description
Hi, first of all, thank you for this wonderful tool :-)

**My issue:**
_

When generating a model for TypeScript, the variable/key "_" is not transformed correctly.

Example YAML Schema:
```yaml
    FooType:
      required:
        - _
      type: object
      properties:
        _:
          type: string
      description: The FooType
      discriminator:
        propertyName: _
        mapping:
          Bar: '#/components/schemas/Bar'
```
Generated model in Typescript (actual):
```
export interface FooType { 
    _u: string;
}
```

Generated model in Typescript (expected):
```
export interface NodeType { 
    _?: string;
}
```
**What works:**
_

When renaming the variable "_" to something like "type", the generated model is expected and working properly. However, due to
backwards-compatibility issues, we can't simply rename this variable.

##### openapi-generator version

openapi-generator-cli version => 5.1.1

##### Suggest a fix

Do not change the variable name? ;-)
