### ISSUE TITLE
String type defined with "pattern" is generated as Object instead of String

### ISSUE THREAD

**Issue by srividhyak27** [OpenAPITools/openapi-generator#972]
##### Description

We have a type defined as string along-with pattern
```
sid:
      type: string
      pattern: '^(phone-[0-9]{5,15}|extphone-.+|.+)$'
```

This is referenced as a parameter in POST method:

```
 parameters:
        - name: sid
          in: path
          description: SID of the user
          required: true
          schema:
             $ref: './common.yaml#/components/schemas/sid
```

The service stub generated has SID defined as object, as shown below:
`addUser(@ApiParam(value = "SID of user",required=true) @PathParam("sid") String sid,....)`

This throws Jersey Model validation errors whille running the service.

I changed the type of the parameter to "string" and the service works fine. Is there any way code/class for such parameter (with patterns/regular expressions) can be generated and referenced ?

##### openapi-generator version

openapi-generator maven plugin, version 3.1.2

##### Command line used for generation

<generatorName>jaxrs-jersey</generatorName>

##### Steps to reproduce

specification example provided above

##### Suggest a fix/enhancement

For parameters in URI path, can we fallback to String (instead of Object) in case the relevant type cannot be generated ?
