### ISSUE TITLE
[BUG] [TYPESCRIPT] HttpFile param is Serialized+Strignifyed but it makes the TS client crashing

### ISSUE THREAD

**Issue by jimmydjabali** [OpenAPITools/openapi-generator#9816]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

I'm supposed to upload a **file** (binary) with a **PUT** method, but the swagger-codegen generate a wrong TS function for my PUT function :
![image](https://user-images.githubusercontent.com/10889224/122725395-3eb52e80-d275-11eb-8cc9-fe1acc747497.png)

Here it should not Serialize nor Stringify my File, because it create this error on the client's side :
![image](https://user-images.githubusercontent.com/10889224/122728496-7d98b380-d278-11eb-941c-47231b8f7ca0.png)

Instead, it should pass the `dataSourceRequestData` directly to the setBody()

##### openapi-generator version

**latest**, as of today on June 21, 2021

##### OpenAPI declaration file content or url

The .yml part of the route that produces this problematic code is :
```yaml
  /datasources/{dataSourceId}/data:
      put:
        consumes:
          - 'application/octet-stream'
          - 'text/csv'
          - 'text/plain'
        tags:
          - 'api-metadata'
        summary: 'Add data to a datasource.'
        operationId: 'putDataSourceData'
        parameters:
          - in: 'path'
            name: 'dataSourceId'
            required: true
            type: 'string'
            pattern: '^[\w:-]+$'
            description: 'Data source identifier.'
          - in: 'body'
            name: 'dataSourceRequestData'
            description: 'Datasource data'
            required: true
            schema:
              type: string
              format: binary
```

##### Generation Details

The generation command is
```
docker run --rm -u "$(USER_GROUP)" -v "$(PWD)":/src openapitools/openapi-generator-cli:latest \
    -i /src/api/flattened.yml \
    -g typescript \
    -o /src/build/package/ts-client
```

##### Steps to reproduce

Run the above command with the above .yml

##### Related issues/PRs

No issue/PR related

##### Suggest a fix

I have actually no idea what could be the problem. Maybe there is a configuration I missed, but I more think this case should be automatically handled.
