### ISSUE TITLE
[KOTLIN] [SPRING] Fixes for: invoker-package / Jackson Module / Configuration / Misc

### ISSUE THREAD

**Issue by dr4ke616** [OpenAPITools/openapi-generator#986]
There are a number of minor bugs that this issue will look to highlight within the Kotlin Code Generator. Ideally these all should be small enough to be fixed as part of a single PR.

##### Description

- Set the `basePackage` from `invokerPackage` so can be picked up from the `--invoker-package` argument.
- Add the [Kotlin Jackson module](https://github.com/FasterXML/jackson-module-kotlin) to support serialization/deserialization of Kotlin classes and data classes
- The base path configuration property key in the `RequestMapping` annotation of each controller is generated from `openapi.{{title}}.base-path`. It might be better to clean this a little and just use something like `api.base-path`, as all child routes are injected as part of each methods `RequestMapping`.
- The application configuration doesn't work. It's generated as a `.yaml` file, but the format of the file is `.properties`. Update the template to use `yaml` structure. E.g change to something like below:

```yaml
spring:
  application:
    name: someApiTitle

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

server:
  port: 8080
```

##### openapi-generator version

- `org.openapitools:openapi-generator:3.2.3`
