### ISSUE TITLE
[Question][typescript-angular] Why are generated enums ambient?

### ISSUE THREAD

**Issue by mimkorn** [OpenAPITools/openapi-generator#9867]
##### Description

typescript-angular generates [ambient enums](https://www.typescriptlang.org/docs/handbook/enums.html#ambient-enums) instead of non-ambient ones. These cannot be used to generate lists, like shown here https://stackblitz.com/edit/ngfor-enum-select-options . You can check it out by adding "declare" before the enum on the third line there. 

##### openapi-generator version

5.1.1

##### OpenAPI declaration file content or url

Any OpenAPI using a string enum, like this:
```yaml
    SomeEnum:
      title: SomeEnum
      type: string
      enum:
        - value1
        - value2
        - value3
```

##### Command line used for generation

```
openapi-generator generate \
-g typescript-angular \
-i ../../subscription.yaml \
--additional-properties \
stringEnums=true
```

##### Suggest a fix/enhancement

Is there any reason why not make it a non-ambient enum? Or some workaround how to convert it into a non-ambient one?
