### ISSUE TITLE
[BUG] typescript-axios generator works bad for formdata array

### ISSUE THREAD

**Issue by andrei-varchanka** [OpenAPITools/openapi-generator#9889]
##### openapi-generator version 
5.1.1

##### OpenAPI declaration file content or url
```yaml
 put:
      summary: "Update a new painting"
      operationId: "updatePainting"
      tags:
        - "Paintings"
      consumes:
        - "multipart/form-data"
      parameters:
        - in: "formData"
          name: "image"
          type: "file"
        - in: "formData"
          name: "genres"
          type: **"array"**
          items:
            type: "string"
          required: true
```

##### Generation Details

openapi-generator-cli generate -g typescript-axios -i ../server/swagger.yaml -o src/api

##### Steps to reproduce

Specification example results in: 
if (genres) {
                localVarFormParams.append(genres.join(COLLECTION_FORMATS.csv));
}

and the error in browser displayed: TypeError: Failed to execute 'append' on 'FormData': 2 arguments required, but only 1 present.

##### Suggest a fix
Expected result: 
if (genres) {
                localVarFormParams.append('genres', genres.join(COLLECTION_FORMATS.csv));
}
