### ISSUE TITLE
[BUG] Discriminator mapping $refs are not resolved

### ISSUE THREAD

**Issue by Sshnyari** [OpenAPITools/openapi-generator#9921]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

From what I understand from the various examples, for polymorphism, we should use oneOf **and** allOf with the discriminator and mapping props. That works fine when we have only one file. When models are scattered in multiple files, it doesn't work. 

After investigating a little bit, I found out that the method `DefaultCodeGen.addOneOfInterfaceModel` uses `ModelUtils.getSimpleRef` to get the mappings and that one only handles internal references (ie: `"#/components/"` and `"#/definitions/"`), hence, the mappedModels[].modelName in mustache files end up printing ERRORUNKNOWN in the generated code.

Further investigation led me to find that multiple files are merged before the generation begins, so the issue may not be in the `addOneOfInterfaceModel` method, but the merged file doesn't have the right values in the mapping section. It is something like

```yaml
  mapping:
    child1: "relative/path/to/child1/yaml/file/from/the/main/schema/file"
    child2: "relative/path/to/child2/yaml/file/from/the/main/schema/file"
```
instead of
```yaml
  mapping:
    child1: "#/definitions/path/to/child1/definition"
    # or
    child2: "#/components/path/to/child2/definition"
```
and there is no reference to child1 and child2 in the merged file

I couldn't find where $refs are resolved to advance further.

##### openapi-generator version

5.1.1

##### OpenAPI declaration file content or url

```yaml
title: parent
type: object
properties:
  objectType:
    type: string
required:
  - objectType
discriminator:
  propertyName: objectType
  mapping:
    child1: "./child1.yaml"
    child2: "./child2.yaml"
```

```yaml
title: child1
type: object
allOf:
  - $ref: "./parent.yaml"
properties:
  objectType:
    type: string
    defaultValue: "child1"
  prop1:
    type: string
```

```yaml
title: child2
type: object
allOf:
  - $ref: "./parent.yaml"
properties:
  objectType:
    type: string
    defaultValue: "child2"
  prop2:
    type: string
```

##### Generation Details

using and generator that supports discriminators would do. I used the aspnetcore one.

##### Steps to reproduce

running the generator on a file with external $refs in the mappings section

##### Related issues/PRs

none

##### Suggest a fix

According to the specs the values in discriminator/mapping props should behave like $ref props (https://swagger.io/specification/#discriminator-object), so a fix would be to properly resolve external paths in discriminator/mapping props.
