### ISSUE TITLE
[REQ] Allow multiples API's in the same maven module

### ISSUE THREAD

**Issue by jorgerod** [OpenAPITools/openapi-generator#9943]
### Is your feature request related to a problem? Please describe.

Currently, the maven plugin only allows a single input API file.
I would like to have the possibility to have several APIs in the same module.

## Describe the solution you'd like

Perhaps, with a file, define the location of each of the apis and their configuration.

```yaml
apis:
  api1:
    inputSpec: openapi-1.yaml
    modelPackage: org.mypackage.dto
    apiPackage: org.mypackage.api
  api2:
    inputSpec: openapi-2.yaml
    modelPackage: org.mypackage.pojo
```

How do you see it?
