### ISSUE TITLE
[BUG][KOTLIN] Multiple tags in YAML input lead to duplicate code generated

### ISSUE THREAD

**Issue by florianbesserprjphxcom** [OpenAPITools/openapi-generator#9995]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Duplicate Kotlin code is generated, which then fails to compile.

##### openapi-generator version

5.2.0

##### OpenAPI declaration file content or url

Excerpt from input file:
```yaml
tags:
  - name: customer
    description: xxx
  - name: customer profile
    description: yyy
```
as well as
```yaml
paths:
  /customers:
    post:
      tags:
        - customer
        - customer profile
      summary: zzz
      operationId: createCustomer
```

##### Generation Details

The following code is produced
```kotlin
@PostMapping(
            value = ["/customers"],
            produces = ["application/json"]
    )
    fun createCustomer( @RequestHeader(value="requestId", required=true) requestId: kotlin.String
): ResponseEntity<CreateCustomerResponse> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }


    @PostMapping(
            value = ["/customers"],
            produces = ["application/json"]
    )
    fun createCustomer( @RequestHeader(value="requestId", required=true) requestId: kotlin.String
): ResponseEntity<CreateCustomerResponse> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }
```

##### Steps to reproduce

Due to privacy constraints we can't paste more code here. However once we remove one of the two tags from the input, e.g.:
```yaml
paths:
  /customers:
    post:
      tags:
        - customer
      summary: zzz
      operationId: createCustomer
```
then the generated Kotlin code does **not** contain a duplicate method `createCustomer` anymore.

##### Related issues/PRs

None

##### Suggest a fix

Do not generate a duplicate method even if multiple tags are provided for a given input.
